/* The prose of the Sliding Window Maximum page: everything the reader sees
 * that is not interactive. Rendered by src/pages/leetcode/[slug].astro through
 * the Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Sliding Window Maximum',
  summary: 'A value with a bigger one to its right can never be a window maximum again. Keep only the ones that can — they fall from front to back — and the front of that deque is every window\'s answer, in O(n) total.',
  eyebrow: 'LeetCode 239 &nbsp;·&nbsp; Hard',
  lede: { en: "Report the largest value in every window of k consecutive numbers. Scanning each window repeats almost all of the previous scan. The fix is to notice which values are already hopeless: once a bigger number has arrived, anything smaller before it will leave the window first and can never be the maximum. Throw those away as they are beaten and what remains is a short, falling queue whose front is the answer.", my: "ဆက်တိုက် ဂဏန်း k ခု window တိုင်းရှိ အကြီးဆုံး value ကို ပြောပါ။ window တစ်ခုစီကို scan လုပ်ခြင်းသည် ယခင် scan ၏ အများစုကို ထပ်လုပ်သည်။ ဖြေရှင်းချက်မှာ မည်သည့် value များ မျှော်လင့်ချက် မရှိတော့သလဲ သတိပြုရန် — ပိုကြီးသော ဂဏန်း ရောက်လာသည်နှင့် ၎င်းရှေ့ရှိ ငယ်သည်မှန်သမျှ window မှ အရင်ထွက်မည်ဖြစ်ပြီး maximum ဘယ်တော့မှ မဖြစ်နိုင်။ ၎င်းတို့ ရှုံးသည်နှင့် ပစ်ပယ်လျှင် ကျန်သည်မှာ ရှေ့ဆုံးသည် အဖြေဖြစ်သော တိုတောင်းပြီး ကျဆင်းသော queue တစ်ခု ဖြစ်သည်။" },
  links: [{ id: 239, title: 'Sliding Window Maximum', slug: 'sliding-window-maximum', difficulty: 'Hard' }],
  constraints: { en: "<span>1 &le; nums.length &le; 10<sup>5</sup></span><span>&minus;10<sup>4</sup> &le; nums[i] &le; 10<sup>4</sup></span><span>1 &le; k &le; nums.length</span>", my: "<span>1 &le; nums.length &le; 10<sup>5</sup></span><span>&minus;10<sup>4</sup> &le; nums[i] &le; 10<sup>4</sup></span><span>1 &le; k &le; nums.length</span>" },
  part1Sub: { en: "Read the statement, then slide the window and see which values could still win.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် window ကို ရွှေ့ပြီး မည်သည့် value များ နိုင်နိုင်သေးသလဲ ကြည့်ပါ။" },
  widgetTitle: { en: "Slide the window, see who can still win", my: "window ကို ရွှေ့ပါ — မည်သူ နိုင်နိုင်သေးသလဲ ကြည့်ပါ" },
  traps: {
    summary: { en: "Three ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ သုံးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>The maximum has to leave too.</strong> A deque that never drops its front when that index slides out of the window keeps reporting an old giant: for <code>[9,1,1,1,8,1]</code> with k = 3 it returns <code>[9,9,9,9]</code> instead of <code>[9,1,8,8]</code>. Store indices, so you can tell.", my: "<strong>maximum လည်း ထွက်ရမည်။</strong> index window မှ ထွက်သွားချိန်တွင် ရှေ့ဆုံးကို ဘယ်တော့မှ မဖယ်သော deque သည် အဟောင်းကြီးကို ဆက်ပြောနေသည် — k = 3 ဖြင့် <code>[9,1,1,1,8,1]</code> အတွက် <code>[9,1,8,8]</code> အစား <code>[9,9,9,9]</code> ပြန်ပေးသည်။ သိနိုင်ရန် index ကို သိမ်းပါ။" },
      { en: "<strong>No answer until the first window is full.</strong> Appending the front from the very first index adds k − 1 answers for windows that do not exist: example 1 comes back <code>[1,3,3,3,5,5,6,7]</code>, eight values for six windows.", my: "<strong>ပထမ window မပြည့်မချင်း အဖြေ မရှိ။</strong> ပထမဆုံး index မှစ၍ ရှေ့ဆုံးကို ထည့်လျှင် မရှိသော window များအတွက် အဖြေ k − 1 ခု ပိုလာသည် — ဥပမာ 1 သည် window ခြောက်ခုအတွက် value ရှစ်ခု <code>[1,3,3,3,5,5,6,7]</code> ပြန်လာသည်။" },
      { en: "<strong>n · k is too slow here.</strong> With n = 10⁵ the window can be 5 × 10⁴ wide, and scanning every window is 2.5 × 10⁹ comparisons (computed). Even k = 1,000 took the Python brute force 1.05 s on this machine against 0.02 s for the deque.", my: "<strong>n · k သည် ဤနေရာတွင် နှေးလွန်းသည်။</strong> n = 10⁵ တွင် window သည် 5 × 10⁴ ကျယ်နိုင်ပြီး window တိုင်းကို scan လုပ်ခြင်းသည် နှိုင်းယှဉ်ခြင်း 2.5 × 10⁹ (တွက်ထားသည်)။ k = 1,000 ပင် ဤစက်ပေါ်တွင် Python brute force ကို 1.05 s ကြာစေပြီး deque သည် 0.02 s။" },
    ],
  },
  part2Sub: { en: "Two approaches. The strip is nums with the current window lit; the stage is what each approach carries — a running best, or the deque of values that can still win.", my: "နည်းလမ်းနှစ်မျိုး။ strip သည် လက်ရှိ window ကို လင်းပြထားသော nums ဖြစ်သည်။ stage သည် နည်းလမ်းတစ်ခုစီ သယ်ဆောင်သည့်အရာ — ယခုထိ အကောင်းဆုံး သို့မဟုတ် နိုင်နိုင်သေးသော value များ၏ deque။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the deque raises", my: "deque နှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why is the while loop not O(n · k)?", my: "while loop သည် ဘာကြောင့် O(n · k) မဟုတ်သလဲ။" }, a: { en: "Count pops, not iterations. Every index is pushed exactly once, so it can be popped at most once — from the back or the front. However the pops bunch up, there are at most n of them across the whole run, so the loop body runs at most n times in total.", my: "iteration မဟုတ်ဘဲ pop ကို ရေတွက်ပါ။ index တိုင်းကို တစ်ကြိမ်တိတိ push သဖြင့် အများဆုံး တစ်ကြိမ်သာ pop ခံရနိုင်သည် — နောက်မှ သို့မဟုတ် ရှေ့မှ။ pop များ မည်သို့ စုနေပါစေ run တစ်ခုလုံးတွင် အများဆုံး n ကြိမ်သာ ရှိသဖြင့် loop body သည် စုစုပေါင်း အများဆုံး n ကြိမ်သာ run သည်။" } },
      { q: { en: "Why pop on ≤ and not just on <?", my: "< တွင်သာမဟုတ်ဘဲ ≤ တွင် ဘာကြောင့် pop သလဲ။" }, a: { en: "Both give the right answer. An equal value that arrived later lasts at least as long and wins every window the older one would, so the older copy is dead weight; popping it keeps the deque shorter. With <, equal values pile up — on an array of all 5s the deque grows to k.", my: "နှစ်ခုလုံး မှန်ကန်သော အဖြေ ပေးသည်။ နောက်မှ ရောက်လာသော တူညီသည့် value သည် အနည်းဆုံး အတူတူ ကြာပြီး အဟောင်း နိုင်မည့် window တိုင်းကို နိုင်သဖြင့် copy အဟောင်းသည် အလေးချိန် အလကား — ၎င်းကို pop လုပ်ခြင်းက deque ကို တိုစေသည်။ < ဖြင့်ဆိုလျှင် တူညီသော value များ စုပုံလာသည် — 5 ချည်း array တွင် deque သည် k အထိ ကြီးသည်။" } },
      { q: { en: "Is there a way without a deque?", my: "deque မပါသော နည်း ရှိသလား။" }, a: { en: "Yes: cut the array into blocks of k and precompute, inside each block, the maximum from its start up to each index and from each index to its end. Any window covers the tail of one block and the head of the next, so its maximum is the larger of one suffix and one prefix maximum. It is also O(n) — and it is the oracle the verifier uses here.", my: "ရှိသည် — array ကို k ခုစီ block များ ဖြတ်ပြီး block တစ်ခုစီအတွင်း အစမှ index တစ်ခုစီအထိ နှင့် index တစ်ခုစီမှ အဆုံးအထိ maximum ကို ကြိုတွက်သည်။ window မည်သည်မဆို block တစ်ခု၏ အမြီးနှင့် နောက် block ၏ ခေါင်းကို ဖုံးသဖြင့် ၎င်း၏ maximum သည် suffix maximum တစ်ခုနှင့် prefix maximum တစ်ခုထဲမှ ပိုကြီးသည် ဖြစ်သည်။ ၎င်းလည်း O(n) ဖြစ်ပြီး ဤနေရာတွင် verifier သုံးသော oracle ဖြစ်သည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "Every value touched twice, not k times", my: "value တိုင်းကို k ကြိမ် မဟုတ်ဘဲ နှစ်ကြိမ် ထိ" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>n = 10⁵, k = 1,000</th></tr></thead>\n  <tbody>\n    <tr><td><b>Scan every window</b></td>\n        <td class=\"mono\">O(n · k)</td><td class=\"mono\">O(1)</td><td class=\"cross\">1.05 s</td></tr>\n    <tr><td><b>Monotonic deque</b></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(k)</td><td class=\"tick\">0.02 s</td></tr>\n  </tbody>\n</table>\n<figcaption>Measured here: the Python listings on an Apple M5 Pro, whole process, best of three. At k = 5 × 10⁴ the scan would do 2.5 × 10⁹ comparisons (computed), so it is not run on the five 10⁵-value cases at all; the deque's cost does not depend on k.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>n = 10⁵, k = 1,000</th></tr></thead>\n  <tbody>\n    <tr><td><b>Scan every window</b></td>\n        <td class=\"mono\">O(n · k)</td><td class=\"mono\">O(1)</td><td class=\"cross\">1.05 s</td></tr>\n    <tr><td><b>Monotonic deque</b></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(k)</td><td class=\"tick\">0.02 s</td></tr>\n  </tbody>\n</table>\n<figcaption>ဤနေရာတွင် တိုင်းတာထားသည် — Apple M5 Pro ပေါ်ရှိ Python listing များ၊ process တစ်ခုလုံး၊ သုံးကြိမ်အနက် အကောင်းဆုံး။ k = 5 × 10⁴ တွင် scan သည် နှိုင်းယှဉ်ခြင်း 2.5 × 10⁹ လုပ်မည်ဖြစ်၍ (တွက်ထားသည်) value 10⁵ ပါ case ငါးခုတွင် လုံးဝ မ run ပါ — deque ၏ ကုန်ကျမှုသည် k ပေါ် မမူတည်ပါ။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission. The deque ran against 20,013 arrays up to 10⁵ values; the scan against the 20,008 below that size.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်သည်။ deque ကို value 10⁵ အထိ array 20,013 ခုဖြင့်၊ scan ကို ထိုအရွယ်အောက် 20,008 ခုဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>nums</code> (up to 12 values) and <code>k</code> above, and both walkthroughs rebuild against them.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>nums</code> (value 12 ခုအထိ) နှင့် <code>k</code> ကို ပြင်လိုက်လျှင် walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
