/* The prose of the Serialize and Deserialize Binary Tree page: everything the
 * reader sees that is not interactive. Rendered by src/pages/leetcode/[slug].astro
 * through the Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Serialize and Deserialize Binary Tree',
  summary: 'Values alone do not record a tree\'s shape; values with a marker for every missing child do. Write the tree in preorder with "#"s and read it back with the same walk, or write it level by level and rebuild it with a queue.',
  eyebrow: 'LeetCode 297 &nbsp;·&nbsp; Hard',
  lede: { en: "Turn a binary tree into a string and back, any format you like. The whole problem is making the string say where the empty children are: once every missing child is written down, a preorder of the values fixes the tree exactly, and reading it back is the same walk again. Level order works too, with a queue on each side instead of recursion.", my: "binary tree တစ်ခုကို string အဖြစ် ပြောင်းပြီး ပြန်ပြောင်းပါ — ကြိုက်သော format ဖြင့်။ ပြဿနာတစ်ခုလုံးမှာ ဗလာ ကလေးများ ဘယ်မှာ ရှိသည်ကို string က ပြောစေခြင်း — မရှိသော ကလေးတိုင်းကို ရေးထားပြီးသည်နှင့် value များ၏ preorder သည် tree ကို အတိအကျ သတ်မှတ်ပြီး ပြန်ဖတ်ခြင်းသည် walk တူတူ ထပ်လုပ်ခြင်းသာ။ level order လည်း အလုပ်ဖြစ်သည် — recursion အစား ဘက်တစ်ခုစီတွင် queue တစ်ခု။" },
  links: [{ id: 297, title: 'Serialize and Deserialize Binary Tree', slug: 'serialize-and-deserialize-binary-tree', difficulty: 'Hard' }],
  constraints: { en: "<span>the number of nodes in the tree is in the range [0, 10<sup>4</sup>]</span><span>&minus;1000 &le; Node.val &le; 1000</span>", my: "<span>tree ထဲရှိ node အရေအတွက်သည် [0, 10<sup>4</sup>] အတွင်း</span><span>&minus;1000 &le; Node.val &le; 1000</span>" },
  part1Sub: { en: "Read the statement, then compare two trees' strings with and without the \"#\" markers.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် tree နှစ်ခု၏ string များကို \"#\" မှတ်သားချက် ပါ/မပါ နှိုင်းယှဉ်ပါ။" },
  widgetTitle: { en: "Can the string tell two trees apart?", my: "string က tree နှစ်ခုကို ခွဲခြားနိုင်သလား" },
  traps: {
    summary: { en: "Four ways the format bites &mdash; worth reading before you code", my: "format ထဲက ချော်လွယ်သည့်နေရာ လေးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>Values alone do not record the shape.</strong> A preorder with no markers writes <code>[1,2]</code> and <code>[1,null,2]</code> both as <code>\"1,2\"</code>: no reader can know whether 2 was a left or a right child. Write a \"#\" for every missing child.", my: "<strong>value များတစ်ခုတည်းက ပုံသဏ္ဌာန်ကို မမှတ်ပါ။</strong> မှတ်သားချက် မပါသော preorder သည် <code>[1,2]</code> နှင့် <code>[1,null,2]</code> နှစ်ခုလုံးကို <code>\"1,2\"</code> အဖြစ် ရေးသည် — 2 သည် ဘယ် သို့မဟုတ် ညာ ကလေးလား ဖတ်သူ မသိနိုင်။ မရှိသော ကလေးတိုင်းအတွက် \"#\" ရေးပါ။" },
      { en: "<strong>Keep a separator between tokens.</strong> Joined with nothing between them, <code>[1,23]</code> and <code>[12,3]</code> both write <code>\"123###\"</code>. Values can have several digits and a minus sign, so a comma — or any character a value cannot contain — has to mark where one ends.", my: "<strong>token များကြားတွင် ခွဲခြားစာလုံး ထားပါ။</strong> ကြားတွင် ဘာမှမပါဘဲ ဆက်လျှင် <code>[1,23]</code> နှင့် <code>[12,3]</code> နှစ်ခုလုံး <code>\"123###\"</code> ရေးသည်။ value များတွင် digit အများအပြားနှင့် minus sign ပါနိုင်သဖြင့် comma — သို့မဟုတ် value တွင် မပါနိုင်သော စာလုံးတစ်ခုခု — က တစ်ခု ဘယ်မှာ ဆုံးသည်ကို မှတ်ရမည်။" },
      { en: "<strong>Do not trim the trailing \"#\"s from a level order.</strong> LeetCode's own format drops them, but a reader that gives each parent the next two tokens then runs off the end: on example 1 the Python listing raises <code>IndexError</code>. Keep them, or check the index before reading.", my: "<strong>level order ၏ နောက်ဆုံး \"#\" များကို မဖြတ်ပါနှင့်။</strong> LeetCode ၏ ကိုယ်ပိုင် format က ၎င်းတို့ကို ဖယ်သော်လည်း parent တစ်ခုစီကို နောက် token နှစ်ခု ပေးသော ဖတ်သူသည် အဆုံးကို ကျော်သွားသည် — ဥပမာ 1 တွင် Python listing က <code>IndexError</code> ဖြစ်သည်။ ၎င်းတို့ကို ထားပါ၊ သို့မဟုတ် မဖတ်မီ index ကို စစ်ပါ။" },
      { en: "<strong>The tree can be a 10<sup>4</sup>-node chain.</strong> A preorder codec recurses that deep in both directions. Measured here on default stacks, cold: Python stops at 1,000 unless the limit is raised; Ruby 3.1 overflows past a chain of 8,185 nodes and Node 24 past 8,881.", my: "<strong>tree သည် node 10<sup>4</sup> ကွင်းဆက် ဖြစ်နိုင်သည်။</strong> preorder codec သည် ဦးတည်ချက် နှစ်ဖက်လုံးတွင် ထိုမျှ နက်အောင် recurse လုပ်သည်။ default stack ပေါ်တွင် cold run ဖြင့် ဤနေရာတွင် တိုင်းတာထားသည် — limit မမြှင့်လျှင် Python သည် 1,000 တွင် ရပ်သည်၊ Ruby 3.1 သည် node 8,185 နှင့် Node 24 သည် 8,881 ကျော်သော ကွင်းဆက်တွင် overflow ဖြစ်သည်။" },
    ],
  },
  part2Sub: { en: "Two formats, each written and then read back. The stage shows the tree — the original while it is written, the rebuilt one as it grows — beside the call stack or the queue, with the token string underneath.", my: "format နှစ်မျိုး၊ တစ်ခုစီကို ရေးပြီး ပြန်ဖတ်သည်။ stage သည် tree ကို ပြသည် — ရေးစဉ် မူလ tree၊ ကြီးထွားလာစဉ် ပြန်တည်ဆောက်ထားသော tree — call stack သို့မဟုတ် queue ဘေးတွင်၊ အောက်တွင် token string။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the codecs raise", my: "codec များနှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why is a preorder with \"#\"s enough, when a preorder alone is not?", my: "preorder တစ်ခုတည်း မလုံလောက်ဘဲ \"#\" များပါသော preorder ဘာကြောင့် လုံလောက်သလဲ။" }, a: { en: "Because the reader never has to guess where a subtree ends. It reads the root, then reads a whole left subtree — which ends exactly when that subtree's own \"#\"s run out — then a whole right subtree. Every token is either a node, whose two subtrees follow, or a \"#\", which is complete by itself, so there is only ever one way to read the string.", my: "ဖတ်သူသည် subtree ဘယ်မှာ ဆုံးသည်ကို ဘယ်တော့မှ ခန့်မှန်းရန် မလိုသောကြောင့်။ root ကို ဖတ်ပြီး ဘယ် subtree တစ်ခုလုံးကို ဖတ်သည် — ၎င်း subtree ၏ ကိုယ်ပိုင် \"#\" များ ကုန်သည့်အခါ အတိအကျ ဆုံးသည် — ပြီးမှ ညာ subtree တစ်ခုလုံး။ token တိုင်းသည် node — ၎င်း၏ subtree နှစ်ခု နောက်မှ လိုက်သည် — သို့မဟုတ် \"#\" — ၎င်းကိုယ်တိုင် ပြည့်စုံသည် — ဖြစ်သဖြင့် string ကို ဖတ်ရန် နည်းလမ်း တစ်ခုတည်းသာ ရှိသည်။" } },
      { q: { en: "Does the string have to look like LeetCode's?", my: "string သည် LeetCode ၏ format နှင့် တူရမည်လား။" }, a: { en: "No. The judge only checks that <code>deserialize(serialize(root))</code> gives back the same tree; the string in between is yours. That is also how this page checked every listing: one codec object serialized, a second deserialized, and the rebuilt tree was compared with the input, 20,014 times per listing.", my: "မလိုပါ။ judge သည် <code>deserialize(serialize(root))</code> က tree တူတူ ပြန်ပေးသည်ကိုသာ စစ်သည် — ကြားရှိ string သည် သင့်ဟာ။ ဤစာမျက်နှာက listing တိုင်းကို စစ်ပုံလည်း ဖြစ်သည် — codec object တစ်ခုက serialize၊ ဒုတိယတစ်ခုက deserialize လုပ်ပြီး ပြန်တည်ဆောက်ထားသော tree ကို input နှင့် listing တစ်ခုလျှင် 20,014 ကြိမ် နှိုင်းယှဉ်သည်။" } },
      { q: { en: "How long is the string?", my: "string မည်မျှ ရှည်သလဲ။" }, a: { en: "Both formats write 2n + 1 tokens for n nodes: every node, and one \"#\" for each of the n + 1 empty child slots a binary tree of n nodes always has. A value is at most five characters (<code>-1000</code>), so with the commas a 10<sup>4</sup>-node tree writes at most about 80 kB.", my: "format နှစ်ခုလုံး node n ခုအတွက် token 2n + 1 ရေးသည် — node တိုင်းနှင့် node n ခုပါ binary tree တွင် အမြဲရှိသော ဗလာ ကလေးနေရာ n + 1 ခုစီအတွက် \"#\" တစ်ခု။ value တစ်ခုသည် စာလုံး ငါးလုံး (<code>-1000</code>) အများဆုံး ဖြစ်သဖြင့် comma များနှင့်အတူ node 10<sup>4</sup> tree သည် 80 kB ခန့် အများဆုံး ရေးသည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "Two formats, the same size, different depth", my: "format နှစ်ခု၊ size တူ၊ အနက် ကွာ" },
    html: { en: "<table>\n  <thead><tr><th>Codec</th><th>Time</th><th>Tokens</th><th>Extra space</th><th>10⁴-node chain</th></tr></thead>\n  <tbody>\n    <tr><td><b>Preorder with # markers</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">recursive, both ways</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">2n + 1</td><td class=\"mono\">O(h) stack</td><td class=\"cross\">10⁴ calls deep</td></tr>\n    <tr><td><b>Level order with a queue</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">iterative, both ways</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">2n + 1</td><td class=\"mono\">O(w) queue</td><td class=\"tick\">no recursion</td></tr>\n  </tbody>\n</table>\n<figcaption>h is the tree's height and w its widest level. Both do the same work and write strings of the same length; what differs is where the pending nodes wait. On a chain h is n; on a complete tree w is about n / 2.</figcaption>", my: "<table>\n  <thead><tr><th>Codec</th><th>အချိန်</th><th>Token</th><th>အပို memory</th><th>node 10⁴ ကွင်းဆက်</th></tr></thead>\n  <tbody>\n    <tr><td><b>Preorder with # markers</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">ဘက်နှစ်ဖက်လုံး recursive</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">2n + 1</td><td class=\"mono\">O(h) stack</td><td class=\"cross\">call 10⁴ ဆင့်</td></tr>\n    <tr><td><b>Level order with a queue</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">ဘက်နှစ်ဖက်လုံး iterative</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">2n + 1</td><td class=\"mono\">O(w) queue</td><td class=\"tick\">recursion မပါ</td></tr>\n  </tbody>\n</table>\n<figcaption>h သည် tree ၏ အမြင့်၊ w သည် အကျယ်ဆုံး level။ နှစ်ခုလုံး အလုပ်တူတူ လုပ်ပြီး အရှည်တူ string ရေးသည် — ကွာသည်မှာ စောင့်နေသော node များ စောင့်ရာ နေရာ။ ကွင်းဆက်တွင် h သည် n — ပြည့်စုံသော tree တွင် w သည် n / 2 ခန့်။</figcaption>" },
  },
  part3Sub: { en: "Two codecs in five languages. Every block is a complete submission, and every one made the same 20,014 round trips, up to 10⁴ nodes; the badges and notes say where the recursion needs more stack.", my: "codec နှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး အားလုံး node 10⁴ အထိ round trip 20,014 ခု တူတူ လုပ်ခဲ့သည် — recursion တွင် stack ပိုလိုသည့်နေရာကို badge နှင့် မှတ်ချက်များက ဖော်ပြသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>root</code> above — level order, <code>null</code> for a missing child, up to 12 nodes, empty for no tree — and both walkthroughs rebuild against it.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>root</code> ကို ပြင်လိုက်လျှင် (level order၊ ကလေး မရှိလျှင် <code>null</code>၊ node 12 ခုအထိ၊ tree မရှိလျှင် ဗလာ) walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
