/* The prose of the Trapping Rain Water page: everything the reader sees that
 * is not interactive. Rendered by src/pages/leetcode/[slug].astro through the
 * Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Trapping Rain Water',
  summary: 'The water over each bar rises to the lower of the tallest bars on either side. Precompute both walls, or walk in from both ends and always settle the lower side — the far wall is known to be tall enough.',
  eyebrow: 'LeetCode 42 &nbsp;·&nbsp; Hard',
  lede: { en: "Work out how much rain a row of bars holds. Look at one bar: water above it can rise until it would spill over one side, so its level is the lower of the tallest bar to its left and the tallest bar to its right. Everything else is bookkeeping — precompute those two walls for every bar, or notice that the lower of two walls, walking in from the ends, is always the one that decides.", my: "bar တန်းတစ်ခု မိုးရေ မည်မျှ ထိန်းသလဲ တွက်ပါ။ bar တစ်ခုကို ကြည့်ပါ — ၎င်းအပေါ်ရှိ ရေသည် တစ်ဖက်ဖက်မှ ဖိတ်မည့်အထိ တက်နိုင်သဖြင့် ၎င်း၏ အမြင့်သည် ဘယ်ဘက် အမြင့်ဆုံး bar နှင့် ညာဘက် အမြင့်ဆုံး bar ထဲမှ နိမ့်သည်။ ကျန်သည်အားလုံး စာရင်းကိုင်ခြင်းသာ — bar တိုင်းအတွက် ထိုနံရံနှစ်ခုကို ကြိုတွက်ပါ၊ သို့မဟုတ် အစွန်များမှ အတွင်းသို့ လျှောက်ရာတွင် နံရံနှစ်ခုထဲမှ နိမ့်သည်က အမြဲ ဆုံးဖြတ်ကြောင်း သတိပြုပါ။" },
  links: [{ id: 42, title: 'Trapping Rain Water', slug: 'trapping-rain-water', difficulty: 'Hard' }],
  constraints: { en: "<span><b>n</b> == height.length</span><span>1 &le; n &le; 2 &times; 10<sup>4</sup></span><span>0 &le; height[i] &le; 10<sup>5</sup></span>", my: "<span><b>n</b> == height.length</span><span>1 &le; n &le; 2 &times; 10<sup>4</sup></span><span>0 &le; height[i] &le; 10<sup>5</sup></span>" },
  part1Sub: { en: "Read the statement, then click a bar and see which wall decides its water.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် bar တစ်ခုကို နှိပ်ပြီး ၎င်း၏ ရေကို မည်သည့် နံရံက ဆုံးဖြတ်သလဲ ကြည့်ပါ။" },
  widgetTitle: { en: "Click a bar, find its lower wall", my: "bar ကို နှိပ်ပါ — ၎င်း၏ နိမ့်သော နံရံကို ရှာပါ" },
  traps: {
    summary: { en: "Three ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ သုံးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>The lower wall, not the higher.</strong> Water spills over the shorter side. Using <code>max(left, right)</code> in place of <code>min</code> gives 22 for example 1 and 14 for example 2, instead of 6 and 9.", my: "<strong>မြင့်သည့် မဟုတ်ဘဲ နိမ့်သော နံရံ။</strong> ရေသည် တိုသည့်ဘက်မှ ဖိတ်သည်။ <code>min</code> အစား <code>max(left, right)</code> သုံးလျှင် ဥပမာ 1 အတွက် 6 အစား 22၊ ဥပမာ 2 အတွက် 9 အစား 14 ရသည်။" },
      { en: "<strong>Both walls count.</strong> A running maximum from the left alone assumes a wall on the right that may not be there: example 1 comes out 11, counting water over bars 8 to 11 that runs off the right edge. Example 2 happens to be right, because its tallest bar is last.", my: "<strong>နံရံ နှစ်ခုလုံး အရေးကြီးသည်။</strong> ဘယ်မှ running maximum တစ်ခုတည်းသည် ညာဘက်တွင် မရှိနိုင်သော နံရံကို ယူဆသည် — ဥပမာ 1 သည် ညာအစွန်မှ စီးထွက်သွားသော bar 8 မှ 11 အပေါ်ရှိ ရေကိုပါ ရေတွက်ပြီး 11 ထွက်သည်။ ဥပမာ 2 သည် ၎င်း၏ အမြင့်ဆုံး bar နောက်ဆုံးတွင် ရှိသဖြင့် တိုက်ဆိုင်စွာ မှန်သည်။" },
      { en: "<strong>Move the lower pointer.</strong> In the two-pointer walk the lower side is the settled one. Moving the taller side instead returns 14 for example 1 and 7 for example 2.", my: "<strong>နိမ့်သော pointer ကို ရွှေ့ပါ။</strong> pointer နှစ်ခု လျှောက်ခြင်းတွင် နိမ့်သည့်ဘက်သည် သတ်မှတ်ပြီးသား ဖြစ်သည်။ မြင့်သည့်ဘက်ကို ရွှေ့လျှင် ဥပမာ 1 အတွက် 14 နှင့် ဥပမာ 2 အတွက် 7 ပြန်ပေးသည်။" },
    ],
  },
  part2Sub: { en: "Two ways to find each bar's lower wall. The strip is height; the stage is the landscape with the water settled so far — for the first version under the two wall arrays it comes from.", my: "bar တစ်ခုစီ၏ နိမ့်သော နံရံကို ရှာရန် နည်းနှစ်မျိုး။ strip သည် height ဖြစ်သည်။ stage သည် ယခုထိ သတ်မှတ်ပြီး ရေပါသော မြေမျက်နှာပြင် ဖြစ်သည် — ပထမ version အတွက် ၎င်းလာရာ နံရံ array နှစ်ခု၏ အောက်တွင်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the water raises", my: "ရေနှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why is the lower side safe to settle?", my: "နိမ့်သည့်ဘက်ကို သတ်မှတ်ရန် ဘာကြောင့် ဘေးကင်းသလဲ။" }, a: { en: "Say height[lo] < height[hi]. Bar lo's water is min(L, R) − height[lo], where L is the tallest bar at or left of lo — that is left_max, and it is final, because the left side has been walked — and R is the tallest bar at or right of lo, which is at least height[hi]. The left pointer only ever moves past a bar lower than some bar on the right, so left_max never exceeds R. The minimum is therefore left_max, and whatever lies between lo and hi can only make R taller, never change the answer.", my: "height[lo] < height[hi] ဟု ဆိုပါစို့။ bar lo ၏ ရေသည် min(L, R) − height[lo] ဖြစ်ပြီး L သည် lo ၏ ဘယ်ဘက် (lo အပါအဝင်) အမြင့်ဆုံး bar — ၎င်းမှာ left_max ဖြစ်ပြီး ဘယ်ဘက်ကို လျှောက်ပြီးသား ဖြစ်သဖြင့် နောက်ဆုံး တန်ဖိုး ဖြစ်သည် — R သည် lo ၏ ညာဘက် (lo အပါအဝင်) အမြင့်ဆုံး bar ဖြစ်ပြီး အနည်းဆုံး height[hi] ဖြစ်သည်။ ဘယ် pointer သည် ညာဘက်ရှိ bar တစ်ခုခုထက် နိမ့်သော bar ကိုသာ ကျော်ရွှေ့သဖြင့် left_max သည် R ကို ဘယ်တော့မှ မကျော်ပါ။ ထို့ကြောင့် minimum သည် left_max ဖြစ်ပြီး lo နှင့် hi ကြားရှိ မည်သည့်အရာကမျှ R ကို ပိုမြင့်စေရုံသာ ဖြစ်ပြီး အဖြေကို မပြောင်းနိုင်ပါ။" } },
      { q: { en: "Does the answer fit in a 32-bit int?", my: "အဖြေသည် 32-bit int ထဲ ဆံ့သလား။" }, a: { en: "Just. The most water is two walls of 10⁵ with 19,998 empty bars between them: 1,999,800,000 units, under 2³¹ − 1 = 2,147,483,647 by about 7%. The verifier runs that case, and the Rust listing's <code>i32</code> holds it. Loosen either constraint and it would not.", my: "ဆံ့ရုံသာ။ အများဆုံး ရေသည် 10⁵ နံရံ နှစ်ခုကြား bar ဗလာ 19,998 — unit 1,999,800,000၊ 2³¹ − 1 = 2,147,483,647 အောက် 7% ခန့်။ verifier က ထို case ကို run ပြီး Rust listing ၏ <code>i32</code> က ဆံ့သည်။ ကန့်သတ်ချက် တစ်ခုခု လျော့လျှင် မဆံ့တော့ပါ။" } },
      { q: { en: "Is there a third way?", my: "တတိယနည်း ရှိသလား။" }, a: { en: "A monotonic stack fills the water in horizontal layers: keep bars in falling height; when a taller bar arrives, the bar it covers becomes a pool floor bounded by the bar before it and the new one. It is O(n) too, and it is the oracle the verifier checks both listings against here.", my: "monotonic stack သည် ရေကို အလွှာ အလျားလိုက် ဖြည့်သည် — bar များကို ကျဆင်းသော အမြင့်ဖြင့် ထား — ပိုမြင့်သော bar ရောက်လာလျှင် ၎င်း ဖုံးသော bar သည် ၎င်း၏ ရှေ့ bar နှင့် အသစ်ကြားရှိ ရေကန် ကြမ်းပြင် ဖြစ်လာသည်။ ၎င်းလည်း O(n) ဖြစ်ပြီး ဤနေရာတွင် verifier က listing နှစ်ခုလုံးကို စစ်သည့် oracle ဖြစ်သည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "The same O(n), without the arrays", my: "O(n) အတူတူ — array မပါ" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>Passes over height</th></tr></thead>\n  <tbody>\n    <tr><td><b>Wall arrays</b><br><span class=\"sub\">prefix and suffix maxima</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(n)</td><td>3</td></tr>\n    <tr><td><b>Two pointers</b></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(1)</td><td class=\"tick\">1</td></tr>\n  </tbody>\n</table>\n<figcaption>Both are linear and both are fast at the constraint; the difference is memory — two arrays of 2 × 10⁴ against four numbers — and one pass instead of three. Counts are computed, not timed.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>height ပေါ် pass</th></tr></thead>\n  <tbody>\n    <tr><td><b>Wall arrays</b><br><span class=\"sub\">prefix နှင့် suffix maxima</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(n)</td><td>3</td></tr>\n    <tr><td><b>Two pointers</b></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(1)</td><td class=\"tick\">1</td></tr>\n  </tbody>\n</table>\n<figcaption>နှစ်ခုလုံး linear ဖြစ်ပြီး ကန့်သတ်ချက်တွင် နှစ်ခုလုံး မြန်သည် — ကွာခြားချက်မှာ memory — 2 × 10⁴ array နှစ်ခု နှင့် ဂဏန်း လေးလုံး — နှင့် pass သုံးခုအစား တစ်ခု။ အရေအတွက်များကို တွက်ထားခြင်းဖြစ်ပြီး အချိန် မတိုင်းထားပါ။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission, and every one was run against the same 20,012 landscapes, up to 2 × 10⁴ bars.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး အားလုံးကို bar 2 × 10⁴ အထိ မြေမျက်နှာပြင် 20,012 ခု တူတူဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>height</code> above — up to 14 bars, 0 to 8 tall — and both walkthroughs rebuild against it.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>height</code> ကို ပြင်လိုက်လျှင် (bar 14 ခုအထိ၊ 0 မှ 8 မြင့်) walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
