/* The prose of the Invert Binary Tree page: everything the reader sees that is not
 * interactive. Rendered by src/pages/leetcode/[slug].astro through the
 * Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Invert Binary Tree',
  summary: 'Swap every node\'s children, by recursion or with a queue. Both do the same n swaps; one pays for the tree\'s height, the other for its width.',
  eyebrow: 'LeetCode 226 &nbsp;·&nbsp; Easy',
  lede: { en: "Turn a binary tree into its mirror image. The work is one swap per node; the whole question is how you keep track of the nodes still waiting — on the call stack, or in a queue.", my: "binary tree တစ်ခုကို ၎င်း၏ ကြေးမုံပုံ ဖြစ်အောင် ပြောင်းပါ။ အလုပ်မှာ node တစ်ခုလျှင် လဲခြင်း တစ်ကြိမ်သာ — မေးခွန်း တစ်ခုလုံးမှာ စောင့်နေဆဲ node များကို call stack ပေါ်တွင်လား၊ queue ထဲတွင်လား ဘယ်လို မှတ်ထားမလဲ ဆိုသည်ပင်။" },
  links: [{ id: 226, title: 'Invert Binary Tree', slug: 'invert-binary-tree', difficulty: 'Easy' }],
  constraints: { en: "<span><b>n</b> the number of nodes in the tree is in the range [0, 100]</span><span>&minus;100 &le; Node.val &le; 100</span>", my: "<span><b>n</b> tree ထဲရှိ node အရေအတွက်သည် [0, 100] အတွင်း</span><span>&minus;100 &le; Node.val &le; 100</span>" },
  part1Sub: { en: "Read the statement, then swap the tree one level at a time and see when it becomes LeetCode's answer.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် tree ကို အဆင့်တစ်ဆင့်ချင်း လဲကြည့်ပြီး ဘယ်အချိန်မှာ LeetCode ၏ အဖြေ ဖြစ်လာသလဲ ကြည့်ပါ။" },
  widgetTitle: { en: "Drag how deep the swaps go", my: "လဲခြင်း မည်မျှ နက်သလဲ ဆွဲကြည့်ပါ" },
  traps: {
    summary: { en: "Four ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ လေးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>\"Invert\" means mirror, at every depth.</strong> The statement never defines it; the examples do. Swapping only the root's two subtrees gets the top level right and every level below it wrong — drag the widget to one level and compare.", my: "<strong>\"Invert\" ဆိုသည်မှာ အနက်တိုင်းတွင် ကြေးမုံပုံ ဖြစ်စေခြင်း ဖြစ်သည်။</strong> မေးခွန်းက အဓိပ္ပာယ် မဖွင့်ဆိုပါ၊ ဥပမာများက ဖွင့်ဆိုသည်။ root ၏ subtree နှစ်ခုကိုသာ လဲလျှင် ထိပ်ဆုံး အဆင့် မှန်ပြီး အောက်ရှိ အဆင့်တိုင်း မှားမည် — widget ကို တစ်ဆင့်သို့ ဆွဲပြီး နှိုင်းယှဉ်ကြည့်ပါ။" },
      { en: "<strong>Don't overwrite a child before you've read it.</strong> <code>root.left = invert(root.right); root.right = invert(root.left)</code> looks symmetrical, but by the second line <code>root.left</code> is already the inverted right subtree — the old left is gone. On example 1 it returns <code>[4,7,7,9,9,9,9]</code>. Swap both at once (a tuple assignment), or save one side first.", my: "<strong>ကလေးကို မဖတ်ရသေးမီ ထပ်မရေးပါနှင့်။</strong> <code>root.left = invert(root.right); root.right = invert(root.left)</code> သည် အချိုးညီသလို ထင်ရသော်လည်း ဒုတိယ စာကြောင်းရောက်ချိန်တွင် <code>root.left</code> သည် ပြောင်းပြန်လှန်ပြီးသော ညာဘက် subtree ဖြစ်နေပြီ — ဘယ်ဘက် အဟောင်း ပျောက်သွားပြီ။ ဥပမာ 1 တွင် ၎င်းက <code>[4,7,7,9,9,9,9]</code> ကို ပြန်ပေးသည်။ နှစ်ခုလုံးကို တစ်ပြိုင်နက် လဲပါ (tuple assignment)၊ သို့မဟုတ် တစ်ဖက်ကို အရင် သိမ်းထားပါ။" },
      { en: "<strong>In-order traversal inverts one subtree twice.</strong> Recurse left, swap, recurse right: after the swap, \"right\" is the subtree you have just inverted, so it is flipped back, and the old right is never touched. On example 1 that returns <code>[4,7,2,6,9,1,3]</code>. Swap first (pre-order) or last (post-order); in-order only works if the second call goes left again.", my: "<strong>In-order traversal သည် subtree တစ်ခုကို နှစ်ကြိမ် ပြောင်းပြန်လှန်သည်။</strong> ဘယ်သို့ recurse၊ လဲ၊ ညာသို့ recurse — လဲပြီးနောက် \"ညာ\" သည် ပြောင်းပြန်လှန်ပြီးခါစ subtree ဖြစ်သဖြင့် ပြန်လှန်မိပြီး ညာဘက် အဟောင်းကို လုံးဝ မထိမိပါ။ ဥပမာ 1 တွင် ၎င်းက <code>[4,7,2,6,9,1,3]</code> ကို ပြန်ပေးသည်။ အရင် လဲပါ (pre-order) သို့မဟုတ် နောက်မှ လဲပါ (post-order) — in-order သည် ဒုတိယ call က ဘယ်ဘက်သို့ ထပ်သွားမှသာ အလုပ်ဖြစ်သည်။" },
      { en: "The tree can be empty — example 3 is <code>[]</code>. Return null without dereferencing it; the recursion's base case and an empty starting queue both handle it with no special code.", my: "tree ဗလာ ဖြစ်နိုင်သည် — ဥပမာ 3 မှာ <code>[]</code> ဖြစ်သည်။ ၎င်းကို မဖတ်ဘဲ null ပြန်ပေးပါ — recursion ၏ base case နှင့် ဗလာဖြင့် စသော queue တို့က သီးခြား code မလိုဘဲ ကိုင်တွယ်သည်။" },
    ],
  },
  part2Sub: { en: "Two approaches over the same tree. The stage shows the tree and what each approach is holding; the panel shows the line running.", my: "tree တစ်ခုတည်းပေါ်တွင် နည်းလမ်းနှစ်မျိုး။ ဘယ်ဘက်က tree နှင့် နည်းတစ်ခုစီ ကိုင်ထားသည့်အရာကို ပြပြီး ညာဘက် panel က အလုပ်လုပ်နေသော code ကြောင်းကို ပြသည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the swap raises", my: "လဲခြင်းနှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why is one swap per node enough?", my: "node တစ်ခုလျှင် လဲခြင်း တစ်ကြိမ် ဘာကြောင့် လုံလောက်သလဲ။" }, a: { en: "Because the mirror of a tree is: the same root, with the mirror of its right subtree on the left and the mirror of its left subtree on the right. Unfold that definition and every node appears exactly once, with its two children swapped. Nothing else changes — no value moves, no node is created, and the root stays on top.", my: "tree တစ်ခု၏ ကြေးမုံပုံဆိုသည်မှာ — root အတူတူ၊ ဘယ်ဘက်တွင် ညာ subtree ၏ ကြေးမုံပုံ၊ ညာဘက်တွင် ဘယ် subtree ၏ ကြေးမုံပုံ ဖြစ်သောကြောင့် ဖြစ်သည်။ ထိုအဓိပ္ပာယ်ကို ဖြန့်ကြည့်လျှင် node တိုင်း တစ်ကြိမ်စီ ပေါ်ပြီး ကလေး နှစ်ခု လဲထားသည်။ အခြား ဘာမျှ မပြောင်းပါ — value မရွှေ့၊ node အသစ် မဖန်တီး၊ root သည် ထိပ်ဆုံးတွင် ရှိနေဆဲ။" } },
      { q: { en: "Stack or queue — which uses less memory?", my: "Stack လား queue လား — ဘယ်ဟာက memory နည်းနည်း သုံးသလဲ။" }, a: { en: "It depends on the tree's shape, which is the real contrast here. The recursion holds one frame per level of the current path, so it costs the tree's <em>height</em>: 8 frames for a balanced 100-node tree, 101 for a chain (counting the last call, on null). The queue holds a level's worth of nodes, so it costs the tree's <em>width</em>: 50 for the balanced tree, 1 for the chain. Deep and narrow favours the queue; shallow and wide favours the recursion.", my: "tree ၏ ပုံသဏ္ဌာန်ပေါ် မူတည်သည် — ဤနေရာ၏ တကယ့် ကွာခြားချက်ပင်။ recursion သည် လက်ရှိ လမ်းကြောင်း၏ အဆင့်တစ်ခုလျှင် frame တစ်ခု ကိုင်သဖြင့် tree ၏ <em>အမြင့်</em> ကုန်သည် — ညီမျှသော node 100 tree အတွက် frame 8၊ ကွင်းဆက်အတွက် 101 (null ပေါ်ရှိ နောက်ဆုံး call ပါ ရေတွက်လျှင်)။ queue သည် အဆင့်တစ်ခုစာ node များ ကိုင်သဖြင့် tree ၏ <em>အကျယ်</em> ကုန်သည် — ညီမျှသော tree အတွက် 50၊ ကွင်းဆက်အတွက် 1။ နက်ပြီး ကျဉ်းလျှင် queue သာသည်၊ တိမ်ပြီး ကျယ်လျှင် recursion သာသည်။" } },
      { q: { en: "Where else does \"do it at every node\" show up?", my: "\"node တိုင်းတွင် လုပ်ပါ\" ဆိုသည့်ပုံစံ နောက်ထပ် ဘယ်မှာ တွေ့ရမလဲ။" }, a: { en: "It is the shape of most easy tree problems: answer the question for one node using the answers for its two subtrees. <strong>Maximum Depth of Binary Tree</strong> is one plus the larger child depth; <strong>Same Tree</strong> compares two roots and recurses in step; <strong>Symmetric Tree</strong> asks whether a tree equals its own mirror — this problem, used as a check.", my: "easy tree ပြဿနာ အများစု၏ ပုံစံ ဖြစ်သည် — subtree နှစ်ခု၏ အဖြေကို သုံး၍ node တစ်ခုအတွက် မေးခွန်းကို ဖြေခြင်း။ <strong>Maximum Depth of Binary Tree</strong> သည် ကလေး၏ ပိုနက်သော အနက်ကို တစ်ပေါင်းခြင်း၊ <strong>Same Tree</strong> သည် root နှစ်ခုကို နှိုင်းယှဉ်ပြီး တပြိုင်နက် recurse လုပ်ခြင်း၊ <strong>Symmetric Tree</strong> သည် tree တစ်ခုက ၎င်း၏ ကြေးမုံပုံနှင့် တူသလား မေးခြင်း — ဤပြဿနာကို စစ်ဆေးရန် သုံးခြင်း ဖြစ်သည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "The same swaps, a different memory bill", my: "လဲခြင်း အတူတူ၊ memory ကုန်ကျမှု မတူ" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>Balanced, 100 nodes</th><th>A 100-node chain</th></tr></thead>\n  <tbody>\n    <tr><td><b>Recursive DFS</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">the call stack</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(h)</td><td class=\"tick\">8 frames</td><td class=\"cross\">101 frames</td></tr>\n    <tr><td><b>Iterative BFS</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">a queue</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(w)</td><td class=\"cross\">50 nodes</td><td class=\"tick\">1 node</td></tr>\n  </tbody>\n</table>\n<figcaption>Counted by simulating both on a complete 100-node tree and a 100-node chain, not timed; h is the height and w the widest level. The stack counts the final call on null. Both make exactly n swaps. At this problem's size neither cost matters — 101 frames is nothing — but on a deep tree of 10⁵ nodes the recursion is the one that overflows.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>ညီမျှ၊ node 100</th><th>node 100 ကွင်းဆက်</th></tr></thead>\n  <tbody>\n    <tr><td><b>Recursive DFS</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">call stack</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(h)</td><td class=\"tick\">frame 8</td><td class=\"cross\">frame 101</td></tr>\n    <tr><td><b>Iterative BFS</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">queue</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(w)</td><td class=\"cross\">node 50</td><td class=\"tick\">node 1</td></tr>\n  </tbody>\n</table>\n<figcaption>ပြည့်စုံသော node 100 tree နှင့် node 100 ကွင်းဆက်ပေါ်တွင် နှစ်ခုလုံးကို simulate လုပ်၍ ရေတွက်ထားခြင်းဖြစ်ပြီး အချိန် မတိုင်းထားပါ — h သည် အမြင့်၊ w သည် အကျယ်ဆုံး အဆင့် ဖြစ်သည်။ stack တွင် null ပေါ်ရှိ နောက်ဆုံး call ပါ ရေတွက်ထားသည်။ နှစ်ခုစလုံး လဲခြင်း n ကြိမ် အတိအကျ လုပ်သည်။ ဤပြဿနာ၏ အရွယ်တွင် မည်သည့်ကုန်ကျမှုမျှ အရေးမကြီးပါ — frame 101 ဆိုသည်မှာ ဘာမျှ မဟုတ်ပါ — သို့သော် node 10⁵ ရှိ နက်သော tree တွင် overflow ဖြစ်မည်မှာ recursion ဖြစ်သည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission, and every one was run against the same 20,010 cases.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး အားလုံးကို case 20,010 ခု တူတူဖြင့် run ထားသည်။" },
  footer: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>root</code> above — level order, <code>null</code> for a missing child, up to 15 nodes — and both walkthroughs rebuild against your tree.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>root</code> ကို ပြင်လိုက်လျှင် (level order၊ ကလေး မရှိလျှင် <code>null</code>၊ node 15 ခုအထိ) walkthrough နှစ်ခုစလုံး သင့် tree ဖြင့် ပြန်တည်ဆောက်မည်။" },
};
