/* The prose of the Implement Trie page: everything the reader sees that is
 * not interactive. Rendered by src/pages/leetcode/[slug].astro through the
 * Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Implement Trie (Prefix Tree)',
  summary: 'Store words letter by letter along paths from a root so shared beginnings share nodes. Every call becomes a walk of one link per letter, and an end mark tells a stored word from the start of a longer one.',
  eyebrow: 'LeetCode 208 &nbsp;·&nbsp; Medium',
  lede: { en: "Build a store of words that answers two questions fast: was this exact word added, and does any added word start with this prefix? A set of words answers the first in one lookup but has to look at every word for the second. A trie spells each word out along a path from a root, so both questions become a walk down the tree, one link per letter, however many words it holds.", my: "မေးခွန်းနှစ်ခုကို မြန်မြန် ဖြေသော word သိုလှောင်မှုတစ်ခု တည်ဆောက်ပါ — ဤ word အတိအကျကို ထည့်ခဲ့သလား၊ ထည့်ခဲ့သော word တစ်ခုခုသည် ဤ prefix ဖြင့် စသလား။ word set တစ်ခုသည် ပထမကို lookup တစ်ကြိမ်ဖြင့် ဖြေသော်လည်း ဒုတိယအတွက် word တိုင်းကို ကြည့်ရသည်။ trie သည် word တစ်ခုစီကို root မှ လမ်းကြောင်းတစ်လျှောက် စာလုံးပေါင်းသဖြင့် word မည်မျှ ကိုင်ထားပါစေ မေးခွန်းနှစ်ခုလုံးသည် tree အောက်သို့ စာလုံးတစ်ခုလျှင် link တစ်ခု လျှောက်ခြင်း ဖြစ်လာသည်။" },
  links: [{ id: 208, title: 'Implement Trie (Prefix Tree)', slug: 'implement-trie-prefix-tree', difficulty: 'Medium' }],
  constraints: { en: "<span>1 &le; word.length, prefix.length &le; 2000</span><span>lowercase English letters only</span><span>at most 3 &times; 10<sup>4</sup> calls in total</span>", my: "<span>1 &le; word.length, prefix.length &le; 2000</span><span>အင်္ဂလိပ် စာလုံးအသေးသာ</span><span>စုစုပေါင်း call အများဆုံး 3 &times; 10<sup>4</sup></span>" },
  part1Sub: { en: "Read the statement, then type a prefix and watch which words share it.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် prefix တစ်ခု ရိုက်ပြီး မည်သည့် word များက မျှသုံးသလဲ ကြည့်ပါ။" },
  widgetTitle: { en: "Type a prefix, see who shares it", my: "prefix ရိုက်ပါ — မည်သူ မျှသုံးသလဲ ကြည့်ပါ" },
  traps: {
    summary: { en: "Three ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ သုံးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>search needs the end mark.</strong> A search that only checks the walk succeeds finds \"app\" inside \"apple\": example 1 returns <code>[null,null,true,true,true,null,true]</code> — true for <code>search(\"app\")</code> before \"app\" was ever inserted.", my: "<strong>search သည် end အမှတ်ကို လိုသည်။</strong> walk အောင်မြင်ခြင်းကိုသာ စစ်သော search သည် \"apple\" အတွင်းရှိ \"app\" ကို တွေ့သည် — ဥပမာ 1 သည် <code>[null,null,true,true,true,null,true]</code> ပြန်ပေးသည် — \"app\" ကို မထည့်ရသေးမီ <code>search(\"app\")</code> အတွက် true။" },
      { en: "<strong>startsWith must ignore it.</strong> The opposite slip — a prefix query that also asks for the end mark — makes startsWith a second search: example 1 returns <code>[null,null,true,false,false,null,true]</code>, false for <code>startsWith(\"app\")</code> although \"apple\" starts with it.", my: "<strong>startsWith သည် ၎င်းကို လျစ်လျူရှုရမည်။</strong> ဆန့်ကျင်ဘက် အမှား — end အမှတ်ကိုပါ တောင်းသော prefix query — သည် startsWith ကို ဒုတိယ search ဖြစ်စေသည် — ဥပမာ 1 သည် <code>[null,null,true,false,false,null,true]</code> ပြန်ပေးသည် — \"apple\" သည် ၎င်းဖြင့် စသော်လည်း <code>startsWith(\"app\")</code> အတွက် false။" },
      { en: "<strong>Reuse a child that is already there.</strong> An insert that always makes a fresh node for each letter replaces the branch it walks: after <code>insert(\"apple\")</code> and <code>insert(\"app\")</code>, <code>search(\"apple\")</code> and <code>startsWith(\"appl\")</code> both return <code>false</code>.", my: "<strong>ရှိပြီးသား child ကို ပြန်သုံးပါ။</strong> စာလုံးတစ်ခုစီအတွက် node အသစ် အမြဲလုပ်သော insert သည် ၎င်းလျှောက်သော အကိုင်းကို အစားထိုးသည် — <code>insert(\"apple\")</code> နှင့် <code>insert(\"app\")</code> ပြီးနောက် <code>search(\"apple\")</code> နှင့် <code>startsWith(\"appl\")</code> နှစ်ခုလုံး <code>false</code> ပြန်ပေးသည်။" },
    ],
  },
  part2Sub: { en: "Two ways to store the words. The strip is the sequence of calls; the stage is the store — a set of whole words, or the trie drawn one node per row, indented by depth, with the prefix each node stands for.", my: "word များကို သိမ်းရန် နည်းလမ်းနှစ်မျိုး။ strip သည် call များ၏ အစီအစဉ် ဖြစ်သည်။ stage သည် သိုလှောင်မှု — word အပြည့် set တစ်ခု၊ သို့မဟုတ် row တစ်ခုလျှင် node တစ်ခု၊ အနက်အလိုက် အတွင်းသို့ ဝင်ပြီး node တစ်ခုစီ ကိုယ်စားပြုသော prefix ပါသည့် trie။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the trie raises", my: "trie နှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Map or array of 26 for the children?", my: "child များအတွက် map လား၊ 26 ခု array လား။" }, a: { en: "Both work. An array indexed by <code>ch - 'a'</code> is fastest and needs no hashing, but every node carries 26 slots even when it has one child — Go and Rust use it here, as is usual in those languages. A map stores only the children that exist, which is what the Python, Ruby and JavaScript listings do. The walk is the same either way.", my: "နှစ်ခုလုံး အလုပ်ဖြစ်သည်။ <code>ch - 'a'</code> ဖြင့် index လုပ်သော array သည် အမြန်ဆုံးဖြစ်ပြီး hashing မလိုသော်လည်း child တစ်ခုသာ ရှိသည့်အခါပင် node တိုင်းတွင် slot 26 ခု ပါသည် — Go နှင့် Rust သည် ထိုဘာသာစကားများတွင် ပုံမှန်ဖြစ်သကဲ့သို့ ဤနေရာတွင် ၎င်းကို သုံးသည်။ map သည် ရှိသော child များကိုသာ သိမ်းပြီး Python၊ Ruby နှင့် JavaScript listing များက ထိုသို့ လုပ်သည်။ walk သည် မည်သို့ပင်ဖြစ်စေ အတူတူ။" } },
      { q: { en: "Why share one walk between search and startsWith?", my: "search နှင့် startsWith ကြား walk တစ်ခုကို ဘာကြောင့် မျှသုံးသလဲ။" }, a: { en: "They ask the same thing up to the last letter — is there a path spelling this string? — and differ only in what they need at the end: search needs a word to finish there, startsWith does not. Writing the walk once keeps the two traps above from creeping in separately.", my: "၎င်းတို့သည် နောက်ဆုံးစာလုံးအထိ တူညီသောအရာကို မေးသည် — ဤ string ကို စာလုံးပေါင်းသော လမ်းကြောင်း ရှိသလား — အဆုံးတွင် လိုအပ်သည့်အရာသာ ကွဲသည် — search သည် word တစ်ခု ထိုနေရာတွင် ဆုံးရန် လိုပြီး startsWith မလို။ walk ကို တစ်ကြိမ်သာ ရေးခြင်းက အထက်ပါ ချော်လွယ်ချက် နှစ်ခု သီးခြားစီ ဝင်မလာစေရန် ကာကွယ်သည်။" } },
      { q: { en: "When is a trie worth its memory?", my: "trie သည် ၎င်း၏ memory နှင့် ဘယ်အချိန်တွင် တန်သလဲ။" }, a: { en: "When prefix questions are frequent: autocomplete, word games (Word Search II builds one of these to prune its search), routing tables. For exact lookups alone a hash set is simpler and smaller. Words with long shared beginnings make a trie cheap; unrelated long words make it a chain of single-child nodes, one per letter.", my: "prefix မေးခွန်းများ မကြာခဏ ရှိသည့်အခါ — autocomplete၊ word game များ (Word Search II သည် ၎င်း၏ ရှာဖွေမှုကို ချုံ့ရန် ဤအရာတစ်ခု တည်ဆောက်သည်)၊ routing table များ။ အတိအကျ lookup သက်သက်အတွက် hash set သည် ပိုရိုးရှင်းပြီး ပိုသေးသည်။ ရှည်လျားသော တူညီသည့် အစများ ပါသော word များက trie ကို သက်သာစေသည် — မဆက်စပ်သော ရှည်လျားသည့် word များက ၎င်းကို စာလုံးတစ်ခုလျှင် တစ်ခု၊ child တစ်ခုတည်းရှိ node ကွင်းဆက် ဖြစ်စေသည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "Prefix queries without the scan", my: "scan မပါသော prefix query" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>insert · search</th><th>startsWith</th><th>10,000 words, 20,000 missing prefixes</th></tr></thead>\n  <tbody>\n    <tr><td><b>Word set</b><br><span class=\"sub\">no trie</span></td>\n        <td class=\"mono\">O(L)</td><td class=\"mono\">O(words · p)</td><td class=\"cross\">6.31 s</td></tr>\n    <tr><td><b>Trie</b><br><span class=\"sub\">prefix tree</span></td>\n        <td class=\"mono\">O(L)</td><td class=\"mono\">O(p)</td><td class=\"tick\">0.02 s</td></tr>\n  </tbody>\n</table>\n<figcaption>Measured here: the Python listings on an Apple M5 Pro, whole process, best of three. L is the word's length, p the prefix's. Every prefix starts with letters no stored word has, so the set checks all 10,000 words on each of the 20,000 queries and the trie stops at the first missing letter.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>insert · search</th><th>startsWith</th><th>word 10,000၊ မရှိသော prefix 20,000</th></tr></thead>\n  <tbody>\n    <tr><td><b>Word set</b><br><span class=\"sub\">trie မဟုတ်</span></td>\n        <td class=\"mono\">O(L)</td><td class=\"mono\">O(words · p)</td><td class=\"cross\">6.31 s</td></tr>\n    <tr><td><b>Trie</b><br><span class=\"sub\">prefix tree</span></td>\n        <td class=\"mono\">O(L)</td><td class=\"mono\">O(p)</td><td class=\"tick\">0.02 s</td></tr>\n  </tbody>\n</table>\n<figcaption>ဤနေရာတွင် တိုင်းတာထားသည် — Apple M5 Pro ပေါ်ရှိ Python listing များ၊ process တစ်ခုလုံး၊ သုံးကြိမ်အနက် အကောင်းဆုံး။ L သည် word ၏ အရှည်၊ p သည် prefix ၏ အရှည်။ prefix တိုင်းသည် သိမ်းထားသော မည်သည့် word တွင်မျှ မရှိသော စာလုံးများဖြင့် စသဖြင့် set သည် query 20,000 တိုင်းတွင် word 10,000 လုံးကို စစ်ပြီး trie သည် ပထမဆုံး မရှိသော စာလုံးတွင် ရပ်သည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission, and every one was run against the same 20,011 call sequences, up to 3 × 10⁴ calls and 2,000-letter words.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး အားလုံးကို call 3 × 10⁴ နှင့် စာလုံး 2,000 word အထိ call အစီအစဉ် 20,011 ခု တူတူဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit the calls above — <code>insert(apple), search(app), startsWith(ap)</code>, up to 8 of them, words up to 6 letters — and both walkthroughs rebuild against them.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က call များ — <code>insert(apple), search(app), startsWith(ap)</code>၊ 8 ခုအထိ၊ word စာလုံး 6 လုံးအထိ — ကို ပြင်လိုက်လျှင် walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
