/* The prose of the Merge Intervals page: everything the reader sees that is
 * not interactive. Rendered by src/pages/leetcode/[slug].astro through the
 * Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Merge Intervals',
  summary: 'Unsorted, every new interval has to be checked against every merged one. Sorted by start, it can only overlap the last one — so the merge is one pass after the sort.',
  eyebrow: 'LeetCode 56 &nbsp;·&nbsp; Medium',
  lede: { en: "Merge every group of overlapping intervals into one. Taken in the order given, a new interval could overlap any interval merged so far. Sorted by start, it can only reach the last one — everything earlier ended before that one began — and the merge becomes a single pass.", my: "overlap ဖြစ်သော interval အုပ်စုတိုင်းကို တစ်ခုတည်း အဖြစ် ပေါင်းပါ။ ပေးထားသည့် အစီအစဉ်အတိုင်း ယူလျှင် interval အသစ်သည် ယခုထိ ပေါင်းခဲ့သမျှ မည်သည့်တစ်ခုနှင့်မဆို overlap ဖြစ်နိုင်သည်။ start ဖြင့် sort လုပ်လျှင် နောက်ဆုံးတစ်ခုကိုသာ ရောက်နိုင်သည် — ယခင်တို့ အားလုံး ၎င်းမစမီ ဆုံးပြီးဖြစ်သည် — ပေါင်းခြင်းသည် တစ်ကြိမ်တည်း ဖြတ်ခြင်း ဖြစ်လာသည်။" },
  links: [{ id: 56, title: 'Merge Intervals', slug: 'merge-intervals', difficulty: 'Medium' }],
  constraints: { en: "<span><b>n</b> 1 &le; intervals.length &le; 10&#8308;</span><span>0 &le; start<sub>i</sub> &le; end<sub>i</sub> &le; 10&#8308;</span><span>any order</span>", my: "<span><b>n</b> 1 &le; intervals.length &le; 10&#8308;</span><span>0 &le; start<sub>i</sub> &le; end<sub>i</sub> &le; 10&#8308;</span><span>မည်သည့် အစီအစဉ်မဆို</span>" },
  part1Sub: { en: "Read the statement, then move two intervals toward each other and find the exact moment they count as overlapping.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် interval နှစ်ခုကို တစ်ခုဆီ တစ်ခု ရွှေ့ပြီး overlap ဟု ရေတွက်သည့် အချိန်အတိအကျကို ရှာပါ။" },
  widgetTitle: { en: "Drag the ends, find where they overlap", my: "အစွန်းများကို ဆွဲပါ — overlap ဖြစ်သည့်နေရာ ရှာပါ" },
  traps: {
    summary: { en: "Four ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ လေးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>Touching counts as overlapping.</strong> Example 2 merges <code>[1,4]</code> and <code>[4,5]</code>. Compare with <code>lo &lt; last end</code> instead of <code>&lt;=</code> and it returns <code>[[1,4],[4,5]]</code>.", my: "<strong>ထိရုံလည်း overlap ဟု ရေတွက်သည်။</strong> ဥပမာ 2 သည် <code>[1,4]</code> နှင့် <code>[4,5]</code> ကို ပေါင်းသည်။ <code>&lt;=</code> အစား <code>lo &lt; last end</code> ဖြင့် နှိုင်းယှဉ်လျှင် <code>[[1,4],[4,5]]</code> ကို ပြန်ပေးသည်။" },
      { en: "<strong>The input is not sorted.</strong> Example 3 is <code>[[4,7],[1,4]]</code>. The sweep without its sort returns <code>[[4,7]]</code>: it extends <code>[4,7]</code> by <code>[1,4]</code> and never moves the start back to 1.", my: "<strong>input ကို sort မလုပ်ထားပါ။</strong> ဥပမာ 3 သည် <code>[[4,7],[1,4]]</code>။ sort မပါသော sweep သည် <code>[[4,7]]</code> ကို ပြန်ပေးသည် — <code>[4,7]</code> ကို <code>[1,4]</code> ဖြင့် ချဲ့ပြီး start ကို 1 သို့ ဘယ်တော့မှ မရွှေ့ပါ။" },
      { en: "<strong>An interval can sit inside another.</strong> Setting the last end to the new <code>hi</code> instead of <code>max(last end, hi)</code> shrinks <code>[1,10]</code> when <code>[2,3]</code> arrives: <code>[[1,10],[2,3],[4,5]]</code> comes back as <code>[[1,3],[4,5]]</code>.", my: "<strong>interval တစ်ခုသည် အခြားတစ်ခုအတွင်း ရှိနိုင်သည်။</strong> <code>max(last end, hi)</code> အစား last end ကို <code>hi</code> အသစ်ဟု သတ်မှတ်လျှင် <code>[2,3]</code> ရောက်လာသည့်အခါ <code>[1,10]</code> ကျုံ့သွားသည် — <code>[[1,10],[2,3],[4,5]]</code> သည် <code>[[1,3],[4,5]]</code> ဖြစ်လာသည်။" },
      { en: "<strong>Covering the same integers is not overlapping.</strong> <code>[1,3]</code> and <code>[4,6]</code> between them cover 1 to 6 with no integer missing, but they share no point, so they stay apart.", my: "<strong>ကိန်းပြည့်တူများကို ဖုံးခြင်းသည် overlap မဟုတ်ပါ။</strong> <code>[1,3]</code> နှင့် <code>[4,6]</code> နှစ်ခုပေါင်း 1 မှ 6 အထိ ကိန်းပြည့် တစ်လုံးမျှ မလွတ်ဘဲ ဖုံးသော်လည်း တူသော point မရှိသဖြင့် ခွဲနေသည်။" },
    ],
  },
  part2Sub: { en: "Two approaches over the same intervals. The stage is a timeline — the interval being placed above the ones merged so far; the panel shows the line running.", my: "interval တူတူပေါ်တွင် နည်းလမ်းနှစ်မျိုး။ ဘယ်ဘက်မှာ timeline — ယခုထိ ပေါင်းပြီးသည်တို့၏ အပေါ်တွင် နေရာချနေသော interval — ဖြစ်ပြီး ညာဘက် panel က အလုပ်လုပ်နေသော code ကြောင်းကို ပြသည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the sweep raises", my: "sweep နှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why is the last merged interval the only one worth checking?", my: "နောက်ဆုံး ပေါင်းထားသည့် interval ကိုသာ ဘာကြောင့် စစ်ရန် တန်သလဲ။" }, a: { en: "After sorting, merged intervals come out in order and do not overlap, so each one ends before the next one starts. A new interval starts no earlier than every interval before it, so if it misses the last merged interval, it starts after that one's end — and every earlier interval ended sooner still.", my: "sort ပြီးနောက် ပေါင်းထားသော interval များသည် အစဉ်လိုက် ထွက်လာပြီး overlap မဖြစ်သဖြင့် တစ်ခုစီသည် နောက်တစ်ခု မစမီ ဆုံးသည်။ interval အသစ်သည် ၎င်းရှေ့ရှိ interval တိုင်းထက် စောပြီး မစ — နောက်ဆုံး ပေါင်းထားသည့် တစ်ခုကို မထိလျှင် ၎င်း၏ အဆုံးပြီးမှ စပြီး ယခင် interval တိုင်းက ပိုစောစွာ ဆုံးခဲ့ပြီးဖြစ်သည်။" } },
      { q: { en: "Without sorting, why can one new interval absorb several merged ones?", my: "sort မလုပ်လျှင် interval အသစ်တစ်ခုက ပေါင်းပြီးသား အများအပြားကို ဘာကြောင့် ပေါင်းယူနိုင်သလဲ။" }, a: { en: "Because it can bridge a gap. Load <em>A bridge</em>: [1,3], [8,10] and [5,6] stay apart until [2,9] arrives and overlaps all of them, and the brute force folds the three into it — [1,10] — in one visit. It never has to look again: merged intervals share no point, so the grown interval is exactly their union, and anything it missed it still misses.", my: "gap တစ်ခုကို ဆက်ပေးနိုင်သောကြောင့်။ <em>A bridge</em> ကို ဖွင့်ကြည့်ပါ — [2,9] ရောက်လာပြီး အားလုံးနှင့် overlap ဖြစ်သည်အထိ [1,3]၊ [8,10] နှင့် [5,6] ခွဲနေပြီး brute force သည် သုံးခုလုံးကို ၎င်းထဲ တစ်ခေါက်တည်းဖြင့် ပေါင်းကာ [1,10] ဖြစ်စေသည်။ ထပ်ကြည့်စရာ မလိုပါ — ပေါင်းထားသော interval များ point မတူသဖြင့် ကြီးလာသော interval သည် ၎င်းတို့၏ union အတိအကျ ဖြစ်ပြီး မထိခဲ့သည့်အရာကို ဆက်မထိပါ။" } },
      { q: { en: "Does the sort need to break ties on the end?", my: "sort သည် end ဖြင့် tie ကို ဖြေရန် လိုသလား။" }, a: { en: "No. Two intervals with the same start overlap each other at that start, so whichever comes first, the second merges into it, and <code>max</code> keeps the larger end. Sorting by start alone is enough.", my: "မလိုပါ။ start တူသော interval နှစ်ခုသည် ထို start တွင် overlap ဖြစ်သဖြင့် မည်သည့်တစ်ခု ရှေ့ရောက်ရောက် ဒုတိယတစ်ခုက ၎င်းထဲ ပေါင်းဝင်ပြီး <code>max</code> က ပိုကြီးသော end ကို ထားသည်။ start ဖြင့်သာ sort လုပ်ခြင်း လုံလောက်သည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "Sort once, compare once", my: "တစ်ကြိမ် sort၊ တစ်ကြိမ် နှိုင်းယှဉ်" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>n = 10⁴, nothing merges</th></tr></thead>\n  <tbody>\n    <tr><td><b>Brute force</b><br><span class=\"sub\">no sorting</span></td>\n        <td class=\"mono\">O(n²)</td><td class=\"mono\">O(n)</td><td class=\"cross\">≈ 5 × 10⁷ comparisons</td></tr>\n    <tr><td><b>Sort + sweep</b><br><span class=\"sub\">compare with the last</span></td>\n        <td class=\"mono\">O(n log n)</td><td class=\"mono\">O(n)</td><td class=\"tick\">≈ 1.3 × 10⁵ for the sort, 10⁴ after</td></tr>\n  </tbody>\n</table>\n<figcaption>Counts are computed, not measured. The brute force's cost depends on how much merges: when everything overlaps, the merged list stays short and it is fast; when nothing does, the list grows to n. The sort costs about n log₂ n comparisons whatever the input.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>n = 10⁴၊ ဘာမျှ မပေါင်း</th></tr></thead>\n  <tbody>\n    <tr><td><b>Brute force</b><br><span class=\"sub\">sort မလုပ်</span></td>\n        <td class=\"mono\">O(n²)</td><td class=\"mono\">O(n)</td><td class=\"cross\">နှိုင်းယှဉ်ခြင်း ≈ 5 × 10⁷</td></tr>\n    <tr><td><b>Sort + sweep</b><br><span class=\"sub\">နောက်ဆုံးနှင့် နှိုင်းယှဉ်</span></td>\n        <td class=\"mono\">O(n log n)</td><td class=\"mono\">O(n)</td><td class=\"tick\">sort အတွက် ≈ 1.3 × 10⁵၊ ပြီးနောက် 10⁴</td></tr>\n  </tbody>\n</table>\n<figcaption>ဤအရေအတွက်များကို တွက်ထားခြင်းဖြစ်ပြီး တိုင်းတာထားခြင်း မဟုတ်ပါ။ brute force ၏ ကုန်ကျမှုသည် မည်မျှ ပေါင်းသလဲအပေါ် မူတည်သည် — အားလုံး overlap ဖြစ်လျှင် ပေါင်းထားသော list တိုသဖြင့် မြန်သည်၊ ဘာမျှ မဖြစ်လျှင် list သည် n အထိ ကြီးသည်။ sort သည် input မည်သို့ပင်ဖြစ်စေ n log₂ n ခန့် နှိုင်းယှဉ်သည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission. The sweep ran against 20,015 cases up to n = 10⁴; the brute force against the 20,010 small enough for it.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်သည်။ sweep ကို n = 10⁴ အထိ case 20,015 ခုဖြင့်၊ brute force ကို ၎င်းအတွက် သေးလောက်သော case 20,010 ခုဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>intervals</code> above — up to 8, with values from 0 to 20 so the timeline fits — and both walkthroughs rebuild against your list.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>intervals</code> ကို ပြင်လိုက်လျှင် (8 ခုအထိ၊ timeline ဆံ့စေရန် value 0 မှ 20 အထိ) walkthrough နှစ်ခုစလုံး သင့် list ဖြင့် ပြန်တည်ဆောက်မည်။" },
};
