/* The prose of the Find Median from Data Stream page: everything the reader
 * sees that is not interactive. Rendered by src/pages/leetcode/[slug].astro
 * through the Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Find Median from Data Stream',
  summary: 'The median only needs the middle. Keep every number sorted and read the middle index, or keep the smaller half in a max-heap and the larger half in a min-heap so the two tops are the middle.',
  eyebrow: 'LeetCode 295 &nbsp;·&nbsp; Hard',
  lede: { en: "Numbers arrive one at a time, and at any moment you may be asked for the median of all of them so far. Sorting on every question is wasteful; keeping one sorted array works but pays to shift numbers on every add. The two-heap design keeps only what the median reads — the largest of the smaller half and the smallest of the larger half — on top of two heaps, at O(log n) an add.", my: "ကိန်းများ တစ်ခုချင်း ရောက်လာပြီး မည်သည့်အချိန်တွင်မဆို ယခုထိ ကိန်းအားလုံး၏ median ကို မေးနိုင်သည်။ မေးတိုင်း sort လုပ်ခြင်း အလဟဿ — စီထားသော array တစ်ခု ထိန်းခြင်း အလုပ်ဖြစ်သော်လည်း ထည့်တိုင်း ကိန်းများ ရွှေ့ရသည်။ heap နှစ်ခု ဒီဇိုင်းသည် median ဖတ်သည့်အရာ — အငယ်တစ်ဝက်၏ အကြီးဆုံးနှင့် အကြီးတစ်ဝက်၏ အငယ်ဆုံး — ကိုသာ heap နှစ်ခု၏ အပေါ်တွင် ထားပြီး ထည့်တစ်ကြိမ်လျှင် O(log n)။" },
  links: [{ id: 295, title: 'Find Median from Data Stream', slug: 'find-median-from-data-stream', difficulty: 'Hard' }],
  constraints: { en: "<span>&minus;10<sup>5</sup> &le; num &le; 10<sup>5</sup></span><span>at least one element before findMedian is called</span><span>at most 5 &times; 10<sup>4</sup> calls to addNum and findMedian</span>", my: "<span>&minus;10<sup>5</sup> &le; num &le; 10<sup>5</sup></span><span>findMedian မခေါ်မီ element အနည်းဆုံး တစ်ခု</span><span>addNum နှင့် findMedian ကို အများဆုံး 5 &times; 10<sup>4</sup> ကြိမ်</span>" },
  part1Sub: { en: "Read the statement, then drag through a stream and watch the sorted numbers split into two halves.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် stream တစ်ခုကို ဆွဲပြီး စီထားသော ကိန်းများ တစ်ဝက်နှစ်ခု ကွဲပုံ ကြည့်ပါ။" },
  widgetTitle: { en: "Two halves, and the middle between them", my: "တစ်ဝက် နှစ်ခု — ၎င်းတို့ကြားရှိ အလယ်" },
  traps: {
    summary: { en: "Three ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ သုံးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>The median of an even count is a mean, and can end in .5.</strong> Averaging with integer division returns 1 for the example's first findMedian, not 1.5. Divide by <code>2.0</code>, or convert first — in Go, <code>float64(a+b) / 2</code>, not <code>float64((a+b) / 2)</code>.", my: "<strong>စုံကိန်း အရေအတွက်၏ median သည် ပျမ်းမျှ ဖြစ်ပြီး .5 ဖြင့် ဆုံးနိုင်သည်။</strong> integer division ဖြင့် ပျမ်းမျှလျှင် ဥပမာ၏ ပထမ findMedian အတွက် 1.5 မဟုတ်ဘဲ 1 ပြန်ပေးသည်။ <code>2.0</code> ဖြင့် စားပါ၊ သို့မဟုတ် အရင် ပြောင်းပါ — Go တွင် <code>float64((a+b) / 2)</code> မဟုတ်ဘဲ <code>float64(a+b) / 2</code>။" },
      { en: "<strong>A new number does not always belong in the smaller half.</strong> Pushing onto low and only fixing the sizes skips the crossing step, and low collects numbers bigger than high's: the example returns 2.0 and 3.0 instead of 1.5 and 2.0. Every add must pass low's largest to high before the sizes are fixed.", my: "<strong>ကိန်းအသစ်သည် အငယ်တစ်ဝက်တွင် အမြဲ မဟုတ်။</strong> low ပေါ် push ပြီး size များကိုသာ ပြင်လျှင် ကူးသည့်အဆင့်ကို ကျော်မိပြီး low တွင် high ထက် ကြီးသော ကိန်းများ စုလာသည် — ဥပမာသည် 1.5 နှင့် 2.0 အစား 2.0 နှင့် 3.0 ပြန်ပေးသည်။ size များကို မပြင်မီ ထည့်တိုင်း low ၏ အကြီးဆုံးကို high သို့ ပေးရမည်။" },
      { en: "<strong>Which half keeps the odd one out is a choice — make findMedian agree with it.</strong> These listings let low hold the extra number, so an odd count reads low's top. Balance toward high instead and findMedian must read high's top: keep the old findMedian and the example's second answer comes back 1.5, the average of 1 and 2, instead of 2.0.", my: "<strong>မည်သည့် တစ်ဝက်က အပိုကိန်းကို ထိန်းမည်ဆိုသည်မှာ ရွေးချယ်မှု — findMedian ကို ၎င်းနှင့် ကိုက်ညီစေပါ။</strong> ဤ listing များတွင် low က အပိုကိန်းကို ထိန်းသဖြင့် မကိန်း အရေအတွက်တွင် low ၏ top ကို ဖတ်သည်။ high ဘက်သို့ balance လုပ်လျှင် findMedian သည် high ၏ top ကို ဖတ်ရမည် — findMedian အဟောင်းကို ထားလျှင် ဥပမာ၏ ဒုတိယ အဖြေသည် 2.0 အစား 1 နှင့် 2 ၏ ပျမ်းမျှ 1.5 ပြန်ထွက်သည်။" },
    ],
  },
  part2Sub: { en: "Two designs over the same calls. The strip is the calls in order; the stage is what the finder keeps between them — one sorted array, or two heaps drawn as the trees their arrays encode.", my: "call များ တူတူပေါ်တွင် ဒီဇိုင်း နှစ်မျိုး။ strip သည် call များ အစဉ်အတိုင်း — stage သည် call များကြားတွင် finder ထိန်းသည့်အရာ — စီထားသော array တစ်ခု၊ သို့မဟုတ် ၎င်းတို့၏ array ကိုယ်စားပြုသော tree များအဖြစ် ဆွဲထားသော heap နှစ်ခု။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the two heaps raise", my: "heap နှစ်ခုနှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why push onto low and then move its largest, instead of comparing first?", my: "အရင် မနှိုင်းယှဉ်ဘဲ low ပေါ် push ပြီးမှ ၎င်း၏ အကြီးဆုံးကို ဘာကြောင့် ရွှေ့သလဲ။" }, a: { en: "Because it needs no cases. Pushing onto low and passing its largest to high guarantees, whatever the number was, that everything in low is at most everything in high. Then one size check fixes the counts. Comparing with the tops first also works, but it has to handle an empty heap and both size cases, and that is where bugs hide.", my: "case မလိုသောကြောင့်။ low ပေါ် push ပြီး ၎င်း၏ အကြီးဆုံးကို high သို့ ပေးခြင်းက ကိန်းမည်သည်ပင် ဖြစ်စေ low ရှိ အရာအားလုံး high ရှိ အရာအားလုံးထက် မကြီးကြောင်း အာမခံသည်။ ထို့နောက် size စစ်ချက် တစ်ခုက အရေအတွက်ကို ပြင်သည်။ top များနှင့် အရင် နှိုင်းယှဉ်ခြင်းလည်း အလုပ်ဖြစ်သော်လည်း ဗလာ heap နှင့် size case နှစ်ခုလုံးကို ကိုင်တွယ်ရပြီး bug များ ပုန်းနေတတ်သည်။" } },
      { q: { en: "Is the sorted array really too slow?", my: "စီထားသော array သည် တကယ် နှေးလွန်းသလား။" }, a: { en: "Not at this size. Inserting shifts up to n numbers, but the shift is one block memory move: 5 &times; 10<sup>4</sup> adds took 148 ms in Python here in the worst order, against 16 ms for the heaps. The quadratic cost shows as the stream grows — a million descending adds took 59.2 s for the array and 0.42 s for the heaps.", my: "ဤ size တွင် မဟုတ်ပါ။ ထည့်ခြင်းက ကိန်း n ခုအထိ ရွှေ့သော်လည်း ရွှေ့ခြင်းသည် memory move တစ်ခုတည်း — ဤနေရာတွင် Python ဖြင့် အဆိုးဆုံး အစဉ်တွင် ထည့်ခြင်း 5 &times; 10<sup>4</sup> သည် 148 ms ကြာပြီး heap များ 16 ms။ stream ကြီးလာသည်နှင့် quadratic ကုန်ကျမှု ပေါ်လာသည် — ကြီးမှငယ် ထည့်ခြင်း တစ်သန်းသည် array အတွက် 59.2 စက္ကန့်၊ heap များအတွက် 0.42 စက္ကန့်။" } },
      { q: { en: "What about the follow-ups, numbers in [0, 100]?", my: "follow-up များ — [0, 100] အတွင်း ကိန်းများ ဆိုလျှင်။" }, a: { en: "Then count instead of storing: 101 counters, and the median is found by walking them to the middle — O(1) per add and at most 101 steps per find. If only 99% of the numbers fall in [0, 100], keep the counters for those and two small sorted lists (or heaps) for the few outside; the median almost always lands among the counters. Neither version is on this page, because neither was run here.", my: "ထိုအခါ သိမ်းမည့်အစား ရေတွက်ပါ — counter 101 ခု၊ median ကို ၎င်းတို့ကို အလယ်အထိ လျှောက်၍ ရှာသည် — ထည့်တစ်ကြိမ်လျှင် O(1)၊ ရှာတစ်ကြိမ်လျှင် အဆင့် 101 အများဆုံး။ ကိန်းများ၏ 99% သာ [0, 100] အတွင်း ရှိလျှင် ၎င်းတို့အတွက် counter များနှင့် အပြင်ရှိ အနည်းငယ်အတွက် စီထားသော list (သို့မဟုတ် heap) သေးသေး နှစ်ခု ထားပါ — median သည် counter များကြားတွင် အမြဲနီးပါး ကျသည်။ version နှစ်ခုလုံး ဤနေရာတွင် မ run ထားသဖြင့် ဤစာမျက်နှာတွင် မပါ။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "Shift the array, or sift a heap", my: "array ကို ရွှေ့ခြင်း သို့မဟုတ် heap ကို sift လုပ်ခြင်း" },
    html: { en: "<table>\n  <thead><tr><th>Design</th><th>addNum</th><th>findMedian</th><th>5 × 10⁴ adds</th><th>10⁶ adds</th></tr></thead>\n  <tbody>\n    <tr><td><b>Sorted array</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">binary search, then shift</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(1)</td><td>148 ms</td><td class=\"cross\">59.2 s</td></tr>\n    <tr><td><b>Two heaps</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">up to three heap operations</span></td>\n        <td class=\"mono\">O(log n)</td><td class=\"mono\">O(1)</td><td class=\"tick\">16 ms</td><td class=\"tick\">0.42 s</td></tr>\n  </tbody>\n</table>\n<figcaption>Python, best of three for 5 × 10⁴ and a single run for 10⁶, on an Apple M5 Pro, adding numbers in descending order — every insert into the sorted array lands at the front and shifts all the rest. At the problem's own limit both designs are fast; the gap is the growth.</figcaption>", my: "<table>\n  <thead><tr><th>ဒီဇိုင်း</th><th>addNum</th><th>findMedian</th><th>ထည့် 5 × 10⁴</th><th>ထည့် 10⁶</th></tr></thead>\n  <tbody>\n    <tr><td><b>Sorted array</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">binary search ပြီးမှ ရွှေ့</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(1)</td><td>148 ms</td><td class=\"cross\">59.2 စက္ကန့်</td></tr>\n    <tr><td><b>Two heaps</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">heap operation သုံးခုအထိ</span></td>\n        <td class=\"mono\">O(log n)</td><td class=\"mono\">O(1)</td><td class=\"tick\">16 ms</td><td class=\"tick\">0.42 စက္ကန့်</td></tr>\n  </tbody>\n</table>\n<figcaption>Python၊ 5 × 10⁴ အတွက် သုံးကြိမ်အနက် အကောင်းဆုံး၊ 10⁶ အတွက် တစ်ကြိမ် run၊ Apple M5 Pro ပေါ်တွင်၊ ကြီးမှငယ် အစဉ်ဖြင့် ထည့်သည် — စီထားသော array ထဲ ထည့်တိုင်း ရှေ့ဆုံးတွင် ကျပြီး ကျန်အားလုံးကို ရွှေ့သည်။ ပြဿနာ၏ ကန့်သတ်ချက်တွင် ဒီဇိုင်း နှစ်ခုလုံး မြန်သည် — ကွာဟချက်မှာ ကြီးထွားနှုန်း။</figcaption>" },
  },
  part3Sub: { en: "Two designs in five languages. Every block is a complete submission, and every one was run against the same 20,013 streams of calls, up to 5 × 10⁴ long.", my: "ဒီဇိုင်း နှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး အားလုံးကို 5 × 10⁴ အထိ ရှည်သော call stream 20,013 ခု တူတူဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit the calls above — <code>addNum(n)</code> and <code>findMedian()</code>, up to 12, numbers from −99 to 99 — and both walkthroughs rebuild against them.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က call များကို ပြင်လိုက်လျှင် (<code>addNum(n)</code> နှင့် <code>findMedian()</code>၊ 12 ခုအထိ၊ −99 မှ 99 အထိ ကိန်းများ) walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
