/* The prose of the Course Schedule page: everything the reader sees that is
 * not interactive. Rendered by src/pages/leetcode/[slug].astro through the
 * Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Course Schedule',
  summary: 'Draw each prerequisite as an arrow; every course can be taken exactly when the arrows never loop. A DFS that remembers its current path finds the loop; Kahn\'s algorithm takes courses with nothing left to wait for and sees whether it runs out.',
  eyebrow: 'LeetCode 207 &nbsp;·&nbsp; Medium',
  lede: { en: "Decide whether a list of prerequisites can all be honoured. Drawn as a graph — one arrow from each prerequisite to the course that needs it — the question becomes whether the arrows ever loop back on themselves. Two answers: follow the arrows depth-first and notice when you step onto your own path, or keep taking whatever has nothing left to wait for and see if you get stuck.", my: "prerequisite စာရင်းတစ်ခုကို အားလုံး လိုက်နာနိုင်မနိုင် ဆုံးဖြတ်ပါ။ graph အဖြစ် ဆွဲလျှင် — prerequisite တစ်ခုစီမှ ၎င်းကို လိုအပ်သော course သို့ မြှားတစ်ခု — မေးခွန်းသည် မြှားများ သူ့ကိုယ်သူ ပြန်ကွင်းပတ်သလား ဖြစ်လာသည်။ အဖြေနှစ်မျိုး — မြှားများကို depth-first လိုက်ပြီး ကိုယ့်လမ်းကြောင်းပေါ် ပြန်နင်းမိချိန်ကို သတိပြုခြင်း၊ သို့မဟုတ် စောင့်စရာ မကျန်တော့သည်ကို ဆက်ယူပြီး ပိတ်မိသလား ကြည့်ခြင်း။" },
  links: [{ id: 207, title: 'Course Schedule', slug: 'course-schedule', difficulty: 'Medium' }],
  constraints: { en: "<span>1 &le; numCourses &le; 2000</span><span>0 &le; prerequisites.length &le; 5000</span><span>prerequisites[i].length == 2</span><span>0 &le; a<sub>i</sub>, b<sub>i</sub> &lt; numCourses</span><span>all pairs are unique</span>", my: "<span>1 &le; numCourses &le; 2000</span><span>0 &le; prerequisites.length &le; 5000</span><span>prerequisites[i].length == 2</span><span>0 &le; a<sub>i</sub>, b<sub>i</sub> &lt; numCourses</span><span>pair အားလုံး မတူ</span>" },
  part1Sub: { en: "Read the statement, then draw arrows between courses and watch for a loop.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် course များကြား မြှားဆွဲပြီး ကွင်း ပေါ်လာသလား ကြည့်ပါ။" },
  widgetTitle: { en: "Draw the arrows, look for a loop", my: "မြှားများ ဆွဲပါ — ကွင်း ရှာပါ" },
  traps: {
    summary: { en: "Four ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ လေးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>Reaching a course twice is not a cycle.</strong> A DFS with a single visited set that returns \"cycle\" whenever it meets a visited course gets the diamond — 0 before 1 and 2, both before 3 — wrong: 3 is reached twice, and it returns <code>false</code> for <code>4, [[1,0],[2,0],[3,1],[3,2]]</code>, which can be finished.", my: "<strong>course တစ်ခုကို နှစ်ကြိမ် ရောက်ခြင်းသည် cycle မဟုတ်ပါ။</strong> visited set တစ်ခုတည်းသုံးပြီး visited course ကို တွေ့တိုင်း \"cycle\" ဟု ပြန်ပေးသော DFS သည် စိန်ပုံ — 1 နှင့် 2 မတိုင်မီ 0၊ နှစ်ခုလုံး 3 မတိုင်မီ — ကို မှားသည် — 3 ကို နှစ်ကြိမ် ရောက်ပြီး ပြီးနိုင်သော <code>4, [[1,0],[2,0],[3,1],[3,2]]</code> အတွက် <code>false</code> ပြန်ပေးသည်။" },
      { en: "<strong>But skipping every visited course misses the loop.</strong> The opposite shortcut — a visited course is simply fine — never sees a cycle at all: example 2 returns <code>true</code>. Telling the two cases apart is why the DFS needs a third state, \"on the path right now\".", my: "<strong>သို့သော် visited course တိုင်းကို ကျော်လျှင် ကွင်းကို လွတ်သွားသည်။</strong> ဆန့်ကျင်ဘက် လမ်းတို — visited course သည် ရိုးရိုး အဆင်ပြေသည် — သည် cycle ကို လုံးဝ မမြင်ပါ — ဥပမာ 2 သည် <code>true</code> ပြန်ပေးသည်။ ထိုအခြေအနေနှစ်ခုကို ခွဲခြားရန် DFS သည် တတိယ state \"ယခု လမ်းပေါ်တွင်\" လိုသည်။" },
      { en: "<strong>Pick one direction and keep it.</strong> <code>[a, b]</code> means b comes first. Kahn's algorithm that stores the arrow as <code>after[b].append(a)</code> but counts <code>need[b] += 1</code> mixes the two readings and returns <code>false</code> on example 1.", my: "<strong>ဦးတည်ချက်တစ်ခု ရွေးပြီး ထိန်းထားပါ။</strong> <code>[a, b]</code> သည် b အရင်လာသည်ဟု ဆိုလိုသည်။ မြှားကို <code>after[b].append(a)</code> ဟု သိမ်းပြီး <code>need[b] += 1</code> ဟု ရေတွက်သော Kahn's algorithm သည် ဖတ်ပုံ နှစ်မျိုးကို ရောပြီး ဥပမာ 1 တွင် <code>false</code> ပြန်ပေးသည်။" },
      { en: "<strong>A chain can be 2,000 courses long.</strong> A recursive DFS goes that deep. Python's default limit of 1,000 calls fails on a chain of 1,000 courses with <code>RecursionError</code> (checked here), so raise it, or use Kahn's algorithm, which does not recurse.", my: "<strong>ကွင်းဆက်သည် course 2,000 ရှည်နိုင်သည်။</strong> recursive DFS သည် ထိုမျှ နက်သွားသည်။ Python ၏ default call 1,000 ကန့်သတ်ချက်သည် course 1,000 ကွင်းဆက်တွင် <code>RecursionError</code> ဖြင့် ကျရှုံးသည် (ဤနေရာတွင် စစ်ထားသည်) — ထို့ကြောင့် မြှင့်ပါ၊ သို့မဟုတ် recurse မလုပ်သော Kahn's algorithm ကို သုံးပါ။" },
    ],
  },
  part2Sub: { en: "Two ways to find the loop. The strip is the one number the approach keeps per course — its DFS state, or how many courses it still needs; the stage draws the prerequisites as the graph they are, with the call stack or the queue beside it.", my: "ကွင်းကို ရှာရန် နည်းလမ်းနှစ်မျိုး။ strip သည် နည်းလမ်းက course တစ်ခုလျှင် ထိန်းထားသော ဂဏန်းတစ်ခု — ၎င်း၏ DFS state သို့မဟုတ် လိုသေးသော course အရေအတွက်။ stage သည် prerequisite များကို ၎င်းတို့ ဖြစ်သည့်အတိုင်း graph အဖြစ် ဆွဲပြီး ဘေးတွင် call stack သို့မဟုတ် queue ပြသည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Four questions the graph raises", my: "graph နှင့်ပတ်သက်၍ မေးစရာ လေးခု" },
    items: [
      { q: { en: "Why is \"no cycle\" the same as \"can finish\"?", my: "\"cycle မရှိ\" သည် \"ပြီးနိုင်\" နှင့် ဘာကြောင့် တူသလဲ။" }, a: { en: "If the arrows loop, every course on the loop waits — through the others — on itself, so none of them can go first. If they do not loop, some course has no arrow coming in (otherwise you could walk backwards forever through finitely many courses, which means repeating one: a loop). Take it, delete it, and the rest still has no loop — repeat until every course is taken. That argument is Kahn's algorithm.", my: "မြှားများ ကွင်းပတ်လျှင် ကွင်းပေါ်ရှိ course တိုင်းသည် — အခြားများမှတစ်ဆင့် — သူ့ကိုယ်သူ စောင့်နေသဖြင့် မည်သည်မျှ အရင် မသွားနိုင်။ ကွင်း မပတ်လျှင် ဝင်လာသော မြှား မရှိသည့် course တစ်ခု ရှိရမည် (မဟုတ်လျှင် course အရေအတွက် အကန့်အသတ်ရှိသော်လည်း နောက်ပြန် အဆုံးမရှိ လျှောက်နိုင်မည် — ဆိုလိုသည်မှာ တစ်ခုကို ထပ်ရောက်ခြင်း — ကွင်း)။ ၎င်းကို ယူ၊ ဖျက်၊ ကျန်သည်တွင် ကွင်း မရှိသေး — course တိုင်း ယူပြီးသည်အထိ ထပ်လုပ်ပါ။ ထိုအကြောင်းပြချက်သည်ပင် Kahn's algorithm ဖြစ်သည်။" } },
      { q: { en: "Does it matter which way the arrows point?", my: "မြှားများ ဘယ်ဘက် ညွှန်သလဲ အရေးကြီးသလား။" }, a: { en: "Not for this question: reversing every arrow keeps every loop a loop. The DFS with <code>after[a].append(b)</code> instead gives the same answer on all 20,016 cases (run here). It matters the moment you want the order itself — Course Schedule II — and inside one solution, where both halves must use the same reading (the third trap).", my: "ဤမေးခွန်းအတွက် မကြီးပါ — မြှားတိုင်းကို ပြောင်းပြန်လှန်လျှင် ကွင်းတိုင်း ကွင်းအဖြစ် ကျန်သည်။ <code>after[a].append(b)</code> သုံးသော DFS သည် case 20,016 ခုလုံးတွင် အဖြေ အတူတူ ပေးသည် (ဤနေရာတွင် run ထားသည်)။ အစီအစဉ်ကိုယ်တိုင် လိုချင်သည့်အခါ — Course Schedule II — နှင့် solution တစ်ခုအတွင်း အပိုင်းနှစ်ခုလုံး ဖတ်ပုံ တူရမည့်နေရာ (တတိယ ချော်လွယ်ချက်) တွင် အရေးကြီးသည်။" } },
      { q: { en: "Why mark a course \"done\" instead of clearing it back to 0?", my: "course ကို 0 ပြန်မထားဘဲ ဘာကြောင့် \"ပြီး\" ဟု မှတ်သလဲ။" }, a: { en: "Clearing it would still be correct — a course off the path is not a loop — but every later search that reaches it walks everything after it again. On a chain of 2,000 courses that is 2,001,000 calls instead of about 4,000; on a stack of diamonds it doubles with each one — 16,299 calls for 10 diamonds, 16,777,061 for 20 (counted here). \"Done\" means \"checked, no loop below\", so a later search stops there at once.", my: "0 ပြန်ထားလည်း မှန်နေဆဲ — လမ်းပေါ်မှ ထွက်သော course သည် ကွင်း မဟုတ် — သို့သော် ၎င်းကို ရောက်သော နောက်ပိုင်း ရှာဖွေမှုတိုင်းက ၎င်းနောက်ရှိ အားလုံးကို ထပ်လျှောက်သည်။ course 2,000 ကွင်းဆက်တွင် call 4,000 ခန့်အစား 2,001,000 ဖြစ်သည် — စိန်ပုံများ ထပ်ထားလျှင် တစ်ခုထပ်တိုင်း နှစ်ဆ ဖြစ်သည် — စိန်ပုံ 10 ခုအတွက် call 16,299၊ 20 ခုအတွက် 16,777,061 (ဤနေရာတွင် ရေတွက်ထားသည်)။ \"ပြီး\" ဆိုသည်မှာ \"စစ်ပြီး၊ အောက်တွင် ကွင်းမရှိ\" ဖြစ်သဖြင့် နောက်ပိုင်း ရှာဖွေမှုသည် ထိုနေရာတွင် ချက်ချင်း ရပ်သည်။" } },
      { q: { en: "Where does this come up outside LeetCode?", my: "LeetCode အပြင်ဘက်တွင် ဘယ်မှာ တွေ့ရသလဲ။" }, a: { en: "Anywhere things depend on other things: build systems ordering compile steps, package managers resolving installs, spreadsheets recalculating cells, task schedulers. Each is \"topologically sort the graph, or report the cycle\" — and the cycle error message is exactly the loop the DFS walks.", my: "အရာများက အခြားအရာများအပေါ် မှီခိုသည့် နေရာတိုင်း — compile အဆင့်များကို စီသော build system၊ install များကို ဖြေရှင်းသော package manager၊ cell များကို ပြန်တွက်သော spreadsheet၊ task scheduler။ တစ်ခုစီသည် \"graph ကို topological sort လုပ်၊ သို့မဟုတ် cycle ကို သတင်းပို့\" ဖြစ်ပြီး cycle error message သည် DFS လျှောက်သော ကွင်း အတိအကျ ဖြစ်သည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "Both linear; one needs a deep stack", my: "နှစ်ခုလုံး linear — တစ်ခုက stack နက်နက် လိုသည်" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>A 2,000-course chain</th></tr></thead>\n  <tbody>\n    <tr><td><b>Three-colour DFS</b><br><span class=\"sub\">recursive</span></td>\n        <td class=\"mono\">O(V + E)</td><td class=\"mono\">O(V) stack</td><td class=\"cross\">2,000 calls deep — past Python's default limit</td></tr>\n    <tr><td><b>Kahn's algorithm</b><br><span class=\"sub\">a queue</span></td>\n        <td class=\"mono\">O(V + E)</td><td class=\"mono\">O(V)</td><td class=\"tick\">one course in the queue at a time</td></tr>\n  </tbody>\n</table>\n<figcaption>V is the number of courses (up to 2,000), E the number of pairs (up to 5,000). Depths are counted, not timed. Both are fast at the constraint; the DFS has the recursion limit to think about, and Kahn's hands you a valid order as a by-product.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>course 2,000 ကွင်းဆက်</th></tr></thead>\n  <tbody>\n    <tr><td><b>Three-colour DFS</b><br><span class=\"sub\">recursive</span></td>\n        <td class=\"mono\">O(V + E)</td><td class=\"mono\">O(V) stack</td><td class=\"cross\">call 2,000 ဆင့် — Python ၏ default ကန့်သတ်ချက်ကို ကျော်</td></tr>\n    <tr><td><b>Kahn's algorithm</b><br><span class=\"sub\">queue</span></td>\n        <td class=\"mono\">O(V + E)</td><td class=\"mono\">O(V)</td><td class=\"tick\">queue ထဲ တစ်ကြိမ်လျှင် course တစ်ခု</td></tr>\n  </tbody>\n</table>\n<figcaption>V သည် course အရေအတွက် (2,000 အထိ)၊ E သည် pair အရေအတွက် (5,000 အထိ)။ အနက်များကို ရေတွက်ထားခြင်းဖြစ်ပြီး အချိန် မတိုင်းထားပါ။ ကန့်သတ်ချက်တွင် နှစ်ခုလုံး မြန်သည် — DFS တွင် recursion ကန့်သတ်ချက်ကို စဉ်းစားရပြီး Kahn's က မှန်ကန်သော အစီအစဉ်ကို ဘေးထွက်အဖြစ် ပေးသည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission, and every one was run against the same 20,016 cases, up to 2,000 courses and 5,000 pairs.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး အားလုံးကို course 2,000 နှင့် pair 5,000 အထိ case 20,016 ခု တူတူဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>numCourses</code> (up to 8) and <code>prerequisites</code> (up to 12 pairs) above, and both walkthroughs rebuild against them.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>numCourses</code> (8 အထိ) နှင့် <code>prerequisites</code> (pair 12 အထိ) ကို ပြင်လိုက်လျှင် walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
