/* The prose of the LRU Cache page: everything the reader sees that is not
 * interactive. Rendered by src/pages/leetcode/[slug].astro through the
 * Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'LRU Cache',
  summary: 'A map finds a key; a recency order says which key to drop. A list gives the order but must be scanned; linking the map to the nodes of a doubly linked list makes every get and put a lookup plus a few pointer writes.',
  eyebrow: 'LeetCode 146 &nbsp;·&nbsp; Medium',
  lede: { en: "Build a cache that holds at most <code>capacity</code> keys and, when a new key would overflow it, drops the one used longest ago — where reading a key counts as using it. Each call needs two things: a key's value, found by key, and the order keys were last used in. A hash map gives the first, a list the second, and O(1) comes from joining them: the map points straight at each key's node in a doubly linked list.", my: "key အများဆုံး <code>capacity</code> ခုကို ကိုင်ထားပြီး key အသစ်တစ်ခုက ပြည့်လျှံစေမည့်အခါ အကြာဆုံး မသုံးခဲ့သော key ကို ဖယ်သော cache တစ်ခု တည်ဆောက်ပါ — key ကို ဖတ်ခြင်းသည် အသုံးပြုခြင်းဟု တွက်သည်။ call တစ်ခုစီတွင် အရာနှစ်ခု လိုသည် — key ဖြင့် ရှာသော value နှင့် key များကို နောက်ဆုံးသုံးခဲ့သည့် အစီအစဉ်။ hash map က ပထမကို၊ list က ဒုတိယကို ပေးပြီး O(1) သည် ၎င်းတို့ကို ပေါင်းခြင်းမှ လာသည် — map က doubly linked list ထဲရှိ key တစ်ခုစီ၏ node ကို တိုက်ရိုက် ညွှန်သည်။" },
  links: [{ id: 146, title: 'LRU Cache', slug: 'lru-cache', difficulty: 'Medium' }],
  constraints: { en: "<span>1 &le; capacity &le; 3000</span><span>0 &le; key &le; 10<sup>4</sup></span><span>0 &le; value &le; 10<sup>5</sup></span><span>at most 2 &times; 10<sup>5</sup> calls to get and put</span>", my: "<span>1 &le; capacity &le; 3000</span><span>0 &le; key &le; 10<sup>4</sup></span><span>0 &le; value &le; 10<sup>5</sup></span><span>get နှင့် put ကို အများဆုံး 2 &times; 10<sup>5</sup> ကြိမ် ခေါ်</span>" },
  part1Sub: { en: "Read the statement, then read keys and see which one each kind of cache would drop.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် key များကို ဖတ်ပြီး cache အမျိုးအစားတစ်ခုစီ ဘယ် key ကို ဖယ်မလဲ ကြည့်ပါ။" },
  widgetTitle: { en: "Read keys, see who goes next", my: "key များ ဖတ်ပါ — နောက် ဘယ်သူ ထွက်မလဲ ကြည့်ပါ" },
  traps: {
    summary: { en: "Four ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ လေးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>A get is a use.</strong> A cache that only tracks when keys were added evicts 1 at <code>put(3, 3)</code> in example 1, although it was just read, and returns <code>[null,null,1,null,2,null,-1,3,4]</code> — 2 where the answer is -1.", my: "<strong>get သည် အသုံးပြုခြင်း ဖြစ်သည်။</strong> key များ ထည့်ခဲ့ချိန်ကိုသာ မှတ်သော cache သည် ဥပမာ 1 ၏ <code>put(3, 3)</code> တွင် ဖတ်ခဲ့ပြီးခါစ 1 ကို ဖယ်ပြီး <code>[null,null,1,null,2,null,-1,3,4]</code> ပြန်ပေးသည် — အဖြေ -1 ဖြစ်ရမည့်နေရာတွင် 2။" },
      { en: "<strong>So is a put to a key already there.</strong> Updating the value without moving the key: after <code>put(1,1), put(2,2), put(1,10), put(3,3)</code> at capacity 2 it evicts 1 instead of 2, so <code>get(1)</code> returns <code>-1</code>, not <code>10</code>.", my: "<strong>ရှိပြီးသား key ကို put လုပ်ခြင်းလည်း ထိုနည်းတူ။</strong> key ကို မရွှေ့ဘဲ value ကိုသာ update လုပ်လျှင် — capacity 2 တွင် <code>put(1,1), put(2,2), put(1,10), put(3,3)</code> ပြီးနောက် 2 အစား 1 ကို ဖယ်သဖြင့် <code>get(1)</code> သည် <code>10</code> မဟုတ်ဘဲ <code>-1</code> ပြန်ပေးသည်။" },
      { en: "<strong>Evict only when the count goes over.</strong> Checking \"full\" before looking the key up evicts on an update that adds nothing: at capacity 2, <code>put(1,1), put(2,2), put(2,20)</code> throws out 1, and <code>get(1)</code> returns <code>-1</code> instead of <code>1</code>.", my: "<strong>အရေအတွက် ကျော်မှသာ ဖယ်ပါ။</strong> key ကို မရှာမီ \"ပြည့်\" ကို စစ်လျှင် ဘာမှ မတိုးသော update တွင် ဖယ်မိသည် — capacity 2 တွင် <code>put(1,1), put(2,2), put(2,20)</code> သည် 1 ကို ပစ်ထုတ်ပြီး <code>get(1)</code> သည် <code>1</code> အစား <code>-1</code> ပြန်ပေးသည်။" },
      { en: "<strong>An evicted key must leave the map too.</strong> Unlinking the oldest node but leaving it in the map keeps answering for it: example 1 returns <code>2</code> for <code>get(2)</code> and <code>1</code> for the second <code>get(1)</code>, both long evicted. That is why each node stores its own key.", my: "<strong>ဖယ်ထားသော key သည် map ထဲမှလည်း ထွက်ရမည်။</strong> အဟောင်းဆုံး node ကို unlink လုပ်ပြီး map ထဲ ချန်ထားလျှင် ၎င်းအတွက် ဆက်ဖြေနေသည် — ဥပမာ 1 သည် ဖယ်ပြီးကြာပြီဖြစ်သော <code>get(2)</code> အတွက် <code>2</code> နှင့် ဒုတိယ <code>get(1)</code> အတွက် <code>1</code> ပြန်ပေးသည်။ ထို့ကြောင့် node တစ်ခုစီက ၎င်း၏ key ကို သိမ်းထားသည်။" },
    ],
  },
  part2Sub: { en: "Two ways to keep the order. The strip is the sequence of calls; the stage is the cache's two structures — the map, and the order it keeps its keys in — and the answer card fills with what each call returned.", my: "အစီအစဉ်ကို ထိန်းရန် နည်းလမ်းနှစ်မျိုး။ strip သည် call များ၏ အစီအစဉ် ဖြစ်သည်။ stage သည် cache ၏ structure နှစ်ခု — map နှင့် ၎င်း၏ key များကို ထိန်းသော အစီအစဉ် — ဖြစ်ပြီး answer card ကို call တစ်ခုစီ ပြန်ပေးခဲ့သည့်အရာဖြင့် ဖြည့်သည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Four questions the design raises", my: "ဒီဇိုင်းနှင့်ပတ်သက်၍ မေးစရာ လေးခု" },
    items: [
      { q: { en: "Why a doubly linked list, not a singly linked one?", my: "singly linked မဟုတ်ဘဲ ဘာကြောင့် doubly linked list လဲ။" }, a: { en: "To cut a node out you must repoint the node before it. With only <code>next</code> pointers, finding that node means walking from the head — a scan again. <code>prev</code> makes the neighbour one step away, so unlinking any node is two writes.", my: "node တစ်ခုကို ဖြတ်ထုတ်ရန် ၎င်း၏ ရှေ့ node ကို ပြန်ညွှန်ရမည်။ <code>next</code> pointer သာ ရှိလျှင် ထို node ကို ရှာရန် head မှ လျှောက်ရမည် — scan ပြန်ဖြစ်သည်။ <code>prev</code> က အိမ်နီးကို တစ်လှမ်းတည်းတွင် ထားသဖြင့် မည်သည့် node ကိုမဆို unlink လုပ်ခြင်းသည် ရေးခြင်း နှစ်ကြိမ်။" } },
      { q: { en: "What are head and tail for?", my: "head နှင့် tail က ဘာအတွက်လဲ။" }, a: { en: "They are sentinels — nodes that hold no key and are never removed. Every real node always has a node before and after it, so <code>unlink</code> and the move to the front never check for an empty list or an end. The least recently used node is always <code>tail.prev</code>.", my: "၎င်းတို့သည် sentinel များ — key မကိုင်ဘဲ ဘယ်တော့မှ မဖယ်ခံရသော node များ။ တကယ့် node တိုင်းတွင် ရှေ့နှင့် နောက်၌ node အမြဲ ရှိသဖြင့် <code>unlink</code> နှင့် ရှေ့ဆုံးသို့ ရွှေ့ခြင်းသည် list ဗလာ သို့မဟုတ် အဆုံးကို ဘယ်တော့မှ မစစ်ရ။ အဟောင်းဆုံး အသုံးပြုထားသော node သည် အမြဲ <code>tail.prev</code> ဖြစ်သည်။" } },
      { q: { en: "Can the language do this for me?", my: "ဘာသာစကားက ဒါကို ကျွန်ုပ်အတွက် လုပ်ပေးနိုင်သလား။" }, a: { en: "Python's <code>OrderedDict</code> is exactly a hash map with a linked list inside: <code>move_to_end</code> and <code>popitem(last=False)</code> are this page's two moves, and the verifier uses it as the oracle here. Ruby's Hash and JavaScript's Map keep insertion order, so deleting and re-inserting a key moves it to the end. Go and Rust have no ordered map in the standard library, which is why the listings build the list by hand everywhere. An interviewer usually wants to see the hand-built one.", my: "Python ၏ <code>OrderedDict</code> သည် အတွင်းတွင် linked list ပါသော hash map အတိအကျ — <code>move_to_end</code> နှင့် <code>popitem(last=False)</code> သည် ဤစာမျက်နှာ၏ လှုပ်ရှားမှု နှစ်ခု ဖြစ်ပြီး verifier က ၎င်းကို oracle အဖြစ် သုံးသည်။ Ruby ၏ Hash နှင့် JavaScript ၏ Map သည် ထည့်သည့် အစီအစဉ်ကို ထိန်းသဖြင့် key ကို ဖျက်ပြီး ပြန်ထည့်လျှင် နောက်ဆုံးသို့ ရွှေ့သည်။ Go နှင့် Rust ၏ standard library တွင် ordered map မရှိသဖြင့် listing များသည် နေရာတိုင်းတွင် list ကို လက်ဖြင့် တည်ဆောက်သည်။ interviewer များသည် များသောအားဖြင့် လက်ဖြင့် တည်ဆောက်ထားသည်ကို မြင်ချင်သည်။" } },
      { q: { en: "Why does the Rust version keep the nodes in a Vec?", my: "Rust version က node များကို ဘာကြောင့် Vec ထဲ ထားသလဲ။" }, a: { en: "A doubly linked list gives every node two owners — its neighbours — which Rust's borrow rules do not allow with plain references. Storing the nodes in a <code>Vec</code> and linking them by index sidesteps that: <code>prev</code> and <code>next</code> are just numbers. Evicted slots are left behind rather than reused, so the Vec grows by one per new key — at most 2 × 10⁵ small nodes.", my: "doubly linked list သည် node တိုင်းကို ပိုင်ရှင် နှစ်ဦး — ၎င်း၏ အိမ်နီးများ — ပေးပြီး Rust ၏ borrow စည်းမျဉ်းက ရိုးရိုး reference ဖြင့် ခွင့်မပြုပါ။ node များကို <code>Vec</code> ထဲ သိမ်းပြီး index ဖြင့် ချိတ်ခြင်းက ထိုပြဿနာကို ရှောင်သည် — <code>prev</code> နှင့် <code>next</code> သည် ဂဏန်းများသာ။ ဖယ်ထားသော slot များကို ပြန်မသုံးဘဲ ချန်ထားသဖြင့် Vec သည် key အသစ်တစ်ခုလျှင် တစ်ခု ကြီးလာသည် — node သေးသေး အများဆုံး 2 × 10⁵။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "A scan per call, or none", my: "call တစ်ခုလျှင် scan တစ်ခု၊ သို့မဟုတ် မရှိ" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Per call</th><th>Space</th><th>Capacity 3,000, 2 × 10⁵ calls</th></tr></thead>\n  <tbody>\n    <tr><td><b>Recency list</b><br><span class=\"sub\">not O(1)</span></td>\n        <td class=\"mono\">O(capacity)</td><td class=\"mono\">O(capacity)</td><td class=\"cross\">2.22 s</td></tr>\n    <tr><td><b>Hash map + linked list</b><br><span class=\"sub\">O(1)</span></td>\n        <td class=\"mono\">O(1)</td><td class=\"mono\">O(capacity)</td><td class=\"tick\">0.05 s</td></tr>\n  </tbody>\n</table>\n<figcaption>Measured here: the Python listings on an Apple M5 Pro, whole process, best of three, on a full 3,000-key cache asked 197,000 times for its newest keys — the worst case for the list, whose scan starts at the oldest end. The list scan runs in C, which hides how much work it does; on random calls the gap is 0.43 s to 0.08 s.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>call တစ်ခုလျှင်</th><th>Memory</th><th>Capacity 3,000၊ call 2 × 10⁵</th></tr></thead>\n  <tbody>\n    <tr><td><b>Recency list</b><br><span class=\"sub\">O(1) မဟုတ်</span></td>\n        <td class=\"mono\">O(capacity)</td><td class=\"mono\">O(capacity)</td><td class=\"cross\">2.22 s</td></tr>\n    <tr><td><b>Hash map + linked list</b><br><span class=\"sub\">O(1)</span></td>\n        <td class=\"mono\">O(1)</td><td class=\"mono\">O(capacity)</td><td class=\"tick\">0.05 s</td></tr>\n  </tbody>\n</table>\n<figcaption>ဤနေရာတွင် တိုင်းတာထားသည် — Apple M5 Pro ပေါ်ရှိ Python listing များ၊ process တစ်ခုလုံး၊ သုံးကြိမ်အနက် အကောင်းဆုံး၊ ၎င်း၏ အသစ်ဆုံး key များကို 197,000 ကြိမ် မေးခံရသော key 3,000 ပြည့် cache ပေါ်တွင် — scan ကို အဟောင်းဆုံးဘက်မှ စသော list အတွက် အဆိုးဆုံး အခြေအနေ။ list scan သည် C ဖြင့် run သဖြင့် ၎င်းလုပ်သော အလုပ်ပမာဏကို ဖုံးကွယ်ထားသည် — ကျပန်း call များတွင် ကွာခြားချက်သည် 0.43 s နှင့် 0.08 s ဖြစ်သည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission, and every one was run against the same 20,010 call sequences, up to 2 × 10⁵ calls at capacity 3,000.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး အားလုံးကို capacity 3,000 တွင် call 2 × 10⁵ အထိ call အစီအစဉ် 20,010 ခု တူတူဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>capacity</code> (up to 4) and the calls above — <code>put(1,1), get(1)</code>, up to 12 of them — and both walkthroughs rebuild against them.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>capacity</code> (4 အထိ) နှင့် call များ — <code>put(1,1), get(1)</code>၊ 12 ခုအထိ — ကို ပြင်လိုက်လျှင် walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
