/* The prose of the Binary Tree Maximum Path Sum page: everything the reader
 * sees that is not interactive. Rendered by src/pages/leetcode/[slug].astro
 * through the Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Binary Tree Maximum Path Sum',
  summary: 'Diameter of Binary Tree with values instead of edges. Every path bends at one highest node; the best one there is the node plus each side\'s best downward sum, with a negative side left out. Score every node from scratch, or collect the sums in one pass.',
  eyebrow: 'LeetCode 124 &nbsp;·&nbsp; Hard',
  lede: { en: "Find the largest sum along any path in the tree. Every path has one highest node where it bends, so the answer is, for some node, its value plus the best path going down its left side plus the best going down its right — and any side worth less than nothing is simply left out. One post-order pass hands each node both of those sums.", my: "tree ထဲရှိ မည်သည့် path တစ်ခုခုတွင်မဆို အကြီးဆုံး ပေါင်းလဒ်ကို ရှာပါ။ path တိုင်းတွင် ကွေ့ရာ အမြင့်ဆုံး node တစ်ခု ရှိသဖြင့် အဖြေမှာ node တစ်ခုခု၏ value နှင့် ၎င်း၏ ဘယ်ဘက်သို့ ဆင်းသော အကောင်းဆုံး path၊ ညာဘက်သို့ ဆင်းသော အကောင်းဆုံး path ပေါင်းလဒ် ဖြစ်သည် — ဘာမှမရှိသည်ထက် နည်းသော ဘက်ကို ချန်လိုက်ရုံသာ။ post-order pass တစ်ခုက node တစ်ခုစီကို ထိုပေါင်းလဒ် နှစ်ခုလုံး ပေးသည်။" },
  links: [{ id: 124, title: 'Binary Tree Maximum Path Sum', slug: 'binary-tree-maximum-path-sum', difficulty: 'Hard' }],
  constraints: { en: "<span>the number of nodes in the tree is in the range [1, 3 &times; 10<sup>4</sup>]</span><span>&minus;1000 &le; Node.val &le; 1000</span>", my: "<span>tree ထဲရှိ node အရေအတွက်သည် [1, 3 &times; 10<sup>4</sup>] အတွင်း</span><span>&minus;1000 &le; Node.val &le; 1000</span>" },
  part1Sub: { en: "Read the statement, then move the top of the path through every node and see which sides it keeps.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် path ၏ ထိပ်ကို node တိုင်းသို့ ရွှေ့ပြီး မည်သည့် ဘက်များကို ထိန်းသည်ကို ကြည့်ပါ။" },
  widgetTitle: { en: "Move the top, drop the negative sides", my: "ထိပ်ကို ရွှေ့ပါ — အနုတ်ဘက်များကို ချန်ပါ" },
  traps: {
    summary: { en: "Four ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ လေးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>A path does not have to reach a leaf.</strong> Adding a child's gain even when it is negative makes every path run to the bottom: on <code>[2,-1]</code> that returns 1, when the path <code>[2]</code> alone gives 2. Clamp each side at 0.", my: "<strong>path သည် leaf အထိ ရောက်ရန် မလိုပါ။</strong> ကလေး၏ gain အနုတ် ဖြစ်နေလျှင်ပင် ပေါင်းပါက path တိုင်း အောက်ဆုံးအထိ ရောက်သွားသည် — <code>[2,-1]</code> တွင် 1 ကို ပြန်ပေးသည်၊ <code>[2]</code> path တစ်ခုတည်းက 2 ပေးသော်လည်း။ ဘက်တစ်ခုစီကို 0 တွင် ညှပ်ပါ။" },
      { en: "<strong>Hand the parent one side, not both.</strong> A path going up through the parent can use only one of a node's sides. Returning <code>val + left + right</code> instead of <code>val + max(left, right)</code> returns 15 on <code>[1,2,3,4,5]</code>, whose answer is 11.", my: "<strong>parent ကို ဘက်နှစ်ဘက် မဟုတ်ဘဲ တစ်ဘက်သာ ပေးပါ။</strong> parent ကိုဖြတ်၍ အပေါ်တက်သော path သည် node တစ်ခု၏ ဘက်တစ်ဘက်ကိုသာ သုံးနိုင်သည်။ <code>val + max(left, right)</code> အစား <code>val + left + right</code> ကို ပြန်ပေးလျှင် <code>[1,2,3,4,5]</code> တွင် 15 ကို ပြန်ပေးသည် — အဖြေမှာ 11။" },
      { en: "<strong>The path is non-empty, and every value may be negative.</strong> Starting <code>best</code> at 0 returns 0 on <code>[-3]</code>, whose answer is −3. Start it at −∞, or at the root's value.", my: "<strong>path သည် ဗလာ မဖြစ်ရ၊ value တိုင်း အနုတ် ဖြစ်နိုင်သည်။</strong> <code>best</code> ကို 0 မှ စလျှင် <code>[-3]</code> တွင် 0 ကို ပြန်ပေးသည် — အဖြေမှာ −3။ −∞ မှ သို့မဟုတ် root ၏ value မှ စပါ။" },
      { en: "<strong>The constraints allow a 3 &times; 10<sup>4</sup>-node chain,</strong> and the recursion goes that deep. Measured here on default stacks, cold: Python stops at 1,000 (<code>RecursionError</code>) unless the limit is raised; the one pass overflows past 8,186 nodes on Ruby 3.1 and 6,911 on Node 24.", my: "<strong>ကန့်သတ်ချက်က node 3 &times; 10<sup>4</sup> ကွင်းဆက်ကို ခွင့်ပြုပြီး</strong> recursion သည် ထိုမျှ နက်သည်။ default stack ပေါ်တွင် cold run ဖြင့် ဤနေရာတွင် တိုင်းတာထားသည် — limit မမြှင့်လျှင် Python သည် 1,000 တွင် ရပ်သည် (<code>RecursionError</code>)၊ pass တစ်ခုတည်း ပုံစံသည် Ruby 3.1 တွင် node 8,186 နှင့် Node 24 တွင် 6,911 ကျော်လျှင် overflow ဖြစ်သည်။" },
    ],
  },
  part2Sub: { en: "Two approaches over the same tree. The stage shows the tree and the calls waiting on the stack; the panel shows the line running.", my: "tree တစ်ခုတည်းပေါ်တွင် နည်းလမ်းနှစ်မျိုး။ ဘယ်ဘက်က tree နှင့် stack ပေါ်တွင် စောင့်နေသော call များကို ပြပြီး ညာဘက် panel က အလုပ်လုပ်နေသော code ကြောင်းကို ပြသည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the one pass raises", my: "pass တစ်ခုတည်းနှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why does <code>gain</code> return one number and record another?", my: "<code>gain</code> က ကိန်းတစ်ခုကို ပြန်ပေးပြီး အခြားတစ်ခုကို ဘာကြောင့် မှတ်သလဲ။" }, a: { en: "Because the parent and the answer want different things from a node. The answer wants the best path that bends <em>here</em>, using both sides: <code>val + left + right</code>. The parent wants the best path that can <em>continue up</em> through this node, which can use only one side: <code>val + max(left, right)</code>. The helper returns what the parent needs and keeps the other in <code>best</code> — the same split as Diameter of Binary Tree.", my: "parent နှင့် အဖြေက node တစ်ခုထံမှ မတူသောအရာများကို လိုချင်သောကြောင့် ဖြစ်သည်။ အဖြေက <em>ဤနေရာ</em>တွင် ကွေ့ပြီး ဘက်နှစ်ဘက်လုံးကို သုံးသော အကောင်းဆုံး path ကို လိုချင်သည် — <code>val + left + right</code>။ parent ကမူ ဤ node ကိုဖြတ်၍ <em>အပေါ်ဆက်တက်</em>နိုင်သော အကောင်းဆုံး path ကို လိုချင်ပြီး ဘက်တစ်ဘက်ကိုသာ သုံးနိုင်သည် — <code>val + max(left, right)</code>။ helper က parent လိုသည့်အရာကို ပြန်ပေးပြီး ကျန်တစ်ခုကို <code>best</code> ထဲတွင် သိမ်းသည် — Diameter of Binary Tree ကဲ့သို့ ခွဲခြင်း ဖြစ်သည်။" } },
      { q: { en: "Can <code>gain</code> return a negative number?", my: "<code>gain</code> က အနုတ်ကိန်း ပြန်ပေးနိုင်သလား။" }, a: { en: "Yes — a negative node with nothing worth taking below it returns its own value, because a path that continues up must include this node. The parent is the one that decides to leave it out, with <code>max(0, …)</code>. Meanwhile the bend always counts the node itself — <code>best</code> sees <code>val + left + right</code> — which is how an all-negative tree still gets its largest single value.", my: "ဟုတ်သည် — အောက်တွင် ယူစရာ မရှိသော အနုတ် node သည် ၎င်း၏ value ကိုယ်တိုင်ကို ပြန်ပေးသည်၊ အပေါ်ဆက်တက်သော path သည် ဤ node ကို ပါရမည် ဖြစ်သောကြောင့်။ ၎င်းကို ချန်ရန် ဆုံးဖြတ်သူမှာ parent ဖြစ်ပြီး <code>max(0, …)</code> ဖြင့် ဆုံးဖြတ်သည်။ ကွေ့ရာကမူ node ကိုယ်တိုင်ကို အမြဲ ရေတွက်သည် — <code>best</code> သည် <code>val + left + right</code> ကို မြင်ပြီး ထို့ကြောင့် အားလုံး အနုတ်ဖြစ်သော tree သည်ပင် ၎င်း၏ အကြီးဆုံး value တစ်ခုကို ရသည်။" } },
      { q: { en: "Can the sum overflow a 32-bit integer?", my: "ပေါင်းလဒ်သည် 32-bit integer ကို ကျော်နိုင်သလား။" }, a: { en: "No. The largest possible path uses all 3 &times; 10<sup>4</sup> nodes at 1000 each: 3 &times; 10<sup>7</sup>, far inside an <code>i32</code>. The corpus includes a 3 &times; 10<sup>4</sup>-node chain of −1000s, the most negative case.", my: "မကျော်ပါ။ ဖြစ်နိုင်သော အကြီးဆုံး path သည် 1000 စီရှိသော node 3 &times; 10<sup>4</sup> လုံးကို သုံးသည် — 3 &times; 10<sup>7</sup>၊ <code>i32</code> အတွင်း အများကြီး ကျန်သည်။ corpus တွင် −1000 များဖြင့် node 3 &times; 10<sup>4</sup> ကွင်းဆက် ပါသည် — အနုတ်အများဆုံး case။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "The same sums, measured once or over and over", my: "ပေါင်းလဒ် အတူတူ — တစ်ကြိမ် တိုင်းခြင်း နှင့် ထပ်ခါထပ်ခါ တိုင်းခြင်း" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>Complete tree, 3 × 10⁴ nodes</th><th>A 3 × 10⁴-node chain</th></tr></thead>\n  <tbody>\n    <tr><td><b>Every node as the top</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">down() from scratch per node</span></td>\n        <td class=\"mono\">O(n²)</td><td class=\"mono\">O(h)</td><td>834,496 calls</td><td class=\"cross\">900,030,000 calls</td></tr>\n    <tr><td><b>One pass returning gain</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">each gain once</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(h)</td><td class=\"tick\">60,001 calls</td><td class=\"tick\">60,001 calls</td></tr>\n  </tbody>\n</table>\n<figcaption>Calls to <code>down</code> or <code>gain</code>, counting the ones on null — computed, not timed. Both approaches recurse as deep as the tree, so both need the stack notes in part 3.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>ပြည့်စုံသော tree၊ node 3 × 10⁴</th><th>node 3 × 10⁴ ကွင်းဆက်</th></tr></thead>\n  <tbody>\n    <tr><td><b>Every node as the top</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">node တိုင်းတွင် down() ကို အစမှ</span></td>\n        <td class=\"mono\">O(n²)</td><td class=\"mono\">O(h)</td><td>call 834,496</td><td class=\"cross\">call 900,030,000</td></tr>\n    <tr><td><b>One pass returning gain</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">gain တစ်ခုစီ တစ်ကြိမ်</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(h)</td><td class=\"tick\">call 60,001</td><td class=\"tick\">call 60,001</td></tr>\n  </tbody>\n</table>\n<figcaption>null ပေါ်ရှိ call များပါ <code>down</code> သို့မဟုတ် <code>gain</code> call အရေအတွက် — တွက်ချက်ထားခြင်းဖြစ်ပြီး အချိန် မတိုင်းထားပါ။ နည်းလမ်း နှစ်ခုလုံး tree ၏ အနက်အထိ recurse လုပ်သဖြင့် part 3 ရှိ stack မှတ်ချက်များ နှစ်ခုလုံးနှင့် သက်ဆိုင်သည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission and was run against the same cases; the badges and notes say where the recursion needs more stack.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး case တူတူဖြင့် run ထားသည် — recursion တွင် stack ပိုလိုသည့်နေရာကို badge နှင့် မှတ်ချက်များက ဖော်ပြသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>root</code> above — level order, <code>null</code> for a missing child, up to 15 nodes — and both walkthroughs rebuild against your tree.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>root</code> ကို ပြင်လိုက်လျှင် (level order၊ ကလေး မရှိလျှင် <code>null</code>၊ node 15 ခုအထိ) walkthrough နှစ်ခုစလုံး သင့် tree ဖြင့် ပြန်တည်ဆောက်မည်။" },
};
