/* The prose of the Longest Increasing Path in a Matrix page: everything the
 * reader sees that is not interactive. Rendered by src/pages/leetcode/[slug].astro
 * through the Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Longest Increasing Path in a Matrix',
  summary: 'The longest path starting at a cell never changes, so a DFS that remembers it visits each cell once. Or peel the peaks off layer by layer and count the layers — the same O(m·n), with no recursion.',
  eyebrow: 'LeetCode 329 &nbsp;·&nbsp; Hard',
  lede: { en: "Find the longest path through a grid that climbs strictly at every step, moving only up, down, left or right. From any cell, the best path is one step to its best larger neighbour and on from there — an answer that never changes, so it can be worked out once and remembered. Because every step goes up, a path can never loop back, and no visited set is needed.", my: "အဆင့်တိုင်းတွင် တင်းကျပ်စွာ တက်ပြီး အပေါ်၊ အောက်၊ ဘယ်၊ ညာ သာ ရွှေ့သော grid ထဲရှိ အရှည်ဆုံး path ကို ရှာပါ။ မည်သည့် cell မှမဆို အကောင်းဆုံး path သည် ၎င်း၏ အကောင်းဆုံး ပိုကြီးသော အိမ်နီးသို့ တစ်ဆင့်သွားပြီး ထိုမှ ဆက်ခြင်း — ဘယ်တော့မှ မပြောင်းသော အဖြေ ဖြစ်သဖြင့် တစ်ကြိမ် တွက်ပြီး မှတ်ထားနိုင်သည်။ အဆင့်တိုင်း တက်သဖြင့် path သည် ဘယ်တော့မှ ပြန်မလှည့်နိုင်ဘဲ visited set မလိုပါ။" },
  links: [{ id: 329, title: 'Longest Increasing Path in a Matrix', slug: 'longest-increasing-path-in-a-matrix', difficulty: 'Hard' }],
  constraints: { en: "<span><b>m</b> == matrix.length</span><span><b>n</b> == matrix[i].length</span><span>1 &le; m, n &le; 200</span><span>0 &le; matrix[i][j] &le; 2<sup>31</sup> &minus; 1</span>", my: "<span><b>m</b> == matrix.length</span><span><b>n</b> == matrix[i].length</span><span>1 &le; m, n &le; 200</span><span>0 &le; matrix[i][j] &le; 2<sup>31</sup> &minus; 1</span>" },
  part1Sub: { en: "Read the statement, then click a cell to see the longest path that climbs from it.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် cell တစ်ခုကို နှိပ်ပြီး ၎င်းမှ တက်သော အရှည်ဆုံး path ကို ကြည့်ပါ။" },
  widgetTitle: { en: "Pick a start, watch the path climb", my: "အစကို ရွေးပါ — path တက်ပုံ ကြည့်ပါ" },
  traps: {
    summary: { en: "Four ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ လေးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>Increasing means strictly.</strong> Stepping onto an equal neighbour with <code>&gt;=</code> lets two equal cells call each other forever, since neither has a memo entry yet: example 1's pair of 9s sends Python into <code>RecursionError</code>.", my: "<strong>Increasing ဆိုသည်မှာ တင်းကျပ်စွာ ဖြစ်သည်။</strong> <code>&gt;=</code> ဖြင့် တူညီသော အိမ်နီးသို့ သွားခွင့်ပြုလျှင် တူညီသော cell နှစ်ခုသည် တစ်ခုကိုတစ်ခု အဆုံးမရှိ ခေါ်သည် — နှစ်ခုလုံးတွင် memo မရှိသေးသောကြောင့်။ ဥပမာ 1 ၏ 9 အတွဲက Python ကို <code>RecursionError</code> ဖြစ်စေသည်။" },
      { en: "<strong>A path can start anywhere.</strong> Climbing only from the smallest value finds 4 on example 1 and 2 on example 2, whose best path starts at a 3. Try every cell as a start; the memo makes that cheap.", my: "<strong>path သည် မည်သည့်နေရာမှမဆို စနိုင်သည်။</strong> အငယ်ဆုံး value မှသာ တက်လျှင် ဥပမာ 1 တွင် 4 ရပြီး ဥပမာ 2 တွင် 2 ရသည် — ၎င်း၏ အကောင်းဆုံး path သည် 3 တစ်ခုမှ စသည်။ cell တိုင်းကို အစအဖြစ် စမ်းပါ — memo က ထိုအရာကို သက်သာစေသည်။" },
      { en: "<strong>Without the memo it is exponential.</strong> The same DFS that forgets each answer re-walks every path from every cell: on a 14 &times; 14 grid of <code>r + c</code> Python took 29.8 s here (Apple M5 Pro), and the constraint is 200 &times; 200. With the memo, 200 &times; 200 takes 0.015 s.", my: "<strong>memo မပါလျှင် exponential ဖြစ်သည်။</strong> အဖြေတစ်ခုစီကို မေ့သော DFS အတူတူသည် cell တိုင်းမှ path တိုင်းကို ပြန်လျှောက်သည် — <code>r + c</code> ၏ 14 &times; 14 grid တွင် Python က ဤနေရာ (Apple M5 Pro) တွင် 29.8 စက္ကန့် ကြာပြီး ကန့်သတ်ချက်မှာ 200 &times; 200။ memo ပါလျှင် 200 &times; 200 သည် 0.015 စက္ကန့်။" },
      { en: "<strong>The recursion can go 20,000 deep.</strong> A 200 &times; 200 grid built as one winding path, with walls between its rows, forces the memo DFS 20,099 calls deep. Measured here on default stacks, cold: Python stops at 1,000 unless the limit is raised; Ruby 3.1 overflows past 2,846 and Node 24 past 4,609.", my: "<strong>recursion သည် 20,000 ဆင့် နက်နိုင်သည်။</strong> row များကြားတွင် နံရံများပါသော ကွေ့ကောက်သည့် path တစ်ခုအဖြစ် တည်ဆောက်ထားသော 200 &times; 200 grid က memo DFS ကို call 20,099 ဆင့် နက်စေသည်။ default stack ပေါ်တွင် cold run ဖြင့် ဤနေရာတွင် တိုင်းတာထားသည် — limit မမြှင့်လျှင် Python သည် 1,000 တွင် ရပ်သည်၊ Ruby 3.1 သည် 2,846 နှင့် Node 24 သည် 4,609 ကျော်လျှင် overflow ဖြစ်သည်။" },
    ],
  },
  part2Sub: { en: "Two approaches over the same matrix. The strip is the matrix, with the cell being worked on in amber; the stage is what each approach fills in — the memo table and the call stack, or the count of larger neighbours still standing.", my: "matrix တစ်ခုတည်းပေါ်တွင် နည်းလမ်းနှစ်မျိုး။ strip သည် matrix ဖြစ်ပြီး လုပ်နေသော cell ကို amber ဖြင့် ပြသည်။ stage သည် နည်းလမ်းတစ်ခုစီ ဖြည့်သည့်အရာ — memo table နှင့် call stack၊ သို့မဟုတ် ကျန်နေသေးသော ပိုကြီးသည့် အိမ်နီး အရေအတွက်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the two approaches raise", my: "နည်းလမ်း နှစ်ခုနှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why is there no visited set?", my: "visited set ဘာကြောင့် မရှိသလဲ။" }, a: { en: "Because every step goes to a strictly larger value, a path can never come back to a cell it has left — it would have to go down to get there. So the DFS cannot loop, and the only thing worth remembering is each cell's finished answer. That is also why the memo can be trusted the moment it is written: the longest path from a cell does not depend on how you arrived at it.", my: "အဆင့်တိုင်း တင်းကျပ်စွာ ပိုကြီးသော value သို့ သွားသဖြင့် path သည် ထွက်ခွာခဲ့သော cell သို့ ဘယ်တော့မှ ပြန်မလာနိုင် — ထိုနေရာရောက်ရန် အောက်သို့ ဆင်းရမည် ဖြစ်သောကြောင့်။ ထို့ကြောင့် DFS သည် loop မဖြစ်နိုင်ဘဲ မှတ်ထိုက်သည့်အရာမှာ cell တစ်ခုစီ၏ ပြီးဆုံးသော အဖြေသာ ဖြစ်သည်။ memo ကို ရေးသည့် ခဏမှာပင် ယုံနိုင်သည့် အကြောင်းလည်း ဖြစ်သည် — cell တစ်ခုမှ အရှည်ဆုံး path သည် ၎င်းသို့ မည်သို့ ရောက်လာသည်အပေါ် မမူတည်ပါ။" } },
      { q: { en: "Why does the number of layers equal the longest path?", my: "layer အရေအတွက်သည် အရှည်ဆုံး path နှင့် ဘာကြောင့် ညီသလဲ။" }, a: { en: "A cell is peeled in layer <em>k</em> exactly when the longest path starting at it has <em>k</em> cells. Layer 1 is the peaks, whose longest path is themselves. A cell joins layer <em>k</em> + 1 when its last larger neighbour is peeled, in layer <em>k</em> — so its best step up leads into layer <em>k</em>, and none of its larger neighbours is in a later one. The last layer holds the starts of the longest paths. This is Kahn's topological sort, counting levels instead of listing an order.", my: "cell တစ်ခုမှ စသော အရှည်ဆုံး path တွင် cell <em>k</em> ခု ရှိမှသာ ၎င်းကို layer <em>k</em> တွင် ခွာသည်။ layer 1 သည် peak များ ဖြစ်ပြီး ၎င်းတို့၏ အရှည်ဆုံး path သည် ကိုယ်တိုင်။ cell တစ်ခုသည် ၎င်း၏ နောက်ဆုံး ပိုကြီးသော အိမ်နီးကို layer <em>k</em> တွင် ခွာသည့်အခါ layer <em>k</em> + 1 ထဲ ဝင်သည် — ထို့ကြောင့် ၎င်း၏ အကောင်းဆုံး တက်ဆင့်သည် layer <em>k</em> သို့ ရောက်ပြီး ၎င်း၏ ပိုကြီးသော အိမ်နီး တစ်ခုမှ နောက်ပိုင်း layer တွင် မရှိ။ နောက်ဆုံး layer တွင် အရှည်ဆုံး path များ၏ အစ ရှိသည်။ ၎င်းသည် Kahn ၏ topological sort ဖြစ်ပြီး အစီအစဉ်ကို စာရင်းမပြုဘဲ level များကို ရေတွက်သည်။" } },
      { q: { en: "Do values up to 2<sup>31</sup> &minus; 1 need a 64-bit type?", my: "2<sup>31</sup> &minus; 1 အထိ value များအတွက် 64-bit type လိုသလား။" }, a: { en: "No. 2<sup>31</sup> &minus; 1 is the largest 32-bit signed integer, so it fits an <code>i32</code> exactly, and the code only ever compares values — it never adds them. The lengths it does add are at most 40,000. The corpus includes a 200 &times; 200 grid of random values up to 2<sup>31</sup> &minus; 1.", my: "မလိုပါ။ 2<sup>31</sup> &minus; 1 သည် အကြီးဆုံး 32-bit signed integer ဖြစ်သဖြင့် <code>i32</code> ထဲ အတိအကျ ဝင်ပြီး code သည် value များကို နှိုင်းယှဉ်ရုံသာ — ဘယ်တော့မှ မပေါင်းပါ။ ၎င်းပေါင်းသော အရှည်များသည် အများဆုံး 40,000။ corpus တွင် 2<sup>31</sup> &minus; 1 အထိ random value များပါသော 200 &times; 200 grid ပါသည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "Remember each answer, or walk every path", my: "အဖြေတစ်ခုစီကို မှတ်ခြင်း သို့မဟုတ် path တိုင်းကို လျှောက်ခြင်း" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>Python, measured</th></tr></thead>\n  <tbody>\n    <tr><td><b>DFS without a memo</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">not on this page — the trap</span></td>\n        <td class=\"mono\">exponential</td><td class=\"mono\">O(m·n)</td><td class=\"cross\">29.8 s on 14 × 14</td></tr>\n    <tr><td><b>DFS with a memo</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">each cell once, recursive</span></td>\n        <td class=\"mono\">O(m·n)</td><td class=\"mono\">O(m·n)</td><td class=\"tick\">0.015 s on 200 × 200</td></tr>\n    <tr><td><b>Peel the peaks</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">each cell once, no recursion</span></td>\n        <td class=\"mono\">O(m·n)</td><td class=\"mono\">O(m·n)</td><td class=\"tick\">0.017 s on 200 × 200</td></tr>\n  </tbody>\n</table>\n<figcaption>Best of three on an Apple M5 Pro, on grids of <code>r + c</code>, where the number of increasing paths explodes. The two O(m·n) approaches cost the same; what separates them is the stack — the memo DFS recurses up to 20,099 deep on a grid built for it, the peeling needs none.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>Python၊ တိုင်းထားသည်</th></tr></thead>\n  <tbody>\n    <tr><td><b>DFS without a memo</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">ဤစာမျက်နှာတွင် မပါ — ထောင်ချောက်</span></td>\n        <td class=\"mono\">exponential</td><td class=\"mono\">O(m·n)</td><td class=\"cross\">14 × 14 တွင် 29.8 စက္ကန့်</td></tr>\n    <tr><td><b>DFS with a memo</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">cell တစ်ခုစီ တစ်ကြိမ်၊ recursive</span></td>\n        <td class=\"mono\">O(m·n)</td><td class=\"mono\">O(m·n)</td><td class=\"tick\">200 × 200 တွင် 0.015 စက္ကန့်</td></tr>\n    <tr><td><b>Peel the peaks</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">cell တစ်ခုစီ တစ်ကြိမ်၊ recursion မပါ</span></td>\n        <td class=\"mono\">O(m·n)</td><td class=\"mono\">O(m·n)</td><td class=\"tick\">200 × 200 တွင် 0.017 စက္ကန့်</td></tr>\n  </tbody>\n</table>\n<figcaption>Apple M5 Pro ပေါ်တွင် သုံးကြိမ်အနက် အကောင်းဆုံး — increasing path အရေအတွက် ပေါက်ကွဲသော <code>r + c</code> grid များပေါ်တွင်။ O(m·n) နည်းလမ်း နှစ်ခု၏ ကုန်ကျမှု တူသည် — ၎င်းတို့ကို ခွဲခြားသည်မှာ stack — memo DFS သည် ထိုအတွက် တည်ဆောက်ထားသော grid တွင် 20,099 ဆင့်အထိ recurse လုပ်ပြီး ခွာခြင်းက မလိုပါ။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission, and every one was run against the same 20,016 grids, up to 200 × 200; the badges and notes say where the recursion needs more stack.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး အားလုံးကို 200 × 200 အထိ grid 20,016 ခု တူတူဖြင့် run ထားသည် — recursion တွင် stack ပိုလိုသည့်နေရာကို badge နှင့် မှတ်ချက်များက ဖော်ပြသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>matrix</code> above — rows split by <code>;</code>, up to 5 × 5, values up to 999 — and both walkthroughs rebuild against it.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>matrix</code> ကို ပြင်လိုက်လျှင် (row များကို <code>;</code> ဖြင့် ခွဲ၊ 5 × 5 အထိ၊ value 999 အထိ) walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
