/* The prose of the Number of Islands page: everything the reader sees that is
 * not interactive. Rendered by src/pages/leetcode/[slug].astro through the
 * Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Number of Islands',
  summary: 'Scan the grid; each land cell nothing has sunk yet starts a new island, and sinking the whole island before moving on keeps the scan from counting it twice. Recursion does it in six lines, and runs 90,000 deep.',
  eyebrow: 'LeetCode 200 &nbsp;·&nbsp; Medium',
  lede: { en: "Count the islands in a grid of land and water. The trick is to count each island exactly once: the first time the scan steps on one, sink the whole thing — turn every connected land cell to water — so nothing later can find it again. Recursion or a queue does the sinking; the choice decides how deep the call stack goes.", my: "ကုန်းနှင့် ရေ grid တစ်ခုရှိ ကျွန်းများကို ရေတွက်ပါ။ နည်းလမ်းမှာ ကျွန်းတစ်ခုစီကို တစ်ကြိမ်တည်း ရေတွက်ရန် — scan က ကျွန်းတစ်ခုကို ပထမဆုံး နင်းမိချိန်တွင် ၎င်းတစ်ခုလုံးကို နှစ်ပစ်သည် — ဆက်နေသော ကုန်း cell တိုင်းကို ရေ ပြောင်းသည် — ထို့ကြောင့် နောက်ပိုင်း ဘာမှ ထပ်မတွေ့နိုင်တော့။ recursion သို့မဟုတ် queue က နှစ်ခြင်းကို လုပ်ပြီး ထိုရွေးချယ်မှုက call stack မည်မျှ နက်မည်ကို ဆုံးဖြတ်သည်။" },
  links: [{ id: 200, title: 'Number of Islands', slug: 'number-of-islands', difficulty: 'Medium' }],
  constraints: { en: "<span><b>m</b> == grid.length</span><span><b>n</b> == grid[i].length</span><span>1 &le; m, n &le; 300</span><span>grid[i][j] is '0' or '1'</span>", my: "<span><b>m</b> == grid.length</span><span><b>n</b> == grid[i].length</span><span>1 &le; m, n &le; 300</span><span>grid[i][j] သည် '0' သို့မဟုတ် '1'</span>" },
  part1Sub: { en: "Read the statement, then raise and flood cells to see which ones join.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် cell များကို ကုန်း/ရေ ပြောင်းပြီး မည်သည်တို့ ဆက်သလဲ ကြည့်ပါ။" },
  widgetTitle: { en: "Click cells, watch which ones join", my: "cell များကို နှိပ်ပါ — မည်သည်တို့ ဆက်သလဲ ကြည့်ပါ" },
  traps: {
    summary: { en: "Four ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ လေးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>Only four neighbours join.</strong> \"Horizontally or vertically\" leaves out the diagonals. Checking all eight neighbours joins the middle cell of example 2 to both corners and returns <code>1</code>, not <code>3</code>.", my: "<strong>အိမ်နီး လေးခုသာ ဆက်သည်။</strong> \"အလျားလိုက် သို့မဟုတ် ဒေါင်လိုက်\" ဆိုသည်က ထောင့်ဖြတ်ကို ချန်ထားသည်။ အိမ်နီး ရှစ်ခုလုံး စစ်လျှင် ဥပမာ 2 ၏ အလယ် cell ကို ထောင့်နှစ်ဖက်လုံးနှင့် ဆက်ပြီး <code>3</code> အစား <code>1</code> ပြန်ပေးသည်။" },
      { en: "<strong>The cells are characters.</strong> The grid holds <code>'1'</code> and <code>'0'</code>, not numbers. Comparing with the integer <code>1</code> — <code>grid[r][c] == 1</code> in Python, <code>=== 1</code> in JavaScript — never matches, and both examples return <code>0</code>.", my: "<strong>cell များသည် စာလုံးများ ဖြစ်သည်။</strong> grid တွင် ဂဏန်းမဟုတ်ဘဲ <code>'1'</code> နှင့် <code>'0'</code> ပါသည်။ integer <code>1</code> နှင့် နှိုင်းယှဉ်လျှင် — Python တွင် <code>grid[r][c] == 1</code>၊ JavaScript တွင် <code>=== 1</code> — ဘယ်တော့မှ မကိုက်ဘဲ ဥပမာ နှစ်ခုလုံး <code>0</code> ပြန်ပေးသည်။" },
      { en: "<strong>Mark a cell before you leave it.</strong> A flood fill that visits neighbours without turning the cell to <code>'0'</code> (or recording it as seen) walks back and forth between two land cells forever: on example 1 Python stops with <code>RecursionError</code>.", my: "<strong>cell တစ်ခုကို မထွက်ခွာမီ အမှတ်အသား လုပ်ပါ။</strong> cell ကို <code>'0'</code> မပြောင်းဘဲ (သို့မဟုတ် မြင်ပြီးဟု မမှတ်ဘဲ) အိမ်နီးများကို သွားသော flood fill သည် ကုန်း cell နှစ်ခုကြား အဆုံးမရှိ အပြန်အလှန် လျှောက်သည် — ဥပမာ 1 တွင် Python သည် <code>RecursionError</code> ဖြင့် ရပ်သည်။" },
      { en: "<strong>One island can be the whole grid.</strong> 300 × 300 land is one island 90,000 cells long, and a recursive flood fill goes that deep. At Python's default limit of 1,000 calls a 32 × 32 grid of land already fails; Ruby's and Node's default stacks give out past 8,729 and 9,813 cells (measured here).", my: "<strong>ကျွန်းတစ်ခုသည် grid တစ်ခုလုံး ဖြစ်နိုင်သည်။</strong> ကုန်းချည်း 300 × 300 သည် cell 90,000 ရှည်သော ကျွန်းတစ်ခု ဖြစ်ပြီး recursive flood fill သည် ထိုမျှ နက်သွားသည်။ Python ၏ default call 1,000 ကန့်သတ်ချက်တွင် ကုန်းချည်း 32 × 32 grid ပင် ကျရှုံးသည် — Ruby နှင့် Node ၏ default stack များသည် cell 8,729 နှင့် 9,813 ကျော်လျှင် ကုန်သည် (ဤနေရာတွင် တိုင်းတာထားသည်)။" },
    ],
  },
  part2Sub: { en: "Two ways to sink an island. The strip is the grid as the code holds it — sunk land keeps a green rim so you can see what has been counted; the stage is what the approach carries between steps: the call stack, or the queue.", my: "ကျွန်းကို နှစ်ရန် နည်းလမ်းနှစ်မျိုး။ strip သည် code ကိုင်ထားသည့်အတိုင်း grid ဖြစ်သည် — နှစ်ပြီးသော ကုန်းသည် အစိမ်းရောင် ဘောင်ကို ထိန်းထားသဖြင့် ဘာကို ရေတွက်ပြီးပြီ မြင်ရသည်။ stage သည် နည်းလမ်းက အဆင့်များကြား သယ်ဆောင်သည့်အရာ — call stack သို့မဟုတ် queue ဖြစ်သည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Four questions the flood fill raises", my: "flood fill နှင့်ပတ်သက်၍ မေးစရာ လေးခု" },
    items: [
      { q: { en: "Why sink the land instead of keeping a visited set?", my: "visited set ထားမည့်အစား ဘာကြောင့် ကုန်းကို နှစ်သလဲ။" }, a: { en: "The grid already has room for one bit of news per cell, and the answer never needs the land again once it is counted. Writing <code>'0'</code> is the visited set, with no extra memory. If the caller needs the grid back unchanged, copy it first or keep a separate <code>seen</code> array — the algorithm is the same.", my: "grid တွင် cell တစ်ခုလျှင် သတင်း bit တစ်ခုအတွက် နေရာ ရှိပြီးသား ဖြစ်ပြီး ရေတွက်ပြီးနောက် အဖြေက ကုန်းကို ထပ်မလိုတော့ပါ။ <code>'0'</code> ရေးခြင်းသည်ပင် visited set ဖြစ်ပြီး အပို memory မလိုပါ။ ခေါ်သူက grid ကို မပြောင်းဘဲ ပြန်လိုလျှင် အရင် copy ကူးပါ သို့မဟုတ် သီးခြား <code>seen</code> array ထားပါ — algorithm အတူတူပင်။" } },
      { q: { en: "Why sink a cell when it is queued, not when it is popped?", my: "cell ကို ထုတ်ချိန်မဟုတ်ဘဲ queue ထဲ ထည့်ချိန်တွင် ဘာကြောင့် နှစ်သလဲ။" }, a: { en: "A cell waiting in the queue is still <code>'1'</code> if you only mark it on pop, so each of its other neighbours queues it again. The count stays right, but on a 300 × 300 grid of land the queue takes 179,401 pushes instead of 90,000 and grows to 599 cells instead of 300 (counted here). Marking on push queues every cell exactly once.", my: "ထုတ်ချိန်တွင်သာ အမှတ်အသား လုပ်လျှင် queue ထဲ စောင့်နေသော cell သည် <code>'1'</code> ဖြစ်နေဆဲ ဖြစ်သဖြင့် ၎င်း၏ အခြား အိမ်နီးတစ်ခုစီက ထပ်ထည့်သည်။ count မှန်နေဆဲ ဖြစ်သော်လည်း ကုန်းချည်း 300 × 300 grid တွင် queue သည် push 90,000 အစား 179,401 ကြိမ် လုပ်ပြီး cell 300 အစား 599 အထိ ကြီးသည် (ဤနေရာတွင် ရေတွက်ထားသည်)။ ထည့်ချိန်တွင် အမှတ်အသားလုပ်လျှင် cell တိုင်းကို တစ်ကြိမ်တိတိ ထည့်သည်။" } },
      { q: { en: "Is there a way without flood fill at all?", my: "flood fill လုံးဝ မပါသော နည်း ရှိသလား။" }, a: { en: "Union-find: start with every land cell as its own island, and for each land cell merge it with the land above and to its left; every successful merge removes one island. It is what the verifier uses as the independent oracle here. It shines when land is added one cell at a time (Number of Islands II), where re-running a flood fill after every change would be slow.", my: "Union-find — ကုန်း cell တိုင်းကို ကိုယ်ပိုင်ကျွန်းအဖြစ် စပြီး ကုန်း cell တစ်ခုစီကို ၎င်း၏ အပေါ်နှင့် ဘယ်ဘက်ရှိ ကုန်းနှင့် ပေါင်းသည် — အောင်မြင်သော ပေါင်းခြင်းတိုင်းက ကျွန်းတစ်ခု လျော့စေသည်။ ဤနေရာတွင် verifier က သီးခြား oracle အဖြစ် သုံးသည့်နည်း ဖြစ်သည်။ ကုန်းကို cell တစ်ခုချင်း ထည့်သည့်အခါ (Number of Islands II) — ပြောင်းလဲမှုတိုင်းနောက် flood fill ပြန် run ရန် နှေးမည့်နေရာတွင် ထူးချွန်သည်။" } },
      { q: { en: "Does the order of the four calls matter?", my: "call လေးခု၏ အစီအစဉ် အရေးကြီးသလား။" }, a: { en: "Not for the count: every order sinks the same island. It changes the path the recursion takes, and so how deep it goes. With the order used here — down, up, right, left — a grid of all land is walked as one snake through every cell, so the calls go one deeper than there are cells — the last one finds nothing: 43 on a 6 × 7 grid in the walkthrough, 90,001 at the constraint.", my: "count အတွက် မကြီးပါ — မည်သည့် အစီအစဉ်မဆို ကျွန်း အတူတူကို နှစ်သည်။ recursion သွားသော လမ်းကြောင်းနှင့် မည်မျှ နက်မည်ကို ပြောင်းစေသည်။ ဤနေရာတွင် သုံးသော အစီအစဉ် — အောက်၊ အပေါ်၊ ညာ၊ ဘယ် — ဖြင့် ကုန်းချည်း grid ကို cell တိုင်းကို ဖြတ်သော မြွေလမ်းကြောင်း တစ်ခုအဖြစ် လျှောက်သဖြင့် call များသည် cell အရေအတွက်ထက် တစ်ဆင့် ပိုနက်သည် — နောက်ဆုံး call က ဘာမှ မတွေ့ — walkthrough ရှိ 6 × 7 grid တွင် 43၊ ကန့်သတ်ချက်တွင် 90,001။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "The same work, a different kind of memory", my: "အလုပ် အတူတူ — memory အမျိုးအစား ကွဲသည်" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>300 × 300, all land</th></tr></thead>\n  <tbody>\n    <tr><td><b>Sink with DFS</b><br><span class=\"sub\">recursive</span></td>\n        <td class=\"mono\">O(m·n)</td><td class=\"mono\">O(m·n) call stack</td><td class=\"cross\">90,000 calls deep — past Ruby's and Node's default stacks</td></tr>\n    <tr><td><b>Sink with BFS</b><br><span class=\"sub\">a queue</span></td>\n        <td class=\"mono\">O(m·n)</td><td class=\"mono\">O(m·n) queue</td><td class=\"tick\">at most 300 cells waiting</td></tr>\n  </tbody>\n</table>\n<figcaption>Depths and queue sizes are counted, not timed. Both do the same scan and sink every cell once; the difference is only where the unfinished work waits — the call stack, which is small and fixed, or a queue on the heap.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>300 × 300 ကုန်းချည်း</th></tr></thead>\n  <tbody>\n    <tr><td><b>Sink with DFS</b><br><span class=\"sub\">recursive</span></td>\n        <td class=\"mono\">O(m·n)</td><td class=\"mono\">O(m·n) call stack</td><td class=\"cross\">call 90,000 ဆင့် နက် — Ruby နှင့် Node ၏ default stack ကို ကျော်</td></tr>\n    <tr><td><b>Sink with BFS</b><br><span class=\"sub\">queue</span></td>\n        <td class=\"mono\">O(m·n)</td><td class=\"mono\">O(m·n) queue</td><td class=\"tick\">အများဆုံး cell 300 စောင့်</td></tr>\n  </tbody>\n</table>\n<figcaption>အနက်နှင့် queue အရွယ်အစားများကို ရေတွက်ထားခြင်းဖြစ်ပြီး အချိန် မတိုင်းထားပါ။ နှစ်ခုလုံး scan အတူတူ လုပ်ပြီး cell တိုင်းကို တစ်ကြိမ် နှစ်သည် — ကွာခြားချက်မှာ မပြီးသေးသော အလုပ် စောင့်သည့်နေရာသာ — သေးငယ်ပြီး ပုံသေ call stack သို့မဟုတ် heap ပေါ်ရှိ queue။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission, and every one was run against the same 20,013 grids, up to 300 × 300.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး အားလုံးကို 300 × 300 အထိ grid 20,013 ခု တူတူဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>grid</code> above — rows of 0s and 1s split by <code>;</code>, up to 6 rows of 7 — and both walkthroughs rebuild against it.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>grid</code> ကို ပြင်လိုက်လျှင် (0 နှင့် 1 row များကို <code>;</code> ဖြင့် ခွဲ၊ row 6 ခု၊ တစ်ခုလျှင် 7 အထိ) walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
