/* The prose of the Diameter of Binary Tree page: everything the reader sees
 * that is not interactive. Rendered by src/pages/leetcode/[slug].astro through
 * the Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Diameter of Binary Tree',
  summary: 'Every path bends at one highest node, so the longest is some node\'s left height plus its right height. Measure the heights afresh at every node, or collect them in one pass.',
  eyebrow: 'LeetCode 543 &nbsp;·&nbsp; Easy',
  lede: { en: "Find the longest path between any two nodes, counted in edges. Every path has one highest node where it bends, so the answer is the best left-height-plus-right-height over all nodes — and Maximum Depth's recursion already hands each node both heights.", my: "node နှစ်ခုကြား အရှည်ဆုံး လမ်းကြောင်းကို edge ဖြင့် ရေတွက်၍ ရှာပါ။ လမ်းကြောင်းတိုင်းတွင် ကွေ့ရာ အမြင့်ဆုံး node တစ်ခု ရှိသဖြင့် အဖြေမှာ node အားလုံးအနက် ဘယ် height နှင့် ညာ height ပေါင်းလဒ် အကောင်းဆုံး ဖြစ်သည် — Maximum Depth ၏ recursion က node တစ်ခုစီကို height နှစ်ခုလုံး ပေးပြီးသား ဖြစ်သည်။" },
  links: [{ id: 543, title: 'Diameter of Binary Tree', slug: 'diameter-of-binary-tree', difficulty: 'Easy' }],
  constraints: { en: "<span><b>n</b> the number of nodes in the tree is in the range [1, 10&#8308;]</span><span>&minus;100 &le; Node.val &le; 100</span>", my: "<span><b>n</b> tree ထဲရှိ node အရေအတွက်သည် [1, 10&#8308;] အတွင်း</span><span>&minus;100 &le; Node.val &le; 100</span>" },
  part1Sub: { en: "Read the statement, then move the bend through every node and see which one the longest path turns at.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် ကွေ့ရာကို node တိုင်းသို့ ရွှေ့ပြီး အရှည်ဆုံး လမ်းကြောင်း မည်သည့်နေရာတွင် ကွေ့သည်ကို ကြည့်ပါ။" },
  widgetTitle: { en: "Drag the bend, count the edges", my: "ကွေ့ရာကို ဆွဲပါ — edge များကို ရေတွက်ပါ" },
  traps: {
    summary: { en: "Four ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ လေးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>The path may not pass through the root.</strong> Adding the root's two heights passes both examples — 3 and 1 — and returns 3 on <code>[1,2,null,3,4,5,null,null,6]</code>, whose longest path bends at 2 and is 4 long. Every node is a candidate bend.", my: "<strong>လမ်းကြောင်းသည် root ကို မဖြတ်နိုင်ပါ။</strong> root ၏ height နှစ်ခုကို ပေါင်းလျှင် ဥပမာ နှစ်ခုလုံး — 3 နှင့် 1 — အောင်သည်၊ သို့သော် <code>[1,2,null,3,4,5,null,null,6]</code> တွင် 3 ကို ပြန်ပေးသည် — ၎င်း၏ အရှည်ဆုံး လမ်းကြောင်းသည် 2 တွင် ကွေ့ပြီး 4 ရှည်သည်။ node တိုင်းသည် ကွေ့ရာ ဖြစ်နိုင်သည်။" },
      { en: "<strong>Length counts edges, not nodes.</strong> Recording <code>1 + left + right</code> at each node counts the nodes on the path and returns 4 on example 1. With heights counted in nodes (null is 0), <code>left + right</code> is already the edge count.", my: "<strong>အရှည်သည် node များ မဟုတ်ဘဲ edge များကို ရေတွက်သည်။</strong> node တိုင်းတွင် <code>1 + left + right</code> ကို မှတ်လျှင် လမ်းကြောင်းပေါ်ရှိ node များကို ရေတွက်မိပြီး ဥပမာ 1 တွင် 4 ကို ပြန်ပေးသည်။ height ကို node ဖြင့် ရေတွက်လျှင် (null သည် 0) <code>left + right</code> သည် edge အရေအတွက် ဖြစ်ပြီးသား ဖြစ်သည်။" },
      { en: "<strong>Hand the parent the deeper side, not the sum.</strong> A path going up through the parent can use only one of a node's sides. Returning <code>1 + left + right</code> instead of <code>1 + max(left, right)</code> returns 4 on example 1.", my: "<strong>parent ကို ပေါင်းလဒ် မဟုတ်ဘဲ ပိုနက်သော ဘက်ကို ပေးပါ။</strong> parent ကိုဖြတ်၍ အပေါ်တက်သော လမ်းကြောင်းသည် node တစ်ခု၏ ဘက်တစ်ဘက်ကိုသာ သုံးနိုင်သည်။ <code>1 + max(left, right)</code> အစား <code>1 + left + right</code> ကို ပြန်ပေးလျှင် ဥပမာ 1 တွင် 4 ကို ပြန်ပေးသည်။" },
      { en: "<strong>The constraints allow a 10<sup>4</sup>-node chain,</strong> and both versions recurse that deep. Measured here on default stacks, cold: Python stops at 1,000 (<code>RecursionError</code>) unless the limit is raised; the DFS overflows past 8,732 nodes on Ruby 3.1 and 7,773 on Node 24.", my: "<strong>ကန့်သတ်ချက်က node 10<sup>4</sup> ကွင်းဆက်ကို ခွင့်ပြုပြီး</strong> ပုံစံ နှစ်ခုလုံး ထိုမျှ နက်အောင် recurse လုပ်သည်။ default stack ပေါ်တွင် cold run ဖြင့် ဤနေရာတွင် တိုင်းတာထားသည် — limit မမြှင့်လျှင် Python သည် 1,000 တွင် ရပ်သည် (<code>RecursionError</code>)၊ DFS သည် Ruby 3.1 တွင် node 8,732 နှင့် Node 24 တွင် 7,773 ကျော်လျှင် overflow ဖြစ်သည်။" },
    ],
  },
  part2Sub: { en: "Two approaches over the same tree. The stage shows the tree and the calls waiting on the stack; the panel shows the line running.", my: "tree တစ်ခုတည်းပေါ်တွင် နည်းလမ်းနှစ်မျိုး။ ဘယ်ဘက်က tree နှင့် stack ပေါ်တွင် စောင့်နေသော call များကို ပြပြီး ညာဘက် panel က အလုပ်လုပ်နေသော code ကြောင်းကို ပြသည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the one pass raises", my: "တစ်ကြိမ်တည်း လျှောက်ခြင်းနှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why does the helper return one number and record another?", my: "helper က ကိန်းတစ်ခုကို ပြန်ပေးပြီး အခြားတစ်ခုကို ဘာကြောင့် မှတ်သလဲ။" }, a: { en: "Because the parent and the answer want different things from a node. The answer wants the longest path that bends <em>here</em>, which uses both sides: <code>left + right</code>. The parent wants the longest path that can <em>continue up</em> through it, which can use only one side: <code>1 + max(left, right)</code>. The helper returns what the parent needs and keeps the other in <code>best</code>.", my: "parent နှင့် အဖြေက node တစ်ခုထံမှ မတူသောအရာများကို လိုချင်သောကြောင့် ဖြစ်သည်။ အဖြေက <em>ဤနေရာ</em>တွင် ကွေ့သော အရှည်ဆုံး လမ်းကြောင်းကို လိုချင်ပြီး ၎င်းသည် ဘက်နှစ်ဘက်လုံးကို သုံးသည် — <code>left + right</code>။ parent ကမူ ၎င်းကိုဖြတ်၍ <em>အပေါ်ဆက်တက်</em>နိုင်သော အရှည်ဆုံး လမ်းကြောင်းကို လိုချင်ပြီး ဘက်တစ်ဘက်ကိုသာ သုံးနိုင်သည် — <code>1 + max(left, right)</code>။ helper က parent လိုသည့်အရာကို ပြန်ပေးပြီး ကျန်တစ်ခုကို <code>best</code> ထဲတွင် သိမ်းသည်။" } },
      { q: { en: "Why does the Python version need <code>nonlocal</code>?", my: "Python ပုံစံတွင် <code>nonlocal</code> ဘာကြောင့် လိုသလဲ။" }, a: { en: "Because <code>best = max(best, …)</code> assigns to <code>best</code>, and an assignment inside a nested function makes the name local to it. Without the declaration, the right-hand side reads a local that does not exist yet: it raises <code>UnboundLocalError</code> on the first node that finishes. Go and JavaScript closures, and Ruby's instance variable, share the outer variable without being asked; Rust passes it as <code>&amp;mut</code>.", my: "<code>best = max(best, …)</code> သည် <code>best</code> ကို assign လုပ်ပြီး nested function အတွင်း assign လုပ်ခြင်းက ထိုအမည်ကို ၎င်းအတွက် local ဖြစ်စေသောကြောင့် ဖြစ်သည်။ ကြေညာချက် မပါလျှင် ညာဘက်က မရှိသေးသော local ကို ဖတ်ပြီး ပထမဆုံး ပြီးသွားသော node တွင် <code>UnboundLocalError</code> ဖြစ်သည်။ Go နှင့် JavaScript ၏ closure များ၊ Ruby ၏ instance variable တို့သည် အပြင်ဘက် variable ကို မမေးဘဲ မျှဝေသုံးသည် — Rust က <code>&amp;mut</code> အဖြစ် ပေးပို့သည်။" } },
      { q: { en: "Is the brute force always quadratic?", my: "brute force သည် အမြဲ quadratic ဖြစ်သလား။" }, a: { en: "No — it depends on the shape. Each node's subtree is re-walked once for every ancestor, so the cost grows with the sum of all the depths. On a complete 10<sup>4</sup>-node tree that is 247,262 calls to <code>height</code>, about n log n. On a 10<sup>4</sup>-node chain every node has thousands of ancestors: 100,010,000 calls, which took Python 4.3 s here.", my: "မဟုတ်ပါ — ပုံသဏ္ဌာန်ပေါ် မူတည်သည်။ node တစ်ခုစီ၏ subtree ကို ၎င်း၏ ancestor တစ်ခုလျှင် တစ်ကြိမ် ပြန်လျှောက်သဖြင့် ကုန်ကျမှုမှာ depth အားလုံး၏ ပေါင်းလဒ် ဖြစ်သည်။ ပြည့်စုံသော node 10<sup>4</sup> tree တွင် <code>height</code> ကို call 247,262 ခု — n log n ခန့်။ node 10<sup>4</sup> ကွင်းဆက်တွင် node တိုင်း၌ ancestor ထောင်ချီ ရှိသည် — call 100,010,000 ခု၊ ဤနေရာတွင် Python က 4.3 စက္ကန့် ကြာသည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "The same heights, measured once or over and over", my: "height အတူတူ — တစ်ကြိမ် တိုင်းခြင်း နှင့် ထပ်ခါထပ်ခါ တိုင်းခြင်း" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>Complete tree, 10⁴ nodes</th><th>A 10⁴-node chain</th></tr></thead>\n  <tbody>\n    <tr><td><b>Height at every node</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">height() from scratch per node</span></td>\n        <td class=\"mono\">O(n²)</td><td class=\"mono\">O(h)</td><td>247,262 calls</td><td class=\"cross\">100,010,000 calls</td></tr>\n    <tr><td><b>One DFS returning height</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">each height once</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(h)</td><td class=\"tick\">20,001 calls</td><td class=\"tick\">20,001 calls</td></tr>\n  </tbody>\n</table>\n<figcaption>Calls to <code>height</code>, counting the ones on null — computed, not timed. One timing, measured on an Apple M5 Pro: the brute force in Python took 4.3 s on the chain. Both approaches recurse as deep as the tree, so both need the stack notes in part 3.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>ပြည့်စုံသော tree၊ node 10⁴</th><th>node 10⁴ ကွင်းဆက်</th></tr></thead>\n  <tbody>\n    <tr><td><b>Height at every node</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">node တိုင်းတွင် height() ကို အစမှ</span></td>\n        <td class=\"mono\">O(n²)</td><td class=\"mono\">O(h)</td><td>call 247,262</td><td class=\"cross\">call 100,010,000</td></tr>\n    <tr><td><b>One DFS returning height</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">height တစ်ခုစီ တစ်ကြိမ်</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(h)</td><td class=\"tick\">call 20,001</td><td class=\"tick\">call 20,001</td></tr>\n  </tbody>\n</table>\n<figcaption>null ပေါ်ရှိ call များပါ <code>height</code> call အရေအတွက် — တွက်ချက်ထားခြင်းဖြစ်ပြီး အချိန် မတိုင်းထားပါ။ Apple M5 Pro ပေါ်တွင် တိုင်းထားသော အချိန် တစ်ခု — Python brute force သည် ကွင်းဆက်တွင် 4.3 စက္ကန့် ကြာသည်။ နည်းလမ်း နှစ်ခုလုံး tree ၏ အနက်အထိ recurse လုပ်သဖြင့် part 3 ရှိ stack မှတ်ချက်များ နှစ်ခုလုံးနှင့် သက်ဆိုင်သည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission and was run against the same 20,009 cases; the badges and notes say where the recursion needs more stack.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး case 20,009 ခု တူတူဖြင့် run ထားသည် — recursion တွင် stack ပိုလိုသည့်နေရာကို badge နှင့် မှတ်ချက်များက ဖော်ပြသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>root</code> above — level order, <code>null</code> for a missing child, up to 15 nodes — and both walkthroughs rebuild against your tree.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>root</code> ကို ပြင်လိုက်လျှင် (level order၊ ကလေး မရှိလျှင် <code>null</code>၊ node 15 ခုအထိ) walkthrough နှစ်ခုစလုံး သင့် tree ဖြင့် ပြန်တည်ဆောက်မည်။" },
};
