/* The prose of the Merge k Sorted Lists page: everything the reader sees that
 * is not interactive. Rendered by src/pages/leetcode/[slug].astro through the
 * Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Merge k Sorted Lists',
  summary: 'Merging two sorted lists is the easy part; the order of the merges is the problem. Folding into one running list re-walks it k times, O(k·N). Merging in pairs, round after round, moves each node once per round: O(N log k).',
  eyebrow: 'LeetCode 23 &nbsp;·&nbsp; Hard',
  lede: { en: "Merge k sorted linked lists into one. The tool is the two-list merge from Merge Two Sorted Lists; the question is how to schedule it. Folding the lists one at a time into a growing result walks that result again for every new list. Pairing them up like a knockout tournament halves the number of lists each round, so every node is touched only log₂ k times.", my: "စီထားသော linked list k ခုကို တစ်ခုအဖြစ် ပေါင်းပါ။ ကိရိယာမှာ Merge Two Sorted Lists မှ list နှစ်ခု merge ဖြစ်ပြီး မေးခွန်းမှာ ၎င်းကို မည်သို့ အစီအစဉ်ချမလဲ ဆိုသည်။ list များကို ကြီးလာသော ရလဒ်ထဲ တစ်ခုချင်း ပေါင်းခြင်းသည် list အသစ်တိုင်းအတွက် ထိုရလဒ်ကို ထပ်လျှောက်သည်။ knockout ပြိုင်ပွဲကဲ့သို့ အတွဲလိုက် တွဲခြင်းက အကြိမ်တိုင်း list အရေအတွက်ကို ထက်ဝက် လျှော့သဖြင့် node တိုင်းကို log₂ k ကြိမ်သာ ထိသည်။" },
  links: [{ id: 23, title: 'Merge k Sorted Lists', slug: 'merge-k-sorted-lists', difficulty: 'Hard' }],
  constraints: { en: "<span><b>k</b> == lists.length</span><span>0 &le; k &le; 10<sup>4</sup></span><span>0 &le; lists[i].length &le; 500</span><span>&minus;10<sup>4</sup> &le; lists[i][j] &le; 10<sup>4</sup></span><span>each list sorted ascending</span><span>at most 10<sup>4</sup> nodes in all</span>", my: "<span><b>k</b> == lists.length</span><span>0 &le; k &le; 10<sup>4</sup></span><span>0 &le; lists[i].length &le; 500</span><span>&minus;10<sup>4</sup> &le; lists[i][j] &le; 10<sup>4</sup></span><span>list တစ်ခုစီ ငယ်စဉ်ကြီးလိုက်</span><span>node စုစုပေါင်း အများဆုံး 10<sup>4</sup></span>" },
  part1Sub: { en: "Read the statement, then drag k and count how often each list's nodes get walked.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် k ကို ဆွဲပြီး list တစ်ခုစီ၏ node များကို မည်မျှ လျှောက်ရသလဲ ရေတွက်ပါ။" },
  widgetTitle: { en: "Drag k, count the walks", my: "k ကို ဆွဲပါ — လျှောက်ခြင်းကို ရေပါ" },
  traps: {
    summary: { en: "Three ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ သုံးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>k can be 0.</strong> Example 2 is <code>[]</code>: code that pairs lists up and returns <code>lists[0]</code> without checking fails there — Python raises <code>IndexError: list index out of range</code>. <code>[[]]</code> (example 3) is different: one list, empty.", my: "<strong>k သည် 0 ဖြစ်နိုင်သည်။</strong> ဥပမာ 2 သည် <code>[]</code> — list များကို အတွဲလိုက်ပေါင်းပြီး မစစ်ဘဲ <code>lists[0]</code> ပြန်သော code သည် ထိုနေရာတွင် ပျက်သည် — Python သည် <code>IndexError: list index out of range</code> ပေးသည်။ <code>[[]]</code> (ဥပမာ 3) သည် ကွဲပြားသည် — list တစ်ခု၊ ဗလာ။" },
      { en: "<strong>Don't drop the odd one out.</strong> Pairing with <code>range(0, len(lists) - 1, 2)</code> skips the last list when k is odd: example 1 loses <code>[2,6]</code> and returns <code>[1,1,3,4,4,5]</code>.", my: "<strong>အပိုတစ်ခုကို မချန်ပါနှင့်။</strong> <code>range(0, len(lists) - 1, 2)</code> ဖြင့် တွဲလျှင် k မဂဏန်းဖြစ်သည့်အခါ နောက်ဆုံး list ကို ကျော်သည် — ဥပမာ 1 သည် <code>[2,6]</code> ကို ဆုံးရှုံးပြီး <code>[1,1,3,4,4,5]</code> ပြန်ပေးသည်။" },
      { en: "<strong>Ties in a Python heap compare the nodes.</strong> The other O(N log k) answer keeps the k heads in a min-heap. Pushing <code>(val, node)</code> pairs crashes on example 1, where two heads are 1: <code>TypeError: '&lt;' not supported between instances of 'ListNode' and 'ListNode'</code>. Push <code>(val, i, node)</code> with a unique <code>i</code>.", my: "<strong>Python heap တွင် တူညီမှုက node များကို နှိုင်းယှဉ်သည်။</strong> အခြား O(N log k) အဖြေသည် ခေါင်း k ခုကို min-heap ထဲ ထားသည်။ <code>(val, node)</code> pair များကို push လုပ်လျှင် ခေါင်းနှစ်ခု 1 ဖြစ်သော ဥပမာ 1 တွင် ပျက်သည် — <code>TypeError: '&lt;' not supported between instances of 'ListNode' and 'ListNode'</code>။ ထူးခြားသော <code>i</code> ပါသည့် <code>(val, i, node)</code> ကို push လုပ်ပါ။" },
    ],
  },
  part2Sub: { en: "The same two-list merge, in two orders. The strip is the lists as given, with the node just taken lit; the stage is the merge in progress above what the approach is holding, and a count of nodes moved.", my: "list နှစ်ခု merge အတူတူ၊ အစီအစဉ် နှစ်မျိုးဖြင့်။ strip သည် ယခုယူလိုက်သော node ကို လင်းပြထားသည့် ပေးထားသော list များ ဖြစ်သည်။ stage သည် နည်းလမ်းက ကိုင်ထားသည့်အရာ၏ အပေါ်တွင် လုပ်ဆောင်နေသော merge နှင့် ရွှေ့ပြီး node အရေအတွက်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the merges raise", my: "merge များနှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why is merging in pairs O(N log k)?", my: "အတွဲလိုက် ပေါင်းခြင်းသည် ဘာကြောင့် O(N log k) ဖြစ်သလဲ။" }, a: { en: "Each round merges disjoint pairs, so every node takes part in at most one merge per round — O(N) per round. Each round halves the number of lists (rounding up), so k lists need ⌈log₂ k⌉ rounds: 14 for the constraint's 10⁴ lists.", my: "အကြိမ်တိုင်း မထပ်သော အတွဲများကို ပေါင်းသဖြင့် node တိုင်းသည် အကြိမ်တစ်ခုလျှင် merge အများဆုံး တစ်ခုတွင်သာ ပါဝင်သည် — အကြိမ်တစ်ခုလျှင် O(N)။ အကြိမ်တိုင်း list အရေအတွက်ကို ထက်ဝက် (အထက်သို့ ပတ်) လျှော့သဖြင့် list k ခုသည် ⌈log₂ k⌉ ကြိမ် လိုသည် — ကန့်သတ်ချက်၏ list 10⁴ ခုအတွက် 14 ကြိမ်။" } },
      { q: { en: "What about a heap?", my: "heap ကော။" }, a: { en: "Put the k heads in a min-heap; pop the smallest, append it, push its successor. Each of the N nodes costs one push and one pop, O(log k) each — the same O(N log k), with O(k) space and no rounds. Python has <code>heapq</code>, Java a <code>PriorityQueue</code>, Rust <code>BinaryHeap</code>, Go <code>container/heap</code>; Ruby and JavaScript have none built in, so the pairwise merge is the portable version here.", my: "ခေါင်း k ခုကို min-heap ထဲ ထည့် — အငယ်ဆုံးကို pop၊ နောက်တွင် ချိတ်၊ ၎င်း၏ နောက် node ကို push။ node N ခု တစ်ခုစီသည် push တစ်ကြိမ်နှင့် pop တစ်ကြိမ်၊ တစ်ခုစီ O(log k) ကုန်ကျသည် — O(N log k) အတူတူ၊ O(k) memory ဖြင့်၊ အကြိမ်များ မလို။ Python တွင် <code>heapq</code>၊ Java တွင် <code>PriorityQueue</code>၊ Rust တွင် <code>BinaryHeap</code>၊ Go တွင် <code>container/heap</code> ရှိသည် — Ruby နှင့် JavaScript တွင် built-in မရှိသဖြင့် ဤနေရာတွင် အတွဲလိုက် merge သည် နေရာတိုင်း သုံးနိုင်သော version ဖြစ်သည်။" } },
      { q: { en: "Why not collect every value and sort?", my: "value အားလုံးကို စုပြီး ဘာကြောင့် sort မလုပ်သလဲ။" }, a: { en: "It works — O(N log N), and it is the verifier's oracle here — but it ignores that each list is already sorted, and it builds new nodes instead of relinking the ones you were given. Merging uses the order that is already there, which is why it only pays log k instead of log N.", my: "အလုပ်ဖြစ်သည် — O(N log N) ဖြစ်ပြီး ဤနေရာတွင် verifier ၏ oracle ဖြစ်သည် — သို့သော် list တစ်ခုစီ စီပြီးသား ဖြစ်ကြောင်းကို လျစ်လျူရှုပြီး ပေးထားသော node များကို ပြန်ချိတ်မည့်အစား node အသစ်များ တည်ဆောက်သည်။ merge သည် ရှိပြီးသား အစီအစဉ်ကို သုံးသဖြင့် log N အစား log k သာ ပေးရသည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "The same merge, a better schedule", my: "merge အတူတူ — ပိုကောင်းသော အစီအစဉ်" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>10⁴ one-node lists</th></tr></thead>\n  <tbody>\n    <tr><td><b>One at a time</b></td>\n        <td class=\"mono\">O(k · N)</td><td class=\"mono\">O(1)</td><td class=\"cross\">0.47 s · 2.5 × 10⁷ moves</td></tr>\n    <tr><td><b>Merge in pairs</b><br><span class=\"sub\">divide and conquer</span></td>\n        <td class=\"mono\">O(N log k)</td><td class=\"mono\">O(k)</td><td class=\"tick\">0.01 s</td></tr>\n  </tbody>\n</table>\n<figcaption>Measured here: the Python listings on an Apple M5 Pro, whole process, best of three; the move count is computed. The values are random, so each new node lands in the middle of the running result on average; in rising order it would be twice as many moves.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>node တစ်ခုစီပါ list 10⁴</th></tr></thead>\n  <tbody>\n    <tr><td><b>One at a time</b></td>\n        <td class=\"mono\">O(k · N)</td><td class=\"mono\">O(1)</td><td class=\"cross\">0.47 s · ရွှေ့ 2.5 × 10⁷</td></tr>\n    <tr><td><b>Merge in pairs</b><br><span class=\"sub\">divide and conquer</span></td>\n        <td class=\"mono\">O(N log k)</td><td class=\"mono\">O(k)</td><td class=\"tick\">0.01 s</td></tr>\n  </tbody>\n</table>\n<figcaption>ဤနေရာတွင် တိုင်းတာထားသည် — Apple M5 Pro ပေါ်ရှိ Python listing များ၊ process တစ်ခုလုံး၊ သုံးကြိမ်အနက် အကောင်းဆုံး — ရွှေ့ခြင်း အရေအတွက်ကို တွက်ထားသည်။ value များ ကျပန်းဖြစ်သဖြင့် node အသစ်တိုင်း ပျမ်းမျှ ရလဒ်၏ အလယ်တွင် ကျသည် — မြင့်တက်သော အစီအစဉ်ဖြင့်ဆိုလျှင် ရွှေ့ခြင်း နှစ်ဆ ဖြစ်မည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission. Merging in pairs ran against 20,014 inputs up to 10⁴ lists; one at a time against the 20,011 with fewer than 1,000 lists.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်သည်။ အတွဲလိုက်ပေါင်းခြင်းကို list 10⁴ အထိ input 20,014 ခုဖြင့်၊ တစ်ခုချင်းကို list 1,000 အောက် 20,011 ခုဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>lists</code> above — up to 6 sorted lists, 14 values in all — and both walkthroughs rebuild against them.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>lists</code> ကို ပြင်လိုက်လျှင် (စီထားသော list 6 ခုအထိ၊ value စုစုပေါင်း 14) walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
