/* The prose of the Climbing Stairs page: everything the reader sees that is
 * not interactive. Rendered by src/pages/leetcode/[slug].astro through the
 * Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Climbing Stairs',
  summary: 'Every climb ends with a 1-step or a 2-step, so ways(n) = ways(n−1) + ways(n−2). Written as plain recursion it is exponential; a memo makes it linear; two variables make it constant space.',
  eyebrow: 'LeetCode 70 &nbsp;·&nbsp; Easy',
  lede: { en: "Count the ways to reach step n taking 1 or 2 steps at a time. The last move is either a 1 or a 2, so the count is the ways to reach the step below plus the ways to reach the one below that — and the only question left is how many times you are willing to work each of those out.", my: "တစ်ကြိမ်လျှင် step 1 ခု သို့မဟုတ် 2 ခု တက်၍ step n သို့ ရောက်ရန် နည်းများကို ရေတွက်ပါ။ နောက်ဆုံး အလှမ်းသည် 1 သို့မဟုတ် 2 ဖြစ်သဖြင့် အရေအတွက်မှာ အောက်တစ်ဆင့်သို့ ရောက်ရန် နည်းနှင့် ထို့အောက်တစ်ဆင့်သို့ ရောက်ရန် နည်း ပေါင်းလဒ် ဖြစ်သည် — ကျန်သော မေးခွန်းမှာ ၎င်းတို့ တစ်ခုစီကို အကြိမ်မည်မျှ တွက်မည်နည်း ဆိုသည်သာ ဖြစ်သည်။" },
  links: [{ id: 70, title: 'Climbing Stairs', slug: 'climbing-stairs', difficulty: 'Easy' }],
  constraints: { en: "<span>1 &le; <b>n</b> &le; 45</span>", my: "<span>1 &le; <b>n</b> &le; 45</span>" },
  part1Sub: { en: "Read the statement, then list every climb for a small n and look at its last move.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် n ငယ်တစ်ခုအတွက် climb အားလုံးကို စာရင်းပြုစုပြီး ၎င်းတို့၏ နောက်ဆုံး အလှမ်းကို ကြည့်ပါ။" },
  widgetTitle: { en: "Drag n, split the climbs by their last move", my: "n ကို ဆွဲပါ — climb များကို နောက်ဆုံး အလှမ်းဖြင့် ခွဲပါ" },
  traps: {
    summary: { en: "Three ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ သုံးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>Order matters.</strong> 1 + 2 and 2 + 1 are different climbs. Counting only how many 2-steps you use gives ⌊n/2⌋ + 1 — 2 on example 2 instead of 3.", my: "<strong>အစီအစဉ် အရေးကြီးသည်။</strong> 1 + 2 နှင့် 2 + 1 သည် မတူသော climb များ ဖြစ်သည်။ 2-step မည်မျှ သုံးသည်ကိုသာ ရေတွက်လျှင် ⌊n/2⌋ + 1 ရသည် — ဥပမာ 2 တွင် 3 အစား 2။" },
      { en: "<strong>ways(0) is 1, not 0.</strong> Standing at the bottom is one way to be at step 0, and ways(2) = ways(1) + ways(0) needs it. A base case of <code>return n if n &lt;= 1</code> returns 1 on example 1 and 2 on example 2 — every answer one step short.", my: "<strong>ways(0) သည် 0 မဟုတ်ဘဲ 1 ဖြစ်သည်။</strong> အောက်ခြေတွင် ရပ်နေခြင်းသည် step 0 တွင် ရှိရန် နည်း တစ်နည်း ဖြစ်ပြီး ways(2) = ways(1) + ways(0) က ၎င်းကို လိုသည်။ <code>return n if n &lt;= 1</code> base case သည် ဥပမာ 1 တွင် 1 နှင့် ဥပမာ 2 တွင် 2 ကို ပြန်ပေးသည် — အဖြေတိုင်း တစ်ဆင့် လိုနေသည်။" },
      { en: "<strong>45 is not small for the plain recursion.</strong> It makes 3,672,623,805 calls at n = 45. Measured here on an Apple M5 Pro, that took Python 72 s and Ruby 63 s — right answer, far too slow to submit.", my: "<strong>plain recursion အတွက် 45 သည် မငယ်ပါ။</strong> n = 45 တွင် call 3,672,623,805 ခု ဖြစ်စေသည်။ ဤနေရာ Apple M5 Pro ပေါ်တွင် တိုင်းရာ Python က 72 စက္ကန့်၊ Ruby က 63 စက္ကန့် ကြာသည် — အဖြေမှန်သော်လည်း submit လုပ်ရန် အလွန် နှေးသည်။" },
    ],
  },
  part2Sub: { en: "Three approaches to the same recurrence. The strip is the staircase; the stage shows the calls waiting and how often each step has been worked out, or the two variables the loop keeps.", my: "recurrence တစ်ခုတည်းအတွက် နည်းလမ်း သုံးမျိုး။ strip သည် လှေကား ဖြစ်သည် — stage က စောင့်နေသော call များနှင့် step တစ်ခုစီကို တွက်ခဲ့သည့် အကြိမ်၊ သို့မဟုတ် loop သိမ်းထားသော variable နှစ်ခုကို ပြသည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the recurrence raises", my: "recurrence နှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why is the plain recursion so slow when each call is two additions?", my: "call တစ်ခုစီသည် ပေါင်းခြင်း နှစ်ခုသာ ဖြစ်လျက် plain recursion က ဘာကြောင့် ဤမျှ နှေးသလဲ။" }, a: { en: "Because the same steps are worked out again in every branch. ways(n) calls ways(n−1) and ways(n−2), and ways(n−1) calls ways(n−2) again — so the call count grows like the answer itself: exactly 2 × ways(n) − 1 calls, which is 177 at n = 10 and 3,672,623,805 at n = 45. Load n = 8 in the plain recursion and watch the bars for steps 0 and 1 grow.", my: "step တူများကို branch တိုင်းတွင် ပြန်တွက်သောကြောင့် ဖြစ်သည်။ ways(n) သည် ways(n−1) နှင့် ways(n−2) ကို ခေါ်ပြီး ways(n−1) က ways(n−2) ကို ထပ်ခေါ်သည် — ထို့ကြောင့် call အရေအတွက်သည် အဖြေကိုယ်တိုင်ကဲ့သို့ ကြီးလာသည် — call 2 × ways(n) − 1 ခု အတိအကျ၊ n = 10 တွင် 177၊ n = 45 တွင် 3,672,623,805။ plain recursion တွင် n = 8 ကို load လုပ်ပြီး step 0 နှင့် 1 ၏ bar များ ကြီးလာပုံကို ကြည့်ပါ။" } },
      { q: { en: "What does the memo actually save?", my: "memo က အမှန်တကယ် ဘာကို ချွေတာသလဲ။" }, a: { en: "Every call after the first for a given step returns at once, so its whole subtree of calls never happens. Each step from 2 to n is worked out once and asked for at most twice: 2n − 1 calls, 89 at n = 45. The price is a table of n entries and a call stack n deep — which the two-variable loop then removes, because each step only ever needs the two below it.", my: "step တစ်ခုအတွက် ပထမ call နောက်ပိုင်း call တိုင်းသည် ချက်ချင်း ပြန်သဖြင့် ၎င်း၏ call subtree တစ်ခုလုံး မဖြစ်တော့ပါ။ step 2 မှ n အထိ တစ်ခုစီကို တစ်ကြိမ် တွက်ပြီး အများဆုံး နှစ်ကြိမ် မေးသည် — call 2n − 1 ခု၊ n = 45 တွင် 89။ ပေးရသည့်တန်ဖိုးမှာ entry n ခုပါ table နှင့် n အနက်ရှိ call stack ဖြစ်သည် — step တစ်ခုစီသည် ၎င်းအောက်ရှိ နှစ်ခုကိုသာ လိုသဖြင့် two-variable loop က ၎င်းတို့ကို ဖယ်ရှားသည်။" } },
      { q: { en: "Why does n stop at 45?", my: "n သည် 45 တွင် ဘာကြောင့် ရပ်သလဲ။" }, a: { en: "Because the answers are Fibonacci numbers — ways(n) is the (n+1)th — and they outgrow a 32-bit integer right after it. ways(45) = 1,836,311,903 fits under 2,147,483,647; ways(46) = 2,971,215,073 would not. That is why the Rust listings can use <code>i32</code>, and why none of them need a bigger type.", my: "အဖြေများသည် Fibonacci ကိန်းများ ဖြစ်ပြီး — ways(n) သည် (n+1) ခုမြောက် — ၎င်းနောက် ချက်ချင်း 32-bit integer ထက် ကြီးသွားသောကြောင့် ဖြစ်သည်။ ways(45) = 1,836,311,903 သည် 2,147,483,647 အောက်တွင် ဆံ့သည် — ways(46) = 2,971,215,073 မဆံ့ပါ။ ထို့ကြောင့် Rust listing များက <code>i32</code> ကို သုံးနိုင်ပြီး မည်သည့် listing မျှ type ပိုကြီးရန် မလိုပါ။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "One recurrence, three bills", my: "recurrence တစ်ခု၊ ကုန်ကျမှု သုံးမျိုး" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>Work at n = 45</th><th>Memory at n = 45</th></tr></thead>\n  <tbody>\n    <tr><td><b>Plain recursion</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">every step, again and again</span></td>\n        <td class=\"mono\">O(φⁿ)</td><td class=\"mono\">O(n)</td><td class=\"cross\">3,672,623,805 calls</td><td>45 frames</td></tr>\n    <tr><td><b>Recursion + memo</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">each step once</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(n)</td><td class=\"tick\">89 calls</td><td>45 frames + 44 entries</td></tr>\n    <tr><td><b>Two variables</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">the last two only</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(1)</td><td class=\"tick\">44 additions</td><td class=\"tick\">2 integers</td></tr>\n  </tbody>\n</table>\n<figcaption>Counts are computed, not timed; φ ≈ 1.618. The plain recursion was also timed at n = 45 on an Apple M5 Pro, each run giving the right answer: Rust 1.6 s, Go 2.7 s, JavaScript 5.5 s, Ruby 63 s, Python 72 s.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>n = 45 တွင် အလုပ်</th><th>n = 45 တွင် memory</th></tr></thead>\n  <tbody>\n    <tr><td><b>Plain recursion</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">step တိုင်းကို ထပ်ခါထပ်ခါ</span></td>\n        <td class=\"mono\">O(φⁿ)</td><td class=\"mono\">O(n)</td><td class=\"cross\">call 3,672,623,805</td><td>frame 45</td></tr>\n    <tr><td><b>Recursion + memo</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">step တစ်ခုစီ တစ်ကြိမ်</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(n)</td><td class=\"tick\">call 89</td><td>frame 45 + entry 44</td></tr>\n    <tr><td><b>Two variables</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">နောက်ဆုံး နှစ်ခုသာ</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(1)</td><td class=\"tick\">ပေါင်းခြင်း 44</td><td class=\"tick\">integer 2</td></tr>\n  </tbody>\n</table>\n<figcaption>အရေအတွက်များကို တွက်ချက်ထားခြင်းဖြစ်ပြီး အချိန် မတိုင်းထားပါ — φ ≈ 1.618။ plain recursion ကို Apple M5 Pro ပေါ်တွင် n = 45 ဖြင့်လည်း အချိန်တိုင်းခဲ့ပြီး အကြိမ်တိုင်း အဖြေမှန်သည် — Rust 1.6 s၊ Go 2.7 s၊ JavaScript 5.5 s၊ Ruby 63 s၊ Python 72 s။</figcaption>" },
  },
  part3Sub: { en: "Three approaches in five languages. Every block is a complete submission. The input is one number from 1 to 45, so the memo and loop versions ran on all of them; the badges on the plain recursion say how long n = 45 took.", my: "နည်းလမ်း သုံးမျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်သည်။ input သည် 1 မှ 45 အထိ ကိန်းတစ်ခု ဖြစ်သဖြင့် memo နှင့် loop ပုံစံများကို အားလုံးပေါ်တွင် run ထားသည် — plain recursion ၏ badge များက n = 45 ကြာချိန်ကို ဖော်ပြသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>n</code> above — 1 to 10, so the plain recursion stays steppable — and all three walkthroughs rebuild.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>n</code> ကို ပြင်လိုက်လျှင် (1 မှ 10 အထိ၊ plain recursion ကို အဆင့်လိုက် ကြည့်နိုင်စေရန်) walkthrough သုံးခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
