/* The prose of the N-Queens page: everything the reader sees that is not
 * interactive. Rendered by src/pages/leetcode/[slug].astro through the
 * Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'N-Queens',
  summary: 'One queen per row, tried column by column, lifted when the rows below dead-end. Every square on a diagonal shares r − c or r + c, so three arrays of flags check a square in O(1) instead of scanning every queen above it.',
  eyebrow: 'LeetCode 51 &nbsp;·&nbsp; Hard',
  lede: { en: "Place n queens so that none can take another, and list every way to do it. Queens attack along rows, columns and both diagonals, so there is exactly one queen per row: the search goes row by row, tries each column, and backs up when a row has nowhere safe. What makes the check cheap is a little geometry — a diagonal is a line where r − c, or r + c, never changes.", my: "queen n ခုကို တစ်ခုက တစ်ခုကို မစားနိုင်အောင် ထားပြီး ထားနိုင်သော နည်းအားလုံးကို စာရင်းပြုပါ။ queen များသည် row၊ column နှင့် diagonal နှစ်ဖက်လုံးတစ်လျှောက် တိုက်သဖြင့် row တစ်ခုလျှင် queen တစ်ခုတိတိ ရှိသည် — ရှာဖွေမှုသည် row အလိုက် သွားပြီး column တစ်ခုစီကို စမ်းကာ row တစ်ခုတွင် လုံခြုံသော နေရာ မရှိလျှင် နောက်ပြန်ဆုတ်သည်။ စစ်ခြင်းကို သက်သာစေသည်မှာ geometry အနည်းငယ် — diagonal ဆိုသည်မှာ r − c သို့မဟုတ် r + c မပြောင်းသော မျဉ်း ဖြစ်သည်။" },
  links: [{ id: 51, title: 'N-Queens', slug: 'n-queens', difficulty: 'Hard' }],
  constraints: { en: "<span>1 &le; n &le; 9</span>", my: "<span>1 &le; n &le; 9</span>" },
  part1Sub: { en: "Read the statement, then place queens and read the diagonal numbers in each square's corner.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် queen များ ထားပြီး နေရာတစ်ခုစီ၏ ထောင့်ရှိ diagonal ဂဏန်းများကို ဖတ်ပါ။" },
  widgetTitle: { en: "Place queens, read the diagonals", my: "queen ထားပါ — diagonal များကို ဖတ်ပါ" },
  traps: {
    summary: { en: "Three ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ သုံးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>A queen has two diagonals.</strong> Checking only the ↘ one (same r − c) lets queens sit on a shared ↙ diagonal: n = 4 gives 7 boards instead of 2.", my: "<strong>queen တစ်ခုတွင် diagonal နှစ်ခု ရှိသည်။</strong> ↘ တစ်ခု (r − c တူ) ကိုသာ စစ်လျှင် queen များ ↙ diagonal တူပေါ်တွင် ထိုင်နိုင်သည် — n = 4 တွင် board 2 ခုအစား 7 ခု ရသည်။" },
      { en: "<strong>Lifting a queen must clear its marks.</strong> The flag version that sets col, diag and anti but never clears them leaves every later row blocked: it finds 0 boards for n = 4 and 0 for n = 8, where there are 2 and 92.", my: "<strong>queen ကို ဖယ်လျှင် ၎င်း၏ အမှတ်များကို ရှင်းရမည်။</strong> col၊ diag နှင့် anti ကို သတ်မှတ်ပြီး ဘယ်တော့မှ မရှင်းသော flag version သည် နောက် row တိုင်းကို ပိတ်ထားသည် — 2 နှင့် 92 ရှိသော n = 4 နှင့် n = 8 အတွက် board 0 ခုစီ ရှာတွေ့သည်။" },
      { en: "<strong>Some n have no answer.</strong> n = 2 and n = 3 return <code>[]</code> — every placement of the second queen is attacked. Code that assumes a board exists, or returns <code>[[]]</code>, gets these wrong.", my: "<strong>n အချို့တွင် အဖြေ မရှိ။</strong> n = 2 နှင့် n = 3 သည် <code>[]</code> ပြန်ပေးသည် — ဒုတိယ queen ၏ ထားနိုင်သော နေရာတိုင်း တိုက်ခံရသည်။ board ရှိမည်ဟု ယူဆသော သို့မဟုတ် <code>[[]]</code> ပြန်ပေးသော code သည် ၎င်းတို့ကို မှားသည်။" },
    ],
  },
  part2Sub: { en: "The same search, two ways to check a square. The strip is cols, the one array both keep; the stage is the board it stands for, with the squares the queens attack faded and the queen that rules a square out lit red.", my: "ရှာဖွေမှု အတူတူ၊ နေရာတစ်ခုကို စစ်ရန် နည်းနှစ်မျိုး။ strip သည် နှစ်ခုလုံး ထိန်းသော array တစ်ခု cols ဖြစ်သည်။ stage သည် ၎င်းကိုယ်စားပြုသော board ဖြစ်ပြီး queen များ တိုက်သော နေရာများ မှိန်ပြီး နေရာတစ်ခုကို ပယ်သော queen ကို အနီရောင် လင်းပြထားသည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the board raises", my: "board နှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why is r − c constant along a diagonal?", my: "diagonal တစ်လျှောက် r − c ဘာကြောင့် မပြောင်းသလဲ။" }, a: { en: "One step down-right adds 1 to both r and c, so their difference stays put; one step down-left adds 1 to r and takes 1 from c, so their sum stays put. Each ↘ diagonal is one value of r − c (from −(n − 1) to n − 1, hence the + n − 1 to index from 0), and each ↙ diagonal one value of r + c (0 to 2n − 2).", my: "ညာအောက်သို့ တစ်လှမ်းသည် r နှင့် c နှစ်ခုလုံးကို 1 ပေါင်းသဖြင့် ၎င်းတို့၏ ခြားနားချက် မပြောင်း — ဘယ်အောက်သို့ တစ်လှမ်းသည် r ကို 1 ပေါင်းပြီး c ကို 1 နုတ်သဖြင့် ၎င်းတို့၏ ပေါင်းလဒ် မပြောင်း။ ↘ diagonal တစ်ခုစီသည် r − c ၏ value တစ်ခု (−(n − 1) မှ n − 1 — ထို့ကြောင့် 0 မှ index ရန် + n − 1) ဖြစ်ပြီး ↙ diagonal တစ်ခုစီသည် r + c ၏ value တစ်ခု (0 မှ 2n − 2)။" } },
      { q: { en: "How big is the search?", my: "ရှာဖွေမှု မည်မျှ ကြီးသလဲ။" }, a: { en: "One queen per row and per column already limits it to at most n! boards, and the diagonal check prunes most of those early. At n = 9 the search tries 72,378 squares to find 352 solutions (counted here) — far fewer than the 9! = 362,880 permutations the verifier's oracle filters, and nothing like the 81-choose-9 ways to put 9 queens anywhere.", my: "row တစ်ခုလျှင် နှင့် column တစ်ခုလျှင် queen တစ်ခုက board အများဆုံး n! ခုသို့ ကန့်သတ်ပြီးသား ဖြစ်ပြီး diagonal စစ်ခြင်းက ၎င်းတို့အများစုကို စောစောကတည်းက ဖြတ်သည်။ n = 9 တွင် ရှာဖွေမှုသည် အဖြေ 352 ကို ရှာရန် နေရာ 72,378 ခု စမ်းသည် (ဤနေရာတွင် ရေတွက်ထားသည်) — verifier ၏ oracle စစ်သော permutation 9! = 362,880 ထက် အများကြီး နည်းပြီး queen 9 ခုကို မည်သည့်နေရာတွင်မဆို ထားနိုင်သော 81-choose-9 နည်းနှင့် လုံးဝ မတူ။" } },
      { q: { en: "Why store cols instead of the board?", my: "board အစား cols ကို ဘာကြောင့် သိမ်းသလဲ။" }, a: { en: "One queen per row means a solution is fully described by the column of each row's queen — n numbers instead of n² characters. The strings are built only when a solution is complete, and building them per solution is the cost the answer itself imposes.", my: "row တစ်ခုလျှင် queen တစ်ခု ဆိုသည်မှာ အဖြေတစ်ခုကို row တစ်ခုစီ၏ queen ရှိ column ဖြင့် အပြည့်အစုံ ဖော်ပြနိုင်သည် — စာလုံး n² အစား ဂဏန်း n ခု။ string များကို အဖြေ ပြည့်စုံမှသာ တည်ဆောက်ပြီး အဖြေတစ်ခုစီအတွက် တည်ဆောက်ခြင်းသည် အဖြေကိုယ်တိုင် တောင်းသော ကုန်ကျမှု ဖြစ်သည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "The same search, a cheaper check", my: "ရှာဖွေမှု အတူတူ — စစ်ခြင်း သက်သာ" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Search</th><th>Per square</th><th>At n = 9</th></tr></thead>\n  <tbody>\n    <tr><td><b>Scan the queens above</b></td>\n        <td class=\"mono\">≤ n!</td><td class=\"mono\">O(n)</td><td>72,378 tries · 243,009 comparisons</td></tr>\n    <tr><td><b>Column and diagonal flags</b></td>\n        <td class=\"mono\">≤ n!</td><td class=\"mono\">O(1)</td><td class=\"tick\">72,378 tries · 72,378 checks</td></tr>\n  </tbody>\n</table>\n<figcaption>Counts are computed, not timed: both finish n = 9 in a blink. The flags make each check constant-time; they do not shrink the search, which is the same tree of 72,378 tries either way.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>ရှာဖွေမှု</th><th>နေရာတစ်ခုလျှင်</th><th>n = 9 တွင်</th></tr></thead>\n  <tbody>\n    <tr><td><b>Scan the queens above</b></td>\n        <td class=\"mono\">≤ n!</td><td class=\"mono\">O(n)</td><td>စမ်း 72,378 · နှိုင်းယှဉ် 243,009</td></tr>\n    <tr><td><b>Column and diagonal flags</b></td>\n        <td class=\"mono\">≤ n!</td><td class=\"mono\">O(1)</td><td class=\"tick\">စမ်း 72,378 · စစ် 72,378</td></tr>\n  </tbody>\n</table>\n<figcaption>အရေအတွက်များကို တွက်ထားခြင်းဖြစ်ပြီး အချိန် မတိုင်းထားပါ — နှစ်ခုလုံး n = 9 ကို မျက်စိတစ်မှိတ်အတွင်း ပြီးသည်။ flag များက စစ်ခြင်းတစ်ခုစီကို constant-time ဖြစ်စေသည် — ရှာဖွေမှုကို မကျုံ့စေပါ၊ မည်သို့ပင်ဖြစ်စေ စမ်းခြင်း 72,378 ၏ tree အတူတူ ဖြစ်သည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission, and every one was run on every n the constraint allows, 1 to 9 — 724 boards in all.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး အားလုံးကို ကန့်သတ်ချက် ခွင့်ပြုသော n တိုင်း၊ 1 မှ 9 — board စုစုပေါင်း 724 — ဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>n</code> above — 1 to 5 — and both walkthroughs rebuild against it.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>n</code> ကို ပြင်လိုက်လျှင် (1 မှ 5) walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
