/* The prose of the Basic Calculator page: everything the reader sees that is
 * not interactive. Rendered by src/pages/leetcode/[slug].astro through the
 * Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Basic Calculator',
  summary: 'With only + and −, an expression is a sum of signed numbers, and a bracket\'s value can stand in for a number. Keep a running total and the next sign; let the call stack hold what waits outside each bracket, or keep it on a stack of your own.',
  eyebrow: 'LeetCode 224 &nbsp;·&nbsp; Hard',
  lede: { en: "Evaluate an expression of numbers, +, −, brackets and spaces, without eval. There is no precedence to worry about: every term is simply added or taken away. The only thing brackets change is sign — a minus in front of one flips everything inside — so read left to right with a running total and the sign of the next term, and when a bracket opens, park the outer total and sign until it closes.", my: "ကိန်းများ၊ +၊ −၊ ကွင်းများနှင့် space များပါသော expression ကို eval မသုံးဘဲ တွက်ပါ။ precedence စိုးရိမ်စရာ မရှိ — term တိုင်းကို ပေါင်းခြင်း သို့မဟုတ် နုတ်ခြင်းသာ။ ကွင်းများ ပြောင်းလဲသည့်အရာမှာ sign တစ်ခုတည်း — ကွင်းရှေ့ရှိ minus က အတွင်းရှိ အရာအားလုံးကို ပြောင်းသည် — ထို့ကြောင့် running total နှင့် နောက် term ၏ sign ဖြင့် ဘယ်မှ ညာ ဖတ်ပြီး ကွင်းဖွင့်သည့်အခါ အပြင် total နှင့် sign ကို ကွင်းပိတ်သည်အထိ ထားထားပါ။" },
  links: [{ id: 224, title: 'Basic Calculator', slug: 'basic-calculator', difficulty: 'Hard' }],
  constraints: { en: "<span>1 &le; s.length &le; 3 &times; 10<sup>5</sup></span><span>s is digits, '+', '-', '(', ')' and ' '</span><span>s is a valid expression</span><span>'+' is never unary</span><span>'-' may be unary</span><span>no two consecutive operators</span><span>every number and running calculation fits in a signed 32-bit integer</span>", my: "<span>1 &le; s.length &le; 3 &times; 10<sup>5</sup></span><span>s တွင် digit၊ '+'၊ '-'၊ '('၊ ')' နှင့် ' ' သာ</span><span>s သည် တရားဝင် expression</span><span>'+' သည် ဘယ်တော့မှ unary မဟုတ်</span><span>'-' သည် unary ဖြစ်နိုင်</span><span>operator နှစ်ခု ဆက်တိုက် မရှိ</span><span>ကိန်းတိုင်းနှင့် running calculation တိုင်း signed 32-bit integer ထဲ ဝင်သည်</span>" },
  part1Sub: { en: "Read the statement, then flip the operators and watch which numbers change sign.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် operator များကို ပြောင်းပြီး မည်သည့် ကိန်းများ sign ပြောင်းသည်ကို ကြည့်ပါ။" },
  widgetTitle: { en: "Every number, with the sign it carries", my: "ကိန်းတိုင်း — ၎င်းသယ်ဆောင်သော sign နှင့်" },
  traps: {
    summary: { en: "Four ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ လေးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>A minus in front of a bracket applies to all of it.</strong> Saving only the outer total at \"(\" — not the sign — adds the bracket instead of subtracting it: <code>1-(2+3)</code> gives 6, not −4. The examples never put a minus before a bracket, so they pass.", my: "<strong>ကွင်းရှေ့ရှိ minus သည် ၎င်းတစ်ခုလုံးအပေါ် သက်ရောက်သည်။</strong> \"(\" တွင် sign မပါဘဲ အပြင် total ကိုသာ သိမ်းလျှင် ကွင်းကို နုတ်မည့်အစား ပေါင်းမိသည် — <code>1-(2+3)</code> သည် −4 မဟုတ်ဘဲ 6 ရသည်။ ဥပမာများတွင် ကွင်းရှေ့ minus မရှိသဖြင့် အောင်သည်။" },
      { en: "<strong>Numbers have more than one digit.</strong> Taking each digit as a number of its own turns <code>12+3</code> into 5. Build it up: <code>num = num × 10 + digit</code>. The examples, all single digits, still pass.", my: "<strong>ကိန်းများတွင် digit တစ်ခုထက် ပိုရှိနိုင်သည်။</strong> digit တစ်ခုစီကို ကိန်းတစ်ခုအဖြစ် ယူလျှင် <code>12+3</code> သည် 5 ဖြစ်သွားသည်။ တည်ဆောက်ပါ — <code>num = num × 10 + digit</code>။ digit တစ်ခုစီသာပါသော ဥပမာများ အောင်နေဆဲ။" },
      { en: "<strong>The last number has no operator after it.</strong> A term is added when the next operator arrives, so the final one is still in <code>num</code> at the end. Returning <code>total</code> alone gives 1 for example 1.", my: "<strong>နောက်ဆုံး ကိန်းနောက်တွင် operator မရှိ။</strong> term တစ်ခုကို နောက် operator ရောက်မှ ပေါင်းသဖြင့် နောက်ဆုံး term သည် အဆုံးတွင် <code>num</code> ထဲ ရှိနေဆဲ။ <code>total</code> တစ်ခုတည်းကို ပြန်ပေးလျှင် ဥပမာ 1 အတွက် 1 ရသည်။" },
      { en: "<strong>Brackets can nest 149,999 deep.</strong> A recursive parser makes one call per level. Measured here on default stacks, cold: Ruby 3.1 overflows past 8,185, Node 24 past 6,912, a Rust release build on its 8 MB main thread past 104,797, and Python stops at 1,000 unless the limit is raised.", my: "<strong>ကွင်းများသည် 149,999 ဆင့် nest ဖြစ်နိုင်သည်။</strong> recursive parser သည် အဆင့်တစ်ခုလျှင် call တစ်ခု ခေါ်သည်။ default stack ပေါ်တွင် cold run ဖြင့် ဤနေရာတွင် တိုင်းတာထားသည် — Ruby 3.1 သည် 8,185၊ Node 24 သည် 6,912၊ 8 MB main thread ပေါ်ရှိ Rust release build သည် 104,797 ကျော်လျှင် overflow ဖြစ်ပြီး limit မမြှင့်လျှင် Python သည် 1,000 တွင် ရပ်သည်။" },
    ],
  },
  part2Sub: { en: "Two places for the waiting to happen. The strip is the string, read left to right; the stage is either the explicit stack of (total, sign) pairs or the call stack of expr() frames, each with its own three numbers.", my: "စောင့်ခြင်း ဖြစ်မည့် နေရာ နှစ်မျိုး။ strip သည် ဘယ်မှ ညာ ဖတ်သော string ဖြစ်သည်။ stage သည် (total, sign) အတွဲများ၏ stack သို့မဟုတ် ကိုယ်ပိုင် ကိန်း သုံးခုစီပါသော expr() frame များ၏ call stack။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the one pass raises", my: "pass တစ်ခုတည်းနှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why does a unary minus need no special case?", my: "unary minus အတွက် ဘာကြောင့် သီးသန့် case မလိုသလဲ။" }, a: { en: "Because every bracket, and the whole string, starts with <code>total = 0</code>. A leading \"−\" adds the empty term before it — 0 — and sets the sign to −1, so the first number is taken away from 0. <code>-(2+3)</code> is read as <code>0 − (2+3)</code>. The statement rules out a unary \"+\", which the same code would handle anyway.", my: "ကွင်းတိုင်းနှင့် string တစ်ခုလုံးသည် <code>total = 0</code> ဖြင့် စသောကြောင့် ဖြစ်သည်။ ရှေ့ဆုံး \"−\" သည် ၎င်းရှေ့ရှိ ဗလာ term — 0 — ကို ပေါင်းပြီး sign ကို −1 သတ်မှတ်သဖြင့် ပထမ ကိန်းကို 0 မှ နုတ်သည်။ <code>-(2+3)</code> ကို <code>0 − (2+3)</code> အဖြစ် ဖတ်သည်။ မေးခွန်းက unary \"+\" ကို တားထားသော်လည်း code တူတူက ကိုင်တွယ်နိုင်သည်။" } },
      { q: { en: "Why hand a bracket back as <code>num</code>, not add it straight in?", my: "ကွင်းကို တိုက်ရိုက် မပေါင်းဘဲ <code>num</code> အဖြစ် ဘာကြောင့် ပြန်ပေးသလဲ။" }, a: { en: "So that a bracket is just another term. After \")\" the code is in exactly the state it would be in after reading a number: the next operator, or the end, adds <code>sign × num</code> to <code>total</code>. Adding the bracket in at \")\" also works, but then \")\" has to do the operator's job too, and it is easy to add a term twice.", my: "ကွင်းသည် နောက်ထပ် term တစ်ခုသာ ဖြစ်စေရန်။ \")\" ပြီးနောက် code သည် ကိန်းတစ်ခု ဖတ်ပြီးချိန်၏ အခြေအနေ အတိအကျတွင် ရှိသည် — နောက် operator သို့မဟုတ် အဆုံးက <code>sign × num</code> ကို <code>total</code> ထဲ ပေါင်းသည်။ \")\" တွင် ကွင်းကို ပေါင်းခြင်းလည်း အလုပ်ဖြစ်သော်လည်း ထိုအခါ \")\" က operator ၏ အလုပ်ကိုပါ လုပ်ရပြီး term တစ်ခုကို နှစ်ကြိမ် ပေါင်းမိလွယ်သည်။" } },
      { q: { en: "Could the running total overflow 32 bits?", my: "running total သည် 32 bit ကို ကျော်နိုင်သလား။" }, a: { en: "The statement promises it will not: every number and running calculation fits in a signed 32-bit integer, so <code>i32</code> is enough in Rust and the listings never widen. The corpus keeps to that promise — its generator throws away any expression whose partial sums leave 32 bits — and includes <code>2147483647</code> itself and sums built from numbers that large.", my: "မေးခွန်းက မကျော်ဟု ကတိပြုထားသည် — ကိန်းတိုင်းနှင့် running calculation တိုင်း signed 32-bit integer ထဲ ဝင်သဖြင့် Rust တွင် <code>i32</code> လုံလောက်ပြီး listing များ ဘယ်တော့မှ မချဲ့ပါ။ corpus သည် ထိုကတိကို လိုက်နာသည် — ၎င်း၏ generator က partial sum များ 32 bit ကျော်သော expression ကို ပစ်သည် — <code>2147483647</code> ကိုယ်တိုင်နှင့် ထိုမျှ ကြီးသော ကိန်းများဖြင့် ပေါင်းလဒ်များ ပါသည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "The same work, waiting in a different place", my: "အလုပ် အတူတူ — မတူသော နေရာတွင် စောင့်ခြင်း" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Waiting totals kept on</th><th>149,999 nested brackets</th></tr></thead>\n  <tbody>\n    <tr><td><b>Recursive parser</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">one call per open bracket</span></td>\n        <td class=\"mono\">O(n)</td><td>the call stack</td><td class=\"cross\">overflows Ruby, Node and Rust defaults</td></tr>\n    <tr><td><b>One pass with a stack</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">one (total, sign) pair per open bracket</span></td>\n        <td class=\"mono\">O(n)</td><td>a list on the heap</td><td class=\"tick\">fine everywhere</td></tr>\n  </tbody>\n</table>\n<figcaption>Both read each character once and keep one entry per open bracket; only where that entry lives differs. Default-stack limits measured here, cold: Ruby 3.1 8,185, Node 24 6,912, Rust 104,797 (release build, 8 MB main thread); Go's stack grows as needed and Python's limit is raised in the listing.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>စောင့်နေသော total များ ထားရာ</th><th>nested ကွင်း 149,999</th></tr></thead>\n  <tbody>\n    <tr><td><b>Recursive parser</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">ဖွင့်ထားသော ကွင်းတစ်ခုလျှင် call တစ်ခု</span></td>\n        <td class=\"mono\">O(n)</td><td>call stack</td><td class=\"cross\">Ruby၊ Node နှင့် Rust default ကို overflow</td></tr>\n    <tr><td><b>One pass with a stack</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">ဖွင့်ထားသော ကွင်းတစ်ခုလျှင် (total, sign) အတွဲ တစ်ခု</span></td>\n        <td class=\"mono\">O(n)</td><td>heap ပေါ်ရှိ list</td><td class=\"tick\">နေရာတိုင်း အဆင်ပြေ</td></tr>\n  </tbody>\n</table>\n<figcaption>နှစ်ခုလုံး စာလုံးတစ်ခုစီကို တစ်ကြိမ် ဖတ်ပြီး ဖွင့်ထားသော ကွင်းတစ်ခုလျှင် entry တစ်ခု ထားသည် — ထို entry ရှိရာ နေရာသာ ကွာသည်။ default stack ကန့်သတ်ချက်များ ဤနေရာတွင် cold run ဖြင့် တိုင်းထားသည် — Ruby 3.1 8,185၊ Node 24 6,912၊ Rust 104,797 (release build၊ 8 MB main thread) — Go ၏ stack သည် လိုသလို ကြီးထွားပြီး Python ၏ limit ကို listing တွင် မြှင့်ထားသည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission, and every one was run against the same 20,019 expressions, up to 3 × 10⁵ characters; the badges and notes say where the recursion needs more stack.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး အားလုံးကို စာလုံး 3 × 10⁵ အထိ expression 20,019 ခု တူတူဖြင့် run ထားသည် — recursion တွင် stack ပိုလိုသည့်နေရာကို badge နှင့် မှတ်ချက်များက ဖော်ပြသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>s</code> above — up to 24 characters, following the statement's rules — and both walkthroughs rebuild against it.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>s</code> ကို ပြင်လိုက်လျှင် (မေးခွန်း၏ စည်းမျဉ်းအတိုင်း စာလုံး 24 လုံးအထိ) walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
