/* The prose of the Word Search II page: everything the reader sees that is
 * not interactive. Rendered by src/pages/leetcode/[slug].astro through the
 * Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Word Search II',
  summary: 'Searching the board once per word repeats every shared beginning. Put the words in a trie and walk the board once, following the trie: a missing child ends a path for every word at once, and found branches are pruned away.',
  eyebrow: 'LeetCode 212 &nbsp;·&nbsp; Hard',
  lede: { en: "Find which of up to 3 × 10⁴ words can be traced on a letter grid, moving across or down and never reusing a cell. One backtracking search per word works, but words that begin alike make it repeat the same walks thousands of times. A trie turns the whole list into one guide: walk the board once from each cell and step down the trie with each letter, stopping as soon as no word continues.", my: "word 3 × 10⁴ အထိထဲမှ မည်သည်တို့ကို စာလုံး grid ပေါ်တွင် ဘေးတိုက် သို့မဟုတ် အောက်သို့ ရွေ့ကာ cell ကို ပြန်မသုံးဘဲ ဆွဲနိုင်သလဲ ရှာပါ။ word တစ်ခုလျှင် backtracking ရှာဖွေမှု တစ်ကြိမ် အလုပ်ဖြစ်သော်လည်း တူညီစွာ စသော word များက လျှောက်ခြင်း အတူတူကို ထောင်ချီ ထပ်လုပ်စေသည်။ trie က စာရင်းတစ်ခုလုံးကို လမ်းညွှန် တစ်ခုအဖြစ် ပြောင်းသည် — cell တစ်ခုစီမှ board ကို တစ်ကြိမ် လျှောက်ပြီး စာလုံးတိုင်းဖြင့် trie အောက်သို့ ဆင်းကာ မည်သည့် word မျှ မဆက်တော့သည်နှင့် ရပ်သည်။" },
  links: [{ id: 212, title: 'Word Search II', slug: 'word-search-ii', difficulty: 'Hard' }],
  constraints: { en: "<span><b>m</b> == board.length</span><span><b>n</b> == board[i].length</span><span>1 &le; m, n &le; 12</span><span>1 &le; words.length &le; 3 &times; 10<sup>4</sup></span><span>1 &le; words[i].length &le; 10</span><span>lowercase English letters</span><span>all words unique</span>", my: "<span><b>m</b> == board.length</span><span><b>n</b> == board[i].length</span><span>1 &le; m, n &le; 12</span><span>1 &le; words.length &le; 3 &times; 10<sup>4</sup></span><span>1 &le; words[i].length &le; 10</span><span>အင်္ဂလိပ် စာလုံးအသေး</span><span>word အားလုံး မတူ</span>" },
  part1Sub: { en: "Read the statement, then spell a path on the board and see which words it could still become.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် board ပေါ်တွင် လမ်းကြောင်း စာလုံးပေါင်းပြီး မည်သည့် word များ ဖြစ်လာနိုင်သေးသလဲ ကြည့်ပါ။" },
  widgetTitle: { en: "Spell a path, see which words survive", my: "လမ်းကြောင်း စာလုံးပေါင်းပါ — မည်သည့် word များ ကျန်သလဲ ကြည့်ပါ" },
  traps: {
    summary: { en: "Four ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ လေးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>No cell twice in one word.</strong> A search that never marks the cells it has used walks back onto them: on the one-row board <code>ab</code> it finds <code>\"aba\"</code>, which needs three cells.", my: "<strong>word တစ်ခုတွင် cell ကို နှစ်ကြိမ် မသုံးရ။</strong> သုံးပြီး cell များကို ဘယ်တော့မှ မမှတ်သော ရှာဖွေမှုသည် ၎င်းတို့ပေါ် ပြန်လျှောက်သည် — row တစ်ခုတည်း board <code>ab</code> ပေါ်တွင် cell သုံးခု လိုသော <code>\"aba\"</code> ကို တွေ့သည်။" },
      { en: "<strong>Put each cell back.</strong> Leaving the <code>'#'</code> mark in place after the search returns blocks the cell for every later path: example 1 then finds only <code>[\"oath\"]</code> and loses <code>\"eat\"</code>.", my: "<strong>cell တစ်ခုစီကို ပြန်ထားပါ။</strong> ရှာဖွေမှု ပြန်လာပြီးနောက် <code>'#'</code> အမှတ်ကို ချန်ထားလျှင် နောက်ပိုင်း လမ်းကြောင်းတိုင်းအတွက် cell ကို ပိတ်သည် — ထိုအခါ ဥပမာ 1 သည် <code>[\"oath\"]</code> ကိုသာ တွေ့ပြီး <code>\"eat\"</code> ကို ဆုံးရှုံးသည်။" },
      { en: "<strong>A word can be found along two paths.</strong> Without clearing a word once it is added, the answer repeats it: on the board <code>aa</code> the word <code>\"a\"</code> comes back twice, <code>[\"a\",\"a\"]</code>.", my: "<strong>word တစ်ခုကို လမ်းကြောင်း နှစ်ခုတစ်လျှောက် တွေ့နိုင်သည်။</strong> ထည့်ပြီးသည်နှင့် word ကို မရှင်းလျှင် အဖြေတွင် ထပ်နေသည် — board <code>aa</code> ပေါ်တွင် word <code>\"a\"</code> သည် နှစ်ကြိမ် ပြန်လာသည်၊ <code>[\"a\",\"a\"]</code>။" },
      { en: "<strong>Don't stop at the first word.</strong> Returning as soon as a node holds a word misses longer words through it: with words <code>a</code> and <code>ab</code> on the board <code>ab</code>, only <code>[\"a\"]</code> comes back.", my: "<strong>ပထမ word တွင် မရပ်ပါနှင့်။</strong> node တွင် word ရှိသည်နှင့် return ပြန်လျှင် ၎င်းကို ဖြတ်သော ပိုရှည်သည့် word များကို လွတ်သည် — board <code>ab</code> ပေါ်တွင် word <code>a</code> နှင့် <code>ab</code> ဖြင့် <code>[\"a\"]</code> သာ ပြန်လာသည်။" },
    ],
  },
  part2Sub: { en: "Two approaches. The strip is the board as the code holds it — '#' where the current path has used a cell; the stage is what guides the walk: one word, or the trie of all of them, shrinking as found branches are pruned.", my: "နည်းလမ်းနှစ်မျိုး။ strip သည် code ကိုင်ထားသည့်အတိုင်း board ဖြစ်သည် — လက်ရှိ လမ်းကြောင်းက သုံးပြီး cell တွင် '#'။ stage သည် လျှောက်ခြင်းကို လမ်းညွှန်သည့်အရာ — word တစ်ခု သို့မဟုတ် ၎င်းတို့အားလုံး၏ trie၊ တွေ့ပြီး အကိုင်းများ ဖြတ်ခံရသည်နှင့် ကျုံ့သည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the trie raises", my: "trie နှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why store the word on its node instead of an end flag?", my: "end flag အစား word ကို ၎င်း၏ node တွင် ဘာကြောင့် သိမ်းသလဲ။" }, a: { en: "The search never carries the letters it has spelled — it only knows which node it is at. Keeping the whole word there means a find is one append, no string building along the path, and setting it back to empty is the \"already found\" mark that stops duplicates.", my: "ရှာဖွေမှုသည် ၎င်း စာလုံးပေါင်းခဲ့သော စာလုံးများကို ဘယ်တော့မှ မသယ်ပါ — ၎င်း မည်သည့် node တွင် ရှိသလဲသာ သိသည်။ word တစ်ခုလုံးကို ထိုနေရာတွင် ထားခြင်းက တွေ့ရှိမှုကို append တစ်ကြိမ် ဖြစ်စေပြီး လမ်းကြောင်းတစ်လျှောက် string တည်ဆောက်ရန် မလို — ၎င်းကို ဗလာ ပြန်ထားခြင်းသည် ထပ်နေခြင်းကို တားသော \"တွေ့ပြီးသား\" အမှတ် ဖြစ်သည်။" } },
      { q: { en: "What does pruning buy?", my: "ဖြတ်ခြင်းက ဘာရသလဲ။" }, a: { en: "Once every word under a node has been found, walking into that node can only waste time. Deleting emptied leaves on the way back up makes later paths stop a letter earlier. On a board of one letter it is what keeps the search from re-walking the same long chains once their words are found.", my: "node တစ်ခုအောက်ရှိ word တိုင်းကို တွေ့ပြီးသည်နှင့် ထို node ထဲ လျှောက်ဝင်ခြင်းသည် အချိန်ဖြုန်းရုံသာ။ ပြန်တက်လာစဉ် ဗလာဖြစ်သော leaf များကို ဖျက်ခြင်းက နောက်ပိုင်း လမ်းကြောင်းများကို စာလုံးတစ်လုံး စောပြီး ရပ်စေသည်။ စာလုံးတစ်မျိုးတည်း board ပေါ်တွင် ၎င်းတို့၏ word များ တွေ့ပြီးသည်နှင့် ရှည်လျားသော ကွင်းဆက် အတူတူကို ပြန်မလျှောက်စေရန် ထိန်းသည်မှာ ၎င်း ဖြစ်သည်။" } },
      { q: { en: "When does the trie make the biggest difference?", my: "trie က ဘယ်အချိန်တွင် အကြီးဆုံး ကွာခြားစေသလဲ။" }, a: { en: "When many words share a long beginning that the board contains but that none of them finishes. The 25 words \"aaaaaaaaa\" + one other letter, on a 12 × 12 board of a's, send the per-word search through every nine-a path 25 times; the trie walks those paths once and checks 25 children at the end. Measured here: 4.89 s against 0.21 s in Python. On a board of mixed letters most words fail at their first letter and the gap is small — 0.12 s against 0.05 s for 20,066 words.", my: "word များစွာသည် board တွင် ပါရှိသော်လည်း မည်သည့် word ကမျှ မပြီးဆုံးသော ရှည်လျားသည့် အစ တူသည့်အခါ။ a ချည်း 12 × 12 board ပေါ်ရှိ \"aaaaaaaaa\" + အခြားစာလုံးတစ်လုံး word 25 ခုသည် word တစ်ခုလျှင် ရှာဖွေမှုကို a ကိုးလုံး လမ်းကြောင်းတိုင်းကို 25 ကြိမ် ဖြတ်စေသည် — trie သည် ထိုလမ်းကြောင်းများကို တစ်ကြိမ်သာ လျှောက်ပြီး အဆုံးတွင် child 25 ခုကို စစ်သည်။ ဤနေရာတွင် တိုင်းတာထားသည် — Python ဖြင့် 4.89 s နှင့် 0.21 s။ စာလုံးရောနှောသော board ပေါ်တွင် word အများစုသည် ပထမ စာလုံးတွင် ကျရှုံးပြီး ကွာခြားချက် သေးသည် — word 20,066 ခုအတွက် 0.12 s နှင့် 0.05 s။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "One walk for every word at once", my: "word တိုင်းအတွက် တစ်ပြိုင်နက် လျှောက်ခြင်း တစ်ကြိမ်" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>12 × 12 of a's, 25 words</th><th>20,066 path words</th></tr></thead>\n  <tbody>\n    <tr><td><b>One search per word</b></td>\n        <td class=\"mono\">O(W · m·n · 3<sup>L</sup>)</td><td class=\"cross\">4.89 s</td><td>0.12 s</td></tr>\n    <tr><td><b>Trie + one walk</b></td>\n        <td class=\"mono\">O(m·n · 3<sup>L</sup>)</td><td class=\"tick\">0.21 s</td><td class=\"tick\">0.05 s</td></tr>\n  </tbody>\n</table>\n<figcaption>Measured here: the Python listings on an Apple M5 Pro, whole process, best of three. W is the number of words, L the longest. The first column is the classic worst case — 25 words that all start with nine a's and are found nowhere; the second is 20,066 words cut from real paths on a random board, where most searches end at the first letter.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>a ချည်း 12 × 12၊ word 25</th><th>path word 20,066</th></tr></thead>\n  <tbody>\n    <tr><td><b>One search per word</b></td>\n        <td class=\"mono\">O(W · m·n · 3<sup>L</sup>)</td><td class=\"cross\">4.89 s</td><td>0.12 s</td></tr>\n    <tr><td><b>Trie + one walk</b></td>\n        <td class=\"mono\">O(m·n · 3<sup>L</sup>)</td><td class=\"tick\">0.21 s</td><td class=\"tick\">0.05 s</td></tr>\n  </tbody>\n</table>\n<figcaption>ဤနေရာတွင် တိုင်းတာထားသည် — Apple M5 Pro ပေါ်ရှိ Python listing များ၊ process တစ်ခုလုံး၊ သုံးကြိမ်အနက် အကောင်းဆုံး။ W သည် word အရေအတွက်၊ L သည် အရှည်ဆုံး။ ပထမ column သည် ဂန္တဝင် အဆိုးဆုံး အခြေအနေ — a ကိုးလုံးဖြင့် စပြီး မည်သည့်နေရာတွင်မျှ မတွေ့ရသော word 25 ခု — ဒုတိယသည် ကျပန်း board ပေါ်ရှိ တကယ့်လမ်းကြောင်းများမှ ဖြတ်ယူသော word 20,066 ခု၊ ရှာဖွေမှု အများစု ပထမ စာလုံးတွင် ပြီးဆုံးသည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission. The trie ran against 20,013 inputs up to 12 × 12 and 3 × 10⁴ words; one search per word against the 20,011 without thousands of words.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်သည်။ trie ကို 12 × 12 နှင့် word 3 × 10⁴ အထိ input 20,013 ခုဖြင့်၊ word တစ်ခုလျှင် ရှာဖွေမှုကို word ထောင်ချီ မပါသော 20,011 ခုဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>board</code> (up to 4 × 4, rows split by <code>;</code>) and <code>words</code> (up to 5, 6 letters each) above, and both walkthroughs rebuild against them.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>board</code> (4 × 4 အထိ၊ row များကို <code>;</code> ဖြင့် ခွဲ) နှင့် <code>words</code> (5 ခုအထိ၊ တစ်ခုလျှင် စာလုံး 6) ကို ပြင်လိုက်လျှင် walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
