/* The prose of the Reverse Nodes in k-Group page: everything the reader sees
 * that is not interactive. Rendered by src/pages/leetcode/[slug].astro through
 * the Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Reverse Nodes in k-Group',
  summary: 'Reverse Linked List, run k nodes at a time. The hard part is the seams: each reversed group must hang off the node before it and point at the group after. Recursion gets the seam for free; the in-place version relinks both ends by hand, in O(1) extra space.',
  eyebrow: 'LeetCode 25 &nbsp;·&nbsp; Hard',
  lede: { en: "Turn a linked list around in groups of k, leaving a short tail untouched. Reversing one group is the familiar three-pointer loop; what makes this Hard is joining the groups. Reverse the rest of the list first and the join is automatic — the group's old head just points at it. Do it in place and you keep a pointer to the node before each group, start the reversal pointing at the node after it, and stitch both ends.", my: "linked list ကို k ခုစီ အုပ်စုလိုက် လှည့်ပြီး အမြီးတိုကို မထိပါနှင့်။ အုပ်စုတစ်ခုကို ပြောင်းပြန်လုပ်ခြင်းသည် ရင်းနှီးသော pointer သုံးခု loop ဖြစ်သည် — ၎င်းကို Hard ဖြစ်စေသည်မှာ အုပ်စုများကို ဆက်ခြင်း။ list ၏ ကျန်သည်ကို အရင် ပြောင်းပြန်လုပ်လျှင် ဆက်ခြင်းသည် အလိုအလျောက် ဖြစ်သည် — အုပ်စု၏ ခေါင်းဟောင်းက ၎င်းကို ရိုးရိုး ညွှန်သည်။ နေရာတွင်ပင် လုပ်လျှင် အုပ်စုတိုင်းရှေ့ရှိ node ကို pointer ဖြင့် ထိန်း၊ ပြောင်းပြန်လုပ်ခြင်းကို ၎င်းနောက်ရှိ node ကို ညွှန်၍ စပြီး အစွန်နှစ်ဖက်ကို ချုပ်သည်။" },
  links: [{ id: 25, title: 'Reverse Nodes in k-Group', slug: 'reverse-nodes-in-k-group', difficulty: 'Hard' }],
  constraints: { en: "<span>the list has <b>n</b> nodes</span><span>1 &le; k &le; n &le; 5000</span><span>0 &le; Node.val &le; 1000</span>", my: "<span>list တွင် node <b>n</b> ခု</span><span>1 &le; k &le; n &le; 5000</span><span>0 &le; Node.val &le; 1000</span>" },
  part1Sub: { en: "Read the statement, then drag k and watch which nodes turn around.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် k ကို ဆွဲပြီး မည်သည့် node များ လှည့်သလဲ ကြည့်ပါ။" },
  widgetTitle: { en: "Drag k, see the groups turn", my: "k ကို ဆွဲပါ — အုပ်စုများ လှည့်ပုံ ကြည့်ပါ" },
  traps: {
    summary: { en: "Three ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ သုံးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>The short tail stays as it is.</strong> Reversing whatever is left at the end, full group or not, turns example 2 into <code>[3,2,1,5,4]</code> instead of <code>[3,2,1,4,5]</code>. Count k nodes before touching any of them.", my: "<strong>အမြီးတိုသည် ရှိသည့်အတိုင်း ကျန်သည်။</strong> အုပ်စု ပြည့်သည်ဖြစ်စေ မပြည့်သည်ဖြစ်စေ အဆုံးတွင် ကျန်သည်ကို ပြောင်းပြန်လုပ်လျှင် ဥပမာ 2 သည် <code>[3,2,1,4,5]</code> အစား <code>[3,2,1,5,4]</code> ဖြစ်သွားသည်။ မည်သည်ကိုမျှ မထိမီ node k ခုကို ရေတွက်ပါ။" },
      { en: "<strong>Move the \"node before\" on.</strong> In the in-place version, forgetting <code>before = first</code> after a group leaves before where it was, and the next pass reverses the same group back: example 1 never finishes.", my: "<strong>\"ရှေ့ node\" ကို ရှေ့တိုးပါ။</strong> နေရာတွင်ပင် version တွင် အုပ်စုတစ်ခုပြီးနောက် <code>before = first</code> ကို မေ့လျှင် before သည် နေရာဟောင်းတွင် ကျန်ပြီး နောက် pass က အုပ်စု အတူတူကို ပြန်လှန်သည် — ဥပမာ 1 သည် ဘယ်တော့မှ မပြီးပါ။" },
      { en: "<strong>k = 1 on 5,000 nodes is 5,000 calls deep.</strong> The recursive version makes one call per group; at Python's default limit of 1,000, a 1,000-node list with k = 1 fails with <code>RecursionError</code> (checked here).", my: "<strong>node 5,000 ပေါ်ရှိ k = 1 သည် call 5,000 ဆင့် နက်သည်။</strong> recursive version သည် အုပ်စုတစ်ခုလျှင် call တစ်ခု လုပ်သည် — Python ၏ default 1,000 ကန့်သတ်ချက်တွင် k = 1 ဖြင့် node 1,000 list သည် <code>RecursionError</code> ဖြင့် ကျရှုံးသည် (ဤနေရာတွင် စစ်ထားသည်)။" },
    ],
  },
  part2Sub: { en: "Two ways to join the groups. The strip is the values in groups of k; the stage is the nodes as the code has linked them — the call stack and the two chains being joined, or the whole list from the dummy with before, first, end and after marked.", my: "အုပ်စုများကို ဆက်ရန် နည်းနှစ်မျိုး။ strip သည် k ခုစီ အုပ်စုလိုက် value များ ဖြစ်သည်။ stage သည် code ချိတ်ထားသည့်အတိုင်း node များ — call stack နှင့် ဆက်နေသော chain နှစ်ခု၊ သို့မဟုတ် before၊ first၊ end နှင့် after ကို မှတ်ထားသော dummy မှ list တစ်ခုလုံး။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the seams raise", my: "ဆက်ရာများနှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why start prev at the node after the group?", my: "prev ကို အုပ်စုနောက်ရှိ node မှ ဘာကြောင့် စသလဲ။" }, a: { en: "Reversing a list normally starts with prev = null, so the old head ends up pointing at nothing. Here the old head of the group should point at whatever follows the group, so start prev there. After k flips the group is reversed and already joined on its right; only the left seam — the node before — is left to fix.", my: "list ကို ပုံမှန် ပြောင်းပြန်လုပ်ခြင်းသည် prev = null ဖြင့် စသဖြင့် ခေါင်းဟောင်းသည် ဘာမှမဟုတ်ကို ညွှန်မည်။ ဤနေရာတွင် အုပ်စု၏ ခေါင်းဟောင်းသည် အုပ်စုနောက်ရှိ အရာကို ညွှန်ရမည် ဖြစ်သဖြင့် prev ကို ထိုနေရာမှ စသည်။ လှန်ခြင်း k ကြိမ်အပြီး အုပ်စုသည် ပြောင်းပြန်ပြီး ၎င်း၏ ညာဘက်တွင် ဆက်ပြီးသား — ဘယ်ဆက်ရာ — ရှေ့ node — ကိုသာ ပြင်ရန် ကျန်သည်။" } },
      { q: { en: "What is the dummy node for?", my: "dummy node က ဘာအတွက်လဲ။" }, a: { en: "Every group has a node before it whose next must be repointed at the reversed group — except the first, whose \"node before\" is the head pointer itself. A dummy in front gives the first group an ordinary node before it, so there is one code path, and the answer is dummy.next.", my: "အုပ်စုတိုင်းတွင် next ကို ပြောင်းပြန်အုပ်စုသို့ ပြန်ညွှန်ရမည့် ရှေ့ node ရှိသည် — ပထမ အုပ်စုမှလွဲ၍၊ ၎င်း၏ \"ရှေ့ node\" သည် head pointer ကိုယ်တိုင် ဖြစ်သည်။ ရှေ့တွင် dummy က ပထမ အုပ်စုကို သာမန် ရှေ့ node တစ်ခု ပေးသဖြင့် code လမ်းကြောင်း တစ်ခုတည်း ရှိပြီး အဖြေမှာ dummy.next ဖြစ်သည်။" } },
      { q: { en: "Could I just swap the values?", my: "value များကိုသာ လဲလို့ ရမလား။" }, a: { en: "It would print the same list, and the statement forbids it: only the nodes may move. The rule is there because in real code a node is often more than its value — other structures may hold pointers to it — and moving values would leave those pointing at the wrong data.", my: "list အတူတူ print ထွက်မည်ဖြစ်သော်လည်း မေးခွန်းက တားသည် — node များသာ ရွေ့ရမည်။ စည်းမျဉ်း ရှိရခြင်းမှာ တကယ့် code တွင် node တစ်ခုသည် ၎င်း၏ value ထက် ပိုလေ့ရှိသောကြောင့် — အခြား structure များက ၎င်းကို pointer ဖြင့် ကိုင်ထားနိုင်သည် — value များကို ရွှေ့လျှင် ၎င်းတို့ မှားသော data ကို ညွှန်နေမည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "Linear either way; the difference is the stack", my: "မည်သို့ပင်ဖြစ်စေ linear — ကွာခြားချက်မှာ stack" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>5,000 nodes, k = 1</th></tr></thead>\n  <tbody>\n    <tr><td><b>Recursive</b></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(n/k) stack</td><td>5,000 calls deep</td></tr>\n    <tr><td><b>In place</b><br><span class=\"sub\">O(1) extra</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(1)</td><td class=\"tick\">four pointers</td></tr>\n  </tbody>\n</table>\n<figcaption>Counts are computed, not timed. Both walk each node twice — once to count, once to flip. Ruby, Node, Go and Rust all took the recursive version 5,000 calls deep on their default stacks here; Python needs its limit raised.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>node 5,000၊ k = 1</th></tr></thead>\n  <tbody>\n    <tr><td><b>Recursive</b></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(n/k) stack</td><td>call 5,000 ဆင့်</td></tr>\n    <tr><td><b>In place</b><br><span class=\"sub\">O(1) အပို</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(1)</td><td class=\"tick\">pointer လေးခု</td></tr>\n  </tbody>\n</table>\n<figcaption>အရေအတွက်များကို တွက်ထားခြင်းဖြစ်ပြီး အချိန် မတိုင်းထားပါ။ နှစ်ခုလုံး node တစ်ခုစီကို နှစ်ကြိမ် လျှောက်သည် — ရေတွက်ရန်တစ်ကြိမ်၊ လှန်ရန်တစ်ကြိမ်။ Ruby၊ Node၊ Go နှင့် Rust အားလုံး ဤနေရာတွင် ၎င်းတို့၏ default stack ပေါ်တွင် recursive version ကို call 5,000 ဆင့် run နိုင်သည် — Python သည် ကန့်သတ်ချက်ကို မြှင့်ရန် လိုသည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission, and every one was run against the same 20,013 lists, up to 5,000 nodes.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး အားလုံးကို node 5,000 အထိ list 20,013 ခု တူတူဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>head</code> (up to 10 values) and <code>k</code> above, and both walkthroughs rebuild against them.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>head</code> (value 10 ခုအထိ) နှင့် <code>k</code> ကို ပြင်လိုက်လျှင် walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
