/* The prose of the Rotate Image page: everything the reader sees that is not
 * interactive. Rendered by src/pages/leetcode/[slug].astro through the
 * Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Rotate Image',
  summary: 'A clockwise quarter turn sends (i, j) to (j, n − 1 − i). Written into a second matrix it breaks the rules; split into a transpose and a row reversal, it is nothing but swaps.',
  eyebrow: 'LeetCode 48 &nbsp;·&nbsp; Medium',
  lede: { en: "Turn a square matrix a quarter clockwise without a second matrix. The rule for where each value goes is one line, but following it directly needs somewhere to put values while their old place is still being read. Two simpler moves — mirror across the diagonal, then flip every row — make the same turn, and each is a set of swaps.", my: "စတုရန်း matrix တစ်ခုကို ဒုတိယ matrix မပါဘဲ နာရီလက်တံအတိုင်း လေးပုံတစ်ပုံ လှည့်ပါ။ value တစ်ခုစီ ဘယ်ရောက်မလဲ စည်းမျဉ်းမှာ တစ်ကြောင်းတည်း ဖြစ်သော်လည်း တိုက်ရိုက်လိုက်နာလျှင် နေရာဟောင်းကို ဖတ်နေဆဲ value များကို ထားရန် နေရာ လိုသည်။ ပိုရိုးရှင်းသော အဆင့်နှစ်ခု — diagonal ကို ဖြတ်၍ မှန်ပြောင်း၊ ပြီးမှ row တိုင်း ပြောင်းပြန် — က လှည့်ခြင်း အတူတူ ဖြစ်စေပြီး တစ်ခုစီသည် လဲလှယ်ခြင်းများသာ ဖြစ်သည်။" },
  links: [{ id: 48, title: 'Rotate Image', slug: 'rotate-image', difficulty: 'Medium' }],
  constraints: { en: "<span><b>n</b> == matrix.length == matrix[i].length</span><span>1 &le; n &le; 20</span><span>&minus;1000 &le; matrix[i][j] &le; 1000</span>", my: "<span><b>n</b> == matrix.length == matrix[i].length</span><span>1 &le; n &le; 20</span><span>&minus;1000 &le; matrix[i][j] &le; 1000</span>" },
  part1Sub: { en: "Read the statement, then click any cell and follow it around the turn.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် မည်သည့် cell ကိုမဆို နှိပ်ပြီး လှည့်ခြင်းတစ်လျှောက် လိုက်ကြည့်ပါ။" },
  widgetTitle: { en: "Click a cell, see where the turn sends it", my: "cell တစ်ခု နှိပ်ပါ — လှည့်ခြင်းက ဘယ်ပို့သလဲ ကြည့်ပါ" },
  traps: {
    summary: { en: "Four ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ လေးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>\"Modify the input\" means the caller's matrix.</strong> In Python, ending with <code>matrix = out</code> only rebinds a local name: example 1 comes back unchanged, <code>[[1,2,3],[4,5,6],[7,8,9]]</code>. <code>matrix[:] = out</code> writes into the list the caller holds.", my: "<strong>\"input ကို ပြင်\" ဆိုသည်မှာ ခေါ်သူ၏ matrix ဖြစ်သည်။</strong> Python တွင် <code>matrix = out</code> ဖြင့် အဆုံးသတ်လျှင် local name ကိုသာ ပြန်ချိတ်သည် — ဥပမာ 1 သည် <code>[[1,2,3],[4,5,6],[7,8,9]]</code> အတိုင်း မပြောင်းဘဲ ပြန်လာသည်။ <code>matrix[:] = out</code> က ခေါ်သူ ကိုင်ထားသော list ထဲ ရေးသည်။" },
      { en: "<strong>Transpose each pair once.</strong> Looping <code>j</code> from 0 instead of <code>i + 1</code> swaps every pair twice, undoing the transpose; after the row reversal example 1 is only mirrored: <code>[[3,2,1],[6,5,4],[9,8,7]]</code>.", my: "<strong>အတွဲတစ်ခုစီကို တစ်ကြိမ်သာ transpose လုပ်ပါ။</strong> <code>j</code> ကို <code>i + 1</code> အစား 0 မှ loop ပတ်လျှင် အတွဲတိုင်းကို နှစ်ကြိမ် လဲပြီး transpose ပြန်ပျက်သည် — row ပြောင်းပြန်ပြီးနောက် ဥပမာ 1 သည် မှန်ပြောင်းရုံသာ — <code>[[3,2,1],[6,5,4],[9,8,7]]</code>။" },
      { en: "<strong>Reverse each row, not the order of the rows.</strong> Transposing and then reversing the list of rows turns the other way: example 1 becomes <code>[[3,6,9],[2,5,8],[1,4,7]]</code>, counter-clockwise.", my: "<strong>row တစ်ခုစီကို ပြောင်းပြန်လုပ်ပါ — row များ၏ အစီအစဉ်ကို မဟုတ်ပါ။</strong> transpose ပြီးမှ row list ကို ပြောင်းပြန်လုပ်လျှင် ဆန့်ကျင်ဘက်သို့ လှည့်သည် — ဥပမာ 1 သည် <code>[[3,6,9],[2,5,8],[1,4,7]]</code>၊ နာရီလက်တံ ပြောင်းပြန် ဖြစ်လာသည်။" },
      { en: "<strong>Writing a value straight to its new place overwrites one you still need.</strong> <code>matrix[j][n−1−i] = matrix[i][j]</code> in place destroys what was at <code>(j, n−1−i)</code> before it has moved. Either hold all four values of a ring in temporaries, or use swaps, as the transpose does.", my: "<strong>value တစ်ခုကို နေရာသစ်သို့ တိုက်ရိုက် ရေးလျှင် လိုသေးသော value တစ်ခုကို ဖျက်ပစ်မိသည်။</strong> နေရာတွင်ပင် <code>matrix[j][n−1−i] = matrix[i][j]</code> ဆိုလျှင် <code>(j, n−1−i)</code> ရှိ value ကို မရွှေ့ရသေးမီ ဖျက်ပစ်သည်။ ကွင်းတစ်ခု၏ value လေးခုလုံးကို ယာယီ variable ထဲ ထားပါ၊ သို့မဟုတ် transpose ကဲ့သို့ လဲခြင်းကို သုံးပါ။" },
    ],
  },
  part2Sub: { en: "Two approaches to the same turn. The strip is the matrix as the code holds it; the stage is what it writes toward — a second matrix, or the finished answer with the cells already in place lit.", my: "လှည့်ခြင်း တစ်ခုတည်းအတွက် နည်းလမ်းနှစ်မျိုး။ strip သည် code ကိုင်ထားသည့်အတိုင်း matrix ဖြစ်ပြီး ဘယ်ဘက်က ၎င်းရေးနေသည့် ပန်းတိုင် — ဒုတိယ matrix သို့မဟုတ် နေရာရောက်ပြီးသော cell များကို လင်းပြသည့် အဖြေ — ဖြစ်သည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the turn raises", my: "လှည့်ခြင်းနှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why do a transpose and a row reversal add up to a clockwise turn?", my: "transpose နှင့် row ပြောင်းပြန်သည် ဘာကြောင့် နာရီလက်တံအတိုင်း လှည့်ခြင်း ဖြစ်သလဲ။" }, a: { en: "Follow one value. The transpose moves (i, j) to (j, i). Reversing row j moves column i to column n − 1 − i. So (i, j) ends at (j, n − 1 − i) — exactly the rule for a clockwise quarter turn.", my: "value တစ်ခုကို လိုက်ကြည့်ပါ။ transpose က (i, j) ကို (j, i) သို့ ရွှေ့သည်။ row j ကို ပြောင်းပြန်လုပ်ခြင်းက column i ကို column n − 1 − i သို့ ရွှေ့သည်။ ထို့ကြောင့် (i, j) သည် (j, n − 1 − i) တွင် ဆုံးသည် — နာရီလက်တံအတိုင်း လေးပုံတစ်ပုံ လှည့်ခြင်း၏ စည်းမျဉ်း အတိအကျ။" } },
      { q: { en: "Is there a one-pass version?", my: "pass တစ်ခုတည်း version ရှိသလား။" }, a: { en: "Yes: walk the rings from the outside in, and for each position rotate its four-cell ring with one temporary — the ring the part 1 widget shows. Every value moves once instead of twice, for the same O(n²). The transpose-and-reverse version is easier to get right, which is why it is the listing here.", my: "ရှိသည် — ကွင်းများကို အပြင်မှ အတွင်းသို့ လျှောက်ပြီး နေရာတစ်ခုစီအတွက် ၎င်း၏ cell လေးခု ကွင်းကို ယာယီ variable တစ်ခုဖြင့် လှည့်သည် — part 1 widget ပြသည့် ကွင်း ဖြစ်သည်။ value တိုင်း နှစ်ကြိမ်အစား တစ်ကြိမ်သာ ရွှေ့ပြီး O(n²) တူသည်။ transpose-and-reverse version သည် မှန်အောင် ရေးရ ပိုလွယ်သဖြင့် ဤနေရာတွင် listing အဖြစ် ထားသည်။" } },
      { q: { en: "How would a counter-clockwise turn go?", my: "နာရီလက်တံ ပြောင်းပြန် လှည့်ခြင်းကို မည်သို့ လုပ်မလဲ။" }, a: { en: "Transpose, then reverse the order of the rows — the third trap above, which is only wrong because the statement asks for clockwise. Or reverse each row first and then transpose.", my: "transpose ပြီးမှ row များ၏ အစီအစဉ်ကို ပြောင်းပြန်လုပ်သည် — အထက်ပါ တတိယ ချော်လွယ်ချက်ဖြစ်ပြီး မေးခွန်းက နာရီလက်တံအတိုင်း တောင်းထားသောကြောင့်သာ မှားသည်။ သို့မဟုတ် row တစ်ခုစီကို အရင်ပြောင်းပြန်လုပ်ပြီးမှ transpose လုပ်သည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "The same moves, no second matrix", my: "ရွှေ့ခြင်း အတူတူ — ဒုတိယ matrix မပါ" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>At n = 20 (the constraint)</th></tr></thead>\n  <tbody>\n    <tr><td><b>Second matrix</b><br><span class=\"sub\">not in place</span></td>\n        <td class=\"mono\">O(n²)</td><td class=\"mono\">O(n²)</td><td class=\"cross\">400 extra cells — forbidden</td></tr>\n    <tr><td><b>Transpose + reverse</b><br><span class=\"sub\">swaps only</span></td>\n        <td class=\"mono\">O(n²)</td><td class=\"mono\">O(1)</td><td class=\"tick\">190 swaps + 20 row reversals</td></tr>\n  </tbody>\n</table>\n<figcaption>Counts are computed, not measured. Both touch every cell, so neither is faster in any way that matters at n = 20; the point is the space, which the statement makes a rule.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>n = 20 (ကန့်သတ်ချက်) တွင်</th></tr></thead>\n  <tbody>\n    <tr><td><b>Second matrix</b><br><span class=\"sub\">နေရာတွင် မဟုတ်</span></td>\n        <td class=\"mono\">O(n²)</td><td class=\"mono\">O(n²)</td><td class=\"cross\">အပို cell 400 — တားထားသည်</td></tr>\n    <tr><td><b>Transpose + reverse</b><br><span class=\"sub\">လဲခြင်းသာ</span></td>\n        <td class=\"mono\">O(n²)</td><td class=\"mono\">O(1)</td><td class=\"tick\">လဲခြင်း 190 + row ပြောင်းပြန် 20</td></tr>\n  </tbody>\n</table>\n<figcaption>ဤအရေအတွက်များကို တွက်ထားခြင်းဖြစ်ပြီး တိုင်းတာထားခြင်း မဟုတ်ပါ။ နှစ်ခုလုံး cell တိုင်းကို ထိသဖြင့် n = 20 တွင် အရေးပါလောက်အောင် မည်သည့်တစ်ခုမျှ ပိုမမြန်ပါ — အဓိကမှာ memory ဖြစ်ပြီး မေးခွန်းက ၎င်းကို စည်းကမ်း ပြုထားသည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission, and every one was run against the same 20,005 cases, up to 20 × 20.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး အားလုံးကို 20 × 20 အထိ case 20,005 ခု တူတူဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>matrix</code> above — square, up to 5 × 5 — and both walkthroughs rebuild against it.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>matrix</code> ကို ပြင်လိုက်လျှင် (စတုရန်း၊ 5 × 5 အထိ) walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
