/* The prose of the 3Sum page: everything the reader sees that is not
 * interactive. Rendered by src/pages/leetcode/[slug].astro through the
 * Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: '3Sum',
  summary: 'Every triple and a set to drop repeats, or sort once, fix the smallest number and squeeze the other two with two pointers — stepping over equal values so no triplet is found twice.',
  eyebrow: 'LeetCode 15 &nbsp;·&nbsp; Medium',
  lede: { en: "Find every distinct triplet that sums to zero. Two things make it harder than Two Sum: there are three numbers, and the answer is a set of values, not positions. Sorting handles both — it turns the last two numbers into a two-pointer squeeze, and puts equal values next to each other where they are easy to skip.", my: "ပေါင်းလျှင် သုည ရသော ကွဲပြားသည့် triplet အားလုံးကို ရှာပါ။ Two Sum ထက် ခက်စေသည့် အချက် နှစ်ခု ရှိသည် — ကိန်းသုံးလုံး ဖြစ်ခြင်းနှင့် အဖြေသည် နေရာများ မဟုတ်ဘဲ value များ၏ set ဖြစ်ခြင်း။ sort လုပ်ခြင်းက နှစ်ခုစလုံးကို ဖြေရှင်းသည် — နောက်ဆုံး ကိန်းနှစ်လုံးကို pointer နှစ်ခု ညှပ်ခြင်း ဖြစ်စေပြီး တူသော value များကို ကပ်လျက် ဖြစ်စေ၍ ကျော်ရ လွယ်စေသည်။" },
  links: [{ id: 15, title: '3Sum', slug: '3sum', difficulty: 'Medium' }],
  constraints: { en: "<span><b>n</b> 3 &le; nums.length &le; 3000</span><span>&minus;10&#8309; &le; nums[i] &le; 10&#8309;</span><span>any order, no repeated triplet</span>", my: "<span><b>n</b> 3 &le; nums.length &le; 3000</span><span>&minus;10&#8309; &le; nums[i] &le; 10&#8309;</span><span>မည်သည့် အစီအစဉ်မဆို၊ triplet မထပ်ရ</span>" },
  part1Sub: { en: "Read the statement, then pick three positions and see how many different ways make the same triplet.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် နေရာသုံးခု ရွေးပြီး triplet တစ်ခုတည်းကို နည်းမည်မျှဖြင့် ရနိုင်သလဲ ကြည့်ပါ။" },
  widgetTitle: { en: "Pick three, see which triplets repeat", my: "သုံးခု ရွေးပါ — ဘယ် triplet ထပ်သလဲ ကြည့်ပါ" },
  traps: {
    summary: { en: "Four ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ လေးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>Distinct triplets, not distinct positions.</strong> Take the two-pointer listing and delete its two skips, and example 1 comes back as <code>[[-1,-1,2],[-1,0,1],[-1,0,1]]</code>: the two −1s each start a <code>[-1,0,1]</code>. <code>[0,0,0,0]</code> gives <code>[0,0,0]</code> twice.", my: "<strong>ကွဲပြားသော triplet များ — ကွဲပြားသော နေရာများ မဟုတ်ပါ။</strong> pointer နှစ်ခု listing မှ ကျော်ခြင်း နှစ်ခုကို ဖျက်လိုက်လျှင် ဥပမာ 1 သည် <code>[[-1,-1,2],[-1,0,1],[-1,0,1]]</code> ဖြစ်လာသည် — −1 နှစ်လုံးစလုံးက <code>[-1,0,1]</code> တစ်ခုစီကို စသည်။ <code>[0,0,0,0]</code> က <code>[0,0,0]</code> ကို နှစ်ကြိမ် ပေးသည်။" },
      { en: "<strong>Only the <em>positions</em> must differ.</strong> <code>i != j != k</code> is about indices, so <code>[0,0,0]</code> is a valid triplet — example 3. Rejecting equal values would return <code>[]</code> there.", my: "<strong><em>နေရာ</em>များသာ ကွဲပြားရမည်။</strong> <code>i != j != k</code> သည် index များအကြောင်း ဖြစ်သဖြင့် <code>[0,0,0]</code> သည် မှန်ကန်သော triplet ဖြစ်သည် — ဥပမာ 3။ value တူသည်ကို ငြင်းလျှင် ထိုနေရာတွင် <code>[]</code> ကို ပြန်ပေးမိမည်။" },
      { en: "<strong>JavaScript's <code>sort()</code> sorts numbers as text.</strong> <code>[-9,11,3,6].sort()</code> leaves the array as it is, because \"11\" comes before \"3\". The two-pointer listing with a bare <code>sort()</code> returns <code>[]</code> there; the answer is <code>[[-9,3,6]]</code>. Pass <code>(a, b) =&gt; a - b</code>.", my: "<strong>JavaScript ၏ <code>sort()</code> သည် ကိန်းများကို စာသားအဖြစ် sort လုပ်သည်။</strong> \"11\" သည် \"3\" ၏ ရှေ့တွင် ရှိသဖြင့် <code>[-9,11,3,6].sort()</code> သည် array ကို မပြောင်းဘဲ ထားသည်။ <code>sort()</code> အလွတ်ဖြင့် pointer နှစ်ခု listing သည် <code>[]</code> ကို ပြန်ပေးသည် — အဖြေမှာ <code>[[-9,3,6]]</code>။ <code>(a, b) =&gt; a - b</code> ကို ထည့်ပေးပါ။" },
      { en: "<strong>n reaches 3000.</strong> Every triple is n(n − 1)(n − 2)/6 ≈ 4.5 × 10⁹ at the limit (computed) — the brute force is here to be the oracle, not the submission.", my: "<strong>n သည် 3000 အထိ ရှိသည်။</strong> triple တိုင်းဆိုလျှင် ကန့်သတ်ချက်တွင် n(n − 1)(n − 2)/6 ≈ 4.5 × 10⁹ (တွက်ထားခြင်း) — brute force သည် oracle အဖြစ် ရှိခြင်းဖြစ်ပြီး submission အဖြစ် မဟုတ်ပါ။" },
    ],
  },
  part2Sub: { en: "Two approaches over the same sorted array. The stage shows what each one carries — the set of triplets found, or the pair the pointers must make; the panel shows the line running.", my: "sort ထားသော array တစ်ခုတည်းပေါ်တွင် နည်းလမ်းနှစ်မျိုး။ ဘယ်ဘက်က နည်းတစ်ခုစီ သယ်ဆောင်သည့်အရာ — တွေ့ပြီးသော triplet set သို့မဟုတ် pointer များ ဖွဲ့ရမည့် အတွဲ — ကို ပြပြီး ညာဘက် panel က အလုပ်လုပ်နေသော code ကြောင်းကို ပြသည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the squeeze raises", my: "ညှပ်ခြင်းနှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why compare <code>nums[i]</code> with the one <em>before</em> it, not the one after?", my: "<code>nums[i]</code> ကို ၎င်း၏ <em>ရှေ့</em>ကကိန်းနှင့် ဘာကြောင့် နှိုင်းယှဉ်ရသလဲ၊ နောက်ကကိန်းနှင့် မဟုတ်ဘဲ။" }, a: { en: "Because the first copy of a value has to run, so it can use the later copies as its partners. Skip when <code>nums[i] == nums[i + 1]</code> instead and the first −1 of example 1 is skipped — the one that could pair with the second −1 — and the answer loses <code>[-1,-1,2]</code>: that version returns <code>[[-1,0,1]]</code>, and <code>[]</code> on <code>[0,0,0]</code>.", my: "value တစ်ခု၏ ပထမ copy သည် run ရမည်ဖြစ်ပြီး နောက် copy များကို partner အဖြစ် သုံးနိုင်ရမည် ဖြစ်သောကြောင့်။ <code>nums[i] == nums[i + 1]</code> ဖြစ်သည့်အခါ ကျော်လျှင် ဥပမာ 1 ၏ ပထမ −1 — ဒုတိယ −1 နှင့် တွဲနိုင်သည့်တစ်ခု — ကို ကျော်သွားပြီး အဖြေမှ <code>[-1,-1,2]</code> ပျောက်သည် — ထို version သည် <code>[[-1,0,1]]</code> ကို ပြန်ပေးပြီး <code>[0,0,0]</code> တွင် <code>[]</code> ကို ပေးသည်။" } },
      { q: { en: "After a hit, why skip repeats of <code>lo</code> but not of <code>hi</code>?", my: "တွေ့ပြီးနောက် <code>lo</code> ၏ ထပ်နေသည်များကိုသာ ဘာကြောင့် ကျော်ပြီး <code>hi</code> ကို မကျော်သလဲ။" }, a: { en: "Once <code>lo</code> has moved to a new, bigger value, a repeat of the old <code>hi</code> value would make the sum too big, and the next comparison moves <code>hi</code> past it anyway. Skipping one side is enough to avoid the repeat; skipping both is also correct, just more code.", my: "<code>lo</code> သည် ပိုကြီးသော value အသစ်သို့ ရွှေ့ပြီးနောက် <code>hi</code> ၏ value ဟောင်း ထပ်နေလျှင် sum သည် ကြီးလွန်းမည်ဖြစ်ပြီး နောက် နှိုင်းယှဉ်မှုက <code>hi</code> ကို မည်သို့ပင်ဖြစ်စေ ကျော်စေမည်။ ထပ်ခြင်းကို ရှောင်ရန် တစ်ဘက်ကျော်ခြင်း လုံလောက်သည် — နှစ်ဘက်ကျော်လည်း မှန်သည်၊ code ပိုရှည်ရုံသာ။" } },
      { q: { en: "Why is it safe to move a pointer past a number for good?", my: "pointer ကို ကိန်းတစ်လုံး ကျော်ပြီး အပြီးတိုင် ရွှေ့ခြင်း ဘာကြောင့် ဘေးကင်းသလဲ။" }, a: { en: "If the sum is too small with <code>nums[hi]</code>, the largest number still in range, then <code>nums[lo]</code> falls short with every number in range, so no triplet uses it with this <code>i</code>. The same holds for <code>hi</code> when the sum is too big. Each move rules out one number for good, so one squeeze is at most n steps.", my: "ကျန်နေသည့်အထဲက အကြီးဆုံးဖြစ်သော <code>nums[hi]</code> နှင့်တောင် sum ငယ်လွန်းလျှင် <code>nums[lo]</code> သည် အပိုင်းအတွင်းရှိ ကိန်းတိုင်းနှင့် မလောက်သဖြင့် ဤ <code>i</code> ဖြင့် ၎င်းကို သုံးသည့် triplet မရှိပါ။ sum ကြီးလွန်းသည့်အခါ <code>hi</code> အတွက်လည်း ထိုနည်းတူ။ ရွှေ့တိုင်း ကိန်းတစ်လုံးကို အပြီးတိုင် ပယ်သဖြင့် ညှပ်ခြင်းတစ်ကြိမ်သည် အဆင့် n အထိသာ ရှိသည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "One dimension fewer", my: "dimension တစ်ခု လျော့" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>At n = 3000 (the constraint)</th></tr></thead>\n  <tbody>\n    <tr><td><b>Brute force</b><br><span class=\"sub\">every triple, then a set</span></td>\n        <td class=\"mono\">O(n³)</td><td class=\"mono\">O(answer)</td><td class=\"cross\">≈ 4.5 × 10⁹ triples</td></tr>\n    <tr><td><b>Sort + two pointers</b><br><span class=\"sub\">fix one, squeeze two</span></td>\n        <td class=\"mono\">O(n²)</td><td class=\"mono\">O(1) beyond the sort</td><td class=\"tick\">≈ 4.5 × 10⁶ pointer moves</td></tr>\n  </tbody>\n</table>\n<figcaption>Counts are computed from the constraint, not measured. The squeeze for each fixed i is at most n − i − 1 moves, so the sum over all i is about n²/2.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>n = 3000 (ကန့်သတ်ချက်) တွင်</th></tr></thead>\n  <tbody>\n    <tr><td><b>Brute force</b><br><span class=\"sub\">triple တိုင်း၊ ပြီးမှ set</span></td>\n        <td class=\"mono\">O(n³)</td><td class=\"mono\">O(answer)</td><td class=\"cross\">triple ≈ 4.5 × 10⁹</td></tr>\n    <tr><td><b>Sort + two pointers</b><br><span class=\"sub\">တစ်လုံး ချုပ်ကိုင်၊ နှစ်လုံး ညှပ်</span></td>\n        <td class=\"mono\">O(n²)</td><td class=\"mono\">sort အပြင် O(1)</td><td class=\"tick\">pointer ရွှေ့ခြင်း ≈ 4.5 × 10⁶</td></tr>\n  </tbody>\n</table>\n<figcaption>ဤအရေအတွက်များကို ကန့်သတ်ချက်မှ တွက်ထားခြင်းဖြစ်ပြီး တိုင်းတာထားခြင်း မဟုတ်ပါ။ ချုပ်ကိုင်ထားသော i တစ်ခုစီအတွက် ညှပ်ခြင်းသည် ရွှေ့ခြင်း n − i − 1 အထိသာ ရှိသဖြင့် i အားလုံး ပေါင်းလျှင် n²/2 ခန့် ဖြစ်သည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission. The two-pointer listings ran against 20,013 cases up to n = 3000; the brute force against the 20,008 small enough for it.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်သည်။ pointer နှစ်ခု listing များကို n = 3000 အထိ case 20,013 ခုဖြင့်၊ brute force ကို ၎င်းအတွက် သေးလောက်သော case 20,008 ခုဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>nums</code> above — 3 to 10 values — and both walkthroughs rebuild against your array.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>nums</code> ကို ပြင်လိုက်လျှင် (value 3 ခုမှ 10 ခုအထိ) walkthrough နှစ်ခုစလုံး သင့် array ဖြင့် ပြန်တည်ဆောက်မည်။" },
};
