/* The prose of the Lowest Common Ancestor of a Binary Tree page: everything
 * the reader sees that is not interactive. Rendered by
 * src/pages/leetcode/[slug].astro through the Walkthrough layout; each value
 * is a string or an { en, my } pair. */
export default {
  title: 'Lowest Common Ancestor of a Binary Tree',
  summary: 'Record every node\'s parent, mark p\'s ancestors and climb from q to the first marked one — or recurse, and let the first node that hears "found" from both sides be the answer.',
  eyebrow: 'LeetCode 236 &nbsp;·&nbsp; Medium',
  lede: { en: "The deepest node that has both p and q beneath it — counting a node as beneath itself. Every node has one path down from the root, and the answer is the last node two paths share. One approach builds the way back up and compares the paths; the other finds the split in a single recursive pass.", my: "p ရော q ပါ ၎င်းအောက်တွင် ရှိသော အနက်ဆုံး node — node တစ်ခုကို ၎င်းကိုယ်တိုင်၏ အောက်တွင် ရှိသည်ဟု ရေတွက်သည်။ node တိုင်းတွင် root မှ ဆင်းသော လမ်းကြောင်း တစ်ခုစီ ရှိပြီး အဖြေသည် လမ်းကြောင်းနှစ်ခု မျှသော နောက်ဆုံး node ဖြစ်သည်။ နည်းတစ်ခုက အပေါ်ပြန်တက်လမ်းကို တည်ဆောက်ပြီး လမ်းကြောင်းများကို နှိုင်းယှဉ်သည် — နောက်တစ်ခုက recursive pass တစ်ကြိမ်တည်းဖြင့် ခွဲရာကို ရှာသည်။" },
  links: [{ id: 236, title: 'Lowest Common Ancestor of a Binary Tree', slug: 'lowest-common-ancestor-of-a-binary-tree', difficulty: 'Medium' }],
  constraints: { en: "<span><b>n</b> 2 &le; nodes &le; 10&#8309;</span><span>&minus;10&#8313; &le; Node.val &le; 10&#8313;</span><span>values unique · p &ne; q · both in the tree</span>", my: "<span><b>n</b> 2 &le; nodes &le; 10&#8309;</span><span>&minus;10&#8313; &le; Node.val &le; 10&#8313;</span><span>value များ ကွဲပြား · p &ne; q · နှစ်ခုလုံး tree ထဲ ရှိ</span>" },
  part1Sub: { en: "Read the statement, then pick p and q and watch where their paths from the root part.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် p နှင့် q ကို ရွေးပြီး root မှ ၎င်းတို့၏ လမ်းကြောင်းများ ဘယ်မှာ ခွဲသလဲ ကြည့်ပါ။" },
  widgetTitle: { en: "Pick p and q, find where their paths split", my: "p နှင့် q ကို ရွေးပါ — လမ်းကြောင်း ခွဲရာကို ရှာပါ" },
  traps: {
    summary: { en: "Three ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ သုံးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>A node is its own descendant.</strong> In example 2, 4 sits under 5, and the answer is 5 itself — not 5's parent, 3. The recursion gets this for free by returning a node the moment it is p or q, without looking below.", my: "<strong>node တစ်ခုသည် ၎င်းကိုယ်တိုင်၏ descendant ဖြစ်သည်။</strong> ဥပမာ 2 တွင် 4 သည် 5 ၏ အောက်တွင် ရှိပြီး အဖြေသည် 5 ကိုယ်တိုင် — 5 ၏ parent 3 မဟုတ်ပါ။ recursion သည် p သို့မဟုတ် q ဖြစ်သည်နှင့် အောက်ကို မကြည့်ဘဲ node ကို ပြန်ပေးခြင်းဖြင့် ဤအရာကို အလိုလို ရသည်။" },
      { en: "<strong>p and q are nodes, not values.</strong> The function receives the nodes themselves, so compare nodes (<code>root is p</code>, <code>root === p</code>), not <code>root.val == p</code>. Values happen to be unique here, which is why the Rust listings may compare by value.", my: "<strong>p နှင့် q သည် node များ ဖြစ်ပြီး value များ မဟုတ်ပါ။</strong> function သည် node ကိုယ်တိုင်များကို လက်ခံသဖြင့် <code>root.val == p</code> မဟုတ်ဘဲ node များကို (<code>root is p</code>၊ <code>root === p</code>) နှိုင်းယှဉ်ပါ။ ဤနေရာတွင် value များ ကွဲပြားနေသဖြင့် Rust listing များက value ဖြင့် နှိုင်းယှဉ်နိုင်သည်။" },
      { en: "<strong>The tree can be 10⁵ levels deep.</strong> A chain of 10⁵ nodes is a legal input. The recursive listing overflows the default stack past 7,687 levels in Ruby 3.1 and past 6,906 in Node 24, and aborts at 10⁵ in Rust — all measured here. The parent-pointer version uses an explicit stack and has no such limit.", my: "<strong>tree သည် 10⁵ ဆင့်အထိ နက်နိုင်သည်။</strong> node 10⁵ ကွင်းဆက်သည် ခွင့်ပြုထားသော input ဖြစ်သည်။ recursive listing သည် Ruby 3.1 တွင် 7,687 ဆင့်ကျော်၊ Node 24 တွင် 6,906 ဆင့်ကျော်လျှင် default stack overflow ဖြစ်ပြီး Rust တွင် 10⁵ တွင် abort ဖြစ်သည် — အားလုံး ဤနေရာတွင် တိုင်းတာထားသည်။ parent-pointer version သည် explicit stack ကို သုံးပြီး ထိုကန့်သတ်ချက် မရှိပါ။" },
    ],
  },
  part2Sub: { en: "Two approaches over the same tree. The stage draws it — recorded parents and p's ancestors, or what each recursive call reported back up — beside the stack each approach keeps; the panel shows the line running.", my: "tree တစ်ခုတည်းပေါ်တွင် နည်းလမ်းနှစ်မျိုး။ ဘယ်ဘက်က ၎င်းကို ဆွဲသည် — မှတ်ပြီးသော parent များနှင့် p ၏ ancestor များ၊ သို့မဟုတ် recursive call တစ်ခုစီ အပေါ်သို့ ပြန်ပို့ခဲ့သည့်အရာ — နည်းတစ်ခုစီ ထားသော stack ၏ ဘေးတွင်။ ညာဘက် panel က အလုပ်လုပ်နေသော code ကြောင်းကို ပြသည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the recursion raises", my: "recursion နှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why is it safe to stop at p without searching below it for q?", my: "p တွင် ရပ်ပြီး ၎င်းအောက်တွင် q ကို မရှာခြင်း ဘာကြောင့် ဘေးကင်းသလဲ။" }, a: { en: "If q is below p, then p is the answer, and returning p is right. If q is elsewhere, some ancestor will hear p from one side and q from the other and return itself. Either way, nothing below p can change the answer.", my: "q သည် p ၏ အောက်တွင် ရှိလျှင် p သည် အဖြေ ဖြစ်ပြီး p ကို ပြန်ပေးခြင်း မှန်သည်။ q သည် အခြားနေရာတွင် ရှိလျှင် ancestor တစ်ခုက တစ်ဘက်မှ p နှင့် ကျန်ဘက်မှ q ကို ကြားပြီး ၎င်းကိုယ်တိုင်ကို ပြန်ပေးမည်။ မည်သို့ပင်ဖြစ်စေ p ၏ အောက်ရှိ မည်သည့်အရာကမျှ အဖြေကို မပြောင်းနိုင်ပါ။" } },
      { q: { en: "What does a call's return value mean?", my: "call တစ်ခု၏ return value ၏ အဓိပ္ပာယ်မှာ ဘာလဲ။" }, a: { en: "Null means neither p nor q is below. Otherwise it is either the one of p, q found below — passed up unchanged — or, once both have been found, their LCA, passed up unchanged from then on. The root's call ends up holding the LCA because the statement promises both nodes are in the tree.", my: "null ဆိုသည်မှာ အောက်တွင် p ရော q ပါ မရှိခြင်း ဖြစ်သည်။ မဟုတ်လျှင် ၎င်းသည် အောက်တွင် တွေ့သော p၊ q ထဲက တစ်ခု — မပြောင်းဘဲ အပေါ်ပို့ — သို့မဟုတ် နှစ်ခုလုံး တွေ့ပြီးသည်နှင့် ၎င်းတို့၏ LCA — ထိုအချိန်မှစ၍ မပြောင်းဘဲ အပေါ်ပို့ — ဖြစ်သည်။ node နှစ်ခုလုံး tree ထဲ ရှိကြောင်း မေးခွန်းက ကတိပြုထားသဖြင့် root ၏ call သည် LCA ကို ကိုင်ထားရသည်။" } },
      { q: { en: "Why walk down with a stack in the parent-pointer version?", my: "parent-pointer version တွင် stack ဖြင့် ဘာကြောင့် အောက်သို့ လျှောက်သလဲ။" }, a: { en: "So that nothing about the approach depends on the tree's depth. A stack in the heap grows as far as memory allows; the call stack of a recursive walk stops at a few thousand frames in Ruby and JavaScript. It also stops as soon as p and q have both been reached, rather than visiting the whole tree.", my: "နည်းလမ်း၏ မည်သည့်အရာမျှ tree ၏ အနက်အပေါ် မမူတည်စေရန်။ heap ပေါ်ရှိ stack သည် memory ခွင့်ပြုသမျှ ကြီးနိုင်သည် — recursive walk ၏ call stack သည် Ruby နှင့် JavaScript တွင် frame ထောင်ဂဏန်းအနည်းငယ်တွင် ရပ်သည်။ ၎င်းသည် tree တစ်ခုလုံးကို မဝင်ဘဲ p နှင့် q နှစ်ခုလုံး ရောက်သည်နှင့် ရပ်သည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "The same visit, a different stack", my: "ဝင်ရောက်မှု အတူတူ — stack မတူ" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>A chain of 10⁵ nodes</th></tr></thead>\n  <tbody>\n    <tr><td><b>Parent pointers</b><br><span class=\"sub\">no recursion</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(n) map</td><td class=\"tick\">ran in all five languages</td></tr>\n    <tr><td><b>Recursion</b><br><span class=\"sub\">report up the tree</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(h) stack</td><td class=\"cross\">overflows in Ruby, JavaScript, Rust; runs in Python and Go</td></tr>\n  </tbody>\n</table>\n<figcaption>Measured here on default stacks: Ruby 3.1 overflows past 7,687 levels, Node 24 past 6,906 (cold), Rust's 8 MB main thread aborts at 10⁵. Python's listing raises its recursion limit; Go's stacks grow on demand. On a balanced tree h is about 17, and both approaches are the same speed.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>node 10⁵ ကွင်းဆက်</th></tr></thead>\n  <tbody>\n    <tr><td><b>Parent pointers</b><br><span class=\"sub\">recursion မပါ</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(n) map</td><td class=\"tick\">ဘာသာစကား ငါးမျိုးလုံးတွင် run ခဲ့သည်</td></tr>\n    <tr><td><b>Recursion</b><br><span class=\"sub\">tree တစ်လျှောက် အပေါ်သို့ ပို့</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(h) stack</td><td class=\"cross\">Ruby၊ JavaScript၊ Rust တွင် overflow — Python နှင့် Go တွင် run သည်</td></tr>\n  </tbody>\n</table>\n<figcaption>ဤနေရာတွင် default stack များပေါ်တွင် တိုင်းတာထားသည် — Ruby 3.1 သည် 7,687 ဆင့်ကျော်၊ Node 24 သည် 6,906 ဆင့်ကျော် (cold) overflow ဖြစ်ပြီး Rust ၏ 8 MB main thread သည် 10⁵ တွင် abort ဖြစ်သည်။ Python ၏ listing သည် recursion limit ကို မြှင့်ထားပြီး Go ၏ stack များသည် လိုအပ်သလို ကြီးသည်။ balanced tree တွင် h သည် 17 ခန့် ဖြစ်ပြီး နည်းလမ်းနှစ်ခုလုံး အမြန်နှုန်း တူသည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission. The parent-pointer version ran against all 20,013 cases, up to 10⁵ nodes; the recursion against all but the two 10⁵-deep chains — see its badges.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်သည်။ parent-pointer version ကို node 10⁵ အထိ case 20,013 ခုလုံးဖြင့်၊ recursion ကို 10⁵ ဆင့် နက်သော ကွင်းဆက် နှစ်ခုမှလွဲ၍ အားလုံးဖြင့် run ထားသည် — ၎င်း၏ badge များကို ကြည့်ပါ။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>root</code>, <code>p</code> or <code>q</code> above — level order, <code>null</code> for a missing child, up to 15 nodes with unique values — and both walkthroughs rebuild.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>root</code>၊ <code>p</code> သို့မဟုတ် <code>q</code> ကို ပြင်လိုက်လျှင် (level order၊ ကလေး မရှိလျှင် <code>null</code>၊ value ကွဲပြားသော node 15 ခုအထိ) walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
