/* The prose of the Largest Rectangle in Histogram page: everything the reader
 * sees that is not interactive. Rendered by src/pages/leetcode/[slug].astro
 * through the Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Largest Rectangle in Histogram',
  summary: 'Every rectangle is as tall as its shortest bar, so try each bar as the shortest and stretch it as wide as it goes. A stack of rising bars finds both limits for every bar in one pass: a bar is measured the moment a lower one pushes it off.',
  eyebrow: 'LeetCode 84 &nbsp;·&nbsp; Hard',
  lede: { en: "Find the biggest rectangle that fits under a histogram. Any rectangle is capped by the shortest bar it covers, so the answer is the best of n candidates: each bar, stretched left and right until a lower bar stops it. Finding those stopping bars one step at a time is quadratic; keeping the bars on a stack with rising heights finds them all in a single pass.", my: "histogram အောက်တွင် ဆံ့သော အကြီးဆုံး rectangle ကို ရှာပါ။ rectangle မည်သည်မဆို ၎င်း ဖုံးသော အတိုဆုံး bar က ကန့်သတ်သဖြင့် အဖြေမှာ candidate n ခုထဲမှ အကောင်းဆုံး — bar တစ်ခုစီကို နိမ့်သော bar က ရပ်တန့်သည်အထိ ဘယ်ညာ ဆန့်ခြင်း။ ထိုရပ်တန့်သည့် bar များကို တစ်လှမ်းချင်း ရှာခြင်းသည် quadratic — bar များကို အမြင့် တက်သော stack ပေါ်တွင် ထားခြင်းက pass တစ်ခုတည်းဖြင့် အားလုံးကို ရှာသည်။" },
  links: [{ id: 84, title: 'Largest Rectangle in Histogram', slug: 'largest-rectangle-in-histogram', difficulty: 'Hard' }],
  constraints: { en: "<span>1 &le; heights.length &le; 10<sup>5</sup></span><span>0 &le; heights[i] &le; 10<sup>4</sup></span>", my: "<span>1 &le; heights.length &le; 10<sup>5</sup></span><span>0 &le; heights[i] &le; 10<sup>4</sup></span>" },
  part1Sub: { en: "Read the statement, then pick a bar as the shortest and see how far its rectangle stretches.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် bar တစ်ခုကို အတိုဆုံးအဖြစ် ရွေးပြီး ၎င်း၏ rectangle မည်မျှ ဆန့်သလဲ ကြည့်ပါ။" },
  widgetTitle: { en: "Pick the shortest bar, stretch the rectangle", my: "အတိုဆုံး bar ကို ရွေးပါ — rectangle ကို ဆန့်ပါ" },
  traps: {
    summary: { en: "Three ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ သုံးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>Empty the stack at the end.</strong> Bars still on the stack when the input runs out have never been measured. Without the extra 0 at the end, example 2 returns <code>0</code> — neither bar is ever popped.", my: "<strong>အဆုံးတွင် stack ကို ရှင်းပါ။</strong> input ကုန်သွားချိန်တွင် stack ပေါ်ရှိနေသေးသော bar များကို ဘယ်တော့မှ မတိုင်းခဲ့ပါ။ အဆုံးရှိ အပို 0 မပါလျှင် ဥပမာ 2 သည် <code>0</code> ပြန်ပေးသည် — bar တစ်ခုမျှ pop မခံရ။" },
      { en: "<strong>The width reaches back past the bars already popped.</strong> A popped bar's rectangle starts just after the bar now under it on the stack, not at itself. Measuring <code>i − top</code> instead of <code>i − left − 1</code> returns <code>2</code> for <code>[2,1,2]</code>, where the 1 spans all three bars for 3.", my: "<strong>အကျယ်သည် pop ပြီးသော bar များကို ကျော်၍ နောက်သို့ ရောက်သည်။</strong> pop ခံရသော bar ၏ rectangle သည် ၎င်းကိုယ်တိုင်မှ မဟုတ်ဘဲ stack ပေါ်တွင် ယခု ၎င်းအောက်ရှိ bar ၏ နောက်မှ စသည်။ <code>i − left − 1</code> အစား <code>i − top</code> ကို တိုင်းလျှင် <code>[2,1,2]</code> အတွက် <code>2</code> ပြန်ပေးသည် — 1 သည် bar သုံးခုလုံးကို ဖြတ်၍ 3 ရသည်။" },
      { en: "<strong>Growing around every bar is O(n²).</strong> With 10⁵ equal bars every bar stretches across all of them — 10¹⁰ steps (computed). Even 10⁴ equal bars took the Python version 2.39 s here, against 0.01 s for the stack.", my: "<strong>bar တိုင်းအနီး ကြီးထွားခြင်းသည် O(n²)။</strong> တူညီသော bar 10⁵ ဖြင့် bar တိုင်းသည် အားလုံးကို ဖြတ်၍ ဆန့်သည် — 10¹⁰ လှမ်း (တွက်ထားသည်)။ တူညီသော bar 10⁴ ပင် ဤနေရာတွင် Python version ကို 2.39 s ကြာစေပြီး stack သည် 0.01 s။" },
    ],
  },
  part2Sub: { en: "Two ways to find each bar's limits. The strip is heights; the stage is the histogram with the rectangle being measured, and the stack of bars still waiting for their right limit.", my: "bar တစ်ခုစီ၏ ကန့်သတ်များကို ရှာရန် နည်းနှစ်မျိုး။ strip သည် heights ဖြစ်သည်။ stage သည် တိုင်းနေသော rectangle ပါသည့် histogram နှင့် ၎င်းတို့၏ ညာကန့်သတ်ကို စောင့်နေဆဲ bar များ၏ stack ဖြစ်သည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the stack raises", my: "stack နှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why is the bar under the top its left limit?", my: "ထိပ်အောက်ရှိ bar သည် ဘာကြောင့် ၎င်း၏ ဘယ်ကန့်သတ် ဖြစ်သလဲ။" }, a: { en: "Popping on ≥ keeps the stack's heights strictly rising, so the bar under the top is lower than it. Any bars that stood between them were popped earlier, which only happens when something no taller arrived — they were at least as tall as the top. So the top can stretch left across all of them and stops exactly at the bar under it.", my: "≥ တွင် pop ခြင်းက stack ၏ အမြင့်များကို တင်းကြပ်စွာ တက်စေသဖြင့် ထိပ်အောက်ရှိ bar သည် ၎င်းထက် နိမ့်သည်။ ၎င်းတို့ကြားရှိ bar မည်သည်မဆို အရင်က pop ခံရပြီး ထိုအရာသည် မမြင့်သော တစ်ခုခု ရောက်လာမှသာ ဖြစ်သည် — ၎င်းတို့သည် ထိပ်လောက် အနည်းဆုံး မြင့်ခဲ့သည်။ ထို့ကြောင့် ထိပ်သည် ၎င်းတို့အားလုံးကို ဖြတ်၍ ဘယ်သို့ ဆန့်နိုင်ပြီး ၎င်းအောက်ရှိ bar တွင် အတိအကျ ရပ်သည်။" } },
      { q: { en: "Pop on ≥ or on >?", my: "≥ တွင်လား > တွင် pop မလား။" }, a: { en: "Either works. With ≥, an equal bar pops its twin early and measures it short — but the later twin stretches back across it, so the full rectangle is still found. With >, equal bars pile up and are measured together at the end. The listings use ≥.", my: "နှစ်မျိုးလုံး အလုပ်ဖြစ်သည်။ ≥ ဖြင့် တူညီသော bar က ၎င်း၏ အမွှာကို စောစော pop ပြီး တိုတိုသာ တိုင်းသည် — သို့သော် နောက်မှ အမွှာက ၎င်းကို ဖြတ်၍ နောက်ပြန် ဆန့်သဖြင့် rectangle အပြည့်ကို တွေ့ဆဲ။ > ဖြင့် တူညီသော bar များ စုပုံပြီး အဆုံးတွင် အတူ တိုင်းသည်။ listing များက ≥ ကို သုံးသည်။" } },
      { q: { en: "Where else does this stack show up?", my: "ဤ stack ကို ဘယ်မှာ ထပ်တွေ့သလဲ။" }, a: { en: "Anywhere each element needs its nearest smaller (or larger) neighbour: daily temperatures, stock span, the sum of subarray minimums, and Maximal Rectangle — which runs this exact algorithm once per row of a 0/1 matrix, with each row's bars counting the 1s above.", my: "element တစ်ခုစီသည် ၎င်း၏ အနီးဆုံး ပိုငယ် (သို့မဟုတ် ပိုကြီး) အိမ်နီးကို လိုသည့် နေရာတိုင်း — daily temperatures၊ stock span၊ subarray minimum များ၏ ပေါင်းလဒ်၊ နှင့် Maximal Rectangle — 0/1 matrix ၏ row တစ်ခုစီအတွက် ဤ algorithm အတိအကျကို တစ်ကြိမ်စီ run ပြီး row တစ်ခုစီ၏ bar များသည် အပေါ်ရှိ 1 များကို ရေတွက်သည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "Every bar measured once", my: "bar တိုင်းကို တစ်ကြိမ် တိုင်း" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>10⁴ equal bars</th></tr></thead>\n  <tbody>\n    <tr><td><b>Grow around each bar</b></td>\n        <td class=\"mono\">O(n²)</td><td class=\"mono\">O(1)</td><td class=\"cross\">2.39 s</td></tr>\n    <tr><td><b>Monotonic stack</b></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(n)</td><td class=\"tick\">0.01 s</td></tr>\n  </tbody>\n</table>\n<figcaption>Measured here: the Python listings on an Apple M5 Pro, whole process, best of three. The constraint allows ten times as many bars, a hundred times the work for the first version; it is not run on the 10⁵-bar inputs at all.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>တူညီသော bar 10⁴</th></tr></thead>\n  <tbody>\n    <tr><td><b>Grow around each bar</b></td>\n        <td class=\"mono\">O(n²)</td><td class=\"mono\">O(1)</td><td class=\"cross\">2.39 s</td></tr>\n    <tr><td><b>Monotonic stack</b></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(n)</td><td class=\"tick\">0.01 s</td></tr>\n  </tbody>\n</table>\n<figcaption>ဤနေရာတွင် တိုင်းတာထားသည် — Apple M5 Pro ပေါ်ရှိ Python listing များ၊ process တစ်ခုလုံး၊ သုံးကြိမ်အနက် အကောင်းဆုံး။ ကန့်သတ်ချက်က bar ဆယ်ဆ ခွင့်ပြုသဖြင့် ပထမ version အတွက် အလုပ် အဆတစ်ရာ — bar 10⁵ input များတွင် လုံးဝ မ run ပါ။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission. The stack ran against 20,013 histograms up to 10⁵ bars; growing around each bar against the 20,008 below that.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်သည်။ stack ကို bar 10⁵ အထိ histogram 20,013 ခုဖြင့်၊ bar တစ်ခုစီအနီး ကြီးထွားခြင်းကို ထိုအောက် 20,008 ခုဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>heights</code> above — up to 12 bars, 0 to 20 tall — and both walkthroughs rebuild against it.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>heights</code> ကို ပြင်လိုက်လျှင် (bar 12 ခုအထိ၊ 0 မှ 20 မြင့်) walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
