/* The prose of the Median of Two Sorted Arrays page: everything the reader
 * sees that is not interactive. Rendered by src/pages/leetcode/[slug].astro
 * through the Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Median of Two Sorted Arrays',
  summary: 'The median splits the combined values into two halves. Merging to the middle finds it in linear time; choosing how many values the shorter array gives to the left half, and checking the four values at the cut, finds it by binary search.',
  eyebrow: 'LeetCode 4 &nbsp;·&nbsp; Hard',
  lede: { en: "Find the median of two sorted arrays without building the merged one. The median is where the combined values split into a lower half and an upper half. Walking the merge to the middle finds that split one value at a time. The logarithmic answer searches for the split itself: pick how many values the shorter array contributes to the lower half, let the other array make up the rest, and check the four values that sit on either side of the two cuts.", my: "ပေါင်းထားသော array ကို မတည်ဆောက်ဘဲ စီထားသော array နှစ်ခု၏ median ကို ရှာပါ။ median သည် ပေါင်းထားသော value များ အောက်တစ်ဝက်နှင့် အပေါ်တစ်ဝက်အဖြစ် ခွဲသည့်နေရာ ဖြစ်သည်။ အလယ်အထိ merge ကို လျှောက်ခြင်းက ထိုခွဲခြမ်းမှုကို value တစ်ခုချင်း ရှာသည်။ logarithmic အဖြေသည် ခွဲခြမ်းမှုကိုယ်တိုင်ကို ရှာသည် — ပိုတိုသော array က အောက်တစ်ဝက်သို့ value မည်မျှ ပေးမလဲ ရွေး၊ အခြား array က ကျန်သည်ကို ဖြည့်စေ၊ ဖြတ်ရာနှစ်ခု၏ ဘေးတစ်ဖက်စီရှိ value လေးခုကို စစ်သည်။" },
  links: [{ id: 4, title: 'Median of Two Sorted Arrays', slug: 'median-of-two-sorted-arrays', difficulty: 'Hard' }],
  constraints: { en: "<span><b>m</b> == nums1.length</span><span><b>n</b> == nums2.length</span><span>0 &le; m, n &le; 1000</span><span>1 &le; m + n &le; 2000</span><span>&minus;10<sup>6</sup> &le; nums1[i], nums2[i] &le; 10<sup>6</sup></span>", my: "<span><b>m</b> == nums1.length</span><span><b>n</b> == nums2.length</span><span>0 &le; m, n &le; 1000</span><span>1 &le; m + n &le; 2000</span><span>&minus;10<sup>6</sup> &le; nums1[i], nums2[i] &le; 10<sup>6</sup></span>" },
  part1Sub: { en: "Read the statement, then drag the cut in the first array and see when the split is right.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် ပထမ array ရှိ ဖြတ်ရာကို ဆွဲပြီး ခွဲခြမ်းမှု မှန်သည့်အချိန်ကို ကြည့်ပါ။" },
  widgetTitle: { en: "Drag the cut, find the median's split", my: "ဖြတ်ရာကို ဆွဲပါ — median ၏ ခွဲခြမ်းမှုကို ရှာပါ" },
  traps: {
    summary: { en: "Three ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ သုံးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>The median of an even count is a fraction.</strong> Averaging with integer division — <code>(a + b) // 2</code> in Python, or <code>(a + b) / 2</code> on ints in Go before converting — returns <code>2</code> for example 2, not <code>2.5</code>.", my: "<strong>စုံ အရေအတွက်၏ median သည် အပိုင်းကိန်း ဖြစ်သည်။</strong> integer division ဖြင့် ပျမ်းမျှလျှင် — Python တွင် <code>(a + b) // 2</code>၊ သို့မဟုတ် Go တွင် မပြောင်းမီ int ပေါ်ရှိ <code>(a + b) / 2</code> — ဥပမာ 2 အတွက် <code>2.5</code> မဟုတ်ဘဲ <code>2</code> ပြန်ပေးသည်။" },
      { en: "<strong>Search the shorter array.</strong> Cutting the longer one lets j = half − i go below 0. In Python the negative index wraps around silently: <code>[1,2,3,4,5]</code> and <code>[6]</code> come back <code>4.5</code> instead of <code>3.5</code>.", my: "<strong>ပိုတိုသော array ကို ရှာပါ။</strong> ပိုရှည်သည်ကို ဖြတ်လျှင် j = half − i သည် 0 အောက် ကျနိုင်သည်။ Python တွင် အနုတ် index သည် တိတ်တဆိတ် ပတ်လည်သည် — <code>[1,2,3,4,5]</code> နှင့် <code>[6]</code> သည် <code>3.5</code> အစား <code>4.5</code> ပြန်လာသည်။" },
      { en: "<strong>Past the end is ±infinity, not 0.</strong> When a cut sits at an array's edge there is no value on that side. Standing 0 in for it breaks as soon as values are negative: <code>[-3,-2]</code> and <code>[-1]</code> return <code>0</code> instead of <code>-2</code>.", my: "<strong>အဆုံးကျော်လျှင် 0 မဟုတ်ဘဲ ±infinity။</strong> ဖြတ်ရာသည် array ၏ အစွန်တွင် ရှိလျှင် ထိုဘက်တွင် value မရှိ။ ၎င်းအစား 0 ထားလျှင် value များ အနုတ်ဖြစ်သည်နှင့် ပျက်သည် — <code>[-3,-2]</code> နှင့် <code>[-1]</code> သည် <code>-2</code> အစား <code>0</code> ပြန်ပေးသည်။" },
    ],
  },
  part2Sub: { en: "Two ways to find the split. The strip is the two arrays; the stage is the merge taken so far, or the cut — the values going to the left half lit, and the four values the check compares marked.", my: "ခွဲခြမ်းမှုကို ရှာရန် နည်းနှစ်မျိုး။ strip သည် array နှစ်ခု ဖြစ်သည်။ stage သည် ယခုထိ ယူခဲ့သော merge၊ သို့မဟုတ် ဖြတ်ရာ — ဘယ်တစ်ဝက်သို့ သွားသော value များ လင်းပြီး စစ်ချက်က နှိုင်းယှဉ်သော value လေးခုကို မှတ်ထားသည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the cut raises", my: "ဖြတ်ရာနှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why are four values enough to check the split?", my: "ခွဲခြမ်းမှုကို စစ်ရန် value လေးခု ဘာကြောင့် လုံလောက်သလဲ။" }, a: { en: "Within each array the values are already in order, so everything left of a cut is ≤ everything right of it. The only comparisons that can fail are across the arrays: the largest left value of each against the smallest right value of the other. Those are left1 ≤ right2 and left2 ≤ right1.", my: "array တစ်ခုစီအတွင်း value များ စီပြီးသား ဖြစ်သဖြင့် ဖြတ်ရာ၏ ဘယ်ရှိ အားလုံး ≤ ညာရှိ အားလုံး။ ပျက်နိုင်သော နှိုင်းယှဉ်ချက်မှာ array ချင်း ကူးသည့်အရာသာ — တစ်ခုစီ၏ အကြီးဆုံး ဘယ် value နှင့် အခြား၏ အငယ်ဆုံး ညာ value။ ၎င်းတို့မှာ left1 ≤ right2 နှင့် left2 ≤ right1။" } },
      { q: { en: "Why half = (m + n + 1) / 2?", my: "half = (m + n + 1) / 2 ဘာကြောင့်လဲ။" }, a: { en: "It puts the extra value on the left when the total is odd, so the median is always the largest left value — no second case for where the middle landed. For an even total it is exactly half, and the median averages the largest left and smallest right.", my: "စုစုပေါင်း မ ဖြစ်သည့်အခါ အပို value ကို ဘယ်တွင် ထားသဖြင့် median သည် အမြဲ အကြီးဆုံး ဘယ် value ဖြစ်သည် — အလယ် ဘယ်ကျသလဲ ဒုတိယ case မလို။ စုံ ဖြစ်လျှင် တစ်ဝက် အတိအကျ ဖြစ်ပြီး median သည် အကြီးဆုံး ဘယ်နှင့် အငယ်ဆုံး ညာကို ပျမ်းမျှသည်။" } },
      { q: { en: "Would the judge even notice O(m + n)?", my: "judge က O(m + n) ကို သတိထားမိမလား။" }, a: { en: "Hardly: with at most 2,000 values, merging to the middle is 1,001 steps — nothing a time limit can tell apart from 10. The requirement is the point of the problem — it is what turns a merge exercise into a binary search on a split — and the kind of thing an interviewer asks you to justify.", my: "မဖြစ်နိုင်သလောက် — value အများဆုံး 2,000 ဖြင့် အလယ်အထိ merge ခြင်းသည် အဆင့် 1,001 — time limit က 10 နှင့် ခွဲမခြားနိုင်။ လိုအပ်ချက်သည် ပြဿနာ၏ အဓိကအချက် — merge လေ့ကျင့်ခန်းကို ခွဲခြမ်းမှုပေါ်ရှိ binary search အဖြစ် ပြောင်းသည့်အရာ — ဖြစ်ပြီး interviewer က သင့်ကို ရှင်းပြခိုင်းမည့် အမျိုးအစား ဖြစ်သည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "A thousand steps, or ten", my: "အဆင့် တစ်ထောင်၊ သို့မဟုတ် ဆယ်" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>1,000 + 1,000 values</th></tr></thead>\n  <tbody>\n    <tr><td><b>Merge to the middle</b></td>\n        <td class=\"mono\">O(m + n)</td><td class=\"mono\">O(1)</td><td>1,001 steps</td></tr>\n    <tr><td><b>Binary search the cut</b></td>\n        <td class=\"mono\">O(log min(m, n))</td><td class=\"mono\">O(1)</td><td class=\"tick\">at most 10 cuts</td></tr>\n  </tbody>\n</table>\n<figcaption>Counts are computed, not timed — both finish instantly at this size. The difference is what the statement asks for, and it grows with the input: at a million values each it would be a million steps against 20.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>value 1,000 + 1,000</th></tr></thead>\n  <tbody>\n    <tr><td><b>Merge to the middle</b></td>\n        <td class=\"mono\">O(m + n)</td><td class=\"mono\">O(1)</td><td>အဆင့် 1,001</td></tr>\n    <tr><td><b>Binary search the cut</b></td>\n        <td class=\"mono\">O(log min(m, n))</td><td class=\"mono\">O(1)</td><td class=\"tick\">ဖြတ်ရာ အများဆုံး 10</td></tr>\n  </tbody>\n</table>\n<figcaption>အရေအတွက်များကို တွက်ထားခြင်းဖြစ်ပြီး အချိန် မတိုင်းထားပါ — ဤအရွယ်တွင် နှစ်ခုလုံး ချက်ချင်း ပြီးသည်။ ကွာခြားချက်သည် မေးခွန်း တောင်းသည့်အရာ ဖြစ်ပြီး input နှင့်အတူ ကြီးလာသည် — တစ်ခုစီ value တစ်သန်းတွင် အဆင့် တစ်သန်းနှင့် 20 ဖြစ်မည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission, and every one was run against the same 20,014 pairs, up to 1,000 values each.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး အားလုံးကို တစ်ခုစီ value 1,000 အထိ pair 20,014 ခု တူတူဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>nums1</code> and <code>nums2</code> above — sorted, up to 8 values each, one may be empty — and both walkthroughs rebuild against them.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>nums1</code> နှင့် <code>nums2</code> ကို ပြင်လိုက်လျှင် (စီထား၊ တစ်ခုစီ value 8 အထိ၊ တစ်ခု ဗလာ ဖြစ်နိုင်) walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
