/* The prose of the Longest Substring Without Repeating Characters page:
 * everything the reader sees that is not interactive. Rendered by
 * src/pages/leetcode/[slug].astro through the Walkthrough layout; each value
 * is a string or an { en, my } pair. */
export default {
  title: 'Longest Substring Without Repeating Characters',
  summary: 'Grow a run from every start until a character repeats, or keep one window and, on a repeat, jump its left edge past the earlier copy — remembered in a map of last positions.',
  eyebrow: 'LeetCode 3 &nbsp;·&nbsp; Medium',
  lede: { en: "The longest stretch of the string where no character appears twice. Starting over at every index works but keeps rereading the same characters. The sliding window reads each one once: when a character repeats, it already knows where the earlier copy was, and moves its left edge just past it.", my: "character တစ်လုံးမျှ နှစ်ကြိမ် မပါသည့် string ၏ အရှည်ဆုံး အပိုင်း။ index တိုင်းမှ ပြန်စခြင်းသည် အလုပ်ဖြစ်သော်လည်း character တူများကို ထပ်ခါထပ်ခါ ဖတ်နေသည်။ sliding window သည် တစ်လုံးစီကို တစ်ကြိမ်သာ ဖတ်သည် — character တစ်ခု ထပ်သည့်အခါ ပထမ copy ဘယ်မှာရှိခဲ့သလဲ သိပြီးသားဖြစ်၍ ဘယ်အစွန်းကို ၎င်း၏ နောက်သို့ တန်းရွှေ့သည်။" },
  links: [{ id: 3, title: 'Longest Substring Without Repeating Characters', slug: 'longest-substring-without-repeating-characters', difficulty: 'Medium' }],
  constraints: { en: "<span><b>n</b> 0 &le; s.length &le; 5 &times; 10&#8308;</span><span>letters, digits, symbols and spaces</span>", my: "<span><b>n</b> 0 &le; s.length &le; 5 &times; 10&#8308;</span><span>စာလုံး၊ ဂဏန်း၊ သင်္ကေတနှင့် space များ</span>" },
  part1Sub: { en: "Read the statement, then click a start and an end and see whether the run between them repeats.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် အစနှင့် အဆုံးကို နှိပ်ပြီး ကြားရှိ run တွင် ထပ်နေသလား ကြည့်ပါ။" },
  widgetTitle: { en: "Click a start and an end, check the run", my: "အစနှင့် အဆုံး နှိပ်ပါ — run ကို စစ်ပါ" },
  traps: {
    summary: { en: "Three ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ သုံးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>Substring, not subsequence.</strong> The characters must be next to each other. Counting the different characters in <code>\"pwwkew\"</code> gives 4 — that is <code>\"pwke\"</code>, which skips a <code>w</code>. The answer is 3.", my: "<strong>substring — subsequence မဟုတ်ပါ။</strong> character များ ကပ်လျက် ဖြစ်ရမည်။ <code>\"pwwkew\"</code> ရှိ မတူသော character များကို ရေတွက်လျှင် 4 ရသည် — ၎င်းမှာ <code>w</code> တစ်လုံးကို ကျော်ထားသော <code>\"pwke\"</code> ဖြစ်သည်။ အဖြေမှာ 3။" },
      { en: "<strong>An old position is not always in the window.</strong> Jumping <code>left</code> to <code>last[ch] + 1</code> every time <code>ch</code> has been seen returns 3 on <code>\"abba\"</code>: at the final <code>a</code>, <code>left</code> is already 2, and jumping back to 1 lets <code>\"bba\"</code> in. Only jump when <code>last[ch] &gt;= left</code>. The answer is 2.", my: "<strong>နေရာဟောင်းသည် window ထဲ အမြဲ မရှိပါ။</strong> <code>ch</code> ကို တွေ့ဖူးတိုင်း <code>left</code> ကို <code>last[ch] + 1</code> သို့ ခုန်လျှင် <code>\"abba\"</code> တွင် 3 ရသည် — နောက်ဆုံး <code>a</code> တွင် <code>left</code> သည် 2 ဖြစ်နေပြီးသား ဖြစ်ပြီး 1 သို့ နောက်ပြန်ခုန်ခြင်းက <code>\"bba\"</code> ကို ဝင်စေသည်။ <code>last[ch] &gt;= left</code> ဖြစ်မှသာ ခုန်ပါ။ အဖြေမှာ 2။" },
      { en: "<strong>The string can be empty, and a space is a character.</strong> <code>\"\"</code> has length 0, so the answer is 0; <code>\" \"</code> is one character, so the answer is 1. Trimming or splitting the input on whitespace changes the question.", my: "<strong>string သည် ဗလာ ဖြစ်နိုင်ပြီး space သည် character တစ်လုံး ဖြစ်သည်။</strong> <code>\"\"</code> ၏ အရှည် 0 ဖြစ်သဖြင့် အဖြေ 0၊ <code>\" \"</code> သည် character တစ်လုံး ဖြစ်သဖြင့် အဖြေ 1။ input ကို trim လုပ်ခြင်း သို့မဟုတ် whitespace ဖြင့် ခွဲခြင်းက မေးခွန်းကို ပြောင်းသွားစေသည်။" },
    ],
  },
  part2Sub: { en: "Two approaches over the same string. The stage shows what each one remembers — a set rebuilt for every start, or a map of last positions that is never cleared; the panel shows the line running.", my: "string တစ်ခုတည်းပေါ်တွင် နည်းလမ်းနှစ်မျိုး။ ဘယ်ဘက်က နည်းတစ်ခုစီ မှတ်ထားသည့်အရာ — start တိုင်းအတွက် ပြန်တည်ဆောက်သော set သို့မဟုတ် ဘယ်တော့မှ မရှင်းသော နောက်ဆုံးနေရာ map — ကို ပြပြီး ညာဘက် panel က အလုပ်လုပ်နေသော code ကြောင်းကို ပြသည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the window raises", my: "window နှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why is it safe to jump <code>left</code> straight past the earlier copy?", my: "<code>left</code> ကို ပထမ copy ၏ နောက်သို့ တန်းခုန်ခြင်း ဘာကြောင့် ဘေးကင်းသလဲ။" }, a: { en: "Any window that starts at or before the earlier copy and reaches <code>right</code> holds both copies, so none of them can be the answer. The first start that can is one past the earlier copy. Moving <code>left</code> one step at a time gets to the same place, just in more steps.", my: "ပထမ copy တွင် သို့မဟုတ် ၎င်းမတိုင်မီ စပြီး <code>right</code> အထိ ရောက်သော window တိုင်းတွင် copy နှစ်ခုလုံး ပါသဖြင့် တစ်ခုမျှ အဖြေ မဖြစ်နိုင်ပါ။ ဖြစ်နိုင်သည့် ပထမ start မှာ ပထမ copy ၏ နောက်တစ်နေရာ ဖြစ်သည်။ <code>left</code> ကို တစ်လှမ်းချင်း ရွှေ့လည်း ထိုနေရာသို့ပင် ရောက်သည်၊ အဆင့် ပိုများရုံသာ။" } },
      { q: { en: "Why is the map never cleared?", my: "map ကို ဘာကြောင့် ဘယ်တော့မှ မရှင်းသလဲ။" }, a: { en: "Because an entry left of the window is harmless as long as it is recognised: <code>last[ch] &gt;= left</code> tells an entry inside the window from a stale one. Clearing the entries <code>left</code> passes would mean walking them, one at a time — the work the jump avoids.", my: "window ၏ ဘယ်ဘက်ရှိ entry ကို သိသမျှ အန္တရာယ် မရှိသောကြောင့်။ <code>last[ch] &gt;= left</code> က window အတွင်းရှိ entry နှင့် ဟောင်းနေသော entry ကို ခွဲခြားပေးသည်။ <code>left</code> ကျော်သွားသော entry များကို ရှင်းမည်ဆိုလျှင် ၎င်းတို့ကို တစ်ခုချင်း လျှောက်ရမည် — ခုန်ခြင်းက ရှောင်ပေးသည့် အလုပ် ဖြစ်သည်။" } },
      { q: { en: "If the brute force passes, why bother with the window?", my: "brute force အောင်လျှင် window ကို ဘာကြောင့် ဂရုစိုက်ရသလဲ။" }, a: { en: "It passes only because of the alphabet: a repeat-free run cannot be longer than the number of different characters, and the statement allows 95 printable ones. With a Unicode alphabet the same code is quadratic. The window is linear whatever the alphabet, and it is the pattern the harder window problems — Minimum Window Substring among them — are built on.", my: "alphabet ကြောင့်သာ အောင်သည် — ထပ်မနေသော run သည် ကွဲပြားသော character အရေအတွက်ထက် မရှည်နိုင်ပြီး မေးခွန်းက printable 95 လုံးကို ခွင့်ပြုသည်။ Unicode alphabet ဆိုလျှင် code တူတူသည် quadratic ဖြစ်သည်။ window သည် alphabet မည်သို့ပင်ဖြစ်စေ linear ဖြစ်ပြီး Minimum Window Substring အပါအဝင် ပိုခက်သော window ပုစ္ဆာများ၏ အခြေခံ ပုံစံ ဖြစ်သည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "Reading each character once", my: "character တစ်လုံးစီကို တစ်ကြိမ်သာ ဖတ်ခြင်း" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>95 characters cycled, n = 10⁵</th><th>Random printable, n = 10⁵</th></tr></thead>\n  <tbody>\n    <tr><td><b>Brute force</b><br><span class=\"sub\">grow from every start</span></td>\n        <td class=\"mono\">O(n · k)</td><td class=\"mono\">O(k)</td><td class=\"cross\">0.48 s</td><td>0.065 s</td></tr>\n    <tr><td><b>Sliding window</b><br><span class=\"sub\">last-seen map</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(k)</td><td class=\"tick\">0.007 s</td><td class=\"tick\">0.006 s</td></tr>\n  </tbody>\n</table>\n<figcaption>k is the number of different characters, at most 95 here. Measured with the Python listings on an Apple M5 Pro (Python 3.12), one run each. The cycled string is the brute force's worst case: every start runs the full 95 before it meets a repeat.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>character 95 လုံး လှည့်ပတ်၊ n = 10⁵</th><th>ကျပန်း printable၊ n = 10⁵</th></tr></thead>\n  <tbody>\n    <tr><td><b>Brute force</b><br><span class=\"sub\">start တိုင်းမှ ချဲ့</span></td>\n        <td class=\"mono\">O(n · k)</td><td class=\"mono\">O(k)</td><td class=\"cross\">0.48 s</td><td>0.065 s</td></tr>\n    <tr><td><b>Sliding window</b><br><span class=\"sub\">last-seen map</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(k)</td><td class=\"tick\">0.007 s</td><td class=\"tick\">0.006 s</td></tr>\n  </tbody>\n</table>\n<figcaption>k သည် ကွဲပြားသော character အရေအတွက် ဖြစ်ပြီး ဤနေရာတွင် 95 အထိ။ Apple M5 Pro (Python 3.12) ပေါ်တွင် Python listing များဖြင့် တစ်ကြိမ်စီ တိုင်းထားသည်။ လှည့်ပတ် string သည် brute force ၏ အဆိုးဆုံး case — start တိုင်းက ထပ်ခြင်း မတွေ့မီ 95 လုံး အပြည့် run ရသည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission, and every one was run against the same 20,015 cases, up to n = 5 × 10⁴.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး အားလုံးကို n = 5 × 10⁴ အထိ case 20,015 ခု တူတူဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>s</code> above — in quotes, up to 12 characters, spaces allowed — and both walkthroughs rebuild against your string.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>s</code> ကို ပြင်လိုက်လျှင် (quote ထဲတွင်၊ character 12 လုံးအထိ၊ space ပါနိုင်သည်) walkthrough နှစ်ခုစလုံး သင့် string ဖြင့် ပြန်တည်ဆောက်မည်။" },
};
