/* The prose of the Minimum Window Substring page: everything the reader sees
 * that is not interactive. Rendered by src/pages/leetcode/[slug].astro through
 * the Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Minimum Window Substring',
  summary: 'Grow one window on the right until it covers t, then shrink it on the left for as long as it still does. One table of what is still owed — negative for spares — and one counter of what is missing make it O(m + n).',
  eyebrow: 'LeetCode 76 &nbsp;·&nbsp; Hard',
  lede: { en: "Find the shortest stretch of s that contains every letter of t, duplicates included. Starting a fresh window at every position repeats the same counting over and over. A single window can do it all: push its right end until nothing is missing, then pull its left end in while nothing goes missing, noting each window that covers t. Both ends only ever move right.", my: "t ၏ စာလုံးတိုင်းကို ထပ်နေသည်များ အပါအဝင် ပါသော s ၏ အတိုဆုံး အပိုင်းကို ရှာပါ။ နေရာတိုင်းတွင် window အသစ် စခြင်းသည် တူညီသော ရေတွက်မှုကို ထပ်ခါထပ်ခါ လုပ်သည်။ window တစ်ခုတည်းက အားလုံး လုပ်နိုင်သည် — ဘာမှ မလိုတော့သည်အထိ ညာဘက်အစွန်ကို တွန်း၊ ပြီးမှ ဘာမှ မလိုလာသမျှ ဘယ်ဘက်အစွန်ကို ဆွဲသွင်းကာ t ကို ဖုံးသော window တိုင်းကို မှတ်သည်။ အစွန်နှစ်ဖက်လုံး ညာဘက်သို့သာ ရွေ့သည်။" },
  links: [{ id: 76, title: 'Minimum Window Substring', slug: 'minimum-window-substring', difficulty: 'Hard' }],
  constraints: { en: "<span><b>m</b> == s.length</span><span><b>n</b> == t.length</span><span>1 &le; m, n &le; 10<sup>5</sup></span><span>upper- and lowercase English letters</span>", my: "<span><b>m</b> == s.length</span><span><b>n</b> == t.length</span><span>1 &le; m, n &le; 10<sup>5</sup></span><span>အင်္ဂလိပ် စာလုံး အကြီး/အသေး</span>" },
  part1Sub: { en: "Read the statement, then drag a window over s and see whether it covers t.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် s ပေါ်တွင် window ကို ဆွဲပြီး t ကို ဖုံးသလား ကြည့်ပါ။" },
  widgetTitle: { en: "Drag a window, check it covers t", my: "window ဆွဲပါ — t ကို ဖုံးသလား စစ်ပါ" },
  traps: {
    summary: { en: "Three ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ သုံးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>Duplicates count.</strong> Treating t as a set of letters needs each letter once: example 3 returns <code>\"a\"</code> although t = \"aa\" needs two, and the answer is <code>\"\"</code>. Count letters, don't just note them.", my: "<strong>ထပ်နေသည်ကို ရေတွက်သည်။</strong> t ကို စာလုံး set အဖြစ် သဘောထားလျှင် စာလုံးတစ်ခုစီကို တစ်ကြိမ်သာ လိုသည် — t = \"aa\" က နှစ်လုံး လိုသော်လည်း ဥပမာ 3 သည် <code>\"a\"</code> ပြန်ပေးပြီး အဖြေမှာ <code>\"\"</code>။ စာလုံးများကို မှတ်ရုံမဟုတ်ဘဲ ရေတွက်ပါ။" },
      { en: "<strong>Shrink with <code>while</code>, not <code>if</code>.</strong> Dropping only one letter from the left each time the window covers t leaves it wider than it has to be: example 1 returns <code>\"ADOBEC\"</code> instead of <code>\"BANC\"</code>.", my: "<strong><code>if</code> မဟုတ်ဘဲ <code>while</code> ဖြင့် ချုံ့ပါ။</strong> window က t ကို ဖုံးတိုင်း ဘယ်ဘက်မှ စာလုံးတစ်လုံးသာ ဖယ်လျှင် လိုသည်ထက် ကျယ်နေမည် — ဥပမာ 1 သည် <code>\"BANC\"</code> အစား <code>\"ADOBEC\"</code> ပြန်ပေးသည်။" },
      { en: "<strong>Case matters, and s can be 10⁵ long.</strong> 'a' and 'A' are different letters, so size the table for both cases (the listings use 128 slots). And growing a window from every start is quadratic: 4.05 s for 10⁴ letters in Python here, and the constraint is ten times that.", my: "<strong>အကြီး/အသေး အရေးကြီးပြီး s သည် 10⁵ ရှည်နိုင်သည်။</strong> 'a' နှင့် 'A' သည် မတူသော စာလုံးများ ဖြစ်သဖြင့် table ကို နှစ်မျိုးလုံးအတွက် ထားပါ (listing များသည် slot 128 သုံးသည်)။ အစတိုင်းမှ window ကြီးထွားစေခြင်းသည် quadratic — ဤနေရာတွင် Python ဖြင့် စာလုံး 10⁴ အတွက် 4.05 s ကြာပြီး ကန့်သတ်ချက်က ၎င်း၏ ဆယ်ဆ ဖြစ်သည်။" },
    ],
  },
  part2Sub: { en: "Two approaches. The strip is s with the current window lit; the stage is the table the approach keeps for t's letters, with how many are still missing and the best window so far.", my: "နည်းလမ်းနှစ်မျိုး။ strip သည် လက်ရှိ window ကို လင်းပြထားသော s ဖြစ်သည်။ stage သည် နည်းလမ်းက t ၏ စာလုံးများအတွက် ထိန်းသော table ဖြစ်ပြီး မည်မျှ လိုနေသေးသလဲ နှင့် ယခုထိ အကောင်းဆုံး window ပါသည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the window raises", my: "window နှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why one counter, missing, instead of checking the whole table?", my: "table တစ်ခုလုံးကို စစ်မည့်အစား counter တစ်ခု missing ကို ဘာကြောင့် သုံးသလဲ။" }, a: { en: "Checking every letter's count each step would cost up to 52 per move. <code>missing</code> is the total still owed, and it only changes when a letter crosses the line between owed and spare: taking one that was owed lowers it, giving back one that is now owed raises it. So \"does the window cover t?\" is <code>missing == 0</code>, O(1).", my: "အဆင့်တိုင်း စာလုံးတိုင်း၏ အရေအတွက်ကို စစ်လျှင် ရွေ့ခြင်းတစ်ခုလျှင် 52 အထိ ကုန်ကျမည်။ <code>missing</code> သည် ပေးရန်ကျန် စုစုပေါင်း ဖြစ်ပြီး စာလုံးတစ်ခုသည် ပေးရန်ကျန်နှင့် ပိုကြားရှိ မျဉ်းကို ဖြတ်သည့်အခါမှသာ ပြောင်းသည် — ပေးရန်ကျန်ကို ယူလျှင် ကျသည်၊ ယခု ပေးရန်ကျန်ဖြစ်လာသည်ကို ပြန်ပေးလျှင် တက်သည်။ ထို့ကြောင့် \"window က t ကို ဖုံးသလား\" သည် <code>missing == 0</code>၊ O(1)။" } },
      { q: { en: "Why is the answer found while shrinking, not while growing?", my: "အဖြေကို ကြီးထွားနေစဉ် မဟုတ်ဘဲ ချုံ့နေစဉ် ဘာကြောင့် တွေ့သလဲ။" }, a: { en: "The moment the right end first makes the window cover t, its left end is usually still loose. Shrinking finds, for this right end, the shortest window that covers. The answer is the shortest window for its own right end, so recording the shortest one for every right end is sure to catch it.", my: "ညာဘက်အစွန်က window ကို t ကို ပထမဆုံး ဖုံးစေသည့် ခဏတွင် ဘယ်ဘက်အစွန်သည် များသောအားဖြင့် ချောင်နေဆဲ။ ချုံ့ခြင်းက ဤညာဘက်အစွန်အတွက် ဖုံးသော အတိုဆုံး window ကို ရှာသည်။ အဖြေသည် ၎င်း၏ ကိုယ်ပိုင် ညာဘက်အစွန်အတွက် အတိုဆုံး window ဖြစ်သဖြင့် ညာဘက်အစွန်တိုင်းအတွက် အတိုဆုံးကို မှတ်ခြင်းက ၎င်းကို သေချာ ဖမ်းမိသည်။" } },
      { q: { en: "What if two shortest windows tie?", my: "အတိုဆုံး window နှစ်ခု တူနေလျှင်။" }, a: { en: "The statement promises tests where it cannot happen. Random tests do not, so every listing here keeps the leftmost — it only replaces the best on a strictly shorter window — and the verifier's oracle does the same. Change <code>&lt;</code> to <code>&lt;=</code> and you get the rightmost instead.", my: "မေးခွန်းက ထိုသို့ မဖြစ်နိုင်သော test များကို ကတိပြုသည်။ ကျပန်း test များ မပြုသဖြင့် ဤနေရာရှိ listing တိုင်းက ဘယ်ဘက်အစွန်ဆုံးကို ထိန်းသည် — တင်းကြပ်စွာ ပိုတိုသော window တွင်သာ best ကို အစားထိုးသည် — verifier ၏ oracle လည်း ထိုနည်းတူ။ <code>&lt;</code> ကို <code>&lt;=</code> ပြောင်းလျှင် ညာဘက်အစွန်ဆုံးကို ရမည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "Two pointers that never go back", my: "နောက်ပြန် မလှည့်သော pointer နှစ်ခု" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>s = 9,999 × a + b, t = ab</th></tr></thead>\n  <tbody>\n    <tr><td><b>Grow from every start</b></td>\n        <td class=\"mono\">O(m²)</td><td class=\"mono\">O(1)</td><td class=\"cross\">4.05 s</td></tr>\n    <tr><td><b>Grow and shrink</b><br><span class=\"sub\">sliding window</span></td>\n        <td class=\"mono\">O(m + n)</td><td class=\"mono\">O(1)</td><td class=\"tick\">0.01 s</td></tr>\n  </tbody>\n</table>\n<figcaption>Measured here: the Python listings on an Apple M5 Pro, whole process, best of three. The only b is at the end, so every start grows all the way to it; the extra space is a table of the letters, a fixed 52 (or 128) entries.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>s = a × 9,999 + b, t = ab</th></tr></thead>\n  <tbody>\n    <tr><td><b>Grow from every start</b></td>\n        <td class=\"mono\">O(m²)</td><td class=\"mono\">O(1)</td><td class=\"cross\">4.05 s</td></tr>\n    <tr><td><b>Grow and shrink</b><br><span class=\"sub\">sliding window</span></td>\n        <td class=\"mono\">O(m + n)</td><td class=\"mono\">O(1)</td><td class=\"tick\">0.01 s</td></tr>\n  </tbody>\n</table>\n<figcaption>ဤနေရာတွင် တိုင်းတာထားသည် — Apple M5 Pro ပေါ်ရှိ Python listing များ၊ process တစ်ခုလုံး၊ သုံးကြိမ်အနက် အကောင်းဆုံး။ b တစ်လုံးတည်းသည် အဆုံးတွင် ရှိသဖြင့် အစတိုင်းက ၎င်းအထိ ကြီးထွားရသည် — အပို memory သည် စာလုံး table၊ entry 52 (သို့မဟုတ် 128) ပုံသေ။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission. The sliding window ran against 20,015 pairs up to 10⁵ letters; growing from every start against the 20,010 below that.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်သည်။ sliding window ကို စာလုံး 10⁵ အထိ pair 20,015 ခုဖြင့်၊ အစတိုင်းမှ ကြီးထွားခြင်းကို ထိုအောက် 20,010 ခုဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>s</code> (up to 16 letters) and <code>t</code> (up to 6) above, and both walkthroughs rebuild against them.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>s</code> (စာလုံး 16 လုံးအထိ) နှင့် <code>t</code> (6 လုံးအထိ) ကို ပြင်လိုက်လျှင် walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
