/* The prose of the Maximum Depth of Binary Tree page: everything the reader sees
 * that is not interactive. Rendered by src/pages/leetcode/[slug].astro through
 * the Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Maximum Depth of Binary Tree',
  summary: 'Ask every node how deep the tree under it goes, or count the levels from the top. The recursion needs a stack as deep as the tree; the constraints make that matter.',
  eyebrow: 'LeetCode 104 &nbsp;·&nbsp; Easy',
  lede: { en: "Count the nodes on the longest path from the root down to a leaf. The recursion answers bottom-up — a node is one deeper than its deeper child — while the loop simply counts levels until there are none left.", my: "root မှ leaf တစ်ခုအထိ အရှည်ဆုံး လမ်းကြောင်းပေါ်ရှိ node များကို ရေတွက်ပါ။ recursion က အောက်မှအပေါ်သို့ ဖြေသည် — node တစ်ခုသည် ၎င်း၏ ပိုနက်သော ကလေးထက် တစ်ဆင့် ပိုနက်သည် — loop ကမူ အဆင့်များ ကုန်သည်အထိ ရိုးရိုး ရေတွက်သည်။" },
  links: [{ id: 104, title: 'Maximum Depth of Binary Tree', slug: 'maximum-depth-of-binary-tree', difficulty: 'Easy' }],
  constraints: { en: "<span><b>n</b> the number of nodes in the tree is in the range [0, 10&#8308;]</span><span>&minus;100 &le; Node.val &le; 100</span>", my: "<span><b>n</b> tree ထဲရှိ node အရေအတွက်သည် [0, 10&#8308;] အတွင်း</span><span>&minus;100 &le; Node.val &le; 100</span>" },
  part1Sub: { en: "Read the statement, then walk each root-to-leaf path and count what the definition counts.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် root မှ leaf အထိ လမ်းကြောင်းတစ်ခုစီကို လျှောက်ပြီး အဓိပ္ပာယ်က ရေတွက်ခိုင်းသည့်အရာကို ရေတွက်ပါ။" },
  widgetTitle: { en: "Drag through the leaves, count the nodes", my: "leaf များကို ဆွဲကြည့်ပါ — node များကို ရေတွက်ပါ" },
  traps: {
    summary: { en: "Four ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ လေးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>Depth counts nodes, not edges.</strong> A single node has depth 1 and an empty tree 0. \"Height\" elsewhere often counts edges, which gives 2 on example 1 instead of 3 — the base case has to return 0 for null, not −1.", my: "<strong>Depth သည် edge များ မဟုတ်ဘဲ node များကို ရေတွက်သည်။</strong> node တစ်ခုတည်းရှိ tree ၏ depth မှာ 1 ဖြစ်ပြီး ဗလာ tree မှာ 0 ဖြစ်သည်။ အခြားနေရာများရှိ \"height\" သည် edge များကို ရေတွက်လေ့ရှိပြီး ဥပမာ 1 တွင် 3 အစား 2 ရသည် — base case သည် null အတွက် −1 မဟုတ်ဘဲ 0 ပြန်ပေးရမည်။" },
      { en: "<strong>The constraints allow a 10<sup>4</sup>-node chain,</strong> which makes the recursion 10<sup>4</sup> calls deep. Python stops at 1,000 by default (<code>RecursionError</code>); measured here, Ruby 3.1's default stack overflowed past 8,733 nodes and Node 24's, run cold, past 7,774. The BFS version has no stack to run out of.", my: "<strong>ကန့်သတ်ချက်က node 10<sup>4</sup> ကွင်းဆက်ကို ခွင့်ပြုသည်</strong> — ထိုအခါ recursion သည် call 10<sup>4</sup> ဆင့် နက်သည်။ Python သည် default အားဖြင့် 1,000 တွင် ရပ်သည် (<code>RecursionError</code>)။ ဤနေရာတွင် တိုင်းတာရာ Ruby 3.1 ၏ default stack သည် node 8,733 ကျော်လျှင်၊ Node 24 ၏ stack သည် cold run တွင် 7,774 ကျော်လျှင် overflow ဖြစ်ခဲ့သည်။ BFS ပုံစံတွင် ကုန်သွားစရာ stack မရှိပါ။" },
      { en: "<strong><code>max</code>, not <code>min</code>, and not a sum.</strong> <code>1 + min(left, right)</code> returns 2 on example 1 — that is a different problem, Minimum Depth. <code>1 + left + right</code> returns 5: it counts every node in the tree.", my: "<strong><code>min</code> မဟုတ်ဘဲ <code>max</code>၊ ပေါင်းခြင်းလည်း မဟုတ်ပါ။</strong> <code>1 + min(left, right)</code> သည် ဥပမာ 1 တွင် 2 ကို ပြန်ပေးသည် — ၎င်းသည် Minimum Depth ဟူသော အခြားပြဿနာ ဖြစ်သည်။ <code>1 + left + right</code> သည် 5 ကို ပြန်ပေးသည် — tree ထဲရှိ node တိုင်းကို ရေတွက်သည်။" },
      { en: "<strong>In BFS, count levels, not nodes.</strong> Adding 1 each time a node leaves the queue counts nodes — 5 on example 1. Process a whole level per count: replace the level with its children, as here, or read the queue's length before the inner loop.", my: "<strong>BFS တွင် node များ မဟုတ်ဘဲ အဆင့်များကို ရေတွက်ပါ။</strong> node တစ်ခု queue မှ ထွက်တိုင်း 1 ပေါင်းလျှင် node များကို ရေတွက်မိသည် — ဥပမာ 1 တွင် 5။ ရေတွက်တစ်ကြိမ်လျှင် အဆင့်တစ်ခုလုံးကို လုပ်ပါ — ဤနေရာကဲ့သို့ အဆင့်ကို ၎င်း၏ ကလေးများဖြင့် အစားထိုးပါ၊ သို့မဟုတ် အတွင်း loop မစမီ queue ၏ အရှည်ကို ဖတ်ထားပါ။" },
    ],
  },
  part2Sub: { en: "Two approaches over the same tree. The stage shows the tree and what each approach is holding; the panel shows the line running.", my: "tree တစ်ခုတည်းပေါ်တွင် နည်းလမ်းနှစ်မျိုး။ ဘယ်ဘက်က tree နှင့် နည်းတစ်ခုစီ ကိုင်ထားသည့်အရာကို ပြပြီး ညာဘက် panel က အလုပ်လုပ်နေသော code ကြောင်းကို ပြသည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the depth raises", my: "depth နှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why does the recursion get its answers from the bottom up?", my: "recursion က အဖြေများကို ဘာကြောင့် အောက်မှ အပေါ်သို့ ရသလဲ။" }, a: { en: "Because a node cannot know its depth until both children have told it theirs. The calls go down first, carrying nothing; the numbers only start when a call reaches null and returns 0. Each node then waits on the stack, adds one to the larger of its two answers, and hands that up — in the walkthrough, a node wears its number only once its whole subtree is finished.", my: "node တစ်ခုသည် ကလေး နှစ်ခုလုံးက ၎င်းတို့၏ depth ကို မပြောမချင်း ၎င်း၏ depth ကို မသိနိုင်သောကြောင့် ဖြစ်သည်။ call များက ဘာမျှ မသယ်ဘဲ အရင် ဆင်းသွားသည် — call တစ်ခုက null သို့ ရောက်ပြီး 0 ပြန်ပေးမှသာ ကိန်းများ စတင်သည်။ ထို့နောက် node တစ်ခုစီက stack ပေါ်တွင် စောင့်၊ အဖြေနှစ်ခုအနက် ပိုကြီးသည့်တစ်ခုကို တစ်ပေါင်းပြီး အပေါ်သို့ ပေးသည် — walkthrough တွင် node တစ်ခုသည် ၎င်း၏ subtree တစ်ခုလုံး ပြီးမှသာ ၎င်း၏ ကိန်းကို ဝတ်ဆင်သည်။" } },
      { q: { en: "Which uses less memory, the stack or the level?", my: "stack နှင့် level — ဘယ်ဟာက memory နည်းနည်း သုံးသလဲ။" }, a: { en: "It depends on the shape. The recursion holds the current path, so it costs the tree's height: 15 frames for a balanced 10<sup>4</sup>-node tree, 10,001 for a chain. The loop holds a level plus the one it is building, so it costs the width: up to 6,144 nodes for the balanced tree, 2 for the chain. Deep and narrow favours the loop — and \"deep\" is exactly where recursion can crash.", my: "ပုံသဏ္ဌာန်ပေါ် မူတည်သည်။ recursion သည် လက်ရှိ လမ်းကြောင်းကို ကိုင်ထားသဖြင့် tree ၏ အမြင့် ကုန်သည် — ညီမျှသော node 10<sup>4</sup> tree အတွက် frame 15၊ ကွင်းဆက်အတွက် 10,001။ loop သည် အဆင့်တစ်ဆင့်နှင့် တည်ဆောက်နေသော နောက်တစ်ဆင့်ကို ကိုင်ထားသဖြင့် အကျယ် ကုန်သည် — ညီမျှသော tree အတွက် node 6,144 အထိ၊ ကွင်းဆက်အတွက် 2။ နက်ပြီး ကျဉ်းလျှင် loop သာသည် — \"နက်\" သည် recursion ပျက်နိုင်သည့်နေရာ အတိအကျ ဖြစ်သည်။" } },
      { q: { en: "Where does \"one more than the deeper child\" show up again?", my: "\"ပိုနက်သော ကလေးထက် တစ်ပို\" ဆိုသည်မှာ နောက်ထပ် ဘယ်မှာ တွေ့ရမလဲ။" }, a: { en: "It is the building block of a family. <strong>Balanced Binary Tree</strong> compares the two children's depths at every node. <strong>Diameter of Binary Tree</strong> adds them instead, because the longest path may bend through a node. <strong>Minimum Depth</strong> takes the smaller one — with the catch that a missing child is not a leaf, so a node with one child cannot use the empty side's 0.", my: "၎င်းသည် ပြဿနာ မိသားစုတစ်ခု၏ အခြေခံ အုတ်ခဲ ဖြစ်သည်။ <strong>Balanced Binary Tree</strong> သည် node တိုင်းတွင် ကလေးနှစ်ခု၏ depth ကို နှိုင်းယှဉ်သည်။ <strong>Diameter of Binary Tree</strong> သည် အရှည်ဆုံး လမ်းကြောင်းက node တစ်ခုကို ဖြတ်၍ ကွေ့နိုင်သဖြင့် ၎င်းတို့ကို ပေါင်းသည်။ <strong>Minimum Depth</strong> သည် ငယ်သည့်တစ်ခုကို ယူသည် — ပျောက်နေသော ကလေးသည် leaf မဟုတ်သဖြင့် ကလေး တစ်ခုသာရှိသော node သည် ဗလာဘက်၏ 0 ကို မသုံးနိုင်ပါ။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "The same count, a different memory bill", my: "ရေတွက်ပုံ အတူတူ၊ memory ကုန်ကျမှု မတူ" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>Balanced, 10⁴ nodes</th><th>A 10⁴-node chain</th></tr></thead>\n  <tbody>\n    <tr><td><b>Recursive DFS</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">the call stack</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(h)</td><td class=\"tick\">15 frames</td><td class=\"cross\">10,001 frames</td></tr>\n    <tr><td><b>Level-by-level BFS</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">one level + the next</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(w)</td><td class=\"cross\">up to 6,144 nodes</td><td class=\"tick\">2 nodes</td></tr>\n  </tbody>\n</table>\n<figcaption>Counted by simulating both on a complete 10⁴-node tree and a 10⁴-node chain, not timed; the stack counts the final call on null. The frame count is not academic here: at 10,001 frames Python needs its recursion limit raised, and Ruby 3.1's and Node 24's default stacks give out first.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>ညီမျှ၊ node 10⁴</th><th>node 10⁴ ကွင်းဆက်</th></tr></thead>\n  <tbody>\n    <tr><td><b>Recursive DFS</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">call stack</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(h)</td><td class=\"tick\">frame 15</td><td class=\"cross\">frame 10,001</td></tr>\n    <tr><td><b>Level-by-level BFS</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">အဆင့်တစ်ဆင့် + နောက်တစ်ဆင့်</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(w)</td><td class=\"cross\">node 6,144 အထိ</td><td class=\"tick\">node 2</td></tr>\n  </tbody>\n</table>\n<figcaption>ပြည့်စုံသော node 10⁴ tree နှင့် node 10⁴ ကွင်းဆက်ပေါ်တွင် နှစ်ခုလုံးကို simulate လုပ်၍ ရေတွက်ထားခြင်းဖြစ်ပြီး အချိန် မတိုင်းထားပါ — stack တွင် null ပေါ်ရှိ နောက်ဆုံး call ပါ ရေတွက်ထားသည်။ frame အရေအတွက်သည် ဤနေရာတွင် သီအိုရီသက်သက် မဟုတ်ပါ — frame 10,001 တွင် Python ၏ recursion limit ကို မြှင့်ရပြီး Ruby 3.1 နှင့် Node 24 ၏ default stack များက အရင် ကုန်သွားသည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission and was run against the same 20,010 cases; the badges and notes say where the recursion needs more stack.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး case 20,010 ခု တူတူဖြင့် run ထားသည် — recursion တွင် stack ပိုလိုသည့်နေရာကို badge နှင့် မှတ်ချက်များက ဖော်ပြသည်။" },
  footer: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>root</code> above — level order, <code>null</code> for a missing child, up to 15 nodes — and both walkthroughs rebuild against your tree.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>root</code> ကို ပြင်လိုက်လျှင် (level order၊ ကလေး မရှိလျှင် <code>null</code>၊ node 15 ခုအထိ) walkthrough နှစ်ခုစလုံး သင့် tree ဖြင့် ပြန်တည်ဆောက်မည်။" },
};
