/* The prose of the Maximum Subarray page: everything the reader sees that is
 * not interactive. Rendered by src/pages/leetcode/[slug].astro through the
 * Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Maximum Subarray',
  summary: "Sum every subarray, or carry one number — the best sum of a subarray ending here — and start over whenever the run behind it is negative. That is Kadane's algorithm.",
  eyebrow: 'LeetCode 53 &nbsp;·&nbsp; Medium',
  lede: { en: "The largest sum of one contiguous run. Summing every subarray is quadratic. Kadane's algorithm makes one decision per index: add this value to the best run ending just before it, or start a new run here — and a run whose sum is negative is never worth keeping.", my: "ဆက်တိုက် run တစ်ခု၏ အကြီးဆုံး ပေါင်းလဒ်။ subarray တိုင်းကို ပေါင်းခြင်းသည် quadratic ဖြစ်သည်။ Kadane's algorithm သည် index တစ်ခုလျှင် ဆုံးဖြတ်ချက် တစ်ခုသာ ချသည် — ဤ value ကို ၎င်းမတိုင်မီ ဆုံးသော အကောင်းဆုံး run ထဲ ပေါင်းမလား၊ ဤနေရာမှ run အသစ် စမလား — ပေါင်းလဒ် အနုတ်ဖြစ်သော run ကို ဘယ်တော့မှ ထားရန် မတန်ပါ။" },
  links: [{ id: 53, title: 'Maximum Subarray', slug: 'maximum-subarray', difficulty: 'Medium' }],
  constraints: { en: "<span><b>n</b> 1 &le; nums.length &le; 10&#8309;</span><span>&minus;10&#8308; &le; nums[i] &le; 10&#8308;</span><span>the subarray is non-empty</span>", my: "<span><b>n</b> 1 &le; nums.length &le; 10&#8309;</span><span>&minus;10&#8308; &le; nums[i] &le; 10&#8308;</span><span>subarray သည် ဗလာ မဖြစ်ရ</span>" },
  part1Sub: { en: "Read the statement, then drag the two ends of a run and see what a negative start costs it.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် run တစ်ခု၏ အစွန်းနှစ်ဘက်ကို ဆွဲပြီး အနုတ် အစက ၎င်းကို မည်မျှ ကုန်ကျစေသလဲ ကြည့်ပါ။" },
  widgetTitle: { en: "Drag the ends, drop the negative start", my: "အစွန်းများကို ဆွဲပါ — အနုတ် အစကို ပယ်ပါ" },
  traps: {
    summary: { en: "Three ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ သုံးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>The subarray is non-empty, so the answer can be negative.</strong> The common shortcut — <code>best = cur = 0</code>, reset <code>cur</code> to 0 when it drops below — passes example 1 but returns 0 on <code>[-3,-1,-2]</code>, as if an empty subarray were allowed. The answer is −1. Start both at <code>nums[0]</code>.", my: "<strong>subarray သည် ဗလာ မဖြစ်ရသဖြင့် အဖြေသည် အနုတ် ဖြစ်နိုင်သည်။</strong> အသုံးများသော shortcut — <code>best = cur = 0</code>၊ <code>cur</code> 0 အောက် ကျလျှင် 0 ပြန်ထား — သည် ဥပမာ 1 ကို အောင်သော်လည်း <code>[-3,-1,-2]</code> တွင် subarray ဗလာကို ခွင့်ပြုသကဲ့သို့ 0 ကို ပြန်ပေးသည်။ အဖြေမှာ −1။ နှစ်ခုလုံးကို <code>nums[0]</code> ဖြင့် စပါ။" },
      { en: "<strong>Subarray means contiguous.</strong> Adding up every positive value in example 1 gives 12; the positives are not next to each other, and the answer is 6.", my: "<strong>subarray ဆိုသည်မှာ ဆက်တိုက် ဖြစ်ရမည်။</strong> ဥပမာ 1 ရှိ အပေါင်း value အားလုံးကို ပေါင်းလျှင် 12 ရသည် — အပေါင်းများ ကပ်လျက် မဟုတ်ပါ၊ အဖြေမှာ 6။" },
      { en: "<strong>n reaches 10⁵.</strong> Every subarray is n(n + 1)/2 ≈ 5 × 10⁹ at the limit (computed). The sum itself is safe: at most 10⁵ × 10⁴ = 10⁹, inside 32 bits.", my: "<strong>n သည် 10⁵ အထိ ရှိသည်။</strong> subarray တိုင်းဆိုလျှင် ကန့်သတ်ချက်တွင် n(n + 1)/2 ≈ 5 × 10⁹ (တွက်ထားခြင်း)။ ပေါင်းလဒ်ကိုယ်တိုင်မှာ ဘေးကင်းသည် — အများဆုံး 10⁵ × 10⁴ = 10⁹၊ 32 bit အတွင်း။" },
    ],
  },
  part2Sub: { en: "Two approaches over the same array. The stage shows what each one carries — the running sum of one start, or the best sum ending here and the best so far; the panel shows the line running.", my: "array တစ်ခုတည်းပေါ်တွင် နည်းလမ်းနှစ်မျိုး။ ဘယ်ဘက်က နည်းတစ်ခုစီ သယ်ဆောင်သည့်အရာ — start တစ်ခု၏ running sum သို့မဟုတ် ဤနေရာတွင် ဆုံးသော အကောင်းဆုံးနှင့် ယခုထိ အကောင်းဆုံး — ကို ပြပြီး ညာဘက် panel က အလုပ်လုပ်နေသော code ကြောင်းကို ပြသည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions Kadane's algorithm raises", my: "Kadane's algorithm နှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why is dropping a negative run always safe?", my: "အနုတ် run ကို ပယ်ခြင်း ဘာကြောင့် အမြဲ ဘေးကင်းသလဲ။" }, a: { en: "Any subarray that ends at i and reaches back past the restart point is some negative run plus a subarray that starts at the restart. Removing the negative part makes it larger. So the best subarray ending at i never needs the part before the restart, and <code>cur</code> loses nothing by forgetting it.", my: "i တွင် ဆုံးပြီး ပြန်စသည့်နေရာ၏ နောက်ဘက်သို့ ကျော်ရောက်သော subarray တိုင်းသည် အနုတ် run တစ်ခု + ပြန်စသည့်နေရာမှ စသော subarray ဖြစ်သည်။ အနုတ်အပိုင်းကို ဖယ်လျှင် ပိုကြီးလာသည်။ ထို့ကြောင့် i တွင် ဆုံးသော အကောင်းဆုံး subarray သည် ပြန်စသည့်နေရာ မတိုင်မီ အပိုင်းကို ဘယ်တော့မှ မလိုဘဲ <code>cur</code> သည် ၎င်းကို မေ့လိုက်၍ ဘာမျှ မဆုံးရှုံးပါ။" } },
      { q: { en: "Why track <code>best</code> separately from <code>cur</code>?", my: "<code>best</code> ကို <code>cur</code> နှင့် ဘာကြောင့် သီးခြား ထိန်းရသလဲ။" }, a: { en: "Because <code>cur</code> is the best run ending <em>here</em>, and the answer may end earlier. In example 1, <code>cur</code> peaks at 6 at index 6, then the −5 takes it to 1 and the final 4 to 5. <code>best</code> remembers the 6.", my: "<code>cur</code> သည် <em>ဤနေရာ</em>တွင် ဆုံးသော အကောင်းဆုံး run ဖြစ်ပြီး အဖြေသည် စောစောက ဆုံးနိုင်သောကြောင့်။ ဥပမာ 1 တွင် <code>cur</code> သည် index 6 တွင် 6 အထိ ရောက်ပြီး −5 က 1 သို့၊ နောက်ဆုံး 4 က 5 သို့ ပြောင်းစေသည်။ <code>best</code> က 6 ကို မှတ်ထားသည်။" } },
      { q: { en: "What is the divide-and-conquer answer the follow-up asks for?", my: "follow-up တောင်းသော divide and conquer အဖြေသည် ဘာလဲ။" }, a: { en: "Split the array in half. The best subarray is entirely in the left half, entirely in the right half, or crosses the middle — and the crossing one is the best suffix of the left plus the best prefix of the right, found in one linear scan each. That is O(n log n): slower than Kadane's, and not on this page's listings. It is worth knowing because the same split, with each half returning four numbers, becomes a segment tree that answers the question for any range.", my: "array ကို တစ်ဝက်စီ ခွဲသည်။ အကောင်းဆုံး subarray သည် ဘယ်တစ်ဝက်ထဲ လုံးလုံး၊ ညာတစ်ဝက်ထဲ လုံးလုံး သို့မဟုတ် အလယ်ကို ဖြတ်သည် — ဖြတ်သည့်တစ်ခုမှာ ဘယ်ဘက်၏ အကောင်းဆုံး suffix + ညာဘက်၏ အကောင်းဆုံး prefix ဖြစ်ပြီး တစ်ခုစီကို linear scan တစ်ကြိမ်ဖြင့် ရှာသည်။ ၎င်းသည် O(n log n) — Kadane's ထက် နှေးပြီး ဤစာမျက်နှာ၏ listing များတွင် မပါပါ။ တစ်ဝက်စီက ကိန်းလေးလုံး ပြန်ပေးသော ထိုခွဲခြင်းသည် မည်သည့် range အတွက်မဆို မေးခွန်းကို ဖြေနိုင်သော segment tree ဖြစ်လာသဖြင့် သိထားသင့်သည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "One decision per index", my: "index တစ်ခုလျှင် ဆုံးဖြတ်ချက် တစ်ခု" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>At n = 10⁵ (the constraint)</th></tr></thead>\n  <tbody>\n    <tr><td><b>Brute force</b><br><span class=\"sub\">every start, running sum</span></td>\n        <td class=\"mono\">O(n²)</td><td class=\"mono\">O(1)</td><td class=\"cross\">≈ 5 × 10⁹ additions</td></tr>\n    <tr><td><b>Kadane's algorithm</b><br><span class=\"sub\">carry on or start over</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(1)</td><td class=\"tick\">10⁵ decisions</td></tr>\n  </tbody>\n</table>\n<figcaption>Counts are computed from the constraint, not measured. Divide and conquer, from the follow-up, sits between them at O(n log n).</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>n = 10⁵ (ကန့်သတ်ချက်) တွင်</th></tr></thead>\n  <tbody>\n    <tr><td><b>Brute force</b><br><span class=\"sub\">start တိုင်း၊ running sum</span></td>\n        <td class=\"mono\">O(n²)</td><td class=\"mono\">O(1)</td><td class=\"cross\">ပေါင်းခြင်း ≈ 5 × 10⁹</td></tr>\n    <tr><td><b>Kadane's algorithm</b><br><span class=\"sub\">ဆက် သို့မဟုတ် ပြန်စ</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(1)</td><td class=\"tick\">ဆုံးဖြတ်ချက် 10⁵</td></tr>\n  </tbody>\n</table>\n<figcaption>ဤအရေအတွက်များကို ကန့်သတ်ချက်မှ တွက်ထားခြင်းဖြစ်ပြီး တိုင်းတာထားခြင်း မဟုတ်ပါ။ follow-up ပါ divide and conquer သည် ၎င်းတို့ကြားတွင် O(n log n) ဖြစ်သည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission. Kadane's ran against 20,013 cases up to n = 10⁵; the brute force against the 20,008 small enough for it.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်သည်။ Kadane's ကို n = 10⁵ အထိ case 20,013 ခုဖြင့်၊ brute force ကို ၎င်းအတွက် သေးလောက်သော case 20,008 ခုဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>nums</code> above — up to 12 values — and both walkthroughs rebuild against your array.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>nums</code> ကို ပြင်လိုက်လျှင် (value 12 ခုအထိ) walkthrough နှစ်ခုစလုံး သင့် array ဖြင့် ပြန်တည်ဆောက်မည်။" },
};
