/* The prose of the Search in Rotated Sorted Array page: everything the reader
 * sees that is not interactive. Rendered by src/pages/leetcode/[slug].astro
 * through the Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Search in Rotated Sorted Array',
  summary: 'Check every value, or binary search: whichever side of mid holds no drop is sorted, and a sorted run tells you in one comparison whether the target can be in it.',
  eyebrow: 'LeetCode 33 &nbsp;·&nbsp; Medium',
  lede: { en: "A sorted array, cut once and swapped around, and a value to find in O(log n). Plain binary search fails because the array is not sorted. What survives the rotation is enough: cut it at the middle and at least one side is still in order — and a sorted side says, from its two ends alone, whether the target could be inside.", my: "တစ်ကြိမ် ဖြတ်ပြီး နေရာလဲထားသော စီထားသည့် array နှင့် O(log n) ဖြင့် ရှာရမည့် value တစ်ခု။ array မစီထားသဖြင့် ရိုးရိုး binary search မအောင်ပါ။ လှည့်ပြီးနောက် ကျန်သည့်အရာ လုံလောက်သည် — အလယ်တွင် ဖြတ်လျှင် အနည်းဆုံး တစ်ဘက်သည် အစဉ်အတိုင်း ရှိနေဆဲ — စီထားသော ဘက်က ၎င်း၏ အစွန်းနှစ်ဘက်မှ target အတွင်းမှာ ရှိနိုင်သလား ပြောပြသည်။" },
  links: [{ id: 33, title: 'Search in Rotated Sorted Array', slug: 'search-in-rotated-sorted-array', difficulty: 'Medium' }],
  constraints: { en: "<span><b>n</b> 1 &le; nums.length &le; 5000</span><span>&minus;10&#8308; &le; nums[i], target &le; 10&#8308;</span><span>values distinct</span>", my: "<span><b>n</b> 1 &le; nums.length &le; 5000</span><span>&minus;10&#8308; &le; nums[i], target &le; 10&#8308;</span><span>value များ ကွဲပြား</span>" },
  part1Sub: { en: "Read the statement, then rotate the array and watch which side of the middle stays sorted.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် array ကို လှည့်ပြီး အလယ်၏ မည်သည့်ဘက် စီထားလျက် ရှိနေသလဲ ကြည့်ပါ။" },
  widgetTitle: { en: "Rotate it, find the sorted side", my: "လှည့်ပါ — စီထားသော ဘက်ကို ရှာပါ" },
  traps: {
    summary: { en: "Three ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ သုံးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>The side test needs <code>&lt;=</code>.</strong> When only two values are left, <code>lo</code> and <code>mid</code> are the same index. Test <code>nums[lo] &lt; nums[mid]</code> instead and the one-value left side counts as unsorted: the listing returns −1 for target 1 in <code>[3,1]</code>. The answer is 1.", my: "<strong>ဘက်စစ်ခြင်းတွင် <code>&lt;=</code> လိုသည်။</strong> value နှစ်ခုသာ ကျန်သည့်အခါ <code>lo</code> နှင့် <code>mid</code> သည် index တူသည်။ <code>nums[lo] &lt; nums[mid]</code> ဖြင့် စစ်လျှင် value တစ်ခုတည်းရှိသော ဘယ်ဘက်ကို မစီထားဟု ယူသွားသည် — listing သည် <code>[3,1]</code> တွင် target 1 အတွက် −1 ကို ပြန်ပေးသည်။ အဖြေမှာ 1။" },
      { en: "<strong>The sorted side includes its first value.</strong> Checking <code>nums[lo] &lt; target</code> instead of <code>&lt;=</code> misses a target sitting at <code>lo</code>: on example 1's array, target 4 comes back as −1. The answer is 0.", my: "<strong>စီထားသော ဘက်တွင် ၎င်း၏ ပထမ value ပါသည်။</strong> <code>&lt;=</code> အစား <code>nums[lo] &lt; target</code> ဖြင့် စစ်လျှင် <code>lo</code> တွင် ရှိသော target ကို လွတ်သွားသည် — ဥပမာ 1 ၏ array တွင် target 4 သည် −1 ဖြစ်လာသည်။ အဖြေမှာ 0။" },
      { en: "<strong>\"Possibly\" rotated.</strong> The array may not be rotated at all, and then both sides are sorted. The test picks the left side first, which is fine — load <em>Not rotated</em>.", my: "<strong>လှည့်ထား\"နိုင်\"သည်။</strong> array ကို လုံးဝ မလှည့်ထားခြင်းလည်း ဖြစ်နိုင်ပြီး ထိုအခါ ဘေးနှစ်ဘက်လုံး စီထားသည်။ စစ်ခြင်းက ဘယ်ဘက်ကို အရင်ရွေးသည် — ပြဿနာ မရှိပါ၊ <em>Not rotated</em> ကို ဖွင့်ကြည့်ပါ။" },
    ],
  },
  part2Sub: { en: "Two approaches over the same array. The stage shows the range still in play and, for the binary search, the sorted side and the one question asked of it; the panel shows the line running.", my: "array တစ်ခုတည်းပေါ်တွင် နည်းလမ်းနှစ်မျိုး။ ဘယ်ဘက်က ရှာနေဆဲ အပိုင်းနှင့် binary search အတွက် စီထားသော ဘက်နှင့် ၎င်းကို မေးသည့် မေးခွန်းကို ပြပြီး ညာဘက် panel က အလုပ်လုပ်နေသော code ကြောင်းကို ပြသည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the binary search raises", my: "binary search နှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why must one side of mid be sorted?", my: "mid ၏ တစ်ဘက်သည် ဘာကြောင့် စီထားရမည်နည်း။" }, a: { en: "A rotated sorted array rises everywhere except at one drop, where the largest value is followed by the smallest. The drop is between two neighbours, so it cannot be on both sides of mid at once. Whichever side it misses rises from end to end.", my: "လှည့်ထားသော စီထားသည့် array သည် ကျဆင်းရာ တစ်နေရာမှလွဲ၍ နေရာတိုင်းတွင် တက်သည် — ထိုနေရာတွင် အကြီးဆုံးနောက် အငယ်ဆုံး လိုက်သည်။ ကျဆင်းရာသည် ကပ်လျက် နှစ်ခုကြားတွင် ရှိသဖြင့် mid ၏ ဘေးနှစ်ဘက်လုံးတွင် တစ်ပြိုင်နက် မရှိနိုင်ပါ။ ၎င်း မရှိသည့်ဘက်သည် အစမှ အဆုံး တက်သည်။" } },
      { q: { en: "Why test the sorted side, not the other one?", my: "ကျန်ဘက် မဟုတ်ဘဲ စီထားသော ဘက်ကို ဘာကြောင့် စစ်သလဲ။" }, a: { en: "Because only a sorted run can answer from its ends: every value in it lies between its first and last, and nothing outside does. The side with the drop holds two separate ranges, so its ends say nothing. Asking the sorted side decides both: if the target is not there, it can only be in the other side.", my: "စီထားသော run တစ်ခုသာ ၎င်း၏ အစွန်းများမှ ဖြေနိုင်သောကြောင့် — ၎င်းရှိ value တိုင်းသည် ပထမနှင့် နောက်ဆုံးကြားတွင် ရှိပြီး အပြင်ရှိ မည်သည့်အရာမျှ မရှိပါ။ ကျဆင်းရာရှိသည့် ဘက်တွင် range နှစ်ခု သီးခြား ရှိသဖြင့် ၎င်း၏ အစွန်းများက ဘာမျှ မပြောနိုင်ပါ။ စီထားသော ဘက်ကို မေးခြင်းက နှစ်ခုလုံးကို ဆုံးဖြတ်သည် — target ထိုနေရာတွင် မရှိလျှင် ကျန်ဘက်တွင်သာ ရှိနိုင်သည်။" } },
      { q: { en: "Why do the values have to be distinct?", my: "value များ ဘာကြောင့် ကွဲပြားရမည်နည်း။" }, a: { en: "With repeats, <code>nums[lo] == nums[mid]</code> no longer proves the left side is sorted: in <code>[1,3,1,1,1]</code> the drop is to the left of mid, yet both ends read 1. That version is LeetCode 81, where the fix is to shrink <code>lo</code> by one and look again — and the worst case falls back to O(n).", my: "ထပ်နေသော value ရှိလျှင် <code>nums[lo] == nums[mid]</code> သည် ဘယ်ဘက် စီထားကြောင်း မသက်သေပြနိုင်တော့ပါ — <code>[1,3,1,1,1]</code> တွင် ကျဆင်းရာ mid ၏ ဘယ်ဘက်တွင် ရှိသော်လည်း အစွန်းနှစ်ခုစလုံး 1။ ထို version သည် LeetCode 81 ဖြစ်ပြီး ပြင်နည်းမှာ <code>lo</code> ကို တစ်ခု လျှော့ပြီး ပြန်ကြည့်ခြင်း — အဆိုးဆုံး case သည် O(n) သို့ ပြန်ကျသည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "Halving, rotation or not", my: "လှည့်သည်ဖြစ်စေ မလှည့်သည်ဖြစ်စေ တစ်ဝက်ချ" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>At n = 5000 (the constraint)</th></tr></thead>\n  <tbody>\n    <tr><td><b>Linear scan</b><br><span class=\"sub\">every value</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(1)</td><td class=\"cross\">up to 5000 comparisons</td></tr>\n    <tr><td><b>Binary search</b><br><span class=\"sub\">find the sorted side</span></td>\n        <td class=\"mono\">O(log n)</td><td class=\"mono\">O(1)</td><td class=\"tick\">at most 13 steps</td></tr>\n  </tbody>\n</table>\n<figcaption>Counts are computed, not measured: ⌈log₂ 5001⌉ = 13. Both pass the judge at this size; the difference is what the statement asks for, and what happens when n is a million.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>n = 5000 (ကန့်သတ်ချက်) တွင်</th></tr></thead>\n  <tbody>\n    <tr><td><b>Linear scan</b><br><span class=\"sub\">value တိုင်း</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(1)</td><td class=\"cross\">နှိုင်းယှဉ်ခြင်း 5000 အထိ</td></tr>\n    <tr><td><b>Binary search</b><br><span class=\"sub\">စီထားသော ဘက်ကို ရှာ</span></td>\n        <td class=\"mono\">O(log n)</td><td class=\"mono\">O(1)</td><td class=\"tick\">အဆင့် 13 အထိ</td></tr>\n  </tbody>\n</table>\n<figcaption>ဤအရေအတွက်များကို တွက်ထားခြင်းဖြစ်ပြီး တိုင်းတာထားခြင်း မဟုတ်ပါ — ⌈log₂ 5001⌉ = 13။ ဤအရွယ်တွင် နှစ်ခုလုံး judge ကို အောင်သည် — ကွာခြားချက်မှာ မေးခွန်း တောင်းသည့်အရာနှင့် n သည် တစ်သန်း ဖြစ်လာသည့်အခါ ဖြစ်မည့်အရာ ဖြစ်သည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission, and every one was run against the same 20,014 cases.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး အားလုံးကို case 20,014 ခု တူတူဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>nums</code> or <code>target</code> above — up to 12 distinct values, sorted and rotated once — and both walkthroughs rebuild against your input.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>nums</code> သို့မဟုတ် <code>target</code> ကို ပြင်လိုက်လျှင် (ကွဲပြားသော value 12 ခုအထိ၊ စီပြီး တစ်ကြိမ် လှည့်ထားသည်) walkthrough နှစ်ခုစလုံး သင့် input ဖြင့် ပြန်တည်ဆောက်မည်။" },
};
