/* The prose of the Word Ladder page: everything the reader sees that is not
 * interactive. Rendered by src/pages/leetcode/[slug].astro through the
 * Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Word Ladder',
  summary: 'Words one letter apart are neighbours, so the shortest ladder is a shortest path: breadth-first search. Find each word\'s neighbours by comparing it with every word, or by changing each letter and asking a hash set.',
  eyebrow: 'LeetCode 127 &nbsp;·&nbsp; Hard',
  lede: { en: "Change beginWord into endWord one letter at a time, every word along the way taken from the list, in as few words as possible. Treat each word as a node and join two when they differ in one letter: the answer is a shortest path, and a breadth-first search finds it, level by level. What makes it Hard is finding the neighbours fast enough when the list holds 5,000 words.", my: "beginWord ကို endWord အဖြစ် စာလုံးတစ်လုံးချင်း ပြောင်းပါ — လမ်းတစ်လျှောက် စကားလုံးတိုင်း list ထဲမှ ယူပြီး စကားလုံး အနည်းဆုံးဖြင့်။ စကားလုံးတစ်ခုစီကို node အဖြစ်ယူ၍ စာလုံးတစ်လုံး ကွာသော နှစ်ခုကို ဆက်ပါ — အဖြေမှာ အတိုဆုံး path ဖြစ်ပြီး breadth-first search က level အလိုက် ရှာသည်။ ၎င်းကို Hard ဖြစ်စေသည်မှာ list တွင် စကားလုံး 5,000 ရှိချိန် အိမ်နီးများကို လုံလောက်စွာ မြန်မြန် ရှာခြင်း။" },
  links: [{ id: 127, title: 'Word Ladder', slug: 'word-ladder', difficulty: 'Hard' }],
  constraints: { en: "<span>1 &le; beginWord.length &le; 10</span><span>endWord.length == beginWord.length</span><span>1 &le; wordList.length &le; 5000</span><span>wordList[i].length == beginWord.length</span><span>lowercase English letters</span><span>beginWord != endWord</span><span>the words in wordList are unique</span>", my: "<span>1 &le; beginWord.length &le; 10</span><span>endWord.length == beginWord.length</span><span>1 &le; wordList.length &le; 5000</span><span>wordList[i].length == beginWord.length</span><span>အင်္ဂလိပ် စာလုံးအသေး</span><span>beginWord != endWord</span><span>wordList ထဲရှိ စကားလုံးများ မထပ်</span>" },
  part1Sub: { en: "Read the statement, then take words out of the list and watch the shortest ladder change.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် list ထဲမှ စကားလုံးများ ထုတ်ပြီး အတိုဆုံး ladder ပြောင်းပုံ ကြည့်ပါ။" },
  widgetTitle: { en: "Words by ladder length", my: "ladder အရှည်အလိုက် စကားလုံးများ" },
  traps: {
    summary: { en: "Three ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ သုံးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>Count the words, not the changes.</strong> The answer includes beginWord: \"hit\" to \"cog\" in example 1 takes 4 changes and is 5 words. Returning the number of changes gives 4.", my: "<strong>ပြောင်းလဲမှုများ မဟုတ်ဘဲ စကားလုံးများကို ရေတွက်ပါ။</strong> အဖြေတွင် beginWord ပါသည် — ဥပမာ 1 ၏ \"hit\" မှ \"cog\" သည် ပြောင်းလဲမှု 4 ခု ဖြစ်ပြီး စကားလုံး 5 ခု။ ပြောင်းလဲမှု အရေအတွက်ကို ပြန်ပေးလျှင် 4 ရသည်။" },
      { en: "<strong>The first ladder found is not the shortest unless the search is breadth-first.</strong> A depth-first search from \"a\" with <code>[\"b\",\"c\"]</code> tries \"b\" first and returns 3; \"a\" → \"c\" is 2. Breadth-first reaches every word by its shortest ladder first.", my: "<strong>ရှာပုံ breadth-first မဟုတ်လျှင် ပထမဆုံး တွေ့သော ladder သည် အတိုဆုံး မဟုတ်။</strong> <code>[\"b\",\"c\"]</code> ဖြင့် \"a\" မှ depth-first search သည် \"b\" ကို အရင်စမ်းပြီး 3 ပြန်ပေးသည် — \"a\" → \"c\" သည် 2။ breadth-first က စကားလုံးတိုင်းကို ၎င်း၏ အတိုဆုံး ladder ဖြင့် အရင် ရောက်သည်။" },
      { en: "<strong>Cross a word off once it is reached.</strong> Leave it in the list and \"hot\" and \"dot\" queue each other forever: with <code>[\"hot\",\"dot\",\"cog\"]</code>, where \"cog\" cannot be reached, Python was still running after 10 s. A word first reached at some length can never be reached by a shorter ladder later.", my: "<strong>ရောက်ပြီးသော စကားလုံးကို ချက်ချင်း ဖျက်ပါ။</strong> list ထဲ ထားလျှင် \"hot\" နှင့် \"dot\" သည် တစ်ခုကိုတစ်ခု အဆုံးမရှိ queue ထဲ ထည့်သည် — \"cog\" ကို မရောက်နိုင်သော <code>[\"hot\",\"dot\",\"cog\"]</code> ဖြင့် Python သည် 10 စက္ကန့်ကြာ၍လည်း ဆက် run နေသည်။ အရှည်တစ်ခုဖြင့် ပထမဆုံး ရောက်သော စကားလုံးကို နောက်ပိုင်း ပိုတိုသော ladder က ဘယ်တော့မှ မရောက်နိုင်။" },
    ],
  },
  part2Sub: { en: "Two ways to find a word's neighbours, inside the same breadth-first search. The strip is the input, with reached words solid; the stage is the queue and what is still unreached — a list to scan, or a set to ask.", my: "breadth-first search တစ်ခုတည်းအတွင်း စကားလုံးတစ်ခု၏ အိမ်နီးများကို ရှာရန် နည်းနှစ်မျိုး။ strip သည် input ဖြစ်ပြီး ရောက်ပြီးသော စကားလုံးများကို အပြည့်ဖြင့် ပြသည်။ stage သည် queue နှင့် မရောက်ရသေးသည့်အရာ — scan လုပ်ရမည့် list၊ သို့မဟုတ် မေးရမည့် set။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the search raises", my: "ရှာပုံနှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why remove a word when it is queued, not when it is popped?", my: "စကားလုံးကို ထုတ်ချိန် မဟုတ်ဘဲ queue ထဲ ထည့်ချိန်တွင် ဘာကြောင့် ဖယ်သလဲ။" }, a: { en: "Because a breadth-first search reaches each word first by a shortest ladder, so the first time a word is found is the only time that matters. Removing it straight away keeps it off the queue a second time; waiting until it is popped lets every word on the level before queue it again, and the queue can hold the same word many times over.", my: "breadth-first search သည် စကားလုံးတိုင်းကို အတိုဆုံး ladder ဖြင့် အရင်ရောက်သဖြင့် စကားလုံးကို ပထမဆုံး တွေ့ချိန်သာ အရေးကြီးသောကြောင့် ဖြစ်သည်။ ချက်ချင်း ဖယ်ခြင်းက ၎င်းကို queue ထဲ ဒုတိယအကြိမ် မဝင်စေ — ထုတ်သည်အထိ စောင့်လျှင် ယခင် level ရှိ စကားလုံးတိုင်းက ထပ်ထည့်နိုင်ပြီး queue တွင် စကားလုံးတစ်ခုတည်း အကြိမ်များစွာ ရှိနိုင်သည်။" } },
      { q: { en: "When does trying 26 letters beat comparing with every word?", my: "စာလုံး 26 လုံး စမ်းခြင်းသည် စကားလုံးတိုင်းနှင့် နှိုင်းယှဉ်ခြင်းကို ဘယ်အချိန် နိုင်သလဲ။" }, a: { en: "When the list is longer than about 26 times the word length. Comparing costs about n &times; L per word popped; changing letters costs 26 &times; L candidates, each L letters to build and hash. At the constraint — 5,000 words of 10 letters — that is 50,000 letter checks against 2,600 candidates per word, and the measured gap in Python here was 1.22 s against 0.054 s.", my: "list သည် စကားလုံး အရှည်၏ 26 ဆခန့်ထက် ရှည်သည့်အခါ။ နှိုင်းယှဉ်ခြင်းသည် ထုတ်သော စကားလုံးတစ်ခုလျှင် n &times; L ခန့် ကုန်ကျသည် — စာလုံးပြောင်းခြင်းသည် candidate 26 &times; L ခု၊ တစ်ခုစီ စာလုံး L လုံး တည်ဆောက်၍ hash လုပ်ရသည်။ ကန့်သတ်ချက်တွင် — 10 လုံးပါ စကားလုံး 5,000 — စကားလုံးတစ်ခုလျှင် စာလုံးစစ်ခြင်း 50,000 နှင့် candidate 2,600 ဖြစ်ပြီး ဤနေရာတွင် Python ဖြင့် တိုင်းထားသော ကွာဟချက်မှာ 1.22 စက္ကန့် နှင့် 0.054 စက္ကန့်။" } },
      { q: { en: "Can it go faster still?", my: "ပိုမြန်နိုင်သေးသလား။" }, a: { en: "Yes, by searching from both ends. A bidirectional BFS grows one level at a time from whichever side has the smaller frontier, and stops when the two meet. Both frontiers stay far smaller than one search's, since the number of words at distance <em>d</em> tends to grow quickly with <em>d</em>. The neighbour step is the same 26-letter trick; it is a common follow-up, but not on this page, because it was not run here.", my: "ဟုတ်သည် — အစွန်းနှစ်ဖက်မှ ရှာခြင်းဖြင့်။ bidirectional BFS သည် frontier ပိုငယ်သော ဘက်မှ level တစ်ခုချင်း ကြီးထွားပြီး နှစ်ဖက် တွေ့သည့်အခါ ရပ်သည်။ အကွာအဝေး <em>d</em> ရှိ စကားလုံး အရေအတွက်သည် <em>d</em> နှင့်အတူ မြန်မြန် ကြီးတတ်သဖြင့် frontier နှစ်ခုလုံး ရှာပုံတစ်ခု၏ frontier ထက် အများကြီး ငယ်သည်။ အိမ်နီး ရှာသည့်အဆင့်မှာ စာလုံး 26 လုံး နည်းလမ်း အတူတူ — ၎င်းသည် ဖြစ်လေ့ရှိသော follow-up ဖြစ်သော်လည်း ဤနေရာတွင် မ run ထားသဖြင့် ဤစာမျက်နှာတွင် မပါ။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "Scan the list, or ask a set", my: "list ကို scan လုပ်ခြင်း သို့မဟုတ် set ကို မေးခြင်း" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>5,000 words of 10 letters, Python</th></tr></thead>\n  <tbody>\n    <tr><td><b>BFS, comparing every word</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">a pass over the unreached list per word</span></td>\n        <td class=\"mono\">O(n² · L)</td><td class=\"mono\">O(n)</td><td class=\"cross\">1.22 s</td></tr>\n    <tr><td><b>BFS, changing each letter</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">26 · L lookups per word</span></td>\n        <td class=\"mono\">O(n · 26 · L²)</td><td class=\"mono\">O(n · L)</td><td class=\"tick\">0.054 s</td></tr>\n  </tbody>\n</table>\n<figcaption>Best of three on an Apple M5 Pro, on a list of 5,000 random 10-letter words over \"abc\" with endWord 50 words away — the search reaches most of the list before it gets there.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>10 လုံးပါ စကားလုံး 5,000၊ Python</th></tr></thead>\n  <tbody>\n    <tr><td><b>BFS, comparing every word</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">စကားလုံးတစ်ခုလျှင် မရောက်ရသေးသော list ကို တစ်ပတ်</span></td>\n        <td class=\"mono\">O(n² · L)</td><td class=\"mono\">O(n)</td><td class=\"cross\">1.22 စက္ကန့်</td></tr>\n    <tr><td><b>BFS, changing each letter</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">စကားလုံးတစ်ခုလျှင် lookup 26 · L</span></td>\n        <td class=\"mono\">O(n · 26 · L²)</td><td class=\"mono\">O(n · L)</td><td class=\"tick\">0.054 စက္ကန့်</td></tr>\n  </tbody>\n</table>\n<figcaption>Apple M5 Pro ပေါ်တွင် သုံးကြိမ်အနက် အကောင်းဆုံး — endWord သည် စကားလုံး 50 ခု အကွာတွင် ရှိသော \"abc\" ပေါ်ရှိ 10 လုံးပါ random စကားလုံး 5,000 list ပေါ်တွင် — ရှာပုံသည် ထိုနေရာမရောက်မီ list အများစုကို ရောက်သည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission, and every one was run against the same 20,015 cases, up to 5,000 words of 10 letters.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး အားလုံးကို 10 လုံးပါ စကားလုံး 5,000 အထိ case 20,015 ခု တူတူဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>beginWord</code>, <code>endWord</code> and <code>wordList</code> above — up to 10 words of up to 5 letters — and both walkthroughs rebuild against them.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>beginWord</code>၊ <code>endWord</code> နှင့် <code>wordList</code> ကို ပြင်လိုက်လျှင် (စာလုံး 5 လုံးအထိ စကားလုံး 10 ခုအထိ) walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
