/* The prose of the Coin Change page: everything the reader sees that is not
 * interactive. Rendered by src/pages/leetcode/[slug].astro through the
 * Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Coin Change',
  summary: 'The fewest coins for an amount is one coin plus the fewest for what it leaves. Plain recursion asks the same smaller amounts hundreds of times; a table from 0 upward answers each one once.',
  eyebrow: 'LeetCode 322 &nbsp;·&nbsp; Medium',
  lede: { en: "The fewest coins that add up to an amount, from an unlimited supply of each. Taking the biggest coin first is wrong. What is right is a recurrence — try every coin as the last one — and the whole difference between the two approaches here is whether each smaller amount is solved once or over and over.", my: "coin အမျိုးအစားတိုင်း အကန့်အသတ်မရှိ ရှိသည့်အထဲက ပမာဏတစ်ခုကို ဖွဲ့သည့် အနည်းဆုံး coin။ အကြီးဆုံး coin ကို အရင်ယူခြင်းသည် မှားသည်။ မှန်သည်မှာ recurrence — coin တိုင်းကို နောက်ဆုံး coin အဖြစ် စမ်းခြင်း — ဖြစ်ပြီး ဤနည်းလမ်းနှစ်ခု၏ ကွာခြားချက် တစ်ခုလုံးမှာ ပမာဏငယ် တစ်ခုစီကို တစ်ကြိမ်သာ ဖြေသလား၊ ထပ်ခါထပ်ခါ ဖြေသလား ဖြစ်သည်။" },
  links: [{ id: 322, title: 'Coin Change', slug: 'coin-change', difficulty: 'Medium' }],
  constraints: { en: "<span><b>coins</b> 1 &le; coins.length &le; 12</span><span>1 &le; coins[i] &le; 2&#179;&#185; &minus; 1</span><span>0 &le; amount &le; 10&#8308;</span>", my: "<span><b>coins</b> 1 &le; coins.length &le; 12</span><span>1 &le; coins[i] &le; 2&#179;&#185; &minus; 1</span><span>0 &le; amount &le; 10&#8308;</span>" },
  part1Sub: { en: "Read the statement, then drag the amount and see where taking the biggest coin first stops being the fewest.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် amount ကို ဆွဲပြီး အကြီးဆုံး coin ကို အရင်ယူခြင်းသည် မည်သည့်နေရာတွင် အနည်းဆုံး မဖြစ်တော့သလဲ ကြည့်ပါ။" },
  widgetTitle: { en: "Drag the amount, race greedy against fewest", my: "amount ကို ဆွဲပါ — greedy နှင့် အနည်းဆုံးကို ယှဉ်ပါ" },
  traps: {
    summary: { en: "Four ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ လေးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>Biggest coin first is not the fewest.</strong> With coins <code>[1,3,4]</code> and amount 6, greedy takes 4 + 1 + 1 — three coins. 3 + 3 is two.", my: "<strong>အကြီးဆုံး coin ကို အရင်ယူခြင်းသည် အနည်းဆုံး မဟုတ်ပါ။</strong> coin <code>[1,3,4]</code> နှင့် amount 6 တွင် greedy သည် 4 + 1 + 1 — coin သုံးခု ယူသည်။ 3 + 3 သည် နှစ်ခုသာ။" },
      { en: "<strong>Amount 0 is 0, not −1.</strong> Example 3: paying nothing takes no coins. A table whose <code>dp[0]</code> is left at \"not reached\" gets every answer wrong, not just this one.", my: "<strong>amount 0 သည် 0၊ −1 မဟုတ်ပါ။</strong> ဥပမာ 3 — ဘာမျှ မပေးရလျှင် coin မလို။ <code>dp[0]</code> ကို \"မရောက်သေး\" အဖြစ် ချန်ထားသော table သည် ဤအဖြေတစ်ခုတည်း မဟုတ်ဘဲ အဖြေတိုင်း မှားသည်။" },
      { en: "<strong>An <code>INT_MAX</code> \"unreached\" mark overflows.</strong> Adding the one coin to it wraps around in 32 bits. The table listing with <code>i32::MAX</code> in place of <code>amount + 1</code>, built with <code>rustc -O</code>, returns −2147483648 for coins <code>[2]</code>, amount 3; a debug build panics. <code>amount + 1</code> can never be a real answer and never overflows.", my: "<strong><code>INT_MAX</code> ကို \"မရောက်သေး\" အမှတ်အဖြစ် သုံးလျှင် overflow ဖြစ်သည်။</strong> ၎င်းကို coin တစ်ခု ပေါင်းလျှင် 32 bit တွင် ပတ်လည်သွားသည်။ <code>amount + 1</code> အစား <code>i32::MAX</code> ပါသော table listing ကို <code>rustc -O</code> ဖြင့် build လုပ်လျှင် coin <code>[2]</code>၊ amount 3 အတွက် −2147483648 ကို ပြန်ပေးသည် — debug build သည် panic ဖြစ်သည်။ <code>amount + 1</code> သည် တကယ့်အဖြေ ဘယ်တော့မှ မဖြစ်နိုင်ဘဲ overflow လည်း မဖြစ်ပါ။" },
      { en: "<strong>A coin can be bigger than the amount — up to 2³¹ − 1.</strong> Check <code>coin &gt; a</code> before indexing <code>dp[a − coin]</code>, or the index goes negative.", my: "<strong>coin သည် amount ထက် ကြီးနိုင်သည် — 2³¹ − 1 အထိ။</strong> <code>dp[a − coin]</code> ကို index မလုပ်မီ <code>coin &gt; a</code> ကို စစ်ပါ၊ မဟုတ်လျှင် index အနုတ် ဖြစ်သွားမည်။" },
    ],
  },
  part2Sub: { en: "Two approaches to the same recurrence. The stage shows what each one keeps — a call stack and a count of how often each amount was asked, or a table where each amount is written once; the panel shows the line running.", my: "recurrence တစ်ခုတည်းအတွက် နည်းလမ်းနှစ်မျိုး။ ဘယ်ဘက်က နည်းတစ်ခုစီ သိမ်းထားသည့်အရာ — call stack နှင့် amount တစ်ခုစီကို မည်မျှ မေးခဲ့သလဲ အရေအတွက်၊ သို့မဟုတ် amount တစ်ခုစီကို တစ်ကြိမ်သာ ရေးသော table — ကို ပြပြီး ညာဘက် panel က အလုပ်လုပ်နေသော code ကြောင်းကို ပြသည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the table raises", my: "table နှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why is \"one coin plus the fewest for the rest\" enough?", my: "\"coin တစ်ခု + ကျန်အတွက် အနည်းဆုံး\" ဘာကြောင့် လုံလောက်သလဲ။" }, a: { en: "Any way of paying a has some last coin c, and the coins before it pay a − c. If they did not use the fewest coins for a − c, swapping in the fewest would make the whole answer smaller. So the best answer for a is one coin plus the best answer for a − c, for the right c — and trying every c finds it.", my: "a ကို ပေးသည့် နည်းတိုင်းတွင် နောက်ဆုံး coin c တစ်ခု ရှိပြီး ၎င်းမတိုင်မီ coin များက a − c ကို ပေးသည်။ ၎င်းတို့သည် a − c အတွက် အနည်းဆုံး coin ကို မသုံးလျှင် အနည်းဆုံးဖြင့် အစားထိုးခြင်းက အဖြေ တစ်ခုလုံးကို ငယ်စေမည်။ ထို့ကြောင့် a အတွက် အကောင်းဆုံးသည် မှန်ကန်သော c အတွက် 1 + a − c ၏ အကောင်းဆုံး ဖြစ်ပြီး c တိုင်းကို စမ်းခြင်းက ၎င်းကို ရှာတွေ့သည်။" } },
      { q: { en: "Would memoizing the recursion be just as good?", my: "recursion ကို memoize လုပ်လျှင် အတူတူ ကောင်းမလား။" }, a: { en: "It removes the repeats — each amount computed once, like the table — but it still recurses as deep as the amount divided by the smallest coin: 10⁴ calls deep with a coin of 1. That overflows Python's default recursion limit of 1000. The table gets the same answers with a loop.", my: "ထပ်ခြင်းများကို ဖယ်ရှားသည် — table ကဲ့သို့ amount တစ်ခုစီကို တစ်ကြိမ်သာ တွက်သည် — သို့သော် amount ÷ အငယ်ဆုံး coin အထိ နက်နက် recurse လုပ်ဆဲ — coin 1 ဖြင့် call 10⁴ ဆင့် နက်သည်။ ၎င်းသည် Python ၏ default recursion limit 1000 ကို ကျော်သည်။ table သည် loop ဖြင့် အဖြေတူ ရသည်။" } },
      { q: { en: "Does the order of the two loops matter?", my: "loop နှစ်ခု၏ အစီအစဉ် အရေးကြီးသလား။" }, a: { en: "Not here. Amounts on the outside, coins inside, means every <code>dp[a − coin]</code> read is already final, since it is a smaller amount. Coins outside and amounts inside also works for the fewest coins. It matters in the sister problem, Coin Change II, which counts combinations: there, coins on the outside is what stops 1 + 2 and 2 + 1 counting twice.", my: "ဤနေရာတွင် မဟုတ်ပါ။ amount များ အပြင်၊ coin များ အတွင်း ဆိုလျှင် ဖတ်သည့် <code>dp[a − coin]</code> တိုင်းသည် ပိုငယ်သော amount ဖြစ်၍ ပြီးဆုံးပြီးသား ဖြစ်သည်။ coin များ အပြင်၊ amount များ အတွင်း ဆိုလည်း အနည်းဆုံး coin အတွက် အလုပ်ဖြစ်သည်။ ပေါင်းစပ်မှုများကို ရေတွက်သော ညီအစ်မ ပုစ္ဆာ Coin Change II တွင် အရေးကြီးသည် — ထိုနေရာတွင် coin များကို အပြင်ထားခြင်းက 1 + 2 နှင့် 2 + 1 ကို နှစ်ကြိမ် မရေတွက်အောင် တားသည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "The same questions, asked once", my: "မေးခွန်းတူ — တစ်ကြိမ်သာ မေး" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Space</th><th>coins [1,2,5]: amount 11</th><th>amount 25</th></tr></thead>\n  <tbody>\n    <tr><td><b>Plain recursion</b><br><span class=\"sub\">every last coin</span></td>\n        <td class=\"mono\">exponential</td><td class=\"mono\">O(amount) stack</td><td>527 calls</td><td class=\"cross\">924,876 calls</td></tr>\n    <tr><td><b>Bottom-up table</b><br><span class=\"sub\">each amount once</span></td>\n        <td class=\"mono\">O(amount · coins)</td><td class=\"mono\">O(amount)</td><td class=\"tick\">28 updates</td><td class=\"tick\">70 updates</td></tr>\n  </tbody>\n</table>\n<figcaption>Counted by running the two approaches, not timed. The recursion's count grows about 1.7 times with every unit of amount; at the constraint, 10⁴, the table does at most 1.2 × 10⁵ updates.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>Space</th><th>coins [1,2,5]: amount 11</th><th>amount 25</th></tr></thead>\n  <tbody>\n    <tr><td><b>Plain recursion</b><br><span class=\"sub\">နောက်ဆုံး coin တိုင်း</span></td>\n        <td class=\"mono\">exponential</td><td class=\"mono\">O(amount) stack</td><td>call 527</td><td class=\"cross\">call 924,876</td></tr>\n    <tr><td><b>Bottom-up table</b><br><span class=\"sub\">amount တစ်ခုစီ တစ်ကြိမ်</span></td>\n        <td class=\"mono\">O(amount · coins)</td><td class=\"mono\">O(amount)</td><td class=\"tick\">update 28</td><td class=\"tick\">update 70</td></tr>\n  </tbody>\n</table>\n<figcaption>နည်းလမ်းနှစ်ခုကို run ၍ ရေတွက်ထားခြင်းဖြစ်ပြီး အချိန် မတိုင်းထားပါ။ recursion ၏ အရေအတွက်သည် amount တစ်ယူနစ်တိုးတိုင်း 1.7 ဆခန့် တိုးသည် — ကန့်သတ်ချက် 10⁴ တွင် table သည် update 1.2 × 10⁵ အထိသာ လုပ်သည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission. The table ran against 20,014 cases up to amount = 10⁴; the recursion against the 15,131 with amount ≤ 12.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်သည်။ table ကို amount = 10⁴ အထိ case 20,014 ခုဖြင့်၊ recursion ကို amount ≤ 12 ဖြစ်သော case 15,131 ခုဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>coins</code> or <code>amount</code> above — up to 5 coins, amount up to 11, since example 1 already takes the recursion 527 calls — and both walkthroughs rebuild.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>coins</code> သို့မဟုတ် <code>amount</code> ကို ပြင်လိုက်လျှင် (coin 5 ခုအထိ၊ amount 11 အထိ — ဥပမာ 1 တွင်ပင် recursion သည် call 527 ကြိမ် ကုန်သည်) walkthrough နှစ်ခုစလုံး ပြန်တည်ဆောက်မည်။" },
};
