/* The prose of the Majority Element page: everything the reader sees that is
 * not interactive. Rendered by src/pages/leetcode/[slug].astro through the
 * Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Majority Element',
  summary: 'Tally every value until one passes half, or keep a single candidate and let every other value cancel one of its votes. A majority is the one thing pairing-off cannot remove.',
  eyebrow: 'LeetCode 169 &nbsp;·&nbsp; Easy',
  lede: { en: "Find the value that fills more than half the array. A count map finds it with up to n/2 rows of memory; the Boyer–Moore vote finds it with two variables, because pairs of different values can be thrown away and a majority is too big to be thrown away completely.", my: "array ၏ တစ်ဝက်ကျော်ကို ယူထားသော value ကို ရှာပါ။ count map သည် memory row n/2 ခုအထိ သုံး၍ ရှာသည် — Boyer–Moore vote ကမူ variable နှစ်ခုဖြင့် ရှာသည်၊ မတူသော value အတွဲများကို ပစ်နိုင်ပြီး majority သည် လုံးလုံး ပစ်၍ မကုန်နိုင်လောက်အောင် ကြီးသောကြောင့် ဖြစ်သည်။" },
  links: [{ id: 169, title: 'Majority Element', slug: 'majority-element', difficulty: 'Easy' }],
  constraints: { en: "<span><b>n</b> == nums.length</span><span>1 &le; n &le; 5 &times; 10&#8308;</span><span>&minus;10&#8313; &le; nums[i] &le; 10&#8313;</span><span>a majority element always exists</span>", my: "<span><b>n</b> == nums.length</span><span>1 &le; n &le; 5 &times; 10&#8308;</span><span>&minus;10&#8313; &le; nums[i] &le; 10&#8313;</span><span>majority element အမြဲ ရှိသည်</span>" },
  part1Sub: { en: "Read the statement, then pair each copy of the majority against a different value and see what survives.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် majority ၏ copy တစ်ခုစီကို မတူသော value တစ်ခုနှင့် အတွဲချပြီး ဘာကျန်သည်ကို ကြည့်ပါ။" },
  widgetTitle: { en: "Drag to cancel pairs, see who is left", my: "အတွဲများကို ချေဖျက်ရန် ဆွဲပါ — ဘယ်သူ ကျန်သလဲ ကြည့်ပါ" },
  traps: {
    summary: { en: "Three ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ သုံးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>More than ⌊n/2⌋, not at least.</strong> Returning as soon as a count reaches ⌊n/2⌋ (<code>&gt;=</code> instead of <code>&gt;</code>) returns 1 on example 2: 1 reaches three copies at index 4, one step before 2 does. Exactly half is not a majority.", my: "<strong>⌊n/2⌋ ထက် ပိုရမည်၊ အနည်းဆုံး ⌊n/2⌋ မဟုတ်ပါ။</strong> count က ⌊n/2⌋ ရောက်သည်နှင့် ပြန်ပေးလျှင် (<code>&gt;</code> အစား <code>&gt;=</code>) ဥပမာ 2 တွင် 1 ကို ပြန်ပေးသည် — 1 သည် index 4 တွင် copy သုံးခု ပြည့်ပြီး 2 ထက် တစ်ဆင့် စောသည်။ တစ်ဝက်တိတိသည် majority မဟုတ်ပါ။" },
      { en: "<strong>The vote leans on the guarantee.</strong> It always returns <em>something</em>. On <code>[1,2,1,2,3]</code>, which has no majority, it returns 3. If the input might have none, a second pass must count the candidate and check it really passes half.", my: "<strong>vote သည် အာမခံချက်ကို မှီခိုသည်။</strong> ၎င်းသည် <em>တစ်ခုခု</em>ကို အမြဲ ပြန်ပေးသည်။ majority မရှိသော <code>[1,2,1,2,3]</code> တွင် 3 ကို ပြန်ပေးသည်။ input တွင် majority မရှိနိုင်လျှင် ဒုတိယအကြိမ် ဖြတ်၍ candidate ကို ရေတွက်ပြီး တစ်ဝက်ကျော်မကျော် စစ်ရမည်။" },
      { en: "<strong>Values reach ±10<sup>9</sup>.</strong> A count array indexed by value would need two billion slots, so the tally has to be a hash map — or, for O(1) space, no tally at all.", my: "<strong>value များသည် ±10<sup>9</sup> အထိ ရှိသည်။</strong> value ဖြင့် index လုပ်သော count array သည် slot နှစ်ဘီလီယံ လိုမည်ဖြစ်သဖြင့် tally သည် hash map ဖြစ်ရမည် — O(1) space အတွက်မူ tally လုံးဝ မလိုပါ။" },
    ],
  },
  part2Sub: { en: "Two approaches over the same array. The stage shows what each one keeps — the whole tally, or one candidate's standing votes; the panel shows the line running.", my: "array တစ်ခုတည်းပေါ်တွင် နည်းလမ်းနှစ်မျိုး။ ဘယ်ဘက်က နည်းတစ်ခုစီ သိမ်းထားသည့်အရာ — tally တစ်ခုလုံး သို့မဟုတ် candidate တစ်ခု၏ ကျန်နေသော မဲများ — ကို ပြပြီး ညာဘက် panel က အလုပ်လုပ်နေသော code ကြောင်းကို ပြသည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the vote raises", my: "vote နှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why can the vote forget everything when the count hits 0?", my: "count 0 ရောက်သည့်အခါ vote က အရာအားလုံးကို ဘာကြောင့် မေ့နိုင်သလဲ။" }, a: { en: "Because at that moment the prefix read so far splits into pairs of different values — each −1 cancelled one earlier +1 for a different value. Removing a pair of different values removes at most one copy of the majority and one other, so the majority of the whole array is still a majority of what remains. Starting over on the rest loses nothing.", my: "ထိုအချိန်တွင် ယခုထိ ဖတ်ခဲ့သော အပိုင်းသည် မတူသော value အတွဲများ အဖြစ် ခွဲ၍ ရသောကြောင့် ဖြစ်သည် — −1 တစ်ခုစီက မတူသော value အတွက် ယခင် +1 တစ်ခုကို ချေဖျက်ခဲ့သည်။ မတူသော value အတွဲတစ်ခုကို ဖယ်ရှားခြင်းက majority ၏ copy အများဆုံး တစ်ခုနှင့် အခြား တစ်ခုကိုသာ ဖယ်သဖြင့် array တစ်ခုလုံး၏ majority သည် ကျန်သည့်အပိုင်း၏ majority အဖြစ် ဆက်ရှိသည်။ ကျန်သည့်အပိုင်းတွင် အသစ်စခြင်းက ဘာမျှ မဆုံးရှုံးစေပါ။" } },
      { q: { en: "Is the candidate the leader at every step?", my: "candidate သည် အဆင့်တိုင်းတွင် ဦးဆောင်သူ ဖြစ်သလား။" }, a: { en: "No, and it does not need to be. Only the final candidate is guaranteed, and only because a majority exists. Load <em>Candidate changes</em>: the candidate is 1, then 2, then 3. After four values, 1 and 2 are tied at two each and the count is 0; the next 2 restarts it, and is cancelled at once by the first 3. None of that says anything about the answer until the array ends.", my: "မဟုတ်ပါ၊ ဖြစ်ရန်လည်း မလိုပါ။ နောက်ဆုံး candidate ကိုသာ အာမခံထားပြီး majority ရှိသောကြောင့်သာ ဖြစ်သည်။ <em>Candidate changes</em> ကို load လုပ်ပါ — candidate သည် 1၊ ထို့နောက် 2၊ ထို့နောက် 3 ဖြစ်သည်။ value လေးခုအပြီးတွင် 1 နှင့် 2 သည် နှစ်ခုစီဖြင့် တူနေပြီး count သည် 0 ဖြစ်သည် — နောက် 2 က ၎င်းကို ပြန်စပြီး ပထမ 3 က ချက်ချင်း ချေဖျက်သည်။ array မဆုံးမချင်း ထိုအရာများက အဖြေအကြောင်း ဘာမျှ မပြောပါ။" } },
      { q: { en: "Why is it safe to start the candidate at 0 in Go and Rust?", my: "Go နှင့် Rust တွင် candidate ကို 0 ဖြင့် စတင်ခြင်း ဘာကြောင့် ဘေးကင်းသလဲ။" }, a: { en: "Because the count starts at 0, so the first element always replaces the candidate before it is ever compared. The 0 is never read — it is a placeholder for a typed variable, not a guess, even though 0 is a legal value in the array. Ruby, Python and JavaScript use <code>nil</code> / <code>None</code> / <code>null</code> for the same placeholder.", my: "count ကို 0 ဖြင့် စသဖြင့် ပထမ element သည် candidate ကို နှိုင်းယှဉ်ခြင်း မပြုမီ အမြဲ အစားထိုးသောကြောင့် ဖြစ်သည်။ 0 ကို ဘယ်တော့မှ မဖတ်ပါ — 0 သည် array ထဲတွင် တရားဝင် value ဖြစ်သော်လည်း ၎င်းသည် ခန့်မှန်းချက် မဟုတ်ဘဲ type ရှိသော variable အတွက် နေရာယူထားခြင်းသာ ဖြစ်သည်။ Ruby၊ Python နှင့် JavaScript တို့က ထိုနေရာအတွက် <code>nil</code> / <code>None</code> / <code>null</code> ကို သုံးသည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "The same pass, n/2 rows against two integers", my: "တစ်ကြိမ် ဖြတ်ခြင်း အတူတူ — row n/2 နှင့် integer နှစ်ခု" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>Majority first, n = 5×10⁴</th><th>Others first, n = 5×10⁴</th></tr></thead>\n  <tbody>\n    <tr><td><b>Count map</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">a row per distinct value</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(n)</td><td class=\"tick\">1 row, 25,001 reads</td><td class=\"cross\">25,000 rows, 50,000 reads</td></tr>\n    <tr><td><b>Boyer–Moore vote</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">candidate + count</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(1)</td><td class=\"tick\">2 variables, 50,000 reads</td><td class=\"tick\">2 variables, 50,000 reads</td></tr>\n  </tbody>\n</table>\n<figcaption>Counted by simulation on the tightest majority (25,001 copies) with the other 24,999 values all distinct, not timed. The count map can stop early and the vote cannot — but the vote's memory never grows, which is what the follow-up asks for.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>majority အရင်၊ n = 5×10⁴</th><th>အခြားများ အရင်၊ n = 5×10⁴</th></tr></thead>\n  <tbody>\n    <tr><td><b>Count map</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">မတူသော value တစ်ခုလျှင် row တစ်ခု</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(n)</td><td class=\"tick\">row 1၊ 25,001 ခု ဖတ်</td><td class=\"cross\">row 25,000၊ 50,000 ခု ဖတ်</td></tr>\n    <tr><td><b>Boyer–Moore vote</b><br><span style=\"color:var(--ink-3);font-size:12.5px\">candidate + count</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(1)</td><td class=\"tick\">variable 2၊ 50,000 ခု ဖတ်</td><td class=\"tick\">variable 2၊ 50,000 ခု ဖတ်</td></tr>\n  </tbody>\n</table>\n<figcaption>အနိုင်ရရုံ majority (copy 25,001) နှင့် ကျန် value 24,999 ခု အားလုံး မတူသည့် အခြေအနေတွင် simulate လုပ်၍ ရေတွက်ထားခြင်းဖြစ်ပြီး အချိန် မတိုင်းထားပါ။ count map သည် စောစော ရပ်နိုင်ပြီး vote မရပ်နိုင်ပါ — သို့သော် vote ၏ memory သည် ဘယ်တော့မှ မကြီးလာပါ၊ follow-up က တောင်းသည်မှာ ၎င်းပင် ဖြစ်သည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission and was run against the same 20,011 cases, up to n = 5×10⁴.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး n = 5×10⁴ အထိ case 20,011 ခု တူတူဖြင့် run ထားသည်။" },
  footer: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>nums</code> above — up to 15 values, and one of them has to fill more than half — and both walkthroughs rebuild against your array.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>nums</code> ကို ပြင်လိုက်လျှင် (value 15 ခုအထိ၊ တစ်ခုက တစ်ဝက်ကျော် ရှိရမည်) walkthrough နှစ်ခုစလုံး သင့် array ဖြင့် ပြန်တည်ဆောက်မည်။" },
};
