/* The prose of the Product of Array Except Self page: everything the reader
 * sees that is not interactive. Rendered by src/pages/leetcode/[slug].astro
 * through the Walkthrough layout; each value is a string or an { en, my } pair. */
export default {
  title: 'Product of Array Except Self',
  summary: 'Every answer is the product of everything to its left times everything to its right. Recompute both for every index, or carry each one as a running product — no division, so zeros need no special case.',
  eyebrow: 'LeetCode 238 &nbsp;·&nbsp; Medium',
  lede: { en: "For each index, the product of every other number. Dividing the whole product by <code>nums[i]</code> is banned, and breaks on a zero anyway. What works is splitting each answer into its left side and its right side, and noticing that neighbouring indices share almost all of both.", my: "index တစ်ခုစီအတွက် ကျန်ကိန်းအားလုံး၏ မြှောက်လဒ်။ မြှောက်လဒ် တစ်ခုလုံးကို <code>nums[i]</code> ဖြင့် စားခြင်းကို တားထားပြီး သုညတစ်လုံး ပါလျှင်လည်း ပျက်သည်။ အလုပ်ဖြစ်သည့်နည်းမှာ အဖြေတစ်ခုစီကို ဘယ်ဘက်နှင့် ညာဘက် ခွဲပြီး ကပ်လျက် index များက ထိုနှစ်ဘက်စလုံး၏ အများစုကို မျှသုံးကြောင်း သတိပြုခြင်း ဖြစ်သည်။" },
  links: [{ id: 238, title: 'Product of Array Except Self', slug: 'product-of-array-except-self', difficulty: 'Medium' }],
  constraints: { en: "<span><b>n</b> 2 &le; nums.length &le; 10&#8309;</span><span>&minus;30 &le; nums[i] &le; 30</span><span>every answer fits in 32 bits</span>", my: "<span><b>n</b> 2 &le; nums.length &le; 10&#8309;</span><span>&minus;30 &le; nums[i] &le; 30</span><span>အဖြေတိုင်း 32 bit ထဲ ဆံ့သည်</span>" },
  part1Sub: { en: "Read the statement, then move i and watch its answer split into a left run and a right run.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် i ကို ရွှေ့ပြီး ၎င်း၏ အဖြေသည် ဘယ်အပိုင်းနှင့် ညာအပိုင်း ကွဲသွားပုံကို ကြည့်ပါ။" },
  widgetTitle: { en: "Drag i, split the product in two", my: "i ကို ဆွဲပါ — မြှောက်လဒ်ကို နှစ်ပိုင်း ခွဲပါ" },
  traps: {
    summary: { en: "Four ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ လေးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>No division, and not only because it is banned.</strong> Taking the whole product and dividing by each <code>nums[i]</code> works on example 1, but on example 2 the whole product is 0: Python raises <code>ZeroDivisionError</code>, and JavaScript returns <code>[-0, 0, NaN, -0, 0]</code> — <code>NaN</code> where the answer is 9.", my: "<strong>စားခြင်း မသုံးရ — တားထား၍သာ မဟုတ်ပါ။</strong> မြှောက်လဒ် တစ်ခုလုံးကို ယူပြီး <code>nums[i]</code> တစ်ခုစီဖြင့် စားခြင်းသည် ဥပမာ 1 တွင် အလုပ်ဖြစ်သော်လည်း ဥပမာ 2 တွင် မြှောက်လဒ် တစ်ခုလုံးမှာ 0 — Python က <code>ZeroDivisionError</code> ပေးပြီး JavaScript က <code>[-0, 0, NaN, -0, 0]</code> ကို ပြန်ပေးသည် — အဖြေ 9 ဖြစ်ရမည့်နေရာတွင် <code>NaN</code>။" },
      { en: "<strong>Zeros are the edge case, and they need no code.</strong> One zero means every answer is 0 except the zero's own; two zeros make every answer 0. Left × right gets all of that right with no <code>if</code>.", my: "<strong>သုညများသည် edge case ဖြစ်သော်လည်း code မလိုပါ။</strong> သုညတစ်လုံး ဆိုလျှင် သုည၏ နေရာမှလွဲ၍ အဖြေတိုင်း 0 ဖြစ်ပြီး သုညနှစ်လုံး ဆိုလျှင် အဖြေတိုင်း 0 ဖြစ်သည်။ ဘယ် × ညာ သည် <code>if</code> မပါဘဲ ထိုအားလုံးကို မှန်အောင် ရသည်။" },
      { en: "<strong>The 32-bit promise covers prefixes and suffixes — not every stretch.</strong> <code>[2, 0, 30 × 15, 0]</code> is legal: every prefix and suffix product is 0 or 2. But the fifteen 30s multiply to about 1.4 × 10²² (computed), past even 64 bits. A brute force that builds the right side from the left end passes through that product; building it from the far end, as the listings here do, only ever holds suffixes.", my: "<strong>32-bit အာမခံချက်သည် prefix နှင့် suffix များအတွက်သာ — အပိုင်းတိုင်းအတွက် မဟုတ်ပါ။</strong> <code>[2, 0, 30 × 15, 0]</code> သည် ခွင့်ပြုထားသော input — prefix နှင့် suffix မြှောက်လဒ်တိုင်း 0 သို့မဟုတ် 2။ သို့သော် 30 ဆယ့်ငါးလုံး၏ မြှောက်လဒ်မှာ 1.4 × 10²² ခန့် (တွက်ထားခြင်း) — 64 bit ကိုပင် ကျော်သည်။ ညာဘက်ကို ဘယ်အစွန်းမှ စ၍ တည်ဆောက်သော brute force သည် ထိုမြှောက်လဒ်ကို ဖြတ်သွားရသည်။ ဤ listing များကဲ့သို့ အဝေးဘက်အစွန်းမှ တည်ဆောက်လျှင် suffix များကိုသာ ကိုင်ထားရသည်။" },
      { en: "<strong>O(n) rules out the obvious loop.</strong> Recomputing left and right for each index is n(n − 1) multiplications — about 10¹⁰ at n = 10⁵ (computed). The fix is not a faster multiply but not repeating one.", my: "<strong>O(n) က သိသာသော loop ကို ပယ်သည်။</strong> index တစ်ခုစီအတွက် ဘယ်နှင့် ညာကို ပြန်တွက်ခြင်းသည် မြှောက်ခြင်း n(n − 1) ကြိမ် — n = 10⁵ တွင် 10¹⁰ ခန့် (တွက်ထားခြင်း)။ ပြင်နည်းမှာ ပိုမြန်သော မြှောက်ခြင်း မဟုတ်ဘဲ မထပ်မြှောက်ခြင်း ဖြစ်သည်။" },
    ],
  },
  part2Sub: { en: "Two approaches over the same array. The stage shows what each one carries — the two partial products, or the answer array filling in two passes; the panel shows the line running.", my: "array တစ်ခုတည်းပေါ်တွင် နည်းလမ်းနှစ်မျိုး။ ဘယ်ဘက်က နည်းတစ်ခုစီ သယ်ဆောင်သည့်အရာ — ကြားဖြတ် မြှောက်လဒ် နှစ်ခု သို့မဟုတ် pass နှစ်ခုဖြင့် ပြည့်လာသော answer array — ကို ပြပြီး ညာဘက် panel က အလုပ်လုပ်နေသော code ကြောင်းကို ပြသည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the two passes raise", my: "pass နှစ်ခုနှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why write <code>answer[i]</code> <em>before</em> multiplying <code>nums[i]</code> into <code>prefix</code>?", my: "<code>nums[i]</code> ကို <code>prefix</code> ထဲ မြှောက်<em>မီ</em> <code>answer[i]</code> ကို ဘာကြောင့် ရေးရသလဲ။" }, a: { en: "Because answer[i] must leave nums[i] out. At the moment it is written, <code>prefix</code> holds nums[0] × … × nums[i − 1] — exactly the left side. The suffix pass keeps the same order for the same reason. Swap the pair in both passes and every slot gets its own number multiplied in twice: example 1 comes back as [24, 48, 72, 96].", my: "answer[i] သည် nums[i] ကို ချန်ထားရမည် ဖြစ်သောကြောင့်။ ရေးသည့်အချိန်တွင် <code>prefix</code> ၌ nums[0] × … × nums[i − 1] — ဘယ်ဘက် အတိအကျ — ရှိသည်။ suffix pass တွင်လည်း အကြောင်းတူ၍ အစီအစဉ်တူသည်။ pass နှစ်ခုစလုံးတွင် စာကြောင်းအတွဲကို နေရာလဲလိုက်လျှင် slot တိုင်းထဲ ၎င်း၏ ကိန်းကိုယ်တိုင် နှစ်ကြိမ် မြှောက်ဝင်သွားပြီး ဥပမာ 1 သည် [24, 48, 72, 96] ဖြစ်လာသည်။" } },
      { q: { en: "Where did the prefix array go?", my: "prefix array ဘယ်ရောက်သွားသလဲ။" }, a: { en: "The textbook version builds a <code>prefix</code> array and a <code>suffix</code> array and multiplies them — O(n) extra space. Pass 1 stores the prefix products straight into <code>answer</code>, which the follow-up says does not count, and pass 2 needs the suffix only one index at a time, so a single variable is enough. That is the whole O(1)-extra trick.", my: "စာအုပ်ပါ ပုံစံသည် <code>prefix</code> array နှင့် <code>suffix</code> array ကို တည်ဆောက်ပြီး မြှောက်သည် — O(n) အပို space။ Pass 1 သည် prefix မြှောက်လဒ်များကို မရေတွက်ဟု follow-up ဆိုထားသော <code>answer</code> ထဲ တိုက်ရိုက် သိမ်းပြီး pass 2 သည် suffix ကို တစ်ကြိမ်လျှင် index တစ်ခုအတွက်သာ လိုသဖြင့် variable တစ်ခု လုံလောက်သည်။ O(1) အပို ဖြစ်စေသည့် နည်းမှာ ထိုမျှသာ ဖြစ်သည်။" } },
      { q: { en: "Why do <code>prefix</code> and <code>suffix</code> never overflow, even in Rust's <code>i32</code>?", my: "Rust ၏ <code>i32</code> တွင်ပင် <code>prefix</code> နှင့် <code>suffix</code> ဘာကြောင့် overflow မဖြစ်သလဲ။" }, a: { en: "Every value <code>prefix</code> takes is the product of a prefix of nums, and every value of <code>suffix</code> is the product of a suffix — including the last one, the whole array, which is both. The statement guarantees all of those fit in 32 bits. The brute force is written to keep the same promise: its right-hand loop walks in from the end so it, too, only ever holds suffixes.", my: "<code>prefix</code> ယူသည့် value တိုင်းသည် nums ၏ prefix တစ်ခု၏ မြှောက်လဒ်ဖြစ်ပြီး <code>suffix</code> ၏ value တိုင်းသည် suffix တစ်ခု၏ မြှောက်လဒ် ဖြစ်သည် — နောက်ဆုံးတန်ဖိုးဖြစ်သော array တစ်ခုလုံးသည် နှစ်မျိုးလုံး ဖြစ်သည်။ ထိုအားလုံး 32 bit ထဲ ဆံ့ကြောင်း မေးခွန်းက အာမခံထားသည်။ brute force ကိုလည်း ထိုကတိ အတိုင်း ရေးထားသည် — ၎င်း၏ ညာဘက် loop သည် နောက်ဆုံးမှ ဝင်လာသဖြင့် suffix များကိုသာ ကိုင်ထားသည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "The same products, without the repeats", my: "မြှောက်လဒ် အတူတူ — ထပ်မြှောက်ခြင်း မပါ" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>At n = 10⁵ (the constraint)</th></tr></thead>\n  <tbody>\n    <tr><td><b>Brute force</b><br><span class=\"sub\">both sides, every index</span></td>\n        <td class=\"mono\">O(n²)</td><td class=\"mono\">O(1)</td><td class=\"cross\">≈ 10¹⁰ multiplications</td></tr>\n    <tr><td><b>Prefix × suffix</b><br><span class=\"sub\">two passes</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">O(1) beyond answer</td><td class=\"tick\">≈ 4 × 10⁵ multiplications</td></tr>\n  </tbody>\n</table>\n<figcaption>Counts are computed from the constraint, not measured: the brute force does n − 1 per index; the two passes do two per index, one into the answer and one into the running product.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>n = 10⁵ (ကန့်သတ်ချက်) တွင်</th></tr></thead>\n  <tbody>\n    <tr><td><b>Brute force</b><br><span class=\"sub\">index တိုင်း၊ ဘေးနှစ်ဘက်</span></td>\n        <td class=\"mono\">O(n²)</td><td class=\"mono\">O(1)</td><td class=\"cross\">မြှောက်ခြင်း ≈ 10¹⁰</td></tr>\n    <tr><td><b>Prefix × suffix</b><br><span class=\"sub\">pass နှစ်ခု</span></td>\n        <td class=\"mono\">O(n)</td><td class=\"mono\">answer အပြင် O(1)</td><td class=\"tick\">မြှောက်ခြင်း ≈ 4 × 10⁵</td></tr>\n  </tbody>\n</table>\n<figcaption>ဤအရေအတွက်များကို ကန့်သတ်ချက်မှ တွက်ထားခြင်းဖြစ်ပြီး တိုင်းတာထားခြင်း မဟုတ်ပါ — brute force သည် index တစ်ခုလျှင် n − 1 ကြိမ်၊ pass နှစ်ခုသည် index တစ်ခုလျှင် နှစ်ကြိမ် (answer ထဲ တစ်ကြိမ်၊ running product ထဲ တစ်ကြိမ်) မြှောက်သည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission. The two passes ran against 20,013 cases up to n = 10⁵; the brute force against the 20,008 small enough for it.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်သည်။ pass နှစ်ခု နည်းကို n = 10⁵ အထိ case 20,013 ခုဖြင့်၊ brute force ကို ၎င်းအတွက် သေးလောက်သော case 20,008 ခုဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>nums</code> above — up to 10 values from −30 to 30 — and both walkthroughs rebuild against your array.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>nums</code> ကို ပြင်လိုက်လျှင် (−30 မှ 30 အထိ value 10 ခုအထိ) walkthrough နှစ်ခုစလုံး သင့် array ဖြင့် ပြန်တည်ဆောက်မည်။" },
};
