/* The prose of the Kth Largest Element in an Array page: everything the
 * reader sees that is not interactive. Rendered by
 * src/pages/leetcode/[slug].astro through the Walkthrough layout; each value
 * is a string or an { en, my } pair. */
export default {
  title: 'Kth Largest Element in an Array',
  summary: 'Sort everything and count k from the end, or keep only the k largest in a min-heap — the smallest of them, at the root, is the answer.',
  eyebrow: 'LeetCode 215 &nbsp;·&nbsp; Medium',
  lede: { en: "The kth largest value, counting duplicates. Sorting finds it by putting all n values in order to read one. A min-heap capped at k keeps only the values that could still be the answer: the k largest so far, with the weakest of them at the root, ready to be thrown out.", my: "ထပ်နေသည်များကို ရေတွက်၍ k ခုမြောက် အကြီးဆုံး value။ sort လုပ်ခြင်းသည် တစ်ခုကို ဖတ်ရန် value n ခုလုံးကို စီပြီး ရှာသည်။ k ဖြင့် ကန့်သတ်ထားသော min-heap သည် အဖြေ ဖြစ်နိုင်သေးသည့် value များကိုသာ ထားသည် — ယခုထိ အကြီးဆုံး k ခု၊ ၎င်းတို့ထဲက အားအနည်းဆုံးကို root တွင် ပစ်ရန် အသင့်ထား။" },
  links: [{ id: 215, title: 'Kth Largest Element in an Array', slug: 'kth-largest-element-in-an-array', difficulty: 'Medium' }],
  constraints: { en: "<span><b>n</b> 1 &le; k &le; nums.length &le; 10&#8309;</span><span>&minus;10&#8308; &le; nums[i] &le; 10&#8308;</span>", my: "<span><b>n</b> 1 &le; k &le; nums.length &le; 10&#8309;</span><span>&minus;10&#8308; &le; nums[i] &le; 10&#8308;</span>" },
  part1Sub: { en: "Read the statement, then drag k and see why duplicates each take their own rank.", my: "မေးခွန်းကို အရင်ဖတ်ပါ။ ပြီးလျှင် k ကို ဆွဲပြီး ထပ်နေသော value တစ်ခုစီ ကိုယ်ပိုင် အဆင့် ဘာကြောင့် ယူသလဲ ကြည့်ပါ။" },
  widgetTitle: { en: "Drag k, count every copy", my: "k ကို ဆွဲပါ — copy တိုင်းကို ရေတွက်ပါ" },
  traps: {
    summary: { en: "Three ways the statement bites &mdash; worth reading before you code", my: "မေးခွန်းစာသားထဲက ချော်လွယ်သည့်နေရာ သုံးခု — code မရေးမီ ဖတ်ထားသင့်သည်" },
    items: [
      { en: "<strong>Not the kth distinct element.</strong> Deduplicating first gives 3 on example 2, because 6, 5, 4, 3 are its four largest distinct values. Both 5s count: 6, 5, 5, 4 — the answer is 4.", my: "<strong>k ခုမြောက် ကွဲပြားသော element မဟုတ်ပါ။</strong> အရင် ထပ်နေသည်ကို ဖယ်လျှင် ဥပမာ 2 တွင် 3 ရသည် — 6, 5, 4, 3 သည် ၎င်း၏ ကွဲပြားသော အကြီးဆုံး လေးခု ဖြစ်သောကြောင့်။ 5 နှစ်ခုလုံး ရေတွက်သည် — 6, 5, 5, 4 — အဖြေမှာ 4။" },
      { en: "<strong>A min-heap, not a max-heap.</strong> The heap has to throw out the smallest of the values it keeps. Evict the largest instead and it keeps the k smallest: example 1 returns 2, the 2nd <em>smallest</em>.", my: "<strong>min-heap၊ max-heap မဟုတ်ပါ။</strong> heap သည် ၎င်းထားသော value များထဲက အငယ်ဆုံးကို ပစ်ရမည်။ အကြီးဆုံးကို ပစ်လျှင် အငယ်ဆုံး k ခုကို ထားသွားသည် — ဥပမာ 1 သည် 2၊ ဒုတိယ <em>အငယ်ဆုံး</em>ကို ပြန်ပေးသည်။" },
      { en: "<strong>JavaScript's <code>sort()</code> sorts numbers as text.</strong> <code>[10,9,2].sort()</code> gives <code>[10,2,9]</code>, so the sort listing without its comparator returns 9 for k = 1. Pass <code>(a, b) =&gt; a - b</code>.", my: "<strong>JavaScript ၏ <code>sort()</code> သည် ကိန်းများကို စာသားအဖြစ် sort လုပ်သည်။</strong> <code>[10,9,2].sort()</code> သည် <code>[10,2,9]</code> ဖြစ်သဖြင့် comparator မပါသော sort listing သည် k = 1 အတွက် 9 ကို ပြန်ပေးသည်။ <code>(a, b) =&gt; a - b</code> ကို ထည့်ပေးပါ။" },
    ],
  },
  part2Sub: { en: "Two approaches over the same array. The stage shows what each one keeps — all of it, sorted, or a heap of at most k drawn as the tree its array encodes; the panel shows the line running.", my: "array တစ်ခုတည်းပေါ်တွင် နည်းလမ်းနှစ်မျိုး။ ဘယ်ဘက်က နည်းတစ်ခုစီ ထားသည့်အရာ — sort ထားသော အားလုံး သို့မဟုတ် ၎င်း၏ array ကိုယ်စားပြုသော tree အဖြစ် ဆွဲထားသည့် k အထိ heap — ကို ပြပြီး ညာဘက် panel က အလုပ်လုပ်နေသော code ကြောင်းကို ပြသည်။" },
  notes: {
    eyebrow: { en: "If you are implementing it", my: "ကိုယ်တိုင် ရေးမည်ဆိုလျှင်" },
    title: { en: "Three questions the heap raises", my: "heap နှင့်ပတ်သက်၍ မေးစရာ သုံးခု" },
    items: [
      { q: { en: "Why is it safe to throw away the heap's smallest?", my: "heap ၏ အငယ်ဆုံးကို ပစ်ခြင်း ဘာကြောင့် ဘေးကင်းသလဲ။" }, a: { en: "When the heap holds k + 1 values, its smallest has k values above it already. Nothing that arrives later can lower that count, so it can never be the kth largest. Everything still in the heap might be.", my: "heap တွင် value k + 1 ခု ရှိသည့်အခါ ၎င်း၏ အငယ်ဆုံးအပေါ်တွင် value k ခု ရှိပြီးသား ဖြစ်သည်။ နောက်မှ ရောက်လာသည့် မည်သည့်အရာကမျှ ထိုအရေအတွက်ကို မလျှော့နိုင်သဖြင့် ၎င်းသည် k ခုမြောက် အကြီးဆုံး ဘယ်တော့မှ မဖြစ်နိုင်ပါ။ heap ထဲ ကျန်သမျှ ဖြစ်နိုင်သည်။" } },
      { q: { en: "How does an array hold a tree?", my: "array တစ်ခုသည် tree ကို မည်သို့ ထားသလဲ။" }, a: { en: "Index 0 is the root, and the children of index i are 2i + 1 and 2i + 2, so the parent of i is (i − 1) / 2. Push appends and lets the value rise past bigger parents; pop moves the last value to the root and lets it sink below smaller children. Both walk one path of a tree of height log k.", my: "index 0 သည် root ဖြစ်ပြီး index i ၏ ကလေးများမှာ 2i + 1 နှင့် 2i + 2 ဖြစ်သဖြင့် i ၏ parent မှာ (i − 1) / 2။ push သည် ထပ်ထည့်ပြီး value ကို ပိုကြီးသော parent များကို ကျော်တက်စေသည် — pop သည် နောက်ဆုံး value ကို root သို့ ရွှေ့ပြီး ပိုငယ်သော ကလေးများအောက်သို့ နစ်စေသည်။ နှစ်ခုလုံးသည် အမြင့် log k tree ၏ လမ်းကြောင်း တစ်ခုကို လျှောက်သည်။" } },
      { q: { en: "Is there anything faster than O(n log k)?", my: "O(n log k) ထက် ပိုမြန်သည် ရှိသလား။" }, a: { en: "Quickselect partitions like quicksort but recurses into only the side holding the kth position: O(n) on average, O(n²) at worst, and LeetCode's tests include inputs — long runs of one value — that punish a naive partition. Here the values are also bounded to ±10⁴, so counting how many of each value there are and walking down from the top is O(n + 2 × 10⁴), with no comparisons at all.", my: "Quickselect သည် quicksort ကဲ့သို့ partition လုပ်သော်လည်း k ခုမြောက် နေရာ ရှိသည့်ဘက်ကိုသာ recurse လုပ်သည် — ပျမ်းမျှ O(n)၊ အဆိုးဆုံး O(n²) — LeetCode ၏ test များတွင် ရိုးရိုး partition ကို ဒုက္ခပေးသည့် input — value တစ်ခုတည်း ရှည်လျားစွာ — ပါသည်။ ဤနေရာတွင် value များကို ±10⁴ ဖြင့်လည်း ကန့်သတ်ထားသဖြင့် value တစ်ခုစီ မည်မျှ ရှိသလဲ ရေတွက်ပြီး အထက်မှ လျှောက်ခြင်းသည် နှိုင်းယှဉ်ခြင်း လုံးဝမပါဘဲ O(n + 2 × 10⁴) ဖြစ်သည်။" } },
    ],
  },
  cost: {
    eyebrow: { en: "Why bother", my: "ဘာကြောင့် ဂရုစိုက်ရသလဲ" },
    title: { en: "Ordering n values to read one", my: "တစ်ခုကို ဖတ်ရန် value n ခုကို စီခြင်း" },
    html: { en: "<table>\n  <thead><tr><th>Approach</th><th>Time</th><th>Extra space</th><th>n = 10⁵, k = 10</th></tr></thead>\n  <tbody>\n    <tr><td><b>Sort</b><br><span class=\"sub\">order everything</span></td>\n        <td class=\"mono\">O(n log n)</td><td class=\"mono\">O(n) or O(1)</td><td>≈ 1.7 × 10⁶ comparisons</td></tr>\n    <tr><td><b>Min-heap of size k</b><br><span class=\"sub\">keep the k largest</span></td>\n        <td class=\"mono\">O(n log k)</td><td class=\"mono\">O(k)</td><td class=\"tick\">≈ 3.5 × 10⁵ heap steps, 10 values held</td></tr>\n  </tbody>\n</table>\n<figcaption>Counts are computed, not measured: n log₂ n and n log₂(k + 1). The heap's advantage grows as k shrinks; at k near n it is no better than the sort. Where the input streams in and n is unknown, only the heap works at all.</figcaption>", my: "<table>\n  <thead><tr><th>နည်းလမ်း</th><th>အချိန်</th><th>အပို memory</th><th>n = 10⁵၊ k = 10</th></tr></thead>\n  <tbody>\n    <tr><td><b>Sort</b><br><span class=\"sub\">အားလုံးကို စီ</span></td>\n        <td class=\"mono\">O(n log n)</td><td class=\"mono\">O(n) သို့မဟုတ် O(1)</td><td>နှိုင်းယှဉ်ခြင်း ≈ 1.7 × 10⁶</td></tr>\n    <tr><td><b>Min-heap of size k</b><br><span class=\"sub\">အကြီးဆုံး k ခုကို ထား</span></td>\n        <td class=\"mono\">O(n log k)</td><td class=\"mono\">O(k)</td><td class=\"tick\">heap အဆင့် ≈ 3.5 × 10⁵၊ value 10 ခု ထား</td></tr>\n  </tbody>\n</table>\n<figcaption>ဤအရေအတွက်များကို တွက်ထားခြင်းဖြစ်ပြီး တိုင်းတာထားခြင်း မဟုတ်ပါ — n log₂ n နှင့် n log₂(k + 1)။ k ငယ်လေ heap ၏ အားသာချက် ကြီးလေ ဖြစ်သည် — k သည် n နှင့် နီးလျှင် sort ထက် မပိုကောင်းပါ။ input သည် စီးဝင်လာပြီး n ကို မသိသည့်နေရာတွင် heap တစ်ခုတည်းသာ အလုပ်ဖြစ်သည်။</figcaption>" },
  },
  part3Sub: { en: "Two approaches in five languages. Every block is a complete submission, and every one was run against the same 20,012 cases, up to n = 10⁵.", my: "နည်းလမ်းနှစ်မျိုးကို ဘာသာစကား ငါးမျိုးဖြင့်။ Block တိုင်းသည် ပြည့်စုံသော submission ဖြစ်ပြီး အားလုံးကို n = 10⁵ အထိ case 20,012 ခု တူတူဖြင့် run ထားသည်။" },
  playHint: { en: "<kbd>←</kbd> <kbd>→</kbd> step · <kbd>space</kbd> play/pause. Edit <code>nums</code> or <code>k</code> above — up to 10 values, k no more than their count — and both walkthroughs rebuild against your input.", my: "<kbd>←</kbd> <kbd>→</kbd> အဆင့် · <kbd>space</kbd> ဖွင့်/ရပ်။ အပေါ်က <code>nums</code> သို့မဟုတ် <code>k</code> ကို ပြင်လိုက်လျှင် (value 10 ခုအထိ၊ k သည် ၎င်းတို့၏ အရေအတွက်ထက် မပို) walkthrough နှစ်ခုစလုံး သင့် input ဖြင့် ပြန်တည်ဆောက်မည်။" },
};
